### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by grundic** [gpakosz/.tmux#102]
Hi,

Great project, but unfortunately I can't use it without license file. Can you please add one?
Here is page about  [no license](https://choosealicense.com/no-license/).

Thank you.

**Comment by gpakosz** [comment]
Hello @grundic,

[This configuration is released under the WTFPL v2 license](https://github.com/gpakosz/.tmux/blob/e7cbc84bedfc849ea2a276c9e67588a55d51c303/.tmux.conf#L3).

**Comment by grundic** [comment]
Sorry, I've must missed it.

Unfortunately this license is very vague and it lacks warranty disclaimer.
Have you been thinking about moving to some other license? 

Here is somewhat [relevant discussion](https://github.com/dimitri/el-get/issues/474) and here is a [comparison with MIT](https://www.slant.co/versus/3575/3580/~mit-license_vs_wtfpl) and question on  [opensource.stackexchange](https://opensource.stackexchange.com/questions/1359/should-i-use-the-wtfpl-for-my-floss-project).

**Comment by gpakosz** [comment]
> Have you been thinking about moving to some other license?

To be honest, no. I mean, it's just a tmux conf after all?

**Comment by grundic** [comment]
Yes, it's just a tmux configuration, but still it's an intellectual property.
My current employer prohibits using software under WTFPL license, that's why I'm concerned. So I just want to follow the rules to be on a safe side.

I do not insist, so feel free just to close this issue.
And thank you for your time.

**Comment by gpakosz** [comment]
Well I'll give it more thoughts. 

What I wanted to avoid in the first place is encumbering all this with a license text telling people to copy the license over. E.g. in the MIT license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Doesn't the above means you're now obliged to carry over **both** the `.tmux.conf` file **and** the license file?

**Comment by gpakosz** [comment]
Also do you know precisely why your company prohibits the use of software licensed under WTFPL? Do they differentiate WTFPL and WTFPL v2?

**Comment by grundic** [comment]
I'm not a layer, can't say for sure about first question. But I see your point. You could probably embed the whole MIT license to the main .tmux.conf file, but it would make it less readable unfortunately.
I think my company just prohibits WTFPL license regardless of it's version.

**Comment by bkaradzic** [comment]
You can use https://unlicense.org/ instead of WTFPL. One reason why people don't allow WTFPL is because of "fuck" that triggers some stricter rating when product has ratings (since license might be distributed as part of package, or printed inside manual). It's stupid license anyway.

**Comment by Leandros** [comment]
It's also outright dangerous, due to a missing non-warranty clause.

**Comment by bkaradzic** [comment]
> missing non-warranty clause

That's author's problem. Doesn't affect really end user.

**Comment by Leandros** [comment]
Correct, but I wouldn't want to distribute any sort of code without a warranty waiver. Many users of the WTFPL aren't aware of that, and could technically be sued for something they might not expect. 
(The author of the WTFPL did that by design, and offers a warranty clause extension)

**Comment by gpakosz** [comment]
@bkaradzic @Leandros So you guys rather recommend a license change vs dual licensing.

Also, again, as much as I'm proud of the way I'm putting this up, this is just a tmux configuration that spawns shells...

And as I said on Twitter, the intent is "Use it, don't use it, take it, change it, adapt it, that's all fine. And if you do, I don't see the point of forcing you distributing that MIT blob of text all over the place"...

Side tracking the discussion to \1-2 files libs: I feel like I don't want to force people distributing MIT or BSD licenses along side their binary: in their docs, on a separate website, beside the executable, ...

**Comment by Leandros** [comment]
I get that, and that's totally fine. I would suggest switching to [Unlicense](http://unlicense.org/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/), instead.
All of these license try to mimic public domain (a concept, which works a little different in Europe compared to the US).

**Comment by gpakosz** [comment]
@grundic Happy tmuxing!

**Comment by grundic** [comment]
Awesome, thank you @gpakosz! :+1:
