### ISSUE TITLE
Change status line display

### ISSUE THREAD

**Issue by JuanCaicedo** [gpakosz/.tmux#103]
Hi there! I'm interested in modifying the way the status line is displayed. Right now the text of the window goes directly above it and there is a blank line below it. 
![image](https://user-images.githubusercontent.com/4341496/29522733-8758047c-868a-11e7-9ab5-99188838729f.png)

I would instead like to have a blank line above the status line and no line below it. 

Could you point me to what I could mess around with in `.tmux` to achieve this? I'm assuming it's configured somewhere in there, but I'm not sure. Thanks!

**Comment by gpakosz** [comment]
Hello @JuanCaicedo.

I'm afraid the "line above" you're referring to is not something one can control. Can you please test launching tmux with `tmux -f /dev/null`. I predict you will see a blank line below your status bar even though you launched tmux with an empty configuration file.
