### ISSUE TITLE
use ANSI colors instead of hard coded ones

### ISSUE THREAD

**Issue by kmarhold** [gpakosz/.tmux#104]
Would it make more sense to use ANSI colors like black, blue, yellow and so on instead of the hard coded ones? That would allow the config to blend in with any terminal color scheme.

**Comment by gpakosz** [comment]
Hello @kmarhold,

I guess you discovered yourself that you can do what you want already 😉.

Just use `yellow` in place of `#ffff00` and you're all set.

**Comment by kmarhold** [comment]
Yeah, right, you can see what happened. Sorry. Maybe this could be documented explicitly though, it took me a while to figure out and I almost passed on this awesome config because of it...

Anyway here's a screenshot of how it looks in iTerm with the base16 one dark color scheme. Sweet!

![image](https://user-images.githubusercontent.com/17476340/29675932-f75a34ca-88f6-11e7-96ba-ddc422f313cb.png)

**Comment by gpakosz** [comment]
I'll think about adding a note somewhere 🙂
