### ISSUE TITLE
How to send command to tmux session inside another tmux session

### ISSUE THREAD

**Issue by kaskavalci** [gpakosz/.tmux#106]
This question on stackoverflow explains how to send command to another tmux session https://stackoverflow.com/questions/8518815/how-to-send-commands-when-opening-a-tmux-session-inside-another-tmux-session

However, it did not work with this repository's tmux config. Is there something I'm missing?

**Comment by gpakosz** [comment]
Hello @kaskavalci,

I'm not sure about what you're asking. With my configuration, `send-prefix` bindings are configured the following way:
```
$ tmux list-keys | grep send-prefix
bind-key    -T prefix       C-a               send-prefix -2
bind-key    -T prefix       C-b               send-prefix
```

It means both `C-a` and `C-b` are valid prefixes and hitting `C-a` or `C-b` twice will send `C-a` or `C-b` to the terminal.

Whatever you're trying to achieve, please validate it's working with tmux's default configuration:
```
tmux -f /dev/null
```

**Comment by kaskavalci** [comment]
My bad, was trying to execute some commands which is not configured on remote tmux. Thanks for prompt answer and awesome config :)
