### ISSUE TITLE
abount copy && paste

### ISSUE THREAD

**Issue by jackiesun8** [gpakosz/.tmux#107]
Hi, author
I want : 
1. use mouse to select text and then copy to  clipboard
2. copy text from outside and paste to linux 

all of above are not work correct, any ideas?

**Comment by gpakosz** [comment]
Hello,

Point 1. works for me for sure. About 2., I'm not sure what you're asking.

If you're using Linux, make sure `xsel` is installed

**Comment by jackiesun8** [comment]
@gpakosz 
Point 1.  I installed xclip,  But how to use? I readed readme, but not found how.
Point 2  I  use xshell on windows to  ssh connect to linux server. So copy text from outside and paste to linux meaning copy text from windows and paste to xshell.

**Comment by gpakosz** [comment]
1. If you installed `xclip` after having launched `tmux`, then try reloading the configuration by hitting `<prefix>` + `r`.

2. I don't know `xshell`. Looks like classical <kbd>CTRL</kbd>+<kbd>V</kbd> should work for you or I don't understand what you're asking. In any case copy/paste through an ssh connection is not supported by this configuration

**Comment by jackiesun8** [comment]
@gpakosz 
tks to your patience, but how to copy/paste? I use mouse to select text but not work. <prefix>+Enter, i tried, but failed.

**Comment by gpakosz** [comment]
Make your you set `tmux_conf_copy_to_os_clipboard=true` in your `~/.tmux.conf.local` copy.

Then look at the output of `tmux list-keys | grep Mouse`:
```
$ tmux list-keys |grep Mouse
bind-key    -T copy-mode    MouseDown1Pane    select-pane
bind-key    -T copy-mode    MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key    -T copy-mode-vi MouseDown1Pane    select-pane
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key    -T root         MouseDown1Pane    select-pane -t = ; send-keys -M
bind-key    -T root         MouseDown1Status  select-window -t =
bind-key    -T root         MouseDown3Pane    if-shell -F -t = "#{mouse_any_flag}" "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key    -T root         MouseDrag1Pane    if-shell -F -t = "#{mouse_any_flag}" "if -Ft= \"#{pane_in_mode}\" \"copy-mode -M\" \"send-keys -M\"" "copy-mode -M"
bind-key    -T root         MouseDrag1Border  resize-pane -M
```
In particular the bindings for `MouseDragEnd1Pane`

**Comment by jackiesun8** [comment]
I tried again, But not work as before. My env is :
run xshell (windows platform)to ssh to linux server(centos7)

**Comment by jackiesun8** [comment]
I found a way to copy && paste. I use mobaXtem,  when copy , need prefix + m to disable mouse mode and then select text and copy. when paste, mouse moude on or off is all ok.

**Comment by jackiesun8** [comment]
I tested in xshell, prefix + m to disable mouse mode work fine. tks very mush.
