### ISSUE TITLE
Powerline symbols vertical align

### ISSUE THREAD

**Issue by art32** [gpakosz/.tmux#109]
Mac OS 10.12.6
Alacrity
Font: Source Code Pro
Size: 14
![screen shot 2017-10-08 at 21 38 44](https://user-images.githubusercontent.com/16598661/31319755-8152d39c-ac71-11e7-8e59-15cca2ef8239.png)

ITerm 2
Font: Source Code Pro
Size: 13
![screen shot 2017-10-08 at 21 38 08](https://user-images.githubusercontent.com/16598661/31319754-81511944-ac71-11e7-8280-5f1c8562e584.png)

**Comment by gpakosz** [comment]
So I had to use my psychic powers to figure out what the articulated question might be...

Anyways... As you noticed, it's not so easy to find out the perfect settings that will align powerline symbols vertically.

Try to play with font sizes and spacing:
![image](https://user-images.githubusercontent.com/553208/31319978-fc9033b0-ac6c-11e7-9309-1e9848084de9.png)

**Comment by art32** [comment]
Sometimes it's better not to say anything to better understand you.

![screen shot 2017-10-08 at 23 57 15](https://user-images.githubusercontent.com/16598661/31320868-6f3526b6-ac84-11e7-9f6c-1e2cb0464701.png)
![screen shot 2017-10-08 at 23 56 40](https://user-images.githubusercontent.com/16598661/31320867-6f33764a-ac84-11e7-9ddd-9719eb41800a.png)

It's better but not perfect) Thank you.
