### ISSUE TITLE
status bar more than one line out.

### ISSUE THREAD

**Issue by nasyxx** [gpakosz/.tmux#111]
When another tmux is in the tmux, more than one line out.

I'm not sure why this is so. The default tmux status bar does not.

<img width="1320" alt="screen shot 2017-10-15 at 2 56 14 pm" src="https://user-images.githubusercontent.com/5007613/31582562-9a67d7f4-b1b9-11e7-847f-bef6ca92e98e.png">
<img width="1303" alt="screen shot 2017-10-15 at 2 55 46 pm" src="https://user-images.githubusercontent.com/5007613/31582567-aa555042-b1b9-11e7-999e-a8780ed056b0.png">

**Comment by gpakosz** [comment]
This problem happens when `tmux` and you terminal emulator disagree on the Unicode character width. See https://github.com/gpakosz/.tmux#troubleshooting

There's pretty much nothing you can do except stopping using the powerline symbols

**Comment by nasyxx** [comment]
Thank you very much. When I remove all of them, it fixed

**Comment by gpakosz** [comment]
Ok. Closing then.

**Comment by EricQAQ** [comment]
What I should do if I want to keep the emoji in Status Line?
It works in Sierra, but I upgrade to High Sierra, it cannot work..
