### ISSUE TITLE
Could you explain more about copy to clipboard and paste from clipboard without mouse?

### ISSUE THREAD

**Issue by eromoe** [gpakosz/.tmux#112]
Hi, I am on windows7 msys2.

The copy-mode looks like for mouse .
There is no explanation about how to copy selected text to system clipboard ,  paste from clipboard  without mouse.

**Comment by eromoe** [comment]
From http://www.rushiagr.com/blog/2016/06/16/everything-you-need-to-know-about-tmux-copy-pasting/
I understand , 
1. I need enter copy-mode
2. use copy-mode-vi shortcut  to select text 

But `2` is not work.

**Comment by eromoe** [comment]
I found I need enable `set -g mode-keys vi` .

Below explanation is not clear,  
# force Vi mode
#   really you should export VISUAL or EDITOR environment variable, see manual

I did't understand that mean enable vi mode in  copy-mode. I think `copy-mode` default support vi shortcut.

**Comment by gpakosz** [comment]
> Hi, I am on windows7 msys2.

Hello, I'm sorry 😉

> The copy-mode looks like for mouse .

Copy mode is a tmux concept. This is the mode where you navigate the history (the scroll buffer). It is not directly related to copy/pasting. By default, when mouse is enabled, selecting text with the mouse enters copy mode and select this text. Here are the bindings on my Mac:

```
$ tmux list-keys | grep copy-
...
bind-key    -T copy-mode-vi MouseDown1Pane    select-pane
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
...
```
The last line shows that I enabled `tmux_conf_copy_to_os_clipboard=true` which causes default bindings to be adjusted to use `copy-pipe-and-cancel`. The default bindings being:
```
$ tmux list-keys | grep copy-
...
bind-key    -T copy-mode-vi MouseDown1Pane    select-pane
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
...
```

On Windows, if you enable `tmux_conf_copy_to_os_clipboard=true` your `MouseDragEnd1Pane` binding should use `clip.exe`.

> Below explanation is not clear

The tmux manual says
```
mode-keys [vi | emacs]
        Use vi or emacs-style key bindings in copy mode.  The default is emacs, unless VISUAL or EDITOR contains `vi'.
```

Exporting an environment variable depends on your shell. If you're using Bash, you can e.g. `export EDITOR="vim"` from your `~/.bashrc`.

**Comment by eromoe** [comment]
Hmm... , I mention `not clear` is mean this block
```
# force Vi mode
#   really you should export VISUAL or EDITOR environment variable, see manual
#set -g status-keys vi
#set -g mode-keys vi
```
in `.tumx.local.conf` is not clear for a newbee of tmux. Like me, I didn't know use `vi` key-binding in `copy-mode` need unccoment the 4th line `#set -g mode-keys vi`.  That is what I mean unclear. 

The idea words would be something like:

If you want to copy string from screen , you need enter `copy-mode` first, then you can use mouse(right click or shift+right click , depend to you settings)  to copy string. Futher more,  if you want to use `vi` key binding in `copy-mode`, you need  unccoment  `#set -g mode-keys vi` in `.tumx.local.conf`.

**Comment by eromoe** [comment]
One question about copy/paste,  I wonder is it possible to make `ctrl+w/ctrl +u` copy(cut string) to clipboard,  `ctrl+y` paste from clipboard in command-line(shell) ? 

From your previous comment
> Copy mode is a tmux concept. This is the mode where you navigate the history (the scroll buffer). It is not directly related to copy/pasting. 

Looks like that is unpossible ?

**Comment by gpakosz** [comment]
When `export EDITOR=vim` from your `~/.bashrc`, when you launch tmux, it reads the `EDITOR` environment variable, see it contains `"vi"` in it and accordingly use`vi` as the default for `status-keys` and `mode-keys`.

For the rest, please get a better tmux understanding by reading the manual again. Thanks!
