### ISSUE TITLE
hi~ this tool is not work for me with tmux 2.6

### ISSUE THREAD

**Issue by samchanye** [gpakosz/.tmux#113]

**Comment by gpakosz** [comment]
That's a bit vague to say the least...

**Comment by samchanye** [comment]
i install tmux 2.6 by brew and execute below
![image](https://user-images.githubusercontent.com/22740401/32040529-bb1684b0-b9f6-11e7-935c-077ba9208122.png)
but ...
![image](https://user-images.githubusercontent.com/22740401/32040574-ef49f9a6-b9f6-11e7-8648-eacabcc0950c.png)

this is my computer config:
Mac 10.11.3

**Comment by gpakosz** [comment]
Make sure you quit tmux before installing then relaunch it.

Also, the symlink should end up being in your home directory:
```
$ cd
$ pwd
/Users/gregory
$ ls -al | grep .tmux.conf
lrwxr-xr-x     1 gregory  staff         16 Oct 31  2016 .tmux.conf -> .tmux/.tmux.conf
-rw-r--r--     1 gregory  staff       9187 Oct 19 08:09 .tmux.conf.local
```

**Comment by samchanye** [comment]
yes, i'm sure i quit tmux before installing and this is my symlink:
![image](https://user-images.githubusercontent.com/22740401/32041114-9b1bc3b2-b9f8-11e7-970c-01d90e328851.png)
maybe this is my destiny~

**Comment by gpakosz** [comment]
Usually, when `tmux` fails to source `~/.tmux.conf` properly, you get to see an error message. The fact that you didn't have one makes me question whether tmux read `~/.tmux.conf` properly.

Another thing you can do to troubleshoot is: once inside tmux, launch
```
$ cut -c3- ~/.tmux.conf | sh -s _apply_configuration
```

**Comment by samchanye** [comment]
ohhhhhhh~ is work for me , thx~
but why i can't read .config properly

**Comment by gpakosz** [comment]
Make sure you really kill all process. It seems a tmux server process is still lying around. In doubt try to reboot

**Comment by gpakosz** [comment]
Are we good?
