### ISSUE TITLE
Support for TPM

### ISSUE THREAD

**Issue by chris-fa** [gpakosz/.tmux#114]
Does this plugin works with TPM?

```.tmux.conf
set -g @plugin 'gpakosz/.tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Added this, ran `<prefix> + I`, restarted tmux but I don't see a status line

**Comment by gpakosz** [comment]
Hello @chris-fa,

I personally don't use TPM because well... The whole thing goes against having a self contained tmux configuration.

But have a look at #61, it seem some people out there managed to make it work with my conf.

Hope that helps.
