### ISSUE TITLE
Error when splitting pane on directories with spaces when reconnect_ssh=true

### ISSUE THREAD

**Issue by lzilhao** [gpakosz/.tmux#115]
If `tmux_conf_new_pane_reconnect_ssh=true` and my path has a directory with a space in it, I get the following error when trying to split: 
`'cut -c3- ~/.tmux.conf | sh -s _split_window /dev/pts/1 -h -c /home/luis/Dropbox/Link to Pictures' returned 1`

**Comment by gpakosz** [comment]
I confirm I can reproduce. Thanks for the report

**Comment by gpakosz** [comment]
Can you please try whether the `gh-115` branch works for you?

**Comment by lzilhao** [comment]
Yes, it's fixed. Thanks, and great job on this config. It's fantastic

**Comment by gpakosz** [comment]
gonna merge soon, thanks for the test
