### ISSUE TITLE
CPU Usage on status bar

### ISSUE THREAD

**Issue by jmesquita** [gpakosz/.tmux#117]
I really don't know how to extend without forking the repo. I really like how this is setup and the idea of overriding things on the local machine. The only thing I miss from my config is this:

```print_cpu_percentage() {
    if command -v "iostat" &> /dev/null; then
                                                                                                                                             
        if iostat -c &> /dev/null; then
            iostat -c 1 2 | tail -n 2 | tr -s ' ' ';' | grep -e '^;' | cut -d ';' -f 7 | awk '{usage=100-$1} END {printf("%5.1f%%", usage)}'
        elif [ $(uname) == "Darwin" ]; then
            iostat -c 2 disk0 | tail -n 1 | tr -s ' ' ';' | cut -d ';' -f 7 | awk '{usage=100-$1} END {printf("%5.1f%%", usage)}'
        elif [ $(uname) == "FreeBSD" ]; then
            iostat -c 2 | tail -n 1 | tr -s ' ' ';' | cut -d ';' -f 11 | awk '{usage=100-$1} END {printf("%5.1f%%", usage)}'
        else
            echo "Unknown iostat version please create an issue"
        fi
    elif command -v "sar" &> /dev/null; then
        sar -u 1 1 | tail -n 1 | tr -s ' ' ';' | cut -d ';' -f 8 | awk '{usage=100-$1} END {printf("%5.1f%", usage)}'
    else
        if command -v WMIC &> /dev/null; then
            usage="$(WMIC cpu get LoadPercentage | grep -Eo '^[0-9]+')"
            printf "%5.1f%%" $usage
        else
            load=`ps -aux | awk '{print $3}' | tail -n+2 | awk '{s+=$1} END {print s}'`
            cpus=$(cpus_number)
            echo "$load $cpus" | awk '{printf "%5.2f%%", $1/$2}'
        fi
    fi
}
```

With that, I was able to place the CPU Usage on the status like this:

```
#       status_right_cpu="${tmux_conf_cpu:-#(cut -c3- ~/.tmux.conf | sh -s print_cpu_percentage)}"
```

The thing is, how would I make this work on the local config?

**Comment by gpakosz** [comment]
Hello @jmesquita.

It seems to me what you pasted above is partial: The beginning of your `print_cpu_percentage()` function is missing and then I quite don't get where you're using `status_right_cpu`.

In any case, the following approach might work for you.
Edit your `~/.tmux.conf.local` file to **make it a polyglot**:
```
# cat << EOF > /dev/null

... same content as before ...

# -- 8< ------------------------------------------------------------------------
#
# EOF
#
# # exit the script if any statement returns a non-true return value
# set -e
#
# export LC_NUMERIC=C
#
# _cpu_usage() {
#  echo "N/A"
# }
#
# "$@"
```
The key observation is:
  - every line starting with a `#` is seen as a comment and ignored by `tmux` when sourcing `~/.tmux.conf.local`
  - after having applied `cut -c3-` the first 3 columns are cut/removed and the `sh` will interpret the `cat << EOF > /dev/null` line making all the `tmux` conf a HEREDOC. The output of `cut -c3- ~/.tmux.conf.local` is now a valid shell script you can pipe to `sh`
  - the last `"$@"` line is what makes `sh -s _cpu_usage` invoke the `_cpu_usage()` function

Now you just have to implement the `_cpu_usage()` shell function to suit your needs and finally you have to call it from e.g. `tmux_conf_theme_status_right`:
```
tmux_conf_theme_status_right='... #(cut -c3- ~/.tmux.conf.local | sh -s _cpu_usage)  ...'
```

**Comment by gpakosz** [comment]
@jmesquita so? how is it going?

**Comment by jmesquita** [comment]
Sorry for the late response, I was swamped and couldn't work on that until now.

Wow! It worked perfectly now! Thank you! I have CPU usage on my bottom right corner now just like I wanted! Thank you!

**Comment by gpakosz** [comment]
You're welcome
