### ISSUE TITLE
Question: vi-choice mode-table

### ISSUE THREAD

**Issue by cdrainxv** [gpakosz/.tmux#121]
I can't be too sure, but what do you mean by *vi-choice mode-table* exactly? I thought it would apply to cases such as in the **choose-tree** interface when trying to switch sessions. However, I find that none of the keys work. Am I wrong in my understanding?

**Comment by gpakosz** [comment]
You're right, it's gone entirely.

You used to have the ability to bind keys for that mode but tmux removed that entirely and you don't have the choice anymore. I'll update `README.md` accordingly.

**Comment by cdrainxv** [comment]
Okay. Thanks for letting me know. I love your work by the way. I will also take a look at your .vim repo - might get some ideas for my own. You are doing the Lord's work. 😄
