### ISSUE TITLE
Tmux has started loading slowly under WSL

### ISSUE THREAD

**Issue by 58bits** [gpakosz/.tmux#122]
Hi - and thanks for the super config settings for tmux. I've been using them for a while now under Ubuntu, OSX, and more recently Windows Subsystem for Linux (WSL) - via both Windows Ubuntu console, and wsl-terminal here at https://github.com/goreliu/wsl-terminal . wsl-terminal seems to provide the best xterm-256 support, for all options, including powerline modified fonts.

Not sure what changed - but everything was working brilliantly under wsl-terminal and tmux was loading fast (less than a second), and then recently started to load slowly - almost 7 seconds before loading completely.

Here's a look at the tmux-client.log file with tmux started as `tmux -v`

```
1513001751.455203 client started (797): version 2.6, socket /tmp/tmux-1000/default, protocol 8
1513001751.455255 on Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014; libevent 2.0.21-stable (poll)
1513001751.455294 socket is /tmp/tmux-1000/default
1513001751.455313 trying connect
1513001751.455343 connect failed: Connection refused
1513001751.455360 lock file is /tmp/tmux-1000/default.lock
1513001751.455741 flock succeeded
1513001751.455764 got lock (6)
1513001751.455780 trying connect
1513001751.455800 connect failed: Connection refused
1513001751.457266 add peer 0x1691840: 7 ((nil))
1513001751.457565 sending message 100 to peer 0x1691840 (4 bytes)
```
The problem appears to be caused by the client being initially refused a connection to the server - before finally connecting.

The tmux-server.log file is over 2MB so not copying here. The full server log is available here at ...
https://s3-ap-southeast-1.amazonaws.com/downloads.infonomic.io/tmux-server-799.log

Any thoughts on what might be happening here?

**Comment by gpakosz** [comment]
Hello @58bits,

At that point I have no idea what's going on. There are so many factors...

This configuration shells out a lot out to implement all its features. If your shell has a slow init phase, this could explain the slowness. Do you e.g. use zsh?

**Comment by 58bits** [comment]
@gpakosz - thanks for the speedy reply. I'm using a fairly standard bash shell - https://github.com/58bits/dotfiles  - and have also just tried removing anything that might slow the shell from starting, like a custom ps1 etc. Strange as until a week or so ago, tmux was loading almost immediately.

**Comment by gpakosz** [comment]
Is it also slow after you make sure you have killed the `tmux` server process and you run the client with `$ tmux -f /dev/null`?

**Comment by gpakosz** [comment]
Dammit I just tested on WSL myself and it takes 9s to start :(

**Comment by 58bits** [comment]
Whew - glad it's not just me.

**Comment by gpakosz** [comment]
I can't promise I'll find a way to speed it up but I'll have a look

**Comment by 58bits** [comment]
Okay - and again, thanks very much for taking the time to reply.

**Comment by gpakosz** [comment]
So well yeah I expect it to be slow in WSL, I'm really not surprised. And what surprises me is that you have the impression it used to be fast(er) while I changed nothing lately

**Comment by 58bits** [comment]
Hi @gpakosz - I have a hunch it was something in a Windows update that changed WSL. It genuinely _was_ faster a week or two ago - with tmux and your configuration loading in under a second. I'll investigate further as time allows.

**Comment by gpakosz** [comment]
So you're telling you didn't update `tmux`? I tried with stock `2.1` that comes with WSL's Ubuntu 16.04

**Comment by 58bits** [comment]
I've tried 2.5 and 2.6 in this instance. I've not yet gone back to 2.1.

**Comment by 58bits** [comment]
For the moment, I've extracted most of your tmux functions into [tmux-functions.sh](https://gist.github.com/58bits/cc342bab79e8d4b5a45227b5fc8f39c0), and sourcing this in .bashrc. And then after loading tmux with basic configuration settings only, calling _apply_theme manually. With things paired down, _apply_theme runs in about two seconds.

**Comment by gpakosz** [comment]
I started profiling things and my analysis so far is that forking is ultimately slow compared to Linux or Mac.

**Comment by 58bits** [comment]
Yup - I agree that's the cause. I only wonder what changed in WSL (unless I failed to notice the 9 second start initially, which is possible, but unlikely ;-)). Do you want to close this? Since it's not really a problem with your tmux.conf?

**Comment by 58bits** [comment]
Okay so in the end I split up all of your helper functions into individual bash script files, like `uptime.sh`, `username.sh`, `hostname.sh` and placed them in my .tmux directory. They're called individually from any tmux config shell directive like `#(~/.tmux/uptime.sh)`. I created a final helper script file called `apply_theme.sh` and sourced/run this at the end of my `.tmux.conf` file as `run '~/.tmux/apply_theme.sh'`. 

tmux and the applied theme load in about 2 seconds - which isn't stellar, but okay for now. 

There are also quite a few options I'm not loading at the moment, including most of the other tmux run commands.

Your bash fu is awesome. I'm not even close :-). If any of this ends up in my .dotfiles, I'll be sure to include a prominent credit and url to this repo at the top of every file. 

In the meantime let's hope that WSL's forking/shell spawning times eventually come down, and I can switch back to your configuration in this repo.

Thanks again for all the hard work in producing a very cool tmux config.

**Comment by naykun** [comment]
While this is still a problem now, and every time I execute a single command (even ls) will cost 1 sec.
