### ISSUE TITLE
question: should pane splitting commands be added to readme?

### ISSUE THREAD

**Issue by cdrainxv** [gpakosz/.tmux#124]
Initially I overwrote the configuration you had for the panes with the one I usually use for my vim splits, but it turns outs we have the same bindings for splits after having a peek at the **.tmux.conf**.

I think the configuration for the splits should be added to the readme, much like the other configs for pane resizing, navigating, etc. This will at least give users the current split commands if they deem to unbind them or if it's their first encounter with tmux, without having to search in the **.tmux.conf**.

**Comment by gpakosz** [comment]
Hello @cdrainxv, can you please give me your opinion on https://github.com/gpakosz/.tmux/tree/gh-124 ?

**Comment by cdrainxv** [comment]
It looks great! Thanks!
