### ISSUE TITLE
Statusbar broken on High Sierra 10.13

### ISSUE THREAD

**Issue by eluft84** [gpakosz/.tmux#126]
Hi,
since the update to OSX High Sierra the status is broken. Sometimes the shell input is also jumping one line. So very strange.
![issue](https://user-images.githubusercontent.com/30810185/34094288-dcd28efa-e3cc-11e7-927e-672343f6d4e6.png)

Any ideas?

**Comment by gpakosz** [comment]
I don't run High Sierra yet. I suspect this is caused by `tmux` and the OS disagreeing on the width of Unicode symbols.

**Comment by eluft84** [comment]
That´s really strange. I changed the font to something else and then back to Meslo L and now i have few _ in the prompt and status bar. 
![issue1](https://user-images.githubusercontent.com/30810185/34095442-b94656d8-e3d1-11e7-8f81-6cc00d53ebc2.png)

**Comment by gpakosz** [comment]
```
$ tmux show -gv status-left
#[fg=#000000,bg=#ffff00,bold] ❐ #S #[fg=#ffff00,bg=#ff00af,none]#[fg=#e4e4e4,bg=#ff00af,none] ↑#{?@uptime_d, #{@uptime_d}d,}#{?@uptime_h, #{@uptime_h}h,}#{?@uptime_m, #{@uptime_m}m,} #[fg=#ff00af,bg=default,none]
```
```
$ tmux show -gv status-right
#(cut -c3- ~/.tmux.conf | sh -s _uptime)#(cut -c3- ~/.tmux.conf | sh -s _battery)#[fg=#080808,bg=default,none]#[fg=#8a8a8a,bg=#080808,none]#[fg=none]#[bg=none]#[none]#{?client_prefix,⌨ ,}#[fg=none]#[bg=none]#[none]#{?session_many_attached,👓 ,} #(ping -t 1 -c 1 google.com >/dev/null 2>&1 && printf ✔ || printf ✘) #{?@battery_status, #{@battery_status},}#{?@battery_vbar, #{@battery_vbar},}#{?@battery_percentage, #{@battery_percentage},} #[fg=#8a8a8a,bg=#080808,none]| %R #[fg=#8a8a8a,bg=#080808,none]| %d %b #[fg=#d70000,bg=#080808,none]#[fg=#e4e4e4,bg=#d70000,none] #(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} true #D)#[fg=none]#[bg=none]#[bold,blink]#(cut -c3- ~/.tmux.conf | sh -s _root #{pane_tty} #D)#[default]#[fg=#e4e4e4,bg=#d70000,none] #[fg=#e4e4e4,bg=#d70000,none]#[fg=#000000,bg=#e4e4e4,bold] #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)
```

You have to realize that this configuration just sets the `status-left` and `status-right` after having evaluated some logic. As such if you want to debug it, a good way is to start `tmux` without a configuration:
```
$ tmux -f /dev/null
```

And from there try to set `status-left` and `status-right` incrementally with portions of what `tmux show -gv` outputted until you find what exactly breaks in your setup.

**Comment by eluft84** [comment]
You´re right. Something is broken in #{?battery_status, #{battery_status},} :-(

**Comment by gpakosz** [comment]
Why symbols are you using for the battery indicators?

Try to revert to the safer
```
tmux_conf_battery_status_charging='↑'       # U+2191
tmux_conf_battery_status_discharging='↓'    # U+2193
```
in your `~/.tmux.conf.local` copy

**Comment by eluft84** [comment]
Bingo ;)
I used 
```
tmux_conf_battery_status_discharging='↓'    # U+2193
tmux_conf_battery_status_charging='⚡'    # U+26A1
```

With charging `tmux_conf_battery_status_charging='↑'       # U+2191` issue is no longer reproducible. Any idea why? Because it works before and i can see the icon, but then the status bar is broken.

**Comment by gpakosz** [comment]
See https://github.com/gpakosz/.tmux#troubleshooting

If you're using iTerm2, you may want to play with the following setting:
<img width="886" alt="sshot" src="https://user-images.githubusercontent.com/553208/34106772-cb9b3740-e3f9-11e7-889b-0b8d4afb5196.png">

Hope that helps.

**Comment by eluft84** [comment]
@gpakosz Thanks! I will try.
