### ISSUE TITLE
status bar support mosh?

### ISSUE THREAD

**Issue by FlamingTree** [gpakosz/.tmux#127]
Can status bar show hostname when use mosh(https://mosh.org/) as a ssh client?

**Comment by gpakosz** [comment]
Hello @FlamingTree,

Actually I started a branch a while ago but didn't find the opportunity to finish it. I'll give it another try.

**Comment by gpakosz** [comment]
@FlamingTree  👋

Can you give the `mosh` branch a spin for a while? I'm not a regular mosh user so things likely need to be ironed out...

**Comment by FlamingTree** [comment]
@gpakosz I will try 👍

**Comment by gpakosz** [comment]
Hello @FlamingTree 👋

Did you have a chance to try the `mosh` branch?

**Comment by FlamingTree** [comment]
@gpakosz  I have used almost two weeks, it worked perfectly. Great work! 🎉🎉🎉

**Comment by gpakosz** [comment]
FYI. I made some trivial tests and should merge this enhancement this week

**Comment by lukechilds** [comment]
@gpakosz is mosh support still planned?

**Comment by gpakosz** [comment]
@lukechilds There's experimental Mosh support in the `mosh` branch. Can you give it a try?
