### ISSUE TITLE
Tag auto rename issue?

### ISSUE THREAD

**Issue by forfrt** [gpakosz/.tmux#128]
Each time I use `<prefix> ,` to rename my working tag, it will be automatically renamed back whenever I do something in this tag, which is annoying since I am using a remote server that has a very nonsense hostname like ` root@iZ2zej8qby6d0rbmoxcdw5Z:~`

I am wondering in which way could I turn this feature off.

**Comment by forfrt** [comment]
It fixed! Thanks! 

I have tried to set `automatic-rename` to off but not useful at all. `allow-rename` option helps.

**Comment by gpakosz** [comment]
Cool.

Are we good then?
