### ISSUE TITLE
Mouse select to cancel copy mode

### ISSUE THREAD

**Issue by itielshwartz** [gpakosz/.tmux#129]
Hi,

Using iterm2 + tmux, wanted to know if its possible to exit (or just not to enter) copy mode while selecting text (so i can use iterm features -> like search in browser etc).

Current config is:
```
set-option -g mouse on
# Fix copying behaviour
set-option -g default-command "reattach-to-user-namespace -l zsh"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

Thanks.

**Comment by gpakosz** [comment]
Hello,

I think what you want is `MouseDragEnd1Pane` to **not enter copy mode** in the first place.

Try to unbind `MouseDragEnd1Pane` which I believe should get you what you want: mouse mode to select/resize panes/windows while letting iTerm2 handle selection.

Please also not this is a general tmux/iTerm2 support question and falls outside of the scope of this configuration.

**Comment by gpakosz** [comment]
My bad, you want to unbind `MouseDrag1Pane`
 
```
→ ~ tmux list-keys | grep begin-selection
bind-key    -T copy-mode    C-Space           send-keys -X begin-selection
bind-key    -T copy-mode    MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi Space             send-keys -X begin-selection
bind-key    -T copy-mode-vi v                 send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
```

**Comment by itielshwartz** [comment]
i added both this lines:
```
unbind-key    -T copy-mode-vi MouseDrag1Pane
unbind-key    -T copy-mode    MouseDrag1Pane
```
And still not seems to work - anything i can do?

**Comment by gpakosz** [comment]
Source your configuration?

**Comment by itielshwartz** [comment]
`# Ring the bell if any background window rang a bell
set -g bell-action any

# Default termtype. If the rcfile sets $TERM, that overrides this value.
set -g default-terminal screen-256color

# Keep your finger on ctrl, or don't
bind-key ^D detach-client

# Create splits and vertical splits
bind-key v split-window -h -p 50 -c "#{pane_current_path}"
bind-key ^V split-window -h -p 50 -c "#{pane_current_path}"
bind-key s split-window -p 50 -c "#{pane_current_path}"
bind-key ^S split-window -p 50 -c "#{pane_current_path}"

# Pane resize in all four directions using vi bindings.
# Can use these raw but I map them to shift-ctrl-<h,j,k,l> in iTerm.
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Smart pane switching with awareness of vim splits.
# Source: https://github.com/christoomey/vim-tmux-navigator
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?x?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# Use vi keybindings for tmux commandline input.
# Note that to get command mode you need to hit ESC twice...
set -g status-keys vi

# Use vi keybindings in copy and choice modes
setw -g mode-keys vi

# easily toggle synchronization (mnemonic: e is for echo)
# sends input to all panes in a given window.
bind e setw synchronize-panes on
bind E setw synchronize-panes off

# set first window to index 1 (not 0) to map more to the keyboard layout...
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mouse on

# color scheme (styled as vim-powerline)
set -g status-left-length 52
set -g status-right-length 451
set -g status-fg white
set -g status-bg colour234
set -g pane-border-fg colour245
set -g pane-active-border-fg colour39
set -g message-fg colour16
set -g message-bg colour221
set -g message-attr bold
set -g status-left '#[fg=colour235,bg=colour252,bold] ❐ #S #[fg=colour252,bg=colour238,nobold]⮀#[fg=colour245,bg=colour238,bold] #(whoami) #[fg=colour238,bg=colour234,nobold]⮀'
set -g window-status-format '#[fg=colour235,bg=colour252,bold] #I #(pwd="#{pane_current_path}"; echo ${pwd####*/}) #W '
set -g window-status-current-format '#[fg=colour234,bg=colour39]⮀#[fg=black,bg=colour39,noreverse,bold] #{?window_zoomed_flag,#[fg=colour228],} #I #(pwd="#{pane_current_path}"; echo ${pwd####*/}) #W #[fg=colour39,bg=colour234,nobold]⮀'
set-option -g status-interval 2

# Patch for OS X pbpaste and pbcopy under tmux.
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Screen like binding
unbind C-b
set -g prefix C-a
bind a send-prefix

# No escape time for vi mode
set -sg escape-time 0

# Screen like binding for last window
unbind l
bind C-a last-window

# Bigger history
set -g history-limit 10000

# New windows/pane in $PWD
bind c new-window -c "#{pane_current_path}"

# Fix key bindings broken in tmux 2.1
set -g assume-paste-time 0

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Local config
if-shell "[ -f ~/.tmux.conf.user ]" 'source ~/.tmux.conf.user'
set-option -g mouse on
unbind-key    -T copy-mode-vi MouseDrag1Pane
unbind-key    -T copy-mode    MouseDrag1Pane
`

**Comment by gpakosz** [comment]
I meant make sure you source your configuration after having changed the bindings. You can verify the binding with `tmux list-keys`.

Hope that helps.

**Comment by gpakosz** [comment]
Hello @itielshwartz,

Did you manage to sort this out?

**Comment by itielshwartz** [comment]
Hi yeah in the end i make something that worked for me :)
thanks!
