### ISSUE TITLE
Why does this project store helper bash methods as comments in the .tmux.conf?

### ISSUE THREAD

**Issue by thalesmello** [gpakosz/.tmux#13]
I noticed this script has several helper bash functions stored as functions in the `.tmux.conf`, and it makes use of the `cut` command to run them.

My question is:

Why is it done that way, rather than storing them in a separate file?
Is there any technical limitation?

**Comment by gpakosz** [comment]
Hello,

This makes the `.tmux.conf` more portable. You just have to copy it around.

**Comment by thalesmello** [comment]
That's a good reason why. Thanks for clearing things up.

**Comment by gpakosz** [comment]
You're welcome.
