### ISSUE TITLE
Synchronize-panes Indicator?

### ISSUE THREAD

**Issue by hu6360567** [gpakosz/.tmux#130]
Hi there,
    Is there any option to show an indicator of synchronize-panes status on the staus bar?

**Comment by gpakosz** [comment]
Hello,

Sure. Whatever you can do with stock's tmux status line is doable. You can edit your `~/.tmux.conf.local` copy and edit one of `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right` variable to which you just have to add `#{?pane_synchronized,🔒 ,}`.

See tmux manual for conditional variables syntax.
