### ISSUE TITLE
tmux is not at the bottom

### ISSUE THREAD

**Issue by Allkoman** [gpakosz/.tmux#132]
http://okj8snz5g.bkt.clouddn.com/blog/04614720-F145-4350-8A2B-227B9093F8DD.png

My tmux bar is not at the bottom and when I use vim , there are two bars

**Comment by gpakosz** [comment]
Hello @Allkoman,

I'm not sure what you're talking about

![image](https://user-images.githubusercontent.com/553208/34554772-da8c682c-f12e-11e7-95a9-5a8502e2575d.png)

My speculation is that you may be facing Unicode width's incompatibility between tmux and your terminal emulator. See https://github.com/gpakosz/.tmux/blob/master/README.md#troubleshooting.

Edit your `~/.tmux.conf.local` copy and try without using powerline symbols and emojis for the various indicator.
