### ISSUE TITLE
can not copy 

### ISSUE THREAD

**Issue by dupl10** [gpakosz/.tmux#136]
I want to copy something as follows:
1) enter copy mode using Control+b [
2) navigate to beginning of text, you want to select and hit Space
3) move around using arrow keys to select region
4) when you reach end of region simply hit Enter to copy the region
5) now Control+b ] will paste the selection

but, 3) unable to "select region" (just moving the cursor) and 4) unable to "quitting selection" (doing nothing )

what is wrong with my .tmux...the config is same as your repo and i am in Debian OS
by the way, it is ok to copy with mouse at "mouse mode"...the above issue is found both "mouse mode" and "keyboard mode" (a name I fabricated, i think you get my point)
I am a chinese with poor English, and hope you can understand my trouble...thx!

**Comment by gpakosz** [comment]
Hello @dupl10,

Well first, I'm not so used to tmux default bindings. But when I have a look at the output of `$ tmux list-keys`, I get (first launch tmux with `$ tmux -L test -f /dev/null` to make sure what the default behavior is without my configuration):

```
$ tmux -L test -f /dev/null list-keys | grep selection
bind-key    -T copy-mode    C-Space           send-keys -X begin-selection
bind-key    -T copy-mode    C-g               send-keys -X clear-selection
bind-key    -T copy-mode    C-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    M-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi C-j               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi Enter             send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi Escape            send-keys -X clear-selection
bind-key    -T copy-mode-vi Space             send-keys -X begin-selection
bind-key    -T copy-mode-vi A                 send-keys -X append-selection-and-cancel
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
```

So it seems <kbd>Space</kbd> only begins a selection if tmux is in vi mode. And you can see that <kbd>Enter</kbd> copies to the tmux buffer only when tmux is in vi mode.

To put tmux in vi mode, either export the `EDITOR` environment variable and set it to `vim` (see tmux manual). Or edit your `~/.tmux.conf.local` copy and make sure the `set -g` lines are uncommented:
```
# force Vi mode
#   really you should export VISUAL or EDITOR environment variable, see manual
set -g status-keys vi
set -g mode-keys vi
```

Hope that helps.

**Comment by dupl10** [comment]
Great! I have done it by exporting EDITOR as great "vim"... thx
