### ISSUE TITLE
Heat palette barely visible on lower battery

### ISSUE THREAD

**Issue by manuelmazzuola** [gpakosz/.tmux#138]
When the battery is low and the heat palette is selected the percentage is barely visible.
 `tmux_conf_battery_bar_palette='heat'`
![image](https://user-images.githubusercontent.com/1757492/34935234-789b2d30-f9dd-11e7-8a0e-95f1f8639d05.png)

**Comment by gpakosz** [comment]
Can you please give the `gh-138` branch a try?

**Comment by manuelmazzuola** [comment]
Perfect 

![image](https://user-images.githubusercontent.com/1757492/35033644-b491eeca-fb6b-11e7-9fe5-4f424be3a728.png)
