### ISSUE TITLE
configurations are not affecting.

### ISSUE THREAD

**Issue by lalitmee** [gpakosz/.tmux#139]
I have followed the process of installing these configurations for tmux but when I am starting my tmux in terminal nothing is changed.

**I am on Ubuntu 16.04.**
**Please help me. Thanx**
![tmux](https://user-images.githubusercontent.com/10762218/35777218-2ed1eed4-09d0-11e8-80b3-e25d48d5a71b.png)

**Comment by gpakosz** [comment]
The `[11]` you're seeing means it's the 11th session. You likely didn't kill the tmux server process before installing my configuration.

You can hit `<prefix>` + `:` and use the `source ~/.tmux.conf` command.

Hope that helps.

**Comment by lalitmee** [comment]
Yeah it worked. Can you please tell me the powerline theme name which is being used in this pic?
![ee3c0ca6-5c02-11e5-890e-05d825a46c92](https://user-images.githubusercontent.com/10762218/35780093-ada30c6c-09fc-11e8-8e26-f45f254b1d60.gif)

**Comment by gpakosz** [comment]
Really everything is described in `README.md` and in your `~/.tmux.conf.local` copy (which you should have if you followed setup instructions).

**Comment by lalitmee** [comment]
It is looking something like this.

![tmux powerline](https://user-images.githubusercontent.com/10762218/35780518-7f18672e-0a02-11e8-91c0-1b74c36c8808.png)

**Comment by gpakosz** [comment]
See https://github.com/gpakosz/.tmux#enabling-the-powerline-look

You need to have proper fonts installed.

**Comment by lalitmee** [comment]
I have installed PowerlineSymbols.otf and other powerline fonts but still it is same. If you can tell me the preferred font which you have used. Maybe it can solve the problem.

**Comment by gpakosz** [comment]
> use a font that already bundles those: this is e.g. the case of the [2.030R-ro/1.050R-it](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro/1.050R-it) version of the Source Code Pro font
