### ISSUE TITLE
Problem with Powerline Theme

### ISSUE THREAD

**Issue by ELD** [gpakosz/.tmux#14]
First off, this may be a font issue rather than a tmux configuration issue and if so, I apologize for wasting your time.

Now, onto the actual problem. When using the Hack font (http://github.com/chrissimpkins/Hack) with your theme, the left separator doesn't want to display even though the font supports the left separator. I've included screenshots of what it looks like in the tmux theme and with the font supporting the character via echoing it to the terminal window.

<img width="326" alt="screenshot 2016-02-19 13 47 45" src="https://cloud.githubusercontent.com/assets/650044/13188595/93684dac-d70f-11e5-95d6-03075a837467.png">
<img width="483" alt="screenshot 2016-02-19 13 48 08" src="https://cloud.githubusercontent.com/assets/650044/13188596/9377220a-d70f-11e5-9121-21c30b7628cc.png">

Let me know if you have any other steps I should do to troubleshoot this.

Thanks!

**Comment by gpakosz** [comment]
Yep, just tried it.

That's because the Hack font doesn't have the Powerline symbols in its bold version it seems.

**Comment by ELD** [comment]
Okay, great, thanks for that. I'll get in touch with the Hack folks then.

**Comment by gpakosz** [comment]
In the meantime you can remove the alter line `233`:

https://github.com/gpakosz/.tmux/blob/33e0fe5468bf3ffa262f3fa3b8535adf764b7426/.tmux.conf#L233

with `#[nobold]$left_separator#[bold]` but that changes the look a bit

**Comment by gpakosz** [comment]
Your prompt's cool btw

**Comment by ELD** [comment]
Okay, thanks for the information on how to modify it.

Also, thanks for the comment on my prompt. I didn't make it myself. It's a ZSH prompt that I'm using with Prezto. It's the Garrett ZSH prompt (https://github.com/chauncey-garrett/zsh-prompt-garrett).
