### ISSUE TITLE
set "pane-border" has no effect in .tmux.conf.local

### ISSUE THREAD

**Issue by Vxider** [gpakosz/.tmux#141]
```
 293 set -s pane-border-status top
 294 set -s pane-border-format "#[bold,fg=#dddddd,bg=#009aff]#{=-80:pane_current_path}"
 297 set-option -s status-interval 1
```
This was the code I added to `.tmux.conf.local` at the bottom. But it dose not work. 
<img width="752" alt="2018-02-27 10 49 31" src="https://user-images.githubusercontent.com/6134315/36709366-7922fc50-1bb2-11e8-94e9-bad84f9cb10f.png">

When I reload the configuration manually, It will work. But I have to reload configuration manually every time when I create new window.

**Comment by gpakosz** [comment]
Hello,

As per tmux manual, `pane-border-status` is a window option, you have to use `set -w` and you want to make it global so it's `set -wg`.

```
set -wg pane-border-status top
set -wg pane-border-format "#[bold,fg=#dddddd,bg=#009aff]#{=-80:pane_current_path}"
```

I personally don't recommend refreshing the status line too often.

Hope that helps.

**Comment by Vxider** [comment]
That helps me, thank you for your help
