### ISSUE TITLE
Ctrl+L does not switch to the last session

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#143]
First off, amazing config, thanks so much for this. After installing it appears that `C-L`, which I believe is a tmux default, no longer switches me to the last session. To be clear, the key combination that I'm used to using for this is prefix then shift + l.

Here are the configs that I found that may be interfering
```
bind -r C-l next-window     # select next window
bind -n C-l send-keys C-l \; run 'sleep 0.1' \; clear-history
```
And on my local
```
bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
```
FWIW the `clear-history` command does not work either but I can open a separate ticket for that.

**Comment by gpakosz** [comment]
Hello @kleinjm,

In my configuration I indeed made the choice to have `C-l` to clear both the terminal and tmux history while `<prefix> C-l` moves one pane to the right, which as you found out is reflected by:
```
$ tmux list-keys | grep C-l
bind-key -r -T prefix       C-l               next-window
bind-key    -T root         C-l               send-keys C-l ; run-shell "sleep 0.1" ; clear-history
```

> After installing it appears that C-L, which I believe is a tmux default, no longer switches me to the last session

Do you mean `last-window`?

```
$ tmux -L test -f /dev/null list-keys | grep last-window
bind-key    -T prefix       l                 last-window
```

If you want to re-establish the default, edit your `~/.tmux.conf.local` copy and add
```
bind l last-window
```

**Comment by gpakosz** [comment]
I marked the issue as "won't fix" since I prefer to have these defaults. As mentioned above, you can customize this configuration to your own preferences by editing your `~/.tmux.conf.local` copy and overriding my choices.

Hope that helps

**Comment by kleinjm** [comment]
Totally understand, thanks for the fast replies on everything 🍻
