### ISSUE TITLE
Ctrl l not clearing history or shell

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#144]
It appears that this config isn't working. Sorry for the duplicate if this is a known issue.
```
bind -n C-l send-keys C-l \; run 'sleep 0.1' \; clear-history
```
From my understanding, this should forward a regular control + l command to the shell and clear the screen.
May be related to https://github.com/gpakosz/.tmux/issues/143

**Comment by gpakosz** [comment]
It works for me.

Can you please run the following command and paste the output?
```
$ tmux list-keys | grep C-l
```

**Comment by gpakosz** [comment]
After reading #143 again, it seems normal to me `C-l` doesn't clear history anymore.

You redefined the binding to do:
```
bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
```

**Comment by kleinjm** [comment]
Didn't know about `tmux list-keys`, very useful. Yes, that was it. I made another mapping for that in my local. Thanks!
