### ISSUE TITLE
Current window status breaks when switching to shell

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#145]
It appears that when I start vim, the status name for the current window switches to vim. When I go to a shell window and enter a command, it changes to my `pwd`. When I go back to vim, it does not change back to vim in the status bar. 
Please see [screen recording](http://g.recordit.co/OdBDD3b5jW.gif).

**Comment by gpakosz** [comment]
I'm not sure of what's going on exactly. It's way possible your shell configuration interferes with tmux.

Can you please test it with a stock tmux configuration?
```
tmux -L test -f /dev/null
```

**Comment by kleinjm** [comment]
I appears to be somewhat similar behavior. When I start vim, the status switches to vim. When I go back to shell then it stays as vim (not sure if that's expected). However, when I split to a new shell it goes to the `pwd` and stays like that even when switching back into vim.
[Screen recording](http://recordit.co/hmjxy9LWoI/gif/notify)

**Comment by gpakosz** [comment]
First I don't use zsh so I don't know what it usually does upon printing prompt.

> When I go back to shell then it stays as vim (not sure if that's expected)

I would say it also depends on the value of `status-interval`.

Also there's `allow-rename` tmux option. When it's `on`, applications can rename the window using escape sequences which is what your zsh prompt may do.

**Comment by kleinjm** [comment]
`set -g allow-rename off` did the trick. Thanks so much Greg, awesome work!

**Comment by gpakosz** [comment]
You're welcome
