### ISSUE TITLE
How do I change the black color?

### ISSUE THREAD

**Issue by Artem-Schander** [gpakosz/.tmux#146]
Hi gpakosz,

I could not find a setting to manipulate the main background color of the statusline
<img width="1671" alt="bildschirmfoto 2018-03-11 um 17 22 07" src="https://user-images.githubusercontent.com/1243826/37255743-ff8cbcca-2550-11e8-8d48-ad87b620257a.png">

**Comment by gpakosz** [comment]
Hello @Artem-Schander,

You want to edit your `~/.tmux.conf.local` copy and edit the `tmux_conf_theme_status_bg` variable:
```
# status line style
tmux_conf_theme_status_fg='#8a8a8a'                     # light gray
tmux_conf_theme_status_bg='#080808'                     # dark gray
tmux_conf_theme_status_attr='none'
```

**Comment by Artem-Schander** [comment]
Thanks :)
