### ISSUE TITLE
Support for unicode codes

### ISSUE THREAD

**Issue by Pk13055** [gpakosz/.tmux#148]
Currently if you replace a given symbol with its unicode code value (and not the actual symbol itself), it ends up printing the code itself.
![screenshot from 2018-03-17 02-59-35](https://user-images.githubusercontent.com/13479308/37545572-40ba1e1c-298f-11e8-8755-5c73c1548787.png)

Here is the relevant tmux config part (_for reference_)
```
# root indicator
tmux_conf_theme_root='\uf21b'
tmux_conf_theme_root_fg='none'
tmux_conf_theme_root_bg='none'
tmux_conf_theme_root_attr='bold,blink'
```

**Comment by gpakosz** [comment]
The content of the `tmux_conf_theme_` variables are given to tmux mostly unchanged which you can see if you do `tmux show -gv status-left` or `tmux show -gv status-right`.

Likely tmux doesn't interpret `\uf21b`

**Comment by Pk13055** [comment]
How would one work towards interpreting this the right way? Given how useful oh-my-tmux has been for me, I would love to add this. This would serve as a great way for us to add extra symbols (stuff under Nerd Fonts, etc) without having to UTF-8 everything manually. There's a quick fix I can think of. Before passing the config to tmux **directly**, we could:
```bash
echo config > .temp_config
mv .temp_config config
# pass this config (having made the terminal do all the translation for us :D) to tmux
```

**Comment by gpakosz** [comment]
Hey @Pk13055 👋

Do you mind giving the `gh-148` branch a try?
