### ISSUE TITLE
source-file error

### ISSUE THREAD

**Issue by KevinGideon** [gpakosz/.tmux#149]
after source-file ~/.tmux.conf, get error "'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1", and pane is dead.

**Comment by gpakosz** [comment]
Which OS are you running and which version of tmux are you using?

**Comment by blackb1rd** [comment]
I also hit this issue with old system(Centos5) with new tmux version 2.6(compiling from source code).
my old system using zsh as default shell.

**Comment by gpakosz** [comment]
Can you please run
```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
```

and upload the log somewhere, e.g. in a gist?

**Comment by blackb1rd** [comment]
Hi,
From my old system, I did found command error with following as below:

> sed: invalid option -- E

During perform:
> sed -E -e 's/[^ \ta-zA-Z0-9,._+@%/-]/\\&/g'

Is it possible to handle this same as https://github.com/scmbreeze/scm_breeze/commit/b224f4985039457ce38e8d0c9c014628d0d36fb5 ?

Thank you.

**Comment by blackb1rd** [comment]
I have tried to change -E to -r and then everything is work!

**Comment by KevinGideon** [comment]
Hi, 
I hit this issue with rhel6.5, with new tmux version 2.6(compiling from source code).

[conf.log](https://github.com/gpakosz/.tmux/files/1827947/conf.log)

**Comment by gpakosz** [comment]
@KevinGideon I'm almost sure you modified your `~/.tmux.conf` in a way that broke the polyglot. It's both a valid tmux configuration and a shell script **provided you don't modify it**. Please try it with my unmodified `.tmux.conf` and only modify your `~/.tmux.conf.local` copy if you want to override some configuration parameters.

@blackb1rd What you're hitting is different from @blackb1rd. Can you please open a separate issue and indicate what's our OS? `sed -E` is mandated by POSIX and there should be no need to change that.

**Comment by blackb1rd** [comment]
The issue was reported #150

**Comment by KevinGideon** [comment]
@gpakosz I redownload the conf file, and it's OK now. Thank you!
