### ISSUE TITLE
Hyper2

### ISSUE THREAD

**Issue by LockeAG** [gpakosz/.tmux#151]
Recently I switched from iterm2 to Hyper2 , and I Love it .

But we notice a very small detail in tmux , like the tmux bar a little bit off the footer

<img width="1303" alt="screenshot 2018-04-23 17 41 56" src="https://user-images.githubusercontent.com/8461849/39156852-a2461db0-471d-11e8-8759-e38e65e62ec9.png">

And another question where can I change to the same color of my Terminal background in the .tmux config??

thanks

**Comment by gpakosz** [comment]
I suspect launching tmux without my configuration will do the same:
```
$ tmux -L test -f /dev/null
```

My understanding is that the window height has to be a multiple of the font height for the title bar to be at the very bottom

**Comment by gpakosz** [comment]
I overlooked your additional question, adjust the `tmux_conf_theme_status_bg` variable in your `~/.tmux.conf.local` copy.

**Comment by gpakosz** [comment]
Hello @LockeAG 

Are we good?

**Comment by LockeAG** [comment]
Everything perfect gpakosz!!!

thanks very much for all!!

**Comment by gpakosz** [comment]
Alright, closing then.

Happy tmuxing!
