### ISSUE TITLE
Right prompt username color when root

### ISSUE THREAD

**Issue by Kidlike** [gpakosz/.tmux#155]
Is it possible to change the color of the username display when it's root ?

Instead of adding text next to the username like `tmux_conf_theme_root`.

Maybe change the behavior of `tmux_conf_theme_root_fg/bg` or create other variables similar to this ?

**Comment by gpakosz** [comment]
Hello @Kidlike,

Currently it's not possible. But I'll figure out a way to do so.

**Comment by gpakosz** [comment]
Hey @Kidlike 👋

I still don't know how to generalize it, but I gave it 5 minutes today 🎁

Here's what you can do in your `~/.tmux.conf.local` copy:
```
tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{?battery_status, #{battery_status},}#{?battery_vbar, #{battery_vbar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{?#(cut -c3- ~/.tmux.conf | sh -s _root #{pane_tty} #D),#[fg=#ffff00]#[bold]#[blink],}#{username}#[inherit] | #{hostname_ssh} '
```

`#{?#(cut -c3- ~/.tmux.conf | sh -s _root #{pane_tty} #D),#[fg=#ffff00]#[bold]#[blink],}#{username}#[inherit]` will make the username bold, yellow and blinking when root.
Please note you can't use `#[fg=#ffff00,bold,blink]` as my parser is not robust enough 🤷‍♂️

Hope that helps!

**Comment by warp4** [comment]
Changed the line, and now I have a blinking red "root" on a yellow background, while the hostname is white on green :

`....#[fg=#d70000]#[bold]#[blink]#[bg=##ffff00],}#{username}#[inherit] | #[fg=#e4e4e4]#{hostname}'

Next step is howto make the username white, while keeping 'root' blinking red.

**Comment by diego898** [comment]
I think this is a great idea, and is also related to #189

**Comment by gpakosz** [comment]
Closing. The solution in #321 is more elegant.
