### ISSUE TITLE
How extend the original scripts and put some extra options on the statusbar?

### ISSUE THREAD

**Issue by amioranza** [gpakosz/.tmux#156]
Hi,

First things first: Great job!

I want to put more information on my statusbar and more colors, only 3 currently.

I've added more info directly to my left-status-bar on .tmux.conf.local, but I want to make it more flexible turning it flags on and off at my statusbar. Below are my status line from my .tmux.conf.local:

tmux_conf_theme_status_left=' ❐ #S , ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} | GO: #(go version | cut -f3 -d" ") | K8S Ctx: #(kubectl config current-context) | Docker Server: #(docker version     -f {{.Server.Version}}) , Client: #(docker version -f {{.Server.Version}}) '

tmux_conf_theme_status_right='#{prefix}#{pairing} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '

The second line remains untouched, but in the first I've added GO version, Kubernetes context and Docker versions. How can I put it on the main tmux file and turn it optional through toggle settings?

Another point is the option to specify how much colors I can specify for the sections of the statubar, currently it has 3 colors, but I want to use 5 or 6, is it possible?

Thanks.

**Comment by gpakosz** [comment]
> The second line remains untouched, but in the first I've added GO version, Kubernetes context and Docker versions. How can I put it on the main tmux file and turn it optional through toggle settings?

Editing your own `~/.tmux.conf.local` copy is exactly the way to go. When you change the main `.tmux.conf` file you take the risk of diverging from my own modifications.

> How can I put it on the main tmux file and turn it optional through toggle settings?

I'm not sure of how you expect this to  work exactly.

> Another point is the option to specify how much colors I can specify for the sections of the statubar, currently it has 3 colors, but I want to use 5 or 6, is it possible?

For this to work you need to make all `tmux_conf_theme_status_left_fg`, `tmux_conf_theme_status_left_bg` and `tmux_conf_theme_status_left_attr` the same *"length"*. So you want to specify 5 `fg` colors, 5 `bg` colors and 5 `attr` modifiers.

**Comment by amioranza** [comment]
> How can I put it on the main tmux file and turn it optional through toggle settings?
> I'm not sure of how you expect this to work exactly.

The idea is to have multiple software versions ready to use on my tmux statuses but only enable which make sense for the specific machine, i. e.: node version for some node server, php version for some php server, docker, go and any other tool via toggle settings, like enabled or disabled without the need to edit the tmux_conf_theme_status_left or tmux_conf_theme_status_right by myself to include that. Something like a preset for common software to use on the statuses. Somenthing like the POWERLEVEL9K do for the zsh prompt:
https://github.com/bhilburn/powerlevel9k#prompt-customization
The section language segments.

Thanks.

**Comment by gpakosz** [comment]
> The idea is to have multiple software versions ready to use on my tmux statuses but only enable which make sense for the specific machine

This still means machine 1 has a different `tmux_conf_theme_status_left` than machine 2.

**Comment by amioranza** [comment]
Yes, but the way to make it different is via toggle options and not changing the tmux_conf_theme_status_(right|left) instead of having to do that we could just turn on or off the items of status theme. It is just an suggestion. Thanks.

**Comment by gpakosz** [comment]
> Yes, but the way to make it different is via toggle options and not changing the tmux_conf_theme_status_(right|left) instead of having to do that we could just turn on or off the items of status theme

I'm still not following you with what you call "toggle options". Imagine you had `#{go_version}` and `#{k8s}` "segments" instead of having to use `#(...)`:

```
tmux_conf_theme_status_left=" ❐ #S | GO: #{go_version} | K8S Ctx: #{k8s} | ... "
```

Now what are you suggesting? Do you suggest having a common `tmux_conf_theme_status_left` definition for all your machines? E.g. the one above? And then have a "toggles options", e.g.:
```
tmux_conf_theme_go_version=true
tmux_conf_theme_k8s=false
```

Imagine you had that, then on the machine where you set `tmux_conf_theme_k8s=false` your status left will contain `" ❐ 0 | GO: go1.10.2 | K8S Ctx:  | ... "`.

Now you could argue the `#{go_version}` and `#{k8s}` would fully expand to `GO: go1.10.2` and to the empty string if `tmux_conf_theme_go_version=true` and `tmux_conf_theme_k8s=false`.

That still looks fragile to me. And I still believe having different definitions of `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` for different machines makes things less complicated.
