### ISSUE TITLE
Adaption to new tmux version

### ISSUE THREAD

**Issue by Jackey-Huo** [gpakosz/.tmux#157]
Thanks a lot for the share in tmux conf, I've used it for a long time and it's perfectly helpful. But recently I migrant to Arch with tmux 2.7, then I find that some configure command are out of date.
the error message paste below
```
/home/jackey/.tmux.conf:102:usage: bind-key [-cnr] [-T key-table] key command [arguments]                                                                                                                     
/home/jackey/.tmux.conf:103: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:106: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:107: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:108: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:115: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:116: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:117: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:118: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:132: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:133: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:134: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:135: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:136: usage: bind-key [-cnr] [-T key-table] key command [arguments]
/home/jackey/.tmux.conf:14: invalid option: quiet
```
I did some modification to fix it. And I open this issue to ask is there a schedule for .tmux to support new tmux version? And do you need a pull request to fix it?

**Comment by gpakosz** [comment]
Hello @Jackey-Huo,

Works for me. I'm using Archlinux myself:
```
$ tmux -V
tmux 2.7
```

```
$ pacman -Q tmux
tmux 2.7-1
```

```
$ cd ~/.tmux
$ git log -1 --oneline
dd74d33 (HEAD -> master, origin/master, origin/HEAD) fixed typo in README.md
```

Likely you modified you're `.tmux.conf` in a way that's not compatible with tmux 2.7?

As you can see, [there's nothing on line 102](https://github.com/gpakosz/.tmux/blob/dd74d33bee449b95422adaf998c72b5133d4dec5/.tmux.conf#L102) and the `.tmux.conf` file doesn't even contain the word "quiet"

**Comment by Jackey-Huo** [comment]
Oh! sorry that I make a mistake. I simply copy my old settings when migrant to arch OS, and this .tmux file are too old. Now after pull down the new commit, every thing works just fine. Thanks so much for your kindly reply, and sorry for the bother.
