### ISSUE TITLE
How about it runs in windows 10 bash shell?

### ISSUE THREAD

**Issue by NicolasShy** [gpakosz/.tmux#159]
This plugin takes up a lot of my GPU resources when I opened tmux in windows 10 bash shell. First of all it stuck the system for a while. Then it wake up and I can saw the colorful user interface. Thirdly, It heats the graphics card and my computer's fans are turning fast.

**Comment by gpakosz** [comment]
While it's well known it's slow under WSL (because WSL just like Cygwin is slow at forking processes), I'm surprised it heats the graphics card
