### ISSUE TITLE
why it?

### ISSUE THREAD

**Issue by xiahei** [gpakosz/.tmux#16]
hi, i do this:
- 1, install the tmux `sudo apt-get install tmux`
    + and it is tmux2.0
- 2, install powerline `pip install powerline-status` and `sudo apt-get install powerline`
- 3, install your config just like readme `1, 2, 3, 4`
- 4, I change some config as readme
- then I restart terminal and turn into tmux but it does not work at all, just like the original tmux
- and Why?
- anyway, Thx!

**Comment by gpakosz** [comment]
Hello, as `README.md` says, the instructions are just

    $ cd
    $ rm -rf .tmux
    $ git clone https://github.com/gpakosz/.tmux.git
    $ ln -s .tmux/.tmux.conf
    $ cp .tmux/.tmux.conf.local .

You may want to replace `$ rm -rf .tmux` with `$ mv ~/.tmux ~/.tmux.save`.

**This tmux configuration doesn't rely on `powerline-status` nor `powerline`.**

This configuration is a self contained tmux configuration that has a "powerline look & feel". The "powerline look & feel" requires you're using a font that contains the powerline symbols. To do so, you have to follow instructions in `README.md` in [the paragraph entitled "Enabling the Powerline like visual theme"](https://github.com/gpakosz/.tmux#enabling-the-powerline-like-visual-theme).

Please try again or describe better "but it does not work at all".

BTW, as a general tmux tip, for colors to work correctly you want to make sure the `TERM` environment variable is set to `xterm-256color` outside of tmux and is set to `screen-256color` inside of tmux.

Hope that helps.

**Comment by xiahei** [comment]
Hi gpakosz: thx for reply
Just now, i try again, uninstall the `tmux`, remove the file `.tmux`, `.tmux.conf`, `.tmux.conf.local`
and then
```
$ cd
$ rm -rf .tmux
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

But when i start tmux, it still like this, status line nothing append.
![mytmux](https://cloud.githubusercontent.com/assets/14919255/14310680/d94c6198-fc15-11e5-8c1d-2009816e544d.png)

It dose not work like the picture in readme
![yourtmux](https://cloud.githubusercontent.com/assets/14919255/14310662/bb2cbc3a-fc15-11e5-899f-8e9db1e97495.png)

THX again! pardon my poor english!

**Comment by gpakosz** [comment]
Hi again,

Can you tell me which version of tmux you're using? By launching:

    $ tmux -V

Also, make sure all tmux processes are killed and try again please.

**Comment by xiahei** [comment]
2.0

**Comment by gpakosz** [comment]
Can you try with the `2.0` branch then?

    cd ~/.tmux
    git checkout 2.0

And try again.

**Comment by zaxguo** [comment]
plz killall tmux and restart it

**Comment by xiahei** [comment]
thanks @zaxguo @gpakosz 
I try check to 2.0 ,and kill all tmux,
 it still not work ,it maybe my problam, :smiley: 
THX!

**Comment by gpakosz** [comment]
According to your screen shot, you're inside the 7th tmux session which seems to indicate a previous tmux server process is still running

**Comment by xiahei** [comment]
But after i kill then and try again.
![tmux](https://cloud.githubusercontent.com/assets/14919255/14313055/fed5475c-fc21-11e5-8d92-af42f6044379.png)

**Comment by gpakosz** [comment]
Which version of Ubuntu are you running?

**Comment by xiahei** [comment]
Ubuntu15.10

**Comment by gpakosz** [comment]
Works for me. Here are the steps I followed:

    cd /→ ~ cd /tmp
    → /tmp vagrant init ubuntu/wily64; vagrant up --provider virtualbox
    A `Vagrantfile` has been placed in this directory. You are now
    ready to `vagrant up` your first virtual environment! Please read
    the comments in the Vagrantfile as well as documentation on
    `vagrantup.com` for more information on using Vagrant.
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Box 'ubuntu/wily64' could not be found. Attempting to find and install...
        default: Box Provider: virtualbox
        default: Box Version: >= 0
    ==> default: Loading metadata for box 'ubuntu/wily64'
        default: URL: https://atlas.hashicorp.com/ubuntu/wily64
    ==> default: Adding box 'ubuntu/wily64' (v20160329.0.0) for provider: virtualbox
        default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/wily64/versions/20160329.0.0/providers/virtualbox.box
    ==> default: Successfully added box 'ubuntu/wily64' (v20160329.0.0) for 'virtualbox'!
    ==> default: Importing base box 'ubuntu/wily64'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Checking if box 'ubuntu/wily64' is up to date...
    ==> default: Setting the name of the VM: tmp_default_1460029312221_72345
    ==> default: Clearing any previously set forwarded ports...
    ==> default: Fixed port collision for 22 => 2222. Now on port 2201.
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 22 => 2201 (adapter 1)
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2201
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: Warning: Connection timeout. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default:
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default:
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if it's present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
    ==> default: Mounting shared folders...
        default: /vagrant => /private/tmp
    → /tmp vagrant ssh
    Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-34-generic x86_64)

    * Documentation:  https://help.ubuntu.com/

      Get cloud support with Ubuntu Advantage Cloud Guest:
        http://www.ubuntu.com/business/services/cloud

    0 packages can be updated.
    0 updates are security updates.

    vagrant@vagrant-ubuntu-wily-64:~$ tmux -V
    tmux 2.0
    vagrant@vagrant-ubuntu-wily-64:~$ git clone https://github.com/gpakosz/.tmux.git
    Cloning into '.tmux'...
    remote: Counting objects: 353, done.
    remote: Total 353 (delta 0), reused 0 (delta 0), pack-reused 353
    Receiving objects: 100% (353/353), 131.93 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (169/169), done.
    Checking connectivity... done.
    vagrant@vagrant-ubuntu-wily-64:~$ ln -s .tmux/.tmux.conf
    vagrant@vagrant-ubuntu-wily-64:~$ cp .tmux/.tmux.conf.local .

    vagrant@vagrant-ubuntu-wily-64:~$ cd .tmux
    vagrant@vagrant-ubuntu-wily-64:~/.tmux$ git checkout 2.0
    Switched to branch '2.0'
    Your branch is up-to-date with 'origin/2.0'.
    vagrant@vagrant-ubuntu-wily-64:~/.tmux$

    vagrant@vagrant-ubuntu-wily-64:~/.tmux$ tmux

And I ended up having the default look:

![image](https://cloud.githubusercontent.com/assets/553208/14350333/025842ec-fcc9-11e5-9091-7b29a636235b.png)

If you want the powerline look&feel and change the style of the battery bar, you have to edit `~/.tmux.conf.local`.

Hope that helps

**Comment by xiahei** [comment]
Oh! it works!! 
Very Thx!!
![tmux](https://cloud.githubusercontent.com/assets/14919255/14387074/32b14e4a-fdda-11e5-8aff-ab4fcef8884b.png)

**Comment by gpakosz** [comment]
So? What did you change to make it work?

**Comment by xiahei** [comment]
I just try again....and the same as yesterday..then it works.

**Comment by gpakosz** [comment]
Ok. I'm closing this issue then.

**Comment by qq291462491** [comment]
it works! This is the original reason！OMG

**Comment by rahilwazir** [comment]
This https://github.com/gpakosz/.tmux/issues/16#issuecomment-206277590 solves it.
Maybe worth mentioning in README to close all tmux session?

Thanks.
