### ISSUE TITLE
Wrong battery percentage and status with wireless keyboard

### ISSUE THREAD

**Issue by szaffarano** [gpakosz/.tmux#161]
I have a wireless keyboard and a wireless mouse, both of them expose a battery device that makes an incorrect battery status level.  If I exclude ```/sys/class/power_supply/hidpp_battery_*``` in line 271 of tmux.conf:

```sh
 271 # $(find /sys/class/power_supply -maxdepth 1 -iname '*bat*')
```
the status level is ok.  Maybe you can exclude devices with ```scope=Device```?

```sh
$ ls /sys/class/power_supply/hidpp_battery_2/
capacity_level  device  manufacturer  model_name  online  power  powers  scope  serial_number  status  subsystem  type  uevent     

$ ls /sys/class/power_supply/BAT0
alarm     capacity_level  charge_full_design  current_now  device        model_name  present        status     technology  uevent              voltage_now                                   
capacity  charge_full     charge_now          cycle_count  manufacturer  power       serial_number  subsystem  type        voltage_min_design 

$ ls /sys/class/power_supply/hidpp_battery_3 
capacity_level  device  manufacturer  model_name  online  power  powers  scope  serial_number  status  subsystem  type  uevent

$ cat /sys/class/power_supply/hidpp_battery_2/scope    
Device
```

```/sys/class/power_supply/BAT0``` is the only one device that should be analyzed, the others, `hidpp_battery_*` are from my wireless keyboard and mouse devices.

Thanks

**Comment by gpakosz** [comment]
Can you please the branch `gh-161` fixes it for you please?

**Comment by szaffarano** [comment]
No, didn't work.
I made a patch that is working (in my environment).  It uses `find` to select the files where execute `grep`

[tmux-gh-161.patch.txt](https://github.com/gpakosz/.tmux/files/2042894/tmux-gh-161.patch.txt)

**Comment by gpakosz** [comment]
My bad, my change should have been:
```
grep -i -q device "$batpath/scope" 2> /dev/null && continue
```

I updated the branch.
