### ISSUE TITLE
Adding .tmux.conf does not change tmux profile

### ISSUE THREAD

**Issue by krshrimali** [gpakosz/.tmux#162]
I've replaced .tmux.conf with the new .tmux.conf file but it does not change anything on tmux.

Have made sure that there are no running sessions of tmux. When I use other .tmux.conf files, every thing works. Do I need to make some edits to run it?

**Comment by gpakosz** [comment]
Hello @krshrimali,

There's likely a tmux server process still running. You can try sourcing the configuration with:
```
$ tmux source ~/.tmux.conf
```

If sourcing the configuration manually works, that's because there was still a tmux server process running.

**Comment by krshrimali** [comment]
@gpakosz - Awesome! It really works. Great work with the config file!
