### ISSUE TITLE
enabling #tmux_conf_battery_status_charging='⚡ ' # U+26A1 causes weird issues

### ISSUE THREAD

**Issue by AXington** [gpakosz/.tmux#163]
This started today (6-11-18) for me. I've been using .tmux for about a year now and I've always had the U+26A1 character enabled for charging in my environment rather than the up and down arrows.

This morning I started a new session and it put a white bar across the bottom of my screen which pushed out the status bar, and my prompt kept adding a return line before my input.

After some troubleshooting, I determined that it was the line below being enabled that caused the issue:
```#tmux_conf_battery_status_charging='⚡ ' # U+26A1```
(I did this by disabling all my custom settings and then re-enabling them one at a time until it broke, then confirmed by removing the line and seeing it fixed)

I'm not sure what broke the config, I just thought I'd mention this in case anybody else ran into this. For now it's no big deal to just have the default up-down arrows.

OS: Mac (High Sierra 10.13.3).
Emulator: iterm2 (3.1.6)
tmux: 2.7
shell: zsh 5.5.1 (x86_64-apple-darwin17.5.0)
omz theme: agnoster

tmux custom settings:
```
bind a last-window
bind n next-window
```

enabled block to replace C-b with C-a instead of both (so I can just use C-b in my ssh sessions)

powerline symbols enabled

tmux_conf_copy_to_os_clipboard=true

start with mouse mode enabled

**Comment by gpakosz** [comment]
Hi @AXington,

You may want to check your iTerm 2 settings and uncheck "Use Unicode version 9 widths":
![sshot](https://user-images.githubusercontent.com/553208/41241269-c5843f32-6d9c-11e8-85b9-664ca9abced3.jpg)

**Comment by jesuiswk** [comment]
what is the cause of this?
