### ISSUE TITLE
Symbol is not showing in docker container 

### ISSUE THREAD

**Issue by evopen** [gpakosz/.tmux#165]
When I use this tmux config in a docker container. There is a symbol in the left corner which is not showing. 

Is there any way to fix it? 

Thanks.

**Comment by gpakosz** [comment]
Hi @evopen 

I believe you should troubleshoot your `TERM` environment variable value as well as your locale settings. Likely you're not using an UTF-8 locale within your Docker container.

**Comment by evopen** [comment]
sorry, my mistake. I was setting the locale variable inside the container. That did not work.
But setting it in Dockerfile is ok. 

Thanks @gpakosz
