### ISSUE TITLE
The effect of <prefix> stays longer than it should

### ISSUE THREAD

**Issue by ian0371** [gpakosz/.tmux#166]
Let's say I have two panes splitted vertically (using `<prefix> _`).
I want to move my cursor from the left pane to the right using `<prefix> l` and then immediately type `ls`.
After successfully moving the cursor to the right pane, the prefix is still in effect (for about 0.5 seconds after `<prefix> l`).
So what happens when I try to type `ls` is that the first letter 'l' will move my cursor back to the left.
You can reproduce this bug by pressing `<prefix> l` and hitting 'l' as many times as you want.
It also happens with `<prefix>` + `h`, `j`, `k`, `H`, `J`, `K`, `L`.

**Comment by gpakosz** [comment]
Hello @ian0371,

I'm afraid there's nothing I can do. tmux decides when to refresh the status line.

**Comment by ian0371** [comment]
That is so sad. I don't want to keep using `<prefix> q 1` to avoid this side effect.. :(

**Comment by gpakosz** [comment]
Hello @ian0371,

In fact I misunderstood your question. At first I believed you complained about the prefix indicator being displayed in the status line for too long.

But in fact what you want is to tune down the `repeat-time` value:
> Allow multiple commands to be entered without pressing the prefix-key again in the specified time milliseconds (the default is 500).

Hope that helps.

**Comment by ian0371** [comment]
Oh, thanks! I just removed the `-r` flag. Problem solved :)

**Comment by gpakosz** [comment]
I'll consider removing it as well. While it makes sense for the resizing bindings, I'm not sure it makes sense to repeat bindings for pane and window navigation.

**Comment by gpakosz** [comment]
Please leave the issue open, I'll close it with a commit 👍

**Comment by gpakosz** [comment]
In fact I prefer to keep the bindings repeatable but you can set `repeat-time` to `0` in your own `~/.tmux.conf.local` copy.
