### ISSUE TITLE
Does unicode supported for tmux_conf_theme_left_separator_main?

### ISSUE THREAD

**Issue by roachsinai** [gpakosz/.tmux#167]
Well, I mean I want to use symbles list at [powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols), the symbles are coded like `\ue0c0`, 

![image](https://user-images.githubusercontent.com/9500049/42294101-2593aea4-8011-11e8-8bcf-d32d0f149f66.png)

and I have installed the font `nerd-fonts-bitstream-vera-mono`.

I update the `.tmux.conf.local` as:

```
# nerd-fonts-bitstream-vera-mono                                                                                                                                                          
tmux_conf_theme_left_separator_main='\ue0c0'                                                                                                                                              
tmux_conf_theme_left_separator_sub='\ue0c1'                                                                                                                                               
tmux_conf_theme_right_separator_main='\ue0c2'                                                                                                                                             tmux_conf_theme_right_separator_sub='\ue0c3'
```

But, it not works,
![image](https://user-images.githubusercontent.com/9500049/42294063-edbe7f7c-8010-11e8-9b66-20b37f3c00a7.png)

So, would you please help me?

Thank you!

**Comment by gpakosz** [comment]
Hello 

This is the same issue as #148.

tmux doesn't support parsing these. You have to give it UTF-8

**Comment by gpakosz** [comment]
One way to do it is, e.g. using the `printf` shell function:
```
$ printf '\ue0c0'
```

and copy paste the glyph from the terminal to your `~/.tmux.conf.local` copy

**Comment by roachsinai** [comment]
Wow, thanks. I've tried use Python get that symbols, failed. And here I learn a little `Bash` from you, now I understand the solution provide by #148. Thanks.

**Comment by gpakosz** [comment]
Hey @roachsinai 👋

Do you mind giving the `gh-148` branch a try?

**Comment by roachsinai** [comment]
Hi, thanks for your work, but seems only `\ue0c1` worked.

![image](https://user-images.githubusercontent.com/9500049/55844353-768d9b00-5b6f-11e9-9eef-bf8d5e2f6d13.png)

**Comment by gpakosz** [comment]
I updated the branch

**Comment by roachsinai** [comment]
Hi @gpakosz I'm using the lastest commit on branch gh-148 rightnow.
And only `tmux_conf_theme_left_separator_main` works for me. Check the screenshot above.

**Comment by gpakosz** [comment]
Dammit forgot to push!

**Comment by roachsinai** [comment]
lol, push it!

**Comment by gpakosz** [comment]
Pushed!
You have to reload the configuration (`<prefix> + r`)

**Comment by roachsinai** [comment]
Thanks, worked!

**Comment by gpakosz** [comment]
Thanks for testing @roachsinai, I will do more tests and close this issue when the branch is merged

**Comment by roachsinai** [comment]
Got it.
