### ISSUE TITLE
SSH aware hostname in title

### ISSUE THREAD

**Issue by dampfklon** [gpakosz/.tmux#168]
I am trying to add a SSH aware hostname to the title so that i can match against it. But with limited success. I added `#(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)`  to `tmux_conf_theme_window_status[_current]_format` and this works fine but the host part doesn't show up in the title while the rest of the window status does.

Any idea how to achive this?

**Comment by gpakosz** [comment]
Hi @dampfklon,

I just tested and it works for me. Can you run the following command and confirm it contains the `#(cut ...)` command?

```
$ tmux show -wg window-status-current-format
window-status-current-format "#[fg=#080808,bg=#00afff]#[fg=default,bg=default,default] #I #W #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D) #[fg=#00afff,bg=#080808,none]"
```

BtW, you used `#(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)`. In that command, `true` means that you want the hostname to be non empty only when there's an SSH connection detected.

If you always want to display the hostname, use `false`.

**Comment by dampfklon** [comment]
Hi,

```
$ tmux show -wg window-status-current-format
```
leads to exactly the output you given. `false` is intended as i only want the hostname only on ssh windows. 

A screenshot of the Problem the window title says `1 ~ atto` but the terminal title only `1 ~`.

**Comment by gpakosz** [comment]
Hello @dampfklon,

Now I understand what you want but I'm not quite sure how to achieve it.

**Comment by gpakosz** [comment]
What do you think of the following?

```
setw -g automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}} #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)#{?pane_dead,[dead],}"
```

**Comment by gpakosz** [comment]
For get that, you want

```
set -g set-titles-string '#h ❐ #S ● #I #W #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)'
```

on top of what you already did with `tmux_conf_theme_window_status_current_format` and `tmux_conf_theme_window_status_format`.

Hope that helps.

**Comment by dampfklon** [comment]
Thanks a lot, works like a charm. I really appreciate your effort.
