### ISSUE TITLE
Couldn't roll back to original configs

### ISSUE THREAD

**Issue by solomonxie** [gpakosz/.tmux#169]
Hi, 
I'm getting this issue that no matter what I did, `tmux` can't roll back to original look.

I've tried these things:
- `rm -rf ~/.tmux`
- `rm ~/.tmux.conf`
- `rm ~/.tmux.conf.local`
- Copy back original `.tmux.conf`
- In tmux: `tmux source-file ~/.tmux.conf`
- `brew uninstall -f tmux`
- `brew install tmux`

Yet none of these works.
Did I miss something big?

**Comment by gpakosz** [comment]
Hello @solomonxie,

I'm convinced what you're experiencing is that you didn't kill all tmux processes (client and server) before starting over.

A thing to remember. When tmux sources `~/.tmux.conf`, it doesn't

1. reset all settings to default
2. apply settings from `~/.tmux.conf` 

So make sure you kill all tmux processes and you should be fine

**Comment by solomonxie** [comment]
Hi @gpakosz,
thanks a lot! Saved me a chunk of time :)

`tmux kill-server -a` works fine for me.

**Comment by solomonxie** [comment]
btw, I was about to reboot my laptop...

**Comment by gpakosz** [comment]
Are we good?

**Comment by solomonxie** [comment]
All good :)

Sent from my iPhone

On 18 Jul 2018, at 4:46 am, Gregory Pakosz <notifications@github.com<mailto:notifications@github.com>> wrote:


Are we good?

**Comment by gpakosz** [comment]
Alright, closing 👋
