### ISSUE TITLE
Powerline not rendered correctly

### ISSUE THREAD

**Issue by agiuliano** [gpakosz/.tmux#171]
Hi, 
I installed PowerlineSymbols.otf but when trying to change the settings to display powerline. This is the result I have. What am I doing wrong?

![screen shot 2018-07-20 at 2 44 57 pm](https://user-images.githubusercontent.com/1260243/43005745-ad797bb6-8c2b-11e8-9bba-1962432d228a.png)

**Comment by gpakosz** [comment]
Hi @agiuliano 👋

> What am I doing wrong?

Installing `PowerlineSymbols.otf` font I guess? 😅

More seriously. I'm sorry I don't know how to help you. It depends on your OS and your terminal emulator. Please make sure you read https://github.com/gpakosz/.tmux#enabling-the-powerline-look if you didn't already.

Your screenshot clearly shows your editor doesn't render Powerline symbols either. As a first troubleshooting step, I would try installing the Source Code Pro font (which contains the proper powerline symbols) and configure my terminal to use it.

Good luck! 🍀

**Comment by agiuliano** [comment]
Thanks @gpakosz , I thought I installed PowerlineSymbols.otf by just downloading it and then running `fc-cache .fonts`. Is that not enough?

**Comment by gpakosz** [comment]
@agiuliano I honestly don't know. I'm myself using Source Code Pro which has the proper symbols 🤷‍♂️

**Comment by agiuliano** [comment]
@gpakosz alright thanks, which installation guide you followed?

**Comment by gpakosz** [comment]
I installed the Source Code Pro font just like any other font

**Comment by agiuliano** [comment]
I'm using an answer from [here](https://askubuntu.com/questions/193072/how-to-use-the-new-adobe-source-code-pro-font) but when I comment out `tmux_conf_theme_left_separator_main=''` I still have the same issue :(

**Comment by gpakosz** [comment]
I'm sorry but troubleshooting your whole Linux + terminal setup is out of scope for this tmux configuration 😐

You'll have to troubleshoot your setup until the following command prints the Powerline symbols correctly. Please make sure it works outside of tmux first.
```
$ printf '%b\n' '\ue0b0\ue0b1\ue0b2\ue0b3'
```
![image](https://user-images.githubusercontent.com/553208/43015014-83a0a062-8c4e-11e8-9bbd-4b78f9003f34.png)

Good luck! 🍀

**Comment by agiuliano** [comment]
thank you @gpakosz !

**Comment by agiuliano** [comment]
I solved  by installing the font on my mac (not on the remote host) and set iTerm to use the patched fonr for powerline

**Comment by gpakosz** [comment]
Yeah sure. Font has to be configured where the terminal emulator runs.

> Thanks @gpakosz , I thought I installed PowerlineSymbols.otf by just downloading it and then running fc-cache .fonts. Is that not enough?

Your comment made me assume you were running everything on Linux

**Comment by killua99** [comment]
I don't understand why my tmux can't see powerline symbols. 

See the gif for more info.

![tmux powerline](https://thumbs.gfycat.com/ImpureHighlevelBeauceron-size_restricted.gif)

**Comment by gpakosz** [comment]
Hey @killua99,

What do you see when you edit your `~/.tmux.conf.local` copy outside of tmux. Do you see the powerline symbols?

**Comment by killua99** [comment]
Yes I do, I did try that.

I ran `printf '\ue0c0'` and I see the symbol (outsite tmux) I run it with tmux, and see nothing. I edit with vim the `~/.tmux.conf.local` and see the symbol too.

**Comment by gpakosz** [comment]
What's `$TERM` outside of tmux?

**Comment by killua99** [comment]
both xterm-256color

**Comment by gpakosz** [comment]
Inside tmux, this should be `screen-256color`

**Comment by killua99** [comment]
Oh, right, I saw wrong, outsite tmux is xterm-256color, inside tmux is screen-256color. My bad I just saw 256 and skip the rest.

**Comment by gpakosz** [comment]
Alright, are you using an `UTF-8` locale?

**Comment by killua99** [comment]
inside tmux

```locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US"
LC_CTYPE="en_US"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL="en_US"
```

outside tmux:

```locale                                                                       (2s 341ms)
LANG="en_US.UTF-8"
LC_COLLATE="en_US"
LC_CTYPE="en_US"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL="en_US"
```

**Comment by gpakosz** [comment]
I'm sorry I don't know then 🤷‍♂️

You may want to launch tmux without my configuration and see whether symbols are printed correctly:
```
$ tmux -L test -f /dev/null
```

My experience is that problems with fonts and Powerline symbols is either a terminal emulator issue or a tmux issue, but not a configuration issue.

**Comment by killua99** [comment]
was something with fish shell, with the LANG variable, I remove it from fish shell setup and it start working. odd 🤷🏽‍♂️

**Comment by leopepe** [comment]
> Alright, are you using an `UTF-8` locale? What happens when you `export LC_ALL=en_US.UTF-8` before launching `tmux`?
> 
> Also, your animated gif shows you're opening your 26th tmux session. Did you try to kill all tmux processes including the server process after having checked your configuration?

Had the same problem and setting LC_ALL before calling tmux on my .bashrc fixed it. Tmux need it to render the fonts correctly

**Comment by uiloat** [comment]
Mac：
Terminal —— Preference——Profiles——Font——change——choose your font

**Comment by aminnairi** [comment]
Just a quick message for those having this issue, I am on **Archlinux** and I forgot to fill my `/etc/locale.conf` file as stated in the official installation, this has caused my TMUX installation to display weird symbols instead of the powerline ones.

Setting the `LC_ALL=en_US.UTF-8` locale inside the `/etc/locale.conf` file (with administrator privileges) has successfully resolved this issue like said [here](https://github.com/gpakosz/.tmux/issues/171#issuecomment-426048355).

```console
$ sudo vim /etc/locale.conf
```

```
LC_ALL=en_US.UTF-8
```

```console
$ reboot #or logout/login
```

**Comment by madrigal1** [comment]
if you have tried all the above and your symbols aren't rendering correctly 
try running tmux -u 
worked for me

tells tmux to use UTF-8

**Comment by rv-nath** [comment]
Thank you madriga/1.  Your suggestion works perfect.

**Comment by ishtiyaq-td** [comment]
Solved it by adding the following to my `.bashrc` or `.zshrc` file:

```bash
export LC_ALL=en_IN.UTF-8
export LANG=en_IN.UTF-8
```

**Comment by wongjiahau** [comment]
Solved by adding this into my fish config (`.config/fish/config.fish`):

```fish
set -gx LC_ALL en_US.UTF-8
```
After this, start a new `fish` session.

**Comment by MahendraSH** [comment]
I think 
```bash 
tmux -u

```
will help 

and yo can add 
```bash 
alias tmux='tmux -u'
```
