### ISSUE TITLE
Add CPU util, load mem stats

### ISSUE THREAD

**Issue by agiuliano** [gpakosz/.tmux#173]
It would be awesome to have by default resources stats from https://github.com/samoshkin/tmux-plugin-sysstat

**Comment by kleinjm** [comment]
@agiuliano did you get tmux-plugin-sysstat working with oh-my-tmux using `tmux_conf_theme_status_right` or `_left`?

**Comment by Glitches** [comment]
Is it possible to use sysstat?? 
I was trying today and couldn't get it to work...

**Comment by danielporto** [comment]
That would be great!!

**Comment by gpakosz** [comment]
Closing as duplicate of #61
