### ISSUE TITLE
Adding plugins require tmux source

### ISSUE THREAD

**Issue by agiuliano** [gpakosz/.tmux#174]
I installed a couple of plugins in ~/.tmux.conf.local to add some extra info in the bar.
Plugin installation is fine, if I run `tmux source ~/.tmux.conf.local` plugins get loaded and I can see the information on the bar below. But if I close the tmux session and enter again, then only the installed plugin disappear and I have to manually run `tmux source ~/.tmux.conf.local` again to get them loaded.

This is how I specified the plugins

```
 set -g @tpm_plugins '          \
    tmux-plugins/tpm             \
    tmux-plugins/tmux-sensible   \
    tmux-plugins/tmux-cpu        \
    samoshkin/tmux-plugin-sysstat  \
  '
```

this is my bar definition

```
tmux_conf_theme_status_right='#{prefix}#{pairing} #{cpu_icon} #{cpu_percentage} #{sysstat_cpu} , #{sysstat_mem} , #{sysstat_loadavg} | #{username}#{root} | #{hostname}'
```

this is the bar with plugins loaded (after sourcing tmux.conf)

<img width="1128" alt="screen shot 2018-07-25 at 8 20 05 am" src="https://user-images.githubusercontent.com/1260243/43185350-961ce096-8fe3-11e8-8f5e-55b682095d48.png">

and this is what happens every time I start a new tmux session

<img width="1127" alt="screen shot 2018-07-25 at 8 21 09 am" src="https://user-images.githubusercontent.com/1260243/43185399-b659392c-8fe3-11e8-9ef5-4398b6478794.png">

**Comment by gpakosz** [comment]
Hello @agiuliano,

I personally don't use tpm and don't plan to support for it.

That being said, you can try looking at https://github.com/gpakosz/.tmux/issues/61#issuecomment-308939495. It seems people have had some success there.

Good luck!
