### ISSUE TITLE
copy mode does not work on Mac

### ISSUE THREAD

**Issue by everiori** [gpakosz/.tmux#175]
run <prefix> Enter can enter copy mode, but keys like v, H, L does not work at all, press q can exit copy mode

the copy mode looks like this
![snipaste_2018-08-03_12-21-41](https://user-images.githubusercontent.com/5765846/43624112-e3d362d4-9717-11e8-9ac6-9c93e5e5ac4d.png)

**Comment by gpakosz** [comment]
Hello @everiori,

If you want to use Vim like key bindings, you either have to use the `status-keys` and the `mode-keys` options or set the `VISUAL` or `EDITOR` environment variables to `vim` before launching the first tmux process

**Comment by everiori** [comment]
set the EDITOR to vim as below, restart tmux, still does not work

~  echo $EDITOR                                                                                                                                                                                                                                                                                                                                                    
vim

**Comment by gpakosz** [comment]
You have to make sure the tmux server process is restarted as well

**Comment by gpakosz** [comment]
If you don't manage to use `EDITOR` or `VISUAL`, or don't want to rely on them, then you can edit your `~/.tmux.conf.local` copy and uncomment the two lines:

```
# force Vi mode
#   really you should export VISUAL or EDITOR environment variable, see manual
#set -g status-keys vi
#set -g mode-keys vi
```

**Comment by gpakosz** [comment]
Hey @everiori it seems you're right!

Can you please try https://github.com/gpakosz/.tmux/pull/176 and tell me if it fixes it for you?

**Comment by everiori** [comment]
@gpakosz I followed your instruction to restart tmux server, the copy mode works. Then I tried your patch, H and L keys works too. Thanks for your support.
