### ISSUE TITLE
What kind of bash you're using?

### ISSUE THREAD

**Issue by zhuxn** [gpakosz/.tmux#177]
I config the tmux using the config, but the bash doesn't look like in the gif,
Can you share your bash config? Thanks.
--- I don't know where to ask the question, so I create an issue.

**Comment by gpakosz** [comment]
Hello @zhuxn 👋

Are you talking about https://pempek.net/articles/2013/10/27/pretty-elided-shell-prompt/ ?

**Comment by zhuxn** [comment]
Yes, Thanks for your comment
