### ISSUE TITLE
display hostname in window format

### ISSUE THREAD

**Issue by divansantana** [gpakosz/.tmux#178]
Greetings :smile: 

How does one display hostname automatically in the window format?

It seems to detect the hostname correctly and display it in bottom right by default. But I'd like it on the tmux "window tab".

I've tried:

```
~ ᐅ tmux setw -g window-status-current-format "#{hostname_ssh}"                                                               
~ ᐅ tmux setw -g window-status-format "#{hostname_ssh}"
```

And similar.

Also:
```
tmux_conf_theme_window_status_current_format='{#hostname}'
```
But it seems that doesn't work and is blank.

**Comment by divansantana** [comment]
I'm also using zsh and oh-my-zsh.

It seems this works 

```
tmux setw -g window-status-format "#{window_index}:#{pane_title}"
tmux setw -g window-format "#{window_index}:#{pane_title}"
```

but is not as ideal as `#{hostname}` would be.

The former shows tabs like this `2:root@omd: ~` and `3:ssh git.santanas.co.za`

which is not as ideal as just displaying the hostname.

**Comment by gpakosz** [comment]
Hey @divansantana 👋

Can you please give the `gh-168-178` branch a try?

**Comment by divansantana** [comment]
@gpakosz This works great! Thanks for the very quick code.

So this works for me now:
```
tmux_conf_theme_window_status_format='#I #{hostname_ssh}'
tmux_conf_theme_window_status_current_format='#I #{hostname_ssh}'
```

This is great thanks a lot!
