### ISSUE TITLE
Restore default shortcut for next/previous window

### ISSUE THREAD

**Issue by magostinelli** [gpakosz/.tmux#180]
Hello,

i want to restore default key for next and previous window:
CTRL + B, N
CTRL + B, P

How to configure it?

I tried to comment the followinf lines without success:
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window

Regards.

**Comment by gpakosz** [comment]
Hello @magostinelli 👋

Commenting these lines won't have any effect until you restart all tmux processes.

I recommend the following approach: at the end of your `~/.tmux.conf.local` copy, add the following bindings:
```
bind n next-window
bind p previous-window
```

**Comment by magostinelli** [comment]
Thank you very much, it works!

**Comment by dessalines** [comment]
This should be default, mainly because these are the defaults in tmux in general. Especially when I often have embedded tmuxs when ssh'ing into servers.

**Comment by c-bg** [comment]
Just out of curiosity, why does Oh My Tmux not use the default bindings? :)

**Comment by gpakosz** [comment]
Because that's before all my configuration 🙃
I may revisit that part though

**Comment by suricactus** [comment]
I bit weird that I use very nice configuration of tmux, but I have to revert some defaults manually. :(
