### ISSUE TITLE
hostname_ssh when tmux is run on remote machine

### ISSUE THREAD

**Issue by zeeMonkeez** [gpakosz/.tmux#181]
Currently, `#{hostname_ssh}` (and `#{username_ssh}`) do not get interpolated as expected when I `ssh` into a remote machine and run `tmux` there. I would expect username and hostname to be shown in that case, as it is my most common use case (use `tmux` on local machine -> don't show hostname for `#{hostname_ssh}`, run it remotely -> show hostname).

This could be fixed by appending a test for there being an ssh connection when testing `! _is_enabled "$ssh_only" `:

```if ! _is_enabled "$ssh_only" || [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then```

This may break other use cases, however.

**Comment by gpakosz** [comment]
Hello @zeeMonkeez 👋

> Currently, `#{hostname_ssh}` (and `#{username_ssh}`) do not get interpolated as expected when I ssh into a remote machine and run `tmux` there

The hostname and username detection for SSH is orthogonal to which command runs on the remote.

Do you mean you want a remote `tmux` to display `hostname` and `username` **only when it's "sshed into"**? If that's the case, how do you deal with the following:
  1. connect to remote server through ssh, e.g. `$ ssh jonas@example.com`
  2. attach to tmux session ← the remote tmux status line displays `jonas` and `example.com`
  3. from there, ssh into yet another server, e.g. `$ ssh gregory@example.net` ← now what the status line should be?

**Comment by zeeMonkeez** [comment]
That was fast :)

Essentially, when I'm not on the local machine, I would like to see the last `username@hostname` of the chain, no matter how many `ssh` and `tmux` hops are in-between.

In your example 3, I'd expect to see `gregory@example.net`.

That may be difficult to achieve ... But to me, having an indication that in the current pane I am or am not on a remote machine is quite valuable, independent of whether I did `ssh`→`tmux` or `tmux`→`ssh`.

**Comment by zeeMonkeez** [comment]
Thanks makes sense :)
