### ISSUE TITLE
Alt + key not working

### ISSUE THREAD

**Issue by AniketSanghi** [gpakosz/.tmux#182]
I am working in OSX 10.13.6, tmux 2.7

I updated the following code to my .tmux.config file

            bind -n M-Left select-pane -L  # move left
            bind -n M-Down select-pane -D  # move down
            bind -n M-Up select-pane -U  # move up
            bind -n M-Right select-pane -R  # move right

It is not working smooth. Sometimes on pressing Alt+Left, it selects left pane and sometime it writes text "OD" on the terminal and the latter one is more frequent. Similarly for others.

**Comment by AniketSanghi** [comment]
Hello @gpakosz 

Yes, the bindings do work in tmux. Actually it also work with your configuration. 
But the problem is that in 1 of 10 attempts it actually change pane. In rest 9 attempts nothing happened. 
While in the case that I make a normal .tmux.conf file and apply changes then Alt + key works absolutely fines in 10/10 attempts.

**Comment by gpakosz** [comment]
I have no idea, my configuration does nothing to existing `select-pane` bindings.

I tried your bindings and it works just fine here on macOS with iTerm 2

**Comment by AniketSanghi** [comment]
In my iTerm 2 holding the Alt key and using the arrow keys (OA,OB,OC,OD) are typed. May be some system issue. I will check it once. Thanks for your help @gpakosz :)

**Comment by gpakosz** [comment]
Do you still reproduce the problem when you set `setw -g xterm-keys off`?

**Comment by AniketSanghi** [comment]
Yes. No effect.

**Comment by bjesus** [comment]
Same here. No solution to this? I've tried adding window switching with `Alt`+`<num>` but it doesn't have any effect.
```
# switch windows alt+number
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
```

**Comment by alma3lol** [comment]
> Same here. No solution to this? I've tried adding window switching with `Alt`+`<num>` but it doesn't have any effect.
> 
> ```
> # switch windows alt+number
> bind-key -n M-1 select-window -t 1
> bind-key -n M-2 select-window -t 2
> bind-key -n M-3 select-window -t 3
> bind-key -n M-4 select-window -t 4
> bind-key -n M-5 select-window -t 5
> bind-key -n M-6 select-window -t 6
> bind-key -n M-7 select-window -t 7
> bind-key -n M-8 select-window -t 8
> bind-key -n M-9 select-window -t 9
> ```

Hi,
I know it's been a long time, but I got the same problem and solved it.
Go to terminal menu File > Preferences > Shortcuts > Tab 1 then edit the shortcut or just hold a modifier (like Shift) and it should be deleted. The key binding in tmux should work.

**Comment by qizy09** [comment]
I met similar issue, i.e. my configs using `Alt` keys start to fail, using Mac's native terminal. After some debugging, it turns out that we need to check the `Use Option as Meta Key` under Terminal's `Edit` menu, then we could use the `Option` key for `Meta` keybindings. Just to share my personal experience, to same some time for other Mac users with the same issue...

<img width="444" alt="image" src="https://user-images.githubusercontent.com/6061320/163656128-f29c6b3e-89eb-4df9-a3d1-bba1e3ad754d.png">

**Comment by hlwjia** [comment]
> I met similar issue, i.e. my configs using `Alt` keys start to fail, using Mac's native terminal. After some debugging, it turns out that we need to check the `Use Option as Meta Key` under Terminal's `Edit` menu, then we could use the `Option` key for `Meta` keybindings. Just to share my personal experience, to same some time for other Mac users with the same issue...
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/6061320/163656128-f29c6b3e-89eb-4df9-a3d1-bba1e3ad754d.png">

Works like a charm! Thank you!
