### ISSUE TITLE
RGB 24-bit colour support not working in tmux 2.7

### ISSUE THREAD

**Issue by AniketSanghi** [gpakosz/.tmux#183]
I recently updated my tmux from 2.6 to 2.7 and suddenly this tmux configuration failed. After checking for bug I found out that setting `tmux_conf_theme_24b_colour=false` solved the issue.
It worked fine with `tmux_conf_theme_24b_colour=true` in tmux 2.6.

     # RGB 24-bit colour support (tmux >= 2.2), possible values are:
     #  - true
     #  - false (default)
     tmux_conf_theme_24b_colour=false

**Comment by gpakosz** [comment]
Hey @AniketSanghi 👋

Works for me 🤷‍♂️ on macOS and iTerm2.

Outside of tmux I have `TERM` set to `xterm-256color`. Then I set `tmux_conf_theme_24b_colour=true` in my `~/.tmux.conf.local` copy. Inside tmux, `TERM` is `screen-256color`.

![image](https://user-images.githubusercontent.com/553208/44430447-fcd27e00-a59a-11e8-8784-cf3f981237ae.png)

That being said, [tmux CHANGES](https://github.com/tmux/tmux/blob/master/CHANGES) file states:
> * Use RGB terminfo(5) capability to detect RGB colour terminals (the existing
  Tc extension remains unchanged).

**Comment by AniketSanghi** [comment]
Hi @gpakosz 👋 

I again checked it and now it worked fine even with true. Now, I am in a dilemma of what happened back then. Seems like my System really need some working. Thanks for helping :)

**Comment by gpakosz** [comment]
Closing.

Here's the `24-bit-color.sh` script for reference: https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh
