### ISSUE TITLE
Slightly different colors

### ISSUE THREAD

**Issue by Artem-Schander** [gpakosz/.tmux#184]
It's not a big deal. I'm more curious than it bothers me. But there are color differences while i'm in a tmux session. See screenshots.

![bildschirmfoto 2018-08-22 um 12 03 11](https://user-images.githubusercontent.com/1243826/44457633-0c39e180-a604-11e8-9712-aba935fd7306.png)
![bildschirmfoto 2018-08-22 um 12 03 16](https://user-images.githubusercontent.com/1243826/44457634-0c39e180-a604-11e8-9145-a07e06efa95f.png)

**Comment by gpakosz** [comment]
Hello @Artem-Schander 👋

The only thing that affects colors in my configuration is the `tmux_conf_theme_24b_colour` option in your `~/.tmux.conf.local` copy.

Outside of tmux, `TERM` should be `xterm-256color` and inside tmux it will be `screen-256color`.

It really seems to be a vim support question. Inside vim, you can try `set t_Co?` to see how many colors vim detects.

Beside that, I have no idea. Do you reproduce the behavior when you don't use my configuration? (pay attention to kill all tmux processes)

**Comment by Artem-Schander** [comment]
Hi @gpakosz 

thanks for the quick reply and for pointing me in the right direction.
In my case it was the following config:
```bash
if (has('mac') && empty($TMUX) && has("termguicolors"))
    set termguicolors
endif
```
For some reason the if statement seems not to be necessary. It works well without.
Thanks again, im closing this issue. 👍
