### ISSUE TITLE
unknown option: focus-events

### ISSUE THREAD

**Issue by hulatang2018** [gpakosz/.tmux#188]
I got .tmux.conf:16: unknown option: focus-events

**Comment by gpakosz** [comment]
Hello @hulatang2018 👋

Are you sure you're using tmux >= 2.3?

**Comment by hulatang2018** [comment]
Yes. The one comes along with centos 7 is v1.8. 
I installed a new one v2.7. Everything comes beautiful.
So many thanks for sharing!!
