### ISSUE TITLE
Easy change color themes 

### ISSUE THREAD

**Issue by danielporto** [gpakosz/.tmux#189]
Is there a way to select between different color themes instead of
handcrafting every single parameter of the configuration file?
I mean, having some presets such as solarized, light and dark themes
such we can alternate easily when the environment has too much light or
is too dark?

**Comment by Artem-Schander** [comment]
You could put your colors into variables and "handcraft" your config file once.
Here is [my example](https://github.com/Artem-Schander/dotfiles/blob/master/tmux/tmux.conf.local.symlink)

**Comment by gpakosz** [comment]
Hello @danielporto 👋

There's no theming system. @Artem-Schander's way is interesting though. I'll give it five minutes.
If I update my configuration in this direction, I would go with
```
tmux_conf_theme_color_1='#ffffff'
tmux_conf_theme_color_2='#ff0000'
...
```

Because I think I won't survivce reading `tmux_conf_theme_color_black='#ffffff'` 😅

Thanks @Artem-Schander  for chiming in!

**Comment by gpakosz** [comment]
I've many refactorings ongoing so I won't rush this one for the moment

**Comment by naliferopoulos** [comment]
Touching on this issue, I would like to ask if there is any support for loading colors from Xresources. Much of my theming automation workflow is based on utilities exporting themes to Xresources colors which are then parsed in the configuration files of each program I need to theme. I believe it would be a nice feature.

**Comment by diego898** [comment]
I think this would be a great addition!

**Comment by Pasqat** [comment]
> You could put your colors into variables and "handcraft" your config file once.
> Here is [my example](https://github.com/Artem-Schander/dotfiles/blob/master/tmux/tmux.conf.local.symlink)

The best solution finded, I've added gruvbox colorscheme in no time, thanks a lot

**Comment by gpakosz** [comment]
Hello there 👋

There's now a `gh-189-244-255` branch to address this need

**Comment by Pasqat** [comment]
> Hello there 👋
> 
> There's now a `gh-189-244-255` branch up for testing that addresses this need

Thannyou! I will give a look at it
