### ISSUE TITLE
Mounts shown on start and on creation

### ISSUE THREAD

**Issue by warp4** [gpakosz/.tmux#191]
When starting TMux and on creation of new pane & screen, my mounts are shown:
/boot                    : already mounted
/                        : ignored
/home                    : already mounted
/media/moun1             : already mounted
/media/mount2            : already mounted
/media/mount3            : already mounted
/media/mount4            : already mounted
/media/mount5            : already mounted
/media/mount6            : already mounted
/media/mount7            : already mounted
/media/mount8            : already mounted
/media/mount9            : already mounted
/media/mount10           : already mounted
/media/mount11           : ignored
/media/mount12           : ignored
/media/mount13           : ignored

**Comment by gpakosz** [comment]
Hello @warp4,

When tmux creates a pane, it launches a login shell, and likely you have `mount` commands in your `~/.bash_profile` or in your `~/.bashrc` file.

**Comment by warp4** [comment]
Shoot, you are right.
Forgot all about this, once added for test purpose, in my .bash_profile!
Thank you.

**Comment by gpakosz** [comment]
BTW, you can test for `$TMUX`, e.g.
```
[ -z "$TMUX" ] && export TERM=xterm-256color
```

**Comment by warp4** [comment]
Already 
`added env TERM=xterm-256color /bin/bash `
to my guake terminal

**Comment by warp4** [comment]
changed it by adding your idea to .bash_profile instead of Guake
