### ISSUE TITLE
Empty space below status line in maximised/fullscreen window

### ISSUE THREAD

**Issue by sixtyfive** [gpakosz/.tmux#193]
Hi, is there any way to make the empty space below the status line go away or at least debug where it's coming from? It's only present when the windows is maximised or fullscreen. Gnome-Terminal 3.28.2, tmux 2.7, latest Budgie.

![image](https://user-images.githubusercontent.com/192860/46920448-b45d9c80-cfee-11e8-9435-a7712e294d78.png)

**Comment by sixtyfive** [comment]
Huh! Never noticed that before ... classic case of "always blame the new thing". Font size changed, happy now. Thank you! :-)

**Comment by gpakosz** [comment]
No worries!

Enjoy 🤝

**Comment by qins** [comment]
Just now press `ctrl +` in my hyper terminal. The pain in ass gone away! 😆 And that's a long time pain. Thank you!
