### ISSUE TITLE
status bar not reach the screen bottom

### ISSUE THREAD

**Issue by Ehco1996** [gpakosz/.tmux#194]
here is the pic 

![](http://opj9lh0x4.bkt.clouddn.com/18-10-15/1331824.jpg)

how can i fix it ?

thanks

**Comment by gpakosz** [comment]
Hello @Ehco1996 

Please see https://github.com/gpakosz/.tmux/issues/193

**Comment by gpakosz** [comment]
I'm personally using the Source Code Pro font which already comes with Powerline symbols.

There's no universal answer. You have to tweak the settings of your terminal emulator (I use iTerm2) like font size and line height.

**Comment by Ehco1996** [comment]
thanks a lot ，after change the font horizontal  and vertical, find the right config
