### ISSUE TITLE
Checking if currently on tty

### ISSUE THREAD

**Issue by dbrw** [gpakosz/.tmux#197]
Hi, I use this wonderful config of tmux all my machine (around 5 of them) which tmux installed. Great config!

I have one question: How to check if currently I have no UTF support (like on TTY) so that I can change the separators character based on it? Some times I need to work from TTY on my local machine.

Thank you for any leads.

**Comment by dbrw** [comment]
Thank, you!
Will try it soon!

**Comment by gpakosz** [comment]
Did you edit your own `~/.tmux.conf.local` copy and reload the configuration?

**Comment by dbrw** [comment]
Yes, I did.
I even restarted my laptop.

**Comment by gpakosz** [comment]
Well if `#{?client_utf8} reports `true`, then it means your system is configured with an UTF-8 capable locale. So looking for UTF-8 capability is a dead end.

That being said, maybe looking at `#{pane_tty}` variable will work for you.

For exemple, on Linux:
```
tmux display -p '#{?#{m:/dev/tty*,#{pane_tty}},yep,nope}'
```
Should display `yep` when you're using a TTY and `nope` when using a terminal emulator.
If that works, you can try the following combination
```
tmux_conf_theme_left_separator_main='#{?#{m:/dev/tty*,#{pane_tty}},,}'
...
```

**Comment by dbrw** [comment]
I checked your command and it return `nope` even on tty. For work around, I use KMSKON on tty so, I have access to true colors.

I think with this we can close this issue. Thank you for the great support!
