### ISSUE TITLE
Why my vim displayed errorly?

### ISSUE THREAD

**Issue by Nobelheaven** [gpakosz/.tmux#199]
![2018-11-16-233141_1910x1077_scrot](https://user-images.githubusercontent.com/33632101/48630756-fcaa1900-e9f7-11e8-911d-c42057ec9893.png)

**Comment by gpakosz** [comment]
Hello @Nobelheaven,

You need to double check your Vim settings.
Here are the things that are important:
- outside tmux, `TERM` should be `xterm-256color`
- inside tmux, `TERM` should be `screen-256color` or `tmux-256color`.

From there, refer to the Vim manual.
See also https://github.com/tmux/tmux/wiki/FAQ

**Comment by Nobelheaven** [comment]
I have double checked my Vim settings :outside tmux, TERM is xterm-256color
inside tmux, TERM is screen-256color.But the highlight in my Vim inside tmux still display errorly.What should I do?
![2018-11-17-084537_949x143_scrot](https://user-images.githubusercontent.com/33632101/48654314-dc557b00-ea46-11e8-8edb-64415a4427e1.png)
![2018-11-17-084638_942x109_scrot](https://user-images.githubusercontent.com/33632101/48654315-dcee1180-ea46-11e8-9b01-8a22cdaa09f6.png)

**Comment by Nobelheaven** [comment]
I have dealt with it.Thanks.

**Comment by gpakosz** [comment]
@Nobelheaven can you please tell us what was wrong in your case, so that people searching closed issues can benefit from your experience?

Thank you

**Comment by gpakosz** [comment]
@Nobelheaven Well... That's definitely not what the tmux manual recommends 🤷‍♂️

I would recommend you to give another look at your Vim settings, e.g. `termguicolors`
