### ISSUE TITLE
error with: "'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127"

### ISSUE THREAD

**Issue by bi-kai** [gpakosz/.tmux#201]
error comes when source config file:
![image](https://user-images.githubusercontent.com/15070379/48674849-cef5d900-eb8b-11e8-8fb1-d662d68dd531.png)

how to fix this?

**Comment by gpakosz** [comment]
Hello @bi-kai 👋

Your screenshot makes me believe you altered `.tmux.conf` to combine it with `tpm`, which I personally don't use and as such can't support.

Thanks for your understanding.

**Comment by bi-kai** [comment]
thx @gpakosz, I removed tpm, and install plugins manually, it's all right now.
