### ISSUE TITLE
Error on Linux

### ISSUE THREAD

**Issue by akoutmos** [gpakosz/.tmux#203]
First off...thanks for the awesome tmux configuration files! I've been using them on my OSX machine for quite a while now and recently migrated over to a Linux machine but seem to be having some issues.

Whenever I start tmux on my Linux box I get the following error:
```
<'cut -c3- ~/.tmux.conf | sh -s _username /dev/pts/6 false %25' not ready><'cut -c3- ~/.tmux.conf | sh -s _root /dev/pts/6 %25' not ready>
```

Curious if you had any thoughts as to why this is happening? Thanks in advance :)

**Comment by gpakosz** [comment]
Hello @akoutmos 👋

What's the version of tmux?
What happens when you launch the `$ cut -c3- ~/.tmux.conf | sh -s _username` command inside a pane?

**Comment by akoutmos** [comment]
Thanks for the quick reply. When I run that I see my username. The error only flashes for a split second and doesn't appear to have any impact on the running tmux session.

![tmux-error](https://user-images.githubusercontent.com/4753634/48974298-82dee480-f022-11e8-95ad-080bd25f6184.png)

**Comment by akoutmos** [comment]
Gotcha. I am currently using zsh along with oh-my-zsh (although only a small group of plugins).

**Comment by gpakosz** [comment]
Maybe you can try adding `default-shell /bin/sh` to your `~.tmux.conf.local` copy to see if it improves the situation.

**Comment by gpakosz** [comment]
Forget that, 

Can you please try:
```
$ tmux run-shell 'echo $0'
```

please?

**Comment by akoutmos** [comment]
I get `sh` when running that

**Comment by gpakosz** [comment]
So do I. So my hypothesis seems to be off 😐

**Comment by akoutmos** [comment]
No worries. It doesn't seem to be causing any issues aside from the message flash. Thanks for help and for the awesome tmux config :)

**Comment by gpakosz** [comment]
Can you give the `mosh` branch a try and tell me if the flashing is shorter?

**Comment by akoutmos** [comment]
Yup. Still happens on that branch as well.

**Comment by gpakosz** [comment]
And out of curiosity, is `/bin/sh` an alias to some heavy weight shell on your system? And BTW which Linux distribution is it?

**Comment by akoutmos** [comment]
I am running LInux Mint 18.3 and `/bin/sh -> dash`

**Comment by Frederick888** [comment]
I can also see a warning says `sh -s _root /dev/pts/1 %0' not ready` under Raspbian.

**Comment by gpakosz** [comment]
I'm afraid there's nothing I can do. If the system is busy, tmux will just print `<command not ready>` and there's pretty much nothing I can do about it 😐
