### ISSUE TITLE
Failed Pasting in Vim

### ISSUE THREAD

**Issue by John-Yao** [gpakosz/.tmux#204]
I can yank from tmux and copy to clipboard when using copy-mode-vi(force vi.). But I failed to pasting to vim with C-B-],some error occurs
① refer to copied-text
② refer to pasted-text in vim
![image](https://user-images.githubusercontent.com/22048231/48978572-3067fb80-f0e8-11e8-8a85-35998ad85522.png)

**Comment by gpakosz** [comment]
Hello @John-Yao 👋

I'm not sure what your exact scenario is.
Can you please try again without my configuration and tell me what happens?
```
$ tmux -L test -f /dev/null
```

**Comment by John-Yao** [comment]
Thanks!
I try switch Vim to paste mode, It work better but it seem paste in a error position:
![image](https://user-images.githubusercontent.com/22048231/48979181-d66c3380-f0f1-11e8-8100-8aaa693821bf.png)
It result to:
![image](https://user-images.githubusercontent.com/22048231/48979192-f1d73e80-f0f1-11e8-80c0-730ae0265d66.png)
Any suggests

**Comment by gpakosz** [comment]
Looks like you pasted while being outside Vim's insert mode

**Comment by John-Yao** [comment]
Thanks for your patient!
I  switch Vim to paste mode(:set paste),change to insert mode(:i),and C-B-]
It work fine!
