### ISSUE TITLE
Italics and the default terminal choice

### ISSUE THREAD

**Issue by jetzerb** [gpakosz/.tmux#205]
I use the [bat](https://github.com/sharkdp/bat) utility in place of cat and/or less.

When used within tmux, though, it was [rendering a lot of reverse text](https://github.com/sharkdp/bat/issues/339#issuecomment-441810117).  Turns out that's due to a deficiency in the "screen" based terminals, and the reverse text was _supposed to be_ italics.

Sure enough, if I follow the [advice from the tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round) and set the default terminal to "tmux", the italics and reverse text are rendered correctly.  In my very limited amount of usage since I made the change, I haven't noticed any problems when using "tmux" terminal rather than the ["screen-256color"](https://github.com/gpakosz/.tmux/blob/ffb1c54769fc78643328ff0ebdc266a99537d3fa/.tmux.conf#L12) used here.

Looks like the [initial commit](https://github.com/gpakosz/.tmux/commit/dcc734f6f754fa292d24dfc7123aefed550992da#diff-404ba9c46ceac3673911dd713648cee5) of .tmux.conf back in 2012 used "screen-256color" and it's just been that way ever since.  Perhaps it's time for an update?

**Comment by gpakosz** [comment]
Hello @jetzerb 

Thanks for porting this to my attention.

Considering the amount of support I to for people who don't set `TERM` properly outside and inside tmux, I would prefer to stay conservative and keep `screen-256color` in `.tmux.conf`.

That being said, I believe having the reference `.tmux.conf.local` file showing off
```
# Use tmux terminal description if you want to use italics 
# set -g default-terminal "tmux"
```

What do you think?

**Comment by gpakosz** [comment]
It may be too early for it to be a default choice.

Here's Vim `8.1 (2018 May 18, compiled Oct 29 2018 06:56:05)` launching inside tmux `2.8` on macOS High Sierra:
```
E558: Terminal entry not found in terminfo
'tmux' not known. Available builtin terminals are:
    builtin_amiga
    builtin_beos-ansi
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
```

**Comment by BenKettlewell** [comment]
Encountered the same problem. I went with
```set -g default-terminal "ansi"
  7 set -as terminal-overrides ',xterm*:sitm=\E[3m'
```
And so far no issues.

**Comment by gpakosz** [comment]
Hi there 👋

I pushed the `gh-205-382` branch that uses `tmux-256color` when available.
