### ISSUE TITLE
Tmp Plugins for status bar not working

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#206]
I've been able to install some plugins using tmp and the alternate syntax. I've verified they're in the `~/.tmux/plugins/`.

I cannot, however, get any of the status bar options working. Ie. see this branch on my dotfiles
https://github.com/kleinjm/dotfiles/commit/379f5e9f929494ccab174e1f29aaaa11fdde81dc

```
tmux_conf_theme_status_right='Down: #{download_speed} #{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} #{pairing}#{prefix} #{battery_status} #{battery_bar} #{battery_percentage} , %R , %d %b | #{username} | #{hostname} '
```
Will output the following.
![image](https://user-images.githubusercontent.com/2565158/49245473-77076f80-f3e0-11e8-9327-91b857976c1e.png)

For a split second when refreshing tmux with `prefix+r`, I see some numbers but they immediately go away. I'm guessing this has to do with how tmux redraws but I'm not too familiar with what happens under the hood.

**Comment by gpakosz** [comment]
Hello @kleinjm 👋

I'm sorry but I don't use tpm so you're on your own.

You may understand what's going on by inspecting the output of  `$ tmux show -g status-left` and `$ tmux show -g status-right`.

Hope that helps!

**Comment by kleinjm** [comment]
It looks as if the values are being added properly but perhaps they should be getting interpolated?

```sh
> tmux show -g status-right
status-right "#(cut -c3- ~/.tmux.conf | sh -s _battery)#[fg=#080808,bg=default,none]#[fg=#8a8a8a,bg=#080808,none]Down: #{download_speed} #{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} #[fg=#e4e4e4]#[bg=none]#[none]#{?session_many_attached,👓,}#[fg=#e4e4e4]#[bg=none]#[none]#{?client_prefix,⌨,} #{@battery_status} #{@battery_bar} #{@battery_percentage} #[fg=#8a8a8a,bg=#080808,none] %R #[fg=#8a8a8a,bg=#080808,none] %d %b #[fg=#d70000,bg=#080808,none]#[fg=#e4e4e4,bg=#d70000,none] #(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} false #D) #[fg=#e4e4e4,bg=#d70000,none]#[fg=#000000,bg=#e4e4e4,bold] #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} false #D) "
```
Anyway, thanks for the help. I'll see what I can figure out.

**Comment by gpakosz** [comment]
It likely means tpm ran too soon or didn't run at all.

**Comment by kleinjm** [comment]
That's 100% true. I moved ` '~/.tmux/plugins/tpm/tpm'` to the bottom of `tmux.conf` instead of my local config and that seems to have worked. Any chance we could get an option for that? Just a simple boolean `load_tmp` would do but I can see a `final_load_command` sort of option being useful as well

**Comment by gpakosz** [comment]
I think I'm going to raise the tmux minimal version. In which case I'll use `source -q` and this should help `tpm` integration from within people's `~/.tmux.conf.local` copy

**Comment by pat-s** [comment]
Hm, neither running `source -q` nor putting the `tmp` init call into `.tmux.conf` worked for me. Did I miss something here? I even get an error when putting `run '~/.tmux/plugins/tpm/tpm'` into `.tmux.conf`.

**Comment by kleinjm** [comment]
What's the error?

Here's the relevant line in my tmux.conf all the way at the bottom. It's the only diff between my tmux conf and the one in this repo.
https://github.com/kleinjm/dotfiles/blob/cf56b547b8958a9add2517625cb7ff1d83f4c8d5/tmux/.tmux.conf#L1184-L1186

**Comment by taybin** [comment]
The error is `'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127`.  On OSX, I had to put the `run tpm` line before the `# -- 8< ------------------------------------------------------------------------` section at the end, `sh` errors on the bad syntax of `n -b '~/.tmux/plugins/tpm/tpm'` being passed to it.

That fixes the syntax error, but I still can't get tmux-cpu to work.

I'm not sure how `source -q` would make a difference.  Doesn't it just suppress error messages?

**Comment by taybin** [comment]
And right after debugging all that, I put the `run tpm` back where @kleinjm suggested it in the first place and it's suddenly working.  Not really sure what happened, or how stable the current setup is.  🤷‍♂
