### ISSUE TITLE
Status bar to display hostname on ssh

### ISSUE THREAD

**Issue by bserrao** [gpakosz/.tmux#208]
Hi, 
The issue i'm facing is the following:
1- I connect over ssh to a jump machine where i have tmux 
2- Attach to existing tmux session or open a new one. (Here everything works as supposed i'm able to see username and host correctly)

![image](https://user-images.githubusercontent.com/8951686/49640005-4d63cf00-fa04-11e8-91f0-2ef7fc158c1d.png)

3- ssh to another machine. Here i would like to have the username and host of the machine i've connected but i get the following

![image](https://user-images.githubusercontent.com/8951686/49640130-a6336780-fa04-11e8-946a-769022195943.png)

It's possible to show the hostname i'm connected to?

Thanks

**Comment by gpakosz** [comment]
Hello @bserrao 👋

I find it strange that `/usr/bin/ssh` ends up being shown as hostname 🤔

I understand that your situation is the following:
  - you're using `host1`, which is your desktop or your laptop and there `tmux` is not running
  - then from `host1`  you `ssh` into `host2`
  - then once connected to `host2`, you attach to a running `tmux` session ← my understanding is that `host2` is in fact `s4gesin2`, as per your screenshot
  - and then you ssh to `host3` from `host2` = `s4gesin2`.

Is that correct?

**Comment by bserrao** [comment]
yep, that's correct.

**Comment by gpakosz** [comment]
Alright, can you please give me the following details?
- OS running on `s4gesin2`
- `tmux` version on `s4gesin2`
- OpenSSH version on `s4gesin2`

Thank you

**Comment by bserrao** [comment]
OS: Centos Release 6.7
Tmux 2.6 (Installed as user, no root previleges)
OpenSSH_5.3p1

**Comment by gpakosz** [comment]
Alright, I'll need a bit of help.

Debugging is tricky but feasible, please follow the following steps.

1. from `s4gesin2`, open a new `tmux` window
2. and run the following command `tmux display -p '#{pane_tty}'` → let's pretend the output is `/dev/ttys050`
3. from that *same pane*, `ssh` into `host3`
4. now from `s4gesin2`, split the window to have a second pane
5. from that second pane, run `cut -c3- ~/.tmux.conf | sh -sx _hostname /dev/ttys050` ← this is important to use the tty from which you initiated the `ssh` connection to `host3`

And please paste the output of `cut -c3- ~/.tmux.conf | sh -sx _hostname /dev/ttys050` in a code block here.

**Comment by gpakosz** [comment]
Ah that's interesting.

It seems my conf is confused by your script. In the debug output, we can see `ssh_parameters=' /usr/bin/ssh c4caredb2'` and `ssh -G /usr/bin/ssh c4caredb2` and this is the culprit.

```
$ ssh -G FOOBARBAZ | grep hostname
hostname FOOBARBAZ
canonicalizehostname false
```
explains why `ssh -G /usr/bin/ssh whatever | grep hostname` answers `/usr/bin/ssh` and that's what you end up seeing displayed.

Can you please paste the output of `ps -t /dev/pts/3 -o command=`?
Where `/dev/pts/3` is the TTY from which the `ssh` command is issued.

**Comment by bserrao** [comment]
sure, here goes

```
-bash
/bin/bash /usr/bin/ssh c4caredb2
/usr/bin/ssh_orig c4caredb2
sudo tee -a /var/log/audit_users/tm504391/tm504391-pts3.ssh.log
tee -a /var/log/audit_users/tm504391/tm504391-pts3.ssh.log

**Comment by gpakosz** [comment]
Thank you.

For now, I'm not sure how to solve this in the general case. And I'm inclined to categorize this issue as enhancement rather than bug.

**Comment by bserrao** [comment]
Okay, thanks for you time.
I understand this isn't the usual behaviour (probably it's only me), so it might not make sense to make changes. If you remember something i can try to change on my side only, to make it work let me know. 

I'll also have look at my script to see if i can make any changes that work.

**Comment by bserrao** [comment]
Hey there,
I haven't updated in a while... but i've just tried the new version
![image](https://user-images.githubusercontent.com/8951686/138255751-478a082f-7840-47d3-9eb1-dcf4a46dead6.png)

This is on the bastion host (jump machine), no uptime, user or hostname shown.
The older version i was using displays like this:
![image](https://user-images.githubusercontent.com/8951686/138256224-622c1743-d324-4dfa-9961-819d0d8cb1d0.png)

**Comment by gpakosz** [comment]
You need to reload the configuration with `<prefix> + r` after pulling changes 🙂

**Comment by gpakosz** [comment]
Does the `master` branch work?

**Comment by gpakosz** [comment]
BTW can you share again the `ssh` script you use to replace the `ssh` command?

**Comment by bserrao** [comment]
Sure,
```
user=`who am i|awk '{print $1}'
sess=`tty|awk -F '/' '{print $3$4}'

/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 "$@"|sudo tee -a /var/log/audit_users/$user/$user-$sess.ssh.lo
```

**Comment by gpakosz** [comment]
So I used the same script as you and with the current commit (b81ccf08007e7203ae4d2401bc2f7b6972eba7f7) in the `gh-208` branch, I see the proper username and hostname in the status bar

**Comment by gpakosz** [comment]
![image](https://user-images.githubusercontent.com/553208/139846644-1e33355c-90e0-41a2-ba53-edf8e911a0ef.png)

👆 In the screenshot above, I did
- create the right pane
- run `tmux display -p '#{pid} #{client_pid} #{pane_pid} #{pane_tty}'`
- use the local `./ssh` wrapper script that calls `/usr/local/bin/ssh` while piping to `tee`
- go back to the left pane
- run `COLUMNS= ps -t /dev/ttys017 -o user= -o pid= -o ppid= -o stat= -o command=` (you don't need the `=XXXXX...` part) to see the process tree
- run `cut -c3- ~/.tmux.conf | sh -s _pane_info 53102 /dev/ttys017` where `53102` is the `pane_pid` of the right pane and `/dev/ttys017` is the TTY of the right pane

As you can see, username and hostname are properly detected

**Comment by bserrao** [comment]
Hum.... 😄   I think we are close here!

# First pane
```
[tm504391@gesin2 ~]$ tmux display -p '#{pid} #{client_pid} #{pane_pid} #{pane_tty}'
2114 2078 6316 /dev/pts/2
[tm504391@gesin2 ~]$ ssh inapps
```

# Second pane
```
[tm504391@gesin2 ~]$ cut -c3- ~/.tmux.conf | sh -s _pane_info 6316 /dev/pts/2
16438:tm504391:/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
```

```
cut -c3- ~/.tmux.conf | sh -sx _hostname $(tmux display -p '6316 /dev/pts/2 false true #h')
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
+ _tmux_version=320
+ command -v pkill
+ _hostname 6316 /dev/pts/2 false true gesin2
+ pane_pid=6316
+ pane_tty=/dev/pts/2
+ ssh_only=false
+ full=true
+ h_or_H=gesin2
++ _pane_info 6316 /dev/pts/2
++ pane_pid=6316
++ pane_tty=pts/2
++ case "$_uname_s" in
++ awk -v pane_pid=6316 '
        ((/ssh/ && !/-W/) || !/ssh/) && !/tee/ {
          user[$2] = $1; if (!child[$3]) child[$3] = $2; pid=$2; $1 = $2 = $3 = ""; command[pid] = substr($0,4)
        }
        END {
          pid = pane_pid
          while (child[pid])
            pid = child[pid]

          print pid":"user[pid]":"command[pid]
        }
      '
++ ps -t pts/2 --sort=lstart -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
+ pane_info='16438:tm504391:/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ command='tm504391:/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ command='/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
++ _ssh_or_mosh_args '/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
++ case "$1" in
+++ printf %s '/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+++ perl -n -e 'print if s/(.*?)\bssh\b\s+(.*)/\2/'
++ args=
++ printf %s ''
+ ssh_or_mosh_args=
+ '[' -n '' ']'
+ _is_enabled false
+ '[' xfalse = xtrue ']'
+ '[' xfalse = xyes ']'
+ '[' xfalse = xenabled ']'
+ '[' xfalse = x1 ']'
+ hostname=gesin2
+ printf '%s\n' gesin2
gesin2
```

**Comment by gpakosz** [comment]
Ah thanks for the feedback!

I pushed a commit to the `gh-208` branch that should wrap it up!

In `_ssh_or_mosh_args()`, the regex I was using didn't match `ssh_orig`. The command had to match `ssh` and nothing else: `perl -n -e 'print if s/(.*?)\bssh\b\s+(.*)/\2/'`

I rewrote it to support `sshxxxx` as well as `dbclient` which is the name of the Dropbear SSH client

**Comment by bserrao** [comment]
No, thank you for putting so much effort into this :)
I confirm the hostname now shows correctly which is a huge improvement for me 🎉 , but now the user isn't showing up.
I believe it's something minor with the regex also... but don't bother if it's something more awkward. 

Dunno if this helps... Tried with ssh hostname and ssh user@hostname, same behavior 
```
+ pane_info='15268:tm504391:/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ command='tm504391:/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ command='/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
++ _ssh_or_mosh_args '/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
++ case "$1" in
+++ printf %s '/usr/bin/ssh_orig -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+++ perl -n -e 'print if s/.*?\b(ssh|dbclient).*?\b\s+(.*)/\2/'
++ args='-o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
++ printf %s '-o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ ssh_or_mosh_args='-o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps'
+ '[' -n '-o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps' ']'
++ awk '/^user / { print $2; exit }'
++ ssh -G -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
+ username=
+ '[' -z '' ']'
++ ssh -T -o ControlPath=none -o 'ProxyCommand=sh -c '\''echo %%username%% %r >&2'\''' -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
++ awk '/^%username% / { print $2; exit }'
+ username=
+ printf '%s\n' ''

```

**Comment by gpakosz** [comment]
This is your `ssh` script interfering again 😅

Can you please run
```
$ ssh -G -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
```

and
```
$ ssh -T -o ControlPath=none -o 'ProxyCommand=sh -c '\''echo %%username%% %r >&2'\''' -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
```
?

**Comment by bserrao** [comment]
Hello, 

The second ssh shows this error: `percent_expand: unknown key %`

**Comment by gpakosz** [comment]
And what does the first one say?

```
$ ssh -G -o ServerAliveInterval=300 -o ServerAliveCountMax=3 inapps
```
This should print out all the values the ssh client will use to connect to the remote server.

**Comment by gpakosz** [comment]
Also can you please try
```
$ ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" inapps
```

**Comment by bserrao** [comment]
Hey there, sorry for the late feedback but work had been crazy this days...

The ssh version in this machine doesn't have the -G option, and the error is the same using ". (unknown key %r)
But like i said before... it's perfect like this :)

Cheers

**Comment by gpakosz** [comment]
Can you please share the version of your ssh client? Is this OpenSSH Client?

**Comment by bserrao** [comment]
OpenSSH_5.3p1

**Comment by gpakosz** [comment]
That's indeed an old version but it should support `%r`.

My understanding is that your client understands `%h`  
```
$ ./ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %h >&2'" inapps
```
But not `%r`
```
$ ./ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %r >&2'" inapps
```

I have a last question please.
Does your `man ssh_config` have a section about `TOKENS` that mentions tokens accepted by `ProxyCommand`?
![image](https://user-images.githubusercontent.com/553208/140929627-f1775172-811b-4559-9fbc-931e00eefdbf.png)

**Comment by gpakosz** [comment]
Hey @bserrao 👋

I installed rhel6 with Vagrant and played with this old version of OpenSSH client.

I forced pushed the `gh-208` branch and I believe this should improve things and display the username provided you have public key authentication configured for the remote host.

**Comment by bserrao** [comment]
Hey @gpakosz 
Sorry for the delay... the man on ssh_config doesn't have the TOKENS section.
Also the last update still doesn't display the username 😢, but for me the host is the most important and it's there... 😃 
Thanks a lot for your work

Cheers

**Comment by gpakosz** [comment]
Alright! I'm tenacious 😅

I forced pushed again. What I pushed had a typo 😢

I believe I'm very close to your setup. While I understand username it's not so important to you, now that I understood that you have a script that replaces the original `ssh` command and that you're running `OpenSSH_5.3p1` I see no blocker beside my own bugs and displaying the username should work.

Can you please try again when you have some more spare minutes? 🙏

**Comment by gpakosz** [comment]
Thanks @bserrao for your patience 👍

I'll merge the branch soon and move on to other features 🎉
