### ISSUE TITLE
How can start-up tmux and splitting in two windows?

### ISSUE THREAD

**Issue by dslackw** [gpakosz/.tmux#209]

**Comment by gpakosz** [comment]
Hello @dslackw 👋

I'm sorry for the late reply.

This is really a general tmux support question.
That being said, everything you can do with stock tmux, you can do it by putting commands in your `~/.tmux.conf.local` copy:
```
...

# move status line to top
#set -g status-position to

new-session
split-window
```

**Comment by dslackw** [comment]
Thanks for the answer @gpakosz
