### ISSUE TITLE
username/hostname in right-status can't be displayed under WSL

### ISSUE THREAD

**Issue by jm33-m0** [gpakosz/.tmux#212]
https://github.com/gpakosz/.tmux/blob/ffb1c54769fc78643328ff0ebdc266a99537d3fa/.tmux.conf#L474

this script looks for `"$OSTYPE" = "cygwin"`, otherwise it uses

`username=$(ps -t "$tty" -o user= -o pid= -o ppid= -o command= | awk ' ... `, which doesn't seems to work under WSL

I tried to set my `$OSTYPE` from `linux-gnu` to `cygwin`, and it successfully falls back to `whoami` method, and the username/hostname gets displayed without issue

**Comment by jm33-m0** [comment]
actually `username` and `hostname` stay where they should be before window resizing or `clear` command.
and i am able to get correct value using 
https://github.com/gpakosz/.tmux/blob/ffb1c54769fc78643328ff0ebdc266a99537d3fa/.tmux.conf#L477
just don't know why they disappear

**Comment by gpakosz** [comment]
Hello @jm33-m0 👋

Sorry for getting back to you so late.
Everything works fine for me when using WSL.

Feel free to open another issue if the problem still exists with the current configuration
