### ISSUE TITLE
Setting default shell in mac does not work

### ISSUE THREAD

**Issue by johnyoonh** [gpakosz/.tmux#213]
I have the following line in my .tmux.conf.local
`if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-command "exec reattach-to-user-namespace -l zsh"'`
This works on it's own, but it seems like `default-command` loses its effect with used together with other settings.
Anybody else faced this trouble? Here are other settings I've tried:

- `set-option -g default-command "command -v reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace -l \"$SHELL\" || exec \"$SHELL\""`
- `set-option -g default-shell /usr/local/bin/zsh`

**Comment by gpakosz** [comment]
Hello @johnyoonh 👋

> it seems like default-command loses its effect with used together with other settings

I'm sorry but the description of your problem is very vague. Can you please explain what you're trying to achieve?

If you want to make use of `reattach-to-user-namespace` to make copy/paste work, **you do not need** the following in your `~/.tmux.conf.local` copy:
```
if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-command "exec reattach-to-user-namespace -l zsh"'
```

My configuration automatically detects if `reattach-to-user-namespace` is present and automatically sets `default-command` to make use of it. The shell given to `reattach-to-user-namespace` is the value `default-shell` as detected by tmux itself.

So, can you please remove your `~/.tmux.conf.local` copy and run the following:
```
$ tmux -Ltest -f/dev/null start \; show -g default-shell
```
```
$ tmux -Ltest start \; show -g default-command
```

**Comment by johnyoonh** [comment]
Okay. I was just trying to change the default shell. I don't know why this command was not working for me before the reboot.
`if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-shell /usr/local/bin/zsh'`
Perhaps tmux was running in the background and didn't actually reload my settings? I am not sure.
As for the output you've asked. Here they are:

    $ tmux -Ltest -f/dev/null start \; show -g default-shell
    default-shell "/bin/bash"

    $ tmux -Ltest start \; show -g default-command
    default-command "exec /usr/local/bin/zsh... 2> /dev/null & reattach-to-user-namespace -l /usr/local/bin/zsh"

**Comment by gpakosz** [comment]
For the record, I'm going to explain the rationale behind
```
exec /usr/local/bin/zsh... 2> /dev/null & reattach-to-user-namespace -l /usr/local/bin/zsh
```

I wasn't pleased with tmux "flashing" `reattach-to-user-namespace -l /usr/local/bin/zsh` when creating a new pane so I'm abusing the way tmux parses `exec <something>`. Every time a pane is created, I'm spawning 2 processes:
  - `exec /usr/local/bin/zsh... 2> /dev/null` in the background
  - and `reattach-to-user-namespace -l /usr/local/bin/zsh`

The first ends immediately as `/usr/local/bin/zsh...` is not a valid program, but it makes tmux display `zsh...` while `reattach-to-user-namespace` is busy launching.

You say:
> My problem is fixed so please feel free to close it any time

Does it mean you now have both `zsh` and `reattach-to-user-namespace` working without altering your `~/.tmux.conf.local` copy?

**Comment by gpakosz** [comment]
@johnyoonh ping? 👋

Do you now have both zsh and reattach-to-user-namespace working without altering your ~/.tmux.conf.local copy?

**Comment by johnyoonh** [comment]
Sorry for the late response. I now have zsh, but not reattach, reattach is not needed by me, so I am satisfied with the current config.

**Comment by gpakosz** [comment]
Thanks for the feedback. Closing then.
