### ISSUE TITLE
how to use source conf

### ISSUE THREAD

**Issue by yuxing1994** [gpakosz/.tmux#214]
my .tmux.conf:

'source  ~/.config/.tmux/.tmux.conf'
'source  ~/.config/.tmux/.tmux.conf.local'

but No effect

**Comment by gpakosz** [comment]
Hello @yuxing1994,

This configuration needs `~/.tmux.conf` to exist, and `~/.tmux.conf.local` to optionally exist.
There's no way to place them in different directories.

Please follow https://github.com/gpakosz/.tmux#installation
