### ISSUE TITLE
Prefix indicator is too small, how to make it bigger?

### ISSUE THREAD

**Issue by Akemi-Homura** [gpakosz/.tmux#215]
![image](https://user-images.githubusercontent.com/16780053/50676381-0383fe00-102f-11e9-9f00-90a99010c606.png)
Iterm2 on OSX 10.14

**Comment by gpakosz** [comment]
Hello @Akemi-Homura 👋

You can try playing with iTerm2 Unicode settings:

![image](https://user-images.githubusercontent.com/553208/50678254-1b8f5980-0ffe-11e9-8040-4c2f19cbfb41.png)

And also change font to see if that helps.

**Comment by Akemi-Homura** [comment]
@gpakosz It works！Thank you !
![image](https://user-images.githubusercontent.com/16780053/50678439-a17cc600-1039-11e9-82ec-4b1f87378a37.png)

**Comment by gpakosz** [comment]
What worked?

**Comment by Akemi-Homura** [comment]
@gpakosz After changing font to `Source Code Pro`, prefix indicator gets bigger.
