### ISSUE TITLE
Last character is missing when copy & pasting

### ISSUE THREAD

**Issue by ncreuschling** [gpakosz/.tmux#218]
I have this one weird issue: When I copy text from a running tmux session (macOS) with your config files the last character is missing in the clipboard. It is always the last one, regardless of the symbol.

When I run `tmux -L test -f /dev/null` all characters can be copied flawlessly. I tested several different terminal applications (iTerm 2, Alacritty, macOS Terminal). That's not the reason. The issue only occurs with your configuration.

Is somebody else having this issue? How can I help to solve this problem - because it is bothering endlessly.

**Comment by ncreuschling** [comment]
Thank you for your attention. Copy & Pasting for me is: Selecting text via mouse stroke, while (left) mouse button pressed, CMD+C for copy, mouse button release and pasting per CMD+V into an editor. 

I don't think I have `reattach-to-user-namespace` installed - at least not via Homebrew.

```
~ zsh --version
zsh 5.6.2 (x86_64-apple-darwin18.0.0)

~ brew info tmux
tmux: stable 2.8 (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/2.8 (10 files, 709.5KB) *
  Poured from bottle on 2018-10-18 at 18:29:33
```

Relevant parts of my `.tmux.conf.local`:

```
# -- user customizations -------------------------------------------------------
# this is the place to override or undo settings

# increase history size
set -g history-limit 10000

# start with mouse mode enabled
set -g mouse on

# synchronize panes
bind b set-window-option synchronize-panes
```

Let me know if you need anything else.

**Comment by gpakosz** [comment]
There's something I'm not sure I understand right.
You're using both mouse mode and you're using <kbd>⌘</kbd>+<kbd>C</kbd> to copy things into the clipboard while still pressing the mouse button?

**Comment by ncreuschling** [comment]
You are right - I just noticed I don't need to press  ⌘+C. Only mouse is sufficient - still, the last character is missing.

**Comment by gpakosz** [comment]
Also, what's the value of `tmux_conf_copy_to_os_clipboard` in your `~/.tmux.conf.local` copy?

**Comment by ncreuschling** [comment]
```
tmux_conf_copy_to_os_clipboard=false
```

**Comment by gpakosz** [comment]
Ok, can you please execute
```
$ tmux -L test list-keys | grep Mouse
```

**Comment by ncreuschling** [comment]
Sure:

```
bind-key    -T copy-mode    MouseDown1Pane    select-pane
bind-key    -T copy-mode    MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi MouseDown1Pane    select-pane
bind-key    -T copy-mode-vi MouseDrag1Pane    select-pane ; send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T root         MouseDown1Pane    select-pane -t = ; send-keys -M
bind-key    -T root         MouseDown1Status  select-window -t =
bind-key    -T root         MouseDown3Pane    if-shell -F -t = "#{mouse_any_flag}" "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key    -T root         MouseDrag1Pane    if-shell -F -t = "#{mouse_any_flag}" "if -Ft= \"#{pane_in_mode}\" \"copy-mode -M\" \"send-keys -M\"" "copy-mode -M"
bind-key    -T root         MouseDrag1Border  resize-pane -M
```

**Comment by gpakosz** [comment]
Which is the default behavior as per `$ tmux -L test -f /dev/null | grep Mouse`. So at that point I don't understand how my configuration is interfering badly 😐

When you release the mouse button, `send-keys -X copy-selection-and-cancel` is sending the selected text to a tmux buffer, not even to the OS clipboard.

Do you have something else that tries to integrate tmux with the OS clipboard? What if you start over and take stock `~/.tmux.conf` and `~/.tmux.conf.local`?

**Comment by ncreuschling** [comment]
Thank you for your assistance so far. It does not happen with your original files. So it must be one of my customizations. I will investigate this further.

**Comment by gpakosz** [comment]
I'm curious to know 🙂

**Comment by ncreuschling** [comment]
So I diffed my `.tmux.conf.local`:

-tmux_conf_theme_status_left=' ❐ #S | ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '
-tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '
+tmux_conf_theme_status_left=' ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '
+tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R | #{username}#{root} '

**Comment by ncreuschling** [comment]
I nailed it down to:

```
set -g mouse on
```

This line breaks Copy & Paste for me.

Without it Copy & Paste works just fine - but now the Powerline symbols are broken.

**Comment by ncreuschling** [comment]
I played around a little bit - it's definitely this setting for me:

```
set -g mouse on
```

I can reproduce the problem now even during running sessions by change this one setting. 

Apologies for taking up so much of your time. Thank you for your help.

**Comment by sergeyignatov** [comment]
@ncreuschling I had the same issue with mouse copy/paste and I  solved it by compiling  tmux without --enable-utf8proc (brew version uses the flag by default)

**Comment by ncreuschling** [comment]
Thank you for your comment. I will look into this.

**Comment by darmach** [comment]
Is this relevant to this issue?
https://github.com/tmux/tmux/issues/1579
