### ISSUE TITLE
Ability to specify location of tmux.conf.local

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#221]
Perhaps an env var like `TMUX_CONF_LOCAL` which can be set to `/path/to/tmux.conf.local`

**Comment by gpakosz** [comment]
Hello @kleinjm  👋

Can you please give the `gh216-gh221` branch a try?

Hope that helps! 🤞

**Comment by kleinjm** [comment]
Works perfectly! I made sure to fully kill tmux to test it. Thanks so much for addressing this

**Comment by gpakosz** [comment]
Thanks for testing the branch @kleinjm 👍

I'll close this issue when I merge the branch.
I quite don't know when it's going to happen though as it bumps the minimum tmux requirements to 2.4

**Comment by gpakosz** [comment]
Hello @kleinjm,

I realize I forgot to ask. Why do you need this feature? What's the problem with having your `.tmux.conf.local` copy in your home directory?

**Comment by kleinjm** [comment]
My dotfiles aren't in my home directory so it makes it easier. I symlink them for now but this a nice-to-have feature that helps set up my env a bit easier

**Comment by gpakosz** [comment]
Hey @kleinjm 👋

Well, if I merge this conf, you'll be able to have `.tmux.conf` and `.tmux.conf.local` somewhere else.
But the first time you'll launch tmux, you will need `-f $TMUX_CONF`, e.g.
```
$ TMUX_CONF=/foo/bar/tmux.conf TMUX_CONF_LOCAL=/foo/bar/tmux.conf.local tmux -f /foo/bar/tmux.conf
```

I suspect forgetting `-f` will happen very often!

**Comment by gpakosz** [comment]
Hello @kleinjm 👋

If you still need this, can you please try `gh-200+221+439+586`?
