### ISSUE TITLE
Error when two different client with different resolution co-work

### ISSUE THREAD

**Issue by Trinkle23897** [gpakosz/.tmux#223]
E.g. when I use 1920x1080 resolution and the other one use 1024x768 and both of us attach to the same panel, my tmux cannot display the other part outside of 1024x768 correctly.

**Comment by gpakosz** [comment]
Hello @Trinkle23897 👋

This is just how tmux generally behaves 🤷‍♂️

**Comment by Trinkle23897** [comment]
But, original tmux do not have such broken lines in the buttom of screen...

**Comment by gpakosz** [comment]
Ok. What do you mean exactly by "broken lines in the bottom of the screen"?

When you say original tmux, is it when launching tmux with
```
$ tmux -L test -f /dev/null
```
?

**Comment by Trinkle23897** [comment]
here is one of the screenshot
![](http://ml.cs.tsinghua.edu.cn/~jiayi/upload/2019-02-22%2021-11-17%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by gpakosz** [comment]
When the status line gets duplicated, it's because tmux and your terminal emulator disagree on Unicode characters width. More details here: https://github.com/gpakosz/.tmux#troubleshooting

**Comment by Trinkle23897** [comment]
Ok, it's my fault... Thank you very much!

**Comment by gpakosz** [comment]
I don't know whose fault it is but that's outside of my control for sure.

Something you can do to work around the problem is to avoid using emojis in the status line.
