### ISSUE TITLE
Unset secondary prefix?

### ISSUE THREAD

**Issue by obitech** [gpakosz/.tmux#227]
Is there a way to unset the secondary prefix `C-a`? In my `.tmux.conf.local` I tried:
```
unbind C-a
unset-option -g prefix2
```
But it's not working :/

**Comment by gpakosz** [comment]
In your `~/.tmux.conf.local` copy
```
set -gu prefix2
unbind C-a
```
should do it

**Comment by obitech** [comment]
This has worked perfectly. Thank you so much for the quick support!

**Comment by andbuitra** [comment]
@gpakosz This isn't working on tmux 3.0a. Any idea how to proceed there?

**Comment by gpakosz** [comment]
Hello @andbuitra 👋

Nothing changed in tmux 3.0a in that respect. Please make sure your reloaded the configuration by hitting `<prefix> + r`
