### ISSUE TITLE
Tmux Plugin Manager & tmux-resurrect support

### ISSUE THREAD

**Issue by nikolayzhmurov** [gpakosz/.tmux#228]
Hi,

Is it possible to use Tmux Plugin Manager and plugins with your configuration? I would like to use Tmux Plugin Manager and tmux-resurrect plugin with your configuration. Their links are below:

https://github.com/tmux-plugins/tpm

https://github.com/tmux-plugins/tmux-resurrect

Regards

**Comment by Glitches** [comment]
@nikolayzhmurov works like a charm!
Use this syntax to add plugins in your tmux.conf.local: 

```
# List of plugins
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-continuum  \
  tmux-plugins/tmux-resurrect  \
  samoshkin/tmux-plugin-sysstat  \
'
```

**Comment by nikolayzhmurov** [comment]
It works! Thanks!

**Comment by shelper** [comment]
> @nikolayzhmurov works like a charm!
> Use this syntax to add plugins in your tmux.conf.local:
> 
> ```
> # List of plugins
> set -g @tpm_plugins '          \
>   tmux-plugins/tpm             \
>   tmux-plugins/tmux-sensible   \
>   tmux-plugins/tmux-continuum  \
>   tmux-plugins/tmux-resurrect  \
>   samoshkin/tmux-plugin-sysstat  \
> '
> ```

I followed exactly this and still could not get tmux-resurrect installed.

**Comment by nikolayzhmurov** [comment]
@shelper the way it looks in my .tmux.conf.local

`# List of plugins
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-resurrect  \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'`

Have you hit `prefix + I` to fetch the plugin and source it?

**Comment by shelper** [comment]
@nikolayzhmurov  this is exactly what i did and it does not install plugin, 
and i have to manually install the plugins. 

interestingly, after a few days i was trying to install another plugin(tmux-yank), and `Prefix + I` worked...

**Comment by GregHilston** [comment]
I'm in the same boat as @shelper  here

**Comment by gpakosz** [comment]
Since this issue was closed, Oh my tmux! acquired a TPM integration.

Please do not alter `~/.tmux.conf`.
See instructions in the most recent `.tmux.conf.local` sample file.
