### ISSUE TITLE
Error: [: 0.45: integer expression expected

### ISSUE THREAD

**Issue by twang817** [gpakosz/.tmux#229]
Having an issue on OSX 10.14.3

```
line 571: [: 0.45: integer expression expected
```
Ignore the line number -- I pulled the code out to test it.

It seems to be this line of code:
```
if [ "$charge" -eq 0 ]; then
```
It doesn't appear that Bash allows float/doubles in their equality operator.
In any case, I changed the line to:
```
if (( $(echo "$charge == 0" | bc -l) )); then
```
That seemed to solve the problem.
Anyone else experiencing this?

**Comment by gpakosz** [comment]
Hello @twang817 👋

I'm using macOS 10.14.3 myself with Bash and it works for me.

Can you please paste the output of
```
$ cut -c3- ~/.tmux.conf | sh -sx _battery
```

?

**Comment by twang817** [comment]
As it turns out, it was my error.  Closing.
