### ISSUE TITLE
SSH username/hostname not showing

### ISSUE THREAD

**Issue by fernandomm** [gpakosz/.tmux#23]
First of all, thanks for your work. 

I enabled tmux_conf_theme_username and tmux_conf_theme_hostname. It shows my local username, but when I access a server using SSH it doesn't change the username and hostname even after restarting tmux.

Any ideas about what I should do?

I'm using tmux 2.1 on OS X.

**Comment by gpakosz** [comment]
Hello,

For now, setting `tmux_conf_theme_username` or `tmux_conf_theme_hostname` to `ssh` is a bit confusing. The way it works is when you're sshing to a server and attaches to a tmux server running remotely.

On the image below, I'm running tmux on my Mac and I'm sshing into a server which runs tmux. On the remote server, the remote tmux has `tmux_conf_theme_username` and `tmux_conf_theme_hostname` set to `ssh`:
![image](https://cloud.githubusercontent.com/assets/553208/16645386/e2071796-4423-11e6-9665-4eda4e96d3db.png)

I started thinking about the best way to implement the feature you're expecting. It may require parsing `~/.ssh/config` or any configuration file passed to ssh with the `-F` flag.

**Comment by gpakosz** [comment]
Hello @fernandomm, I just pushed a major rewrite that does what you were looking for at last! Hope you enjoy it!

**Comment by fernandomm** [comment]
Thanks! I just tested and it works perfectly.
