### ISSUE TITLE
Font used in README and status bars are blocks

### ISSUE THREAD

**Issue by DVCoder** [gpakosz/.tmux#232]
1 - What font/theme is used in the terminal in the README examples? 

2 - Why is my status bars all rectangles, not looking like the arrows?
https://imgur.com/a/XZZMNad

**Comment by DVCoder** [comment]
I solved #2, due to  the  fact  that  my  terminal was not using a Powerline font.

**Comment by gpakosz** [comment]
Hello @DVCoder 👋

https://github.com/gpakosz/.tmux#enabling-the-powerline-look details it all. I'm using Source Code Pro. Enabling powerline symbols implies modifying your `~/.tmux.conf.local` copy.

**Comment by DVCoder** [comment]
Thanks !!
