### ISSUE TITLE
lost_server after kvm switch click

### ISSUE THREAD

**Issue by fthzkrtn** [gpakosz/.tmux#233]
Tmux server crashed and closed with a "lost_server" echo. After dealing with logs saw that battery_* parameters causes server to crash. I do not know why, but, when i remove battery_* variables from tmux.conf.local file, then error stopped and tmux started to work smoothly.

**Comment by gpakosz** [comment]
Hello @fthzkrtn 👋

I find it bizarre that shelling out to inspect battery status causes the tmux server to crash.
What makes you believe it's the case?
And BTW can you please tell me which OS and which tmux version you're using?

**Comment by gpakosz** [comment]
Hey @fthzkrtn 👋

Can you please give the `gh-233` branch a try? It's a long shot but reading the code again I at least found a bug in the battery detection logic.

**Comment by fthzkrtn** [comment]
Hey @gpakosz thanks for reply! I'll checkout the fix and let you know, sorry for late reply.
