### ISSUE TITLE
tmux row is not aligned

### ISSUE THREAD

**Issue by chaosma** [gpakosz/.tmux#234]
In MacOS terminal, the tmux status bar is not showing correctly.  The status bar is either above a gray bar(see picture below) or the status bar is disappear with only gray bar there.

Also, notice that the prompt symbol is one line above when the type line.  I tried to remove the powerline emoji with default symbol in the config.local, still got the same issue, i.e. the status bar is above the gray bar and keep flashing every once in a while.

<img width="773" alt="Screen Shot 2019-04-09 at 10 28 08 AM" src="https://user-images.githubusercontent.com/3767044/55821609-be022180-5ab2-11e9-93d8-9887c0d4aeea.png">

**Comment by gpakosz** [comment]
Hello @chaosma,

This is the never ending story of tmux and your terminal emulator disagreeing on Unicode characters' width. Either change your terminal settings, or stop using special symbols (emojis, powerline symbols, ...) in your status bar.

**Comment by chaosma** [comment]
I changed the tmux_conf_theme_left_separator_main (right and sub) to non-powerline symbols, but it still didn't work. As for change terminal setting, could you be more specific about which setting to choose?  Thanks!

**Comment by gpakosz** [comment]
What's your terminal emulator?

**Comment by chaosma** [comment]
It’s the default terminal on MacOS and I use zsh to replace the default bash.

**Comment by gpakosz** [comment]
I don't think stock macOS `Terminal.app` lets one configure Unicode characters' width, while iTerm2 does.

You can keep altering your `~/.tmux.conf.local` copy until it works, likely one of the emojis (lightning bold, or some other one) makes it fail.

But in any case, my config does nothing more but setting `status-left` and `status-right`, which you can inspect with
```
$ tmux show -g status-left
```
and
```
tmux show -g status-right
```

**Comment by chaosma** [comment]
Thanks for the hint! After trial and fail, the line is narrowed down to the battery charging symbol:

`tmux_conf_battery_status_charging='⚡ '    # U+26A1`

How can I change the terminal setting (change the character width??) to fix it?
