### ISSUE TITLE
How to tweak this?

### ISSUE THREAD

**Issue by mazzy89** [gpakosz/.tmux#236]
![image](https://user-images.githubusercontent.com/5463218/56608998-5ef0f080-660c-11e9-996d-f9356a6307ae.png)

I did not find the option how to tweak that arrow which remains black despite i've changed the bg of the status bar.

Any idea?

**Comment by gpakosz** [comment]
Hello @mazzy89 👋

You need to adjust `tmux_conf_theme_status_left_fg` and `tmux_conf_theme_status_left_bg` when you change `tmux_conf_theme_status_fg` and `tmux_conf_theme_status_bg`.

**Comment by mazzy89** [comment]
I've already tried to tune `tmux_conf_theme_status_left_bg` and `tmux_conf_theme_status_left_fg` but without any luck. that black arrow on the left of the light blue block is still there

**Comment by gpakosz** [comment]
Can you please give me details of what you changed?

And also please paste the output of
```
$ tmux show -g status-left
```

**Comment by mazzy89** [comment]
This is the result 

```
status-left "#[fg=#000000,bg=#ffff00,bold] ❐ #S #[fg=#ffff00,bg=#ff00af,none]#[fg=#e4e4e4,bg=#ff00af,none] ↑#{?@uptime_d, #{@uptime_d}d,}#{?@uptime_h, #{@uptime_h}h,}#{?@uptime_m, #{@uptime_m}m,} #[fg=#ff00af,bg=default,none] "
```

and i have changed this:

```
tmux_conf_theme_status_bg='#19545e'
```

**Comment by gpakosz** [comment]
Right!

In fact you also need
```
tmux_conf_theme_window_status_bg='#19545e'
```

**Comment by mazzy89** [comment]
worked like a charm. thanks a lot @gpakosz 

appreciated a lot

**Comment by gpakosz** [comment]
no problem, enjoy!

**Comment by gpakosz** [comment]
Are we good?

**Comment by mazzy89** [comment]
Yes. going to close this. thank you again and have a good evening :-)
