### ISSUE TITLE
tmux 2.9 breaks tab background color

### ISSUE THREAD

**Issue by jm33-m0** [gpakosz/.tmux#237]
![image](https://user-images.githubusercontent.com/10167884/56706648-5ac9ed80-6748-11e9-8d53-ca2aad630a8b.png)
as the screenshot shows, `1 vim`'s background color is black instead of blue

**Comment by jm33-m0** [comment]
this happens after tmux 2.9 update

**Comment by jm33-m0** [comment]
https://github.com/tmux/tmux/blob/master/CHANGES#L61
might be the reason?

**Comment by gpakosz** [comment]
Hello @jm33-m0 👋

No `-fg`, `-bg` options were not used.

**Comment by jm33-m0** [comment]
![image](https://user-images.githubusercontent.com/10167884/56712667-d6846400-6761-11e9-8f83-87137eeda86a.png)
looks like this defines window status line

**Comment by gpakosz** [comment]
The cause is not what you're referring to 🙅‍♂️

Please give the `gh-237` branch a try 🙏

**Comment by jm33-m0** [comment]
thank you for the fix, but it seems not working

![image](https://user-images.githubusercontent.com/10167884/56718003-8234b080-6770-11e9-9fd1-b456c3064fb7.png)

**Comment by gpakosz** [comment]
You need to reload the configuration

**Comment by jm33-m0** [comment]
yeah, i even restarted tmux server, but nothing changed

**Comment by gpakosz** [comment]
Can you run
```
$ tmux -L test showw -g window-status-current-format
```

**Comment by jm33-m0** [comment]
```
window-status-current-format "#[fg=#080808,bg=#00afff]#[fg=default,bg=default,default] #I #W #[fg=#00afff,bg=#080808,none]"
```

**Comment by gpakosz** [comment]
`#[fg=default,bg=default,default]` means you didn't reload the configuration or something prevented the configuration from reloading

**Comment by gpakosz** [comment]
Also changing `.tmux.conf` to do `set -g default-terminal "xterm-256color"` like you're doing in the screenshot above is bogus

**Comment by jm33-m0** [comment]
somehow `git checkout` didnt actually switch to that branch, i re-cloned the repo and it worked.

for `xterm-256color`, i dont know why but without it, vim doesnt show any colors

**Comment by gpakosz** [comment]
> for `xterm-256color`, i dont know why but without it, vim doesnt show any colors

This is best fixed on vim's side. Did you try `set termguicolors`?

**Comment by jm33-m0** [comment]
yeah, vim is always using `termguicolors`, but it does require `xterm-256color` terminfo to show colors for me

**Comment by gpakosz** [comment]
Well, in my experience, `TERM` has to be `xterm-256color` outside of tmux, before tmux is launched, and should be `screen-256color` or `tmux` (but fewer terminal emulator and software support this) within tmux

**Comment by jm33-m0** [comment]
> This is best fixed on vim's side. Did you try `set termguicolors`?

`set termguicolors&` actually works, but, as it implies, `termguicolors` is off
