### ISSUE TITLE
True colors work for windows + panes, but not statusbar

### ISSUE THREAD

**Issue by josh-cain** [gpakosz/.tmux#239]
I've been able to get my oh-my-tmux configs to render true colors (OSX + iTerm).  However, the status bar along the bottom is not rendering in true colors:

<img width="667" alt="Screen Shot 2019-04-27 at 10 02 00 PM" src="https://user-images.githubusercontent.com/2659880/56857933-975c3b80-6938-11e9-865d-f90cdacce6c3.png">

Both the red for "master" and background red for "jcain" are the same value, but they're clearly rendered differently :(

Any ideas on what configs would help the statusbar to render in true colors?

**Comment by gpakosz** [comment]
Hello @josh-cain 👋

Can you please have a look at the value of `TERM`, outside **and** inside tmux?
My configuration expects `xterm-256color` outside and `screen-256color` inside.

Now, when you set `tmux_conf_theme_24b_colour=true` in your `~/.tmux.conf.local` copy, my configuration does the following under the hood:
```
tmux set-option -ga terminal-overrides ",*256col*:Tc"
```

And after having changed the value of `tmux_conf_theme_24b_colour` you need to relaunch the tmux server process entirely.

Then inside tmux, the `Tc` flag should be set:
```
$ tmux info | grep Tc
 202: Tc: (flag) true
```

And 24b colors work for me on macOS and iTerm, running https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh:

![image](https://user-images.githubusercontent.com/553208/56859708-0d8b8d00-698f-11e9-9017-0a9a928135cb.png)

Which I also derived to set rainbow colors to the status line:

```
#!/usr/bin/env bash

# Gives a color $1/255 % along HSV
# Who knows what happens when $1 is outside 0-255
# Echoes "$red $green $blue" where
# $red $green and $blue are integers
# ranging between 0 and 255 inclusive
rainbowColor()
{ 
    let h=$1/43
    let f=$1-43*$h
    let t=$f*255/43
    let q=255-t

    if [ $h -eq 0 ]
    then
        echo "255 $t 0"
    elif [ $h -eq 1 ]
    then
        echo "$q 255 0"
    elif [ $h -eq 2 ]
    then
        echo "0 255 $t"
    elif [ $h -eq 3 ]
    then
        echo "0 $q 255"
    elif [ $h -eq 4 ]
    then
        echo "$t 0 255"
    elif [ $h -eq 5 ]
    then
        echo "255 0 $q"
    else
        # execution should never reach here
        echo "0 0 0"
    fi
}

for i in $(seq 255 128); do
  triplet=$(rainbowColor $i)
  printf "#[bg=#%02x%02x%02x] " $triplet
done

```

![image](https://user-images.githubusercontent.com/553208/56860538-f1401e00-6997-11e9-9727-038b69ca8100.png)

So you likely want to check the color triplets used in the output of:
```
$ tmux show -g status-right
```

**Comment by josh-cain** [comment]
gpakosz++ Thanks for helping troubleshoot!  the `tmux set-option -ga terminal-overrides ",*256col*:Tc"` portion wound up being the issue.  Now I've got the colors displaying correctly.

Thanks for making the tmux experience even more awesome!

**Comment by gpakosz** [comment]
What do you exactly mean by
> the `tmux set-option -ga terminal-overrides ",*256col*:Tc"` portion wound up being the issue

?

**Comment by josh-cain** [comment]
Sorry - can definitely see where that was unclear.  I meant that my .tmux.conf/.tmux.conf.local did not have:

```
set-option -ga terminal-overrides ",*256col*:Tc"
```

As such, when I checked that flag using `tmux info`, it was showing up as `undefined`.  All other settings were as you prescribed above ^.  Adding the aforementioned line made the colors display correctly.

**Comment by gpakosz** [comment]
Ok well, you don't have to add this line manually.

But you need to set `tmux_conf_theme_24b_colour=true` in your `~/.tmux.conf.local` copy.

When `tmux_conf_theme_24b_colour` is `true`, the proper terminal override will be applied.

**Comment by josh-cain** [comment]
ah, good to know!  so I actually did both, as I was playing with the `tmux_conf_theme_24b_colour` config previously.  However, there has been more than one time in which I've failed to fully restart tmux + apply changes when tinkering with these.  Thanks again!

**Comment by gpakosz** [comment]
You're welcome! Enjoy!

**Comment by mcanevet** [comment]
@gpakosz somehow setting `tmux_conf_theme_24b_colour` to `true` does not work for me, be setting explicitly `tmux set-option -ga terminal-overrides ",*256col*:Tc"` in my `.tmux.conf.local` works!,

**Comment by gpakosz** [comment]
```
# _apply_overrides() {
#   tmux_conf_theme_24b_colour=${tmux_conf_theme_24b_colour:-false}
#   if _is_enabled "$tmux_conf_theme_24b_colour"; then
#   case "$TERM" in
#     screen-*|tmux-*)
#       ;;
#     *)
#       tmux set-option -ga terminal-overrides ",*256col*:Tc"
#       ;;
#   esac
#   fi
# }
```

@mcanevet what's the value of `$TERM` outside and inside `tmux`?

**Comment by mcanevet** [comment]
@gpakosz `xterm-256color`

**Comment by gpakosz** [comment]
@mcanevet Noticed that I asked **outside** and **inside** `tmux`.

Outside of `tmux`, that is before launching `tmux`, `TERM` should set to `xterm-256` color or `rxvt-unicode-256color` if you're using `rxvt`.

Then inside of `tmux`, it should be `screen-256color` or `tmux-256color`. If it's still `xterm-25color`, it's likely because your shell's `.rc` file overrides it ← if that's the case a simple tweak consists in not redefining `TERM` when the `TMUX` environment variable exits.

See https://github.com/tmux/tmux/wiki/FAQ

**Comment by mcanevet** [comment]
@gpakosz sorry, inside tmux it's `screen-256color`.

**Comment by gpakosz** [comment]
@mcanevet I see.

Well the way I chose to implement it is to do `tmux set-option -ga terminal-overrides ",*256col*:Tc"` only when the server process is starting because doing it afterwards didn't work reliably

**Comment by gpakosz** [comment]
It seems that I can relax the constraints. It seems setting `tmux set-option -ga terminal-overrides ",*256col*:Tc"` after the server process has started works but you need to detach and reattach your client
