### ISSUE TITLE
reattach-to-user-namespace is not support on new macos

### ISSUE THREAD

**Issue by xiaods** [gpakosz/.tmux#240]
macos 10.14 don't need reattach-to-user-namespace

**Comment by gpakosz** [comment]
Hello @xiaods,

What's the issue exactly?

**Comment by xiaods** [comment]
@gpakosz macos 10.14 don't need   reattach-to-user-namespace, install the tmux conf, it will report warning for reattach-to-user-namespace

**Comment by gpakosz** [comment]
Hello @xiaods,

`reattach-to-user-namespace` has always been optional. Which warning message are you referring to?

**Comment by xiaods** [comment]
@gpakosz thanks for your reminder, in first experience step. i have not setup tmux.local file setting. then the reattach-to-user-namespace print in terminal. now i understand the config. close it.
