### ISSUE TITLE
Username truncated in right-status; help?

### ISSUE THREAD

**Issue by beschissen** [gpakosz/.tmux#241]
Username is truncated in right-status; username in question is nine characters in length however tmux is only displaying seven characters of said username with a '+' appended to the seven characters shown. I've been searching and combing through lines to no avail -- any insight into this would be greatly appreciated!

**Comment by gpakosz** [comment]
Hello @beschissen 👋

Which OS are you running?

**Comment by beschissen** [comment]
Hello @gpakosz! Thanks for replying so swiftly!

OS is Arch Linux x86_64, terminal is Guake

**Comment by gpakosz** [comment]
Alright,

Can you please launch the following command from within tmux please?
```
$ ps -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=
```

**Comment by beschissen** [comment]
`$ ps -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=`
produces the following two lines:
`meursau+   5479 -zsh`
`meursau+ 19291 ps -t /dev/pts/1 -o user= -o pid= command=`

while `whoami` results in the expected username, `meursault`

**Comment by gpakosz** [comment]
Does the following help?

```
$ COLUMNS=32 ps -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=
```

**Comment by beschissen** [comment]
`$ COLUMNS=32 ps -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=`

produces the following two lines

```
meursau+ 4981 ps -t /dev/pts/1
meursau+ 5479 -zsh
```
I reloaded the tmux configuration and restarted the terminal; unfortunately it doesn't seem to have had an effect.

**Comment by gpakosz** [comment]
Ok,

Can you please try
```
$ ps -t $(tmux display -p '#{pane_tty}') -o user:32= -o pid= -o command=
```

And
```
$ ps -t $(tmux display -p '#{pane_tty}') -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o command=
```

**Comment by gpakosz** [comment]
And finally, can you please try

```
ps -ww -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=
```

**Comment by beschissen** [comment]
`$ ps -t $(tmux display -p '#{pane_tty}') -o user:32= -o pid= -o command=`

produces the following two lines:
```
meursault                        15549 -zsh
meursault                        16326 ps -t /dev/pts/5 -o user:32= -o pid= -o command=
```
while

`$ ps -t $(tmux display -p '#{pane_tty}') -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o command=`

produces the following three lines:
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ~
meursault                        15549 -zsh
meursault                        16695 ps -t /dev/pts/5 -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o command=~
```

and

`ps -ww -t $(tmux display -p '#{pane_tty}') -o user= -o pid= -o command=`

produces the following two lines: 
```
meursau+ 15549 -zsh
meursau+ 17173 ps -ww -t /dev/pts/5 -o user= -o pid= -o command=
```

**Comment by gpakosz** [comment]
Can you please give the `gh-241` branch a try for a while?

**Comment by beschissen** [comment]
Looks like that did the trick! Thank you so much - trying to troubleshoot this has been a distraction for months, I really appreciate your help!

**Comment by gpakosz** [comment]
I'll close this issue when I merge the branch

**Comment by beschissen** [comment]
Ahh my bad - still getting the hang of GitHub haha. Thank you again!

**Comment by JellyZhang** [comment]
I came across this problem , and gh-241 、master  branch doesnot work for me. 
However , I look into the commit history and tried 8809af7c ,  it works!
Just want to leave a message to help others.
btw, my env is debian 9. tmux 3.2
