### ISSUE TITLE
Remove The Oh-my-tmux

### ISSUE THREAD

**Issue by ZCDu** [gpakosz/.tmux#246]
When I use the SSH, the Oh-my-tmux look so bad, how can I remove it and use the original tmux?

**Comment by gpakosz** [comment]
Hello @ZCDu 👋

Can you also please give more details?
- Can you detail "look so bad" with a screenshot maybe?
- What's the setup (OS, tmux version, shell, locale) on the machine you're SSHing from?
- What's the setup (OS, tmux version, shell, locale) on the machine you're SSHing to?
- Where does tmux run?
  - Locally?
  - Remotely?
  - Both?
- Is the remote machine only accessed through SSH?

**Comment by ZCDu** [comment]
![t](https://user-images.githubusercontent.com/28478805/57907971-7b9de280-78b1-11e9-87df-7a0bd12d1c57.png)
Thanks for your response.I have uploaded a picture to show this problem,can you get it? I use SSH to remote a linux machine at windows shell.

**Comment by gpakosz** [comment]
I would say your best bet is to use [wsltty](https://github.com/mintty/wsltty)

**Comment by ZCDu** [comment]
OK,I solve it!Thank you.

**Comment by gpakosz** [comment]
Good, closing then.

**Comment by raceychan** [comment]
so there is no way to remove it?
