### ISSUE TITLE
cursor changes from iTerm profile config

### ISSUE THREAD

**Issue by cdrani** [gpakosz/.tmux#248]
In my iTerm profile I have my cursor to be a blinking underline (_). When I start/attach to a tmux session there's continuity, but when I create a new window the cursor changes to blinking box/block. This change carries on through even after I detach from the session. 

I was not too sure whether the issue was with tmux or iTerm, so I tried using Hyper and the same problem rears it head.

**Comment by gpakosz** [comment]
Hello @cdrani 👋

My configuration isn't supposed to do anything with cursors.

You should try closing tmux (all clients and server processes) and try to launch `tmux -f /dev/null` to see whether the problem still happens with stock configuration.

**Comment by cdrani** [comment]
Thanks for the suggestion @gpakosz! Upon further investigation, it seems that neovim is the culprit here. Disabling the defaults (`set guicolor=`) settings seems to be the current solution.
