### ISSUE TITLE
Pane separator

### ISSUE THREAD

**Issue by EltonSouza** [gpakosz/.tmux#249]
Hi,
The issue I'm facing is the following.
The pane separator isn't working.
![Screenshot from 2019-05-20 11-04-47](https://user-images.githubusercontent.com/6872375/58028465-26501400-7af1-11e9-9780-2e4bb570790c.png)

**Comment by gpakosz** [comment]
Hello @EltonSouza,

I bet you're using WSL right?
If that's the case, your best chance is to use https://github.com/mintty/wsltty

If you're not using WSL, please see give details on your configuration: os, terminal emulator, tmux version.

There's also https://github.com/gpakosz/.tmux#troubleshooting

**Comment by EltonSouza** [comment]
I'm using Fedora 30, zsh with oh my zsh and my tmux version is tmux 2.9a

**Comment by gpakosz** [comment]
Oh well in fact, aren't you facing the exact same problem as #237?

Is your clone up to date?

**Comment by EltonSouza** [comment]
Is exactly the same problem as #237 
This worked form me https://github.com/nks5295/.tmux/commit/ba2976452e853c95dc4a4dddf9c154fa3105df8c
Thanks!
