### ISSUE TITLE
SSH/Mosh aware split pane (reconnects to remote server)

### ISSUE THREAD

**Issue by AaronVasquez** [gpakosz/.tmux#251]
Any docs on how to get this to work?

**Comment by gpakosz** [comment]
Hello @AaronVasquez 👋

Please refer to setup instructions and create your `~/.tmux.conf.local` copy.

Then edit it to set the `tmux_conf_new_pane_reconnect_ssh` variable to `true`.

Hope that helps 🤞

**Comment by gpakosz** [comment]
Ping @AaronVasquez?

**Comment by AaronVasquez** [comment]
This works. Thanks!
