### ISSUE TITLE
tmux_conf_copy_to_os_clipboard=true doesn't work on my MacOSX

### ISSUE THREAD

**Issue by djvsrose** [gpakosz/.tmux#252]
I almost feel it must be my problem but I just can't get it to work. I have reattach-to-user-namespace installed and tmux_conf_copy_to_os_clipboard=true in .tmux.conf.local. I used vim as editor. When I copy something in copy mode, it just doesn't copy the content automatically to OS clipboard. I have to do 'tmux show-buffer | pbcopy' explicitly to get the content to OS clipboard. I'm on MacOS 10.14.

**Comment by gpakosz** [comment]
Hello @djvsrose 👋

First, are you sure you edited your own copy of `~/.tmux.conf.local`, that is the one you copied into your home directory?

Then, did you reload the configuration after having edited your `~/.tmux.conf.local` copy?

Finally, can you please paste the output of:
```
$ tmux list-keys |grep -e 'copy-selection\|copy-pipe'
```

**Comment by djvsrose** [comment]
The answer is yes for the first 2 questions.

tmux list-keys | grep -e 'copy-selection\|copy-pipe'    => no output for this
Looks like I don't have any 'copy-pipe' in the keys.

**Comment by djvsrose** [comment]
tmux list-keys | grep -e 'copy-selection\|copy-pipe'  <= I did remember to type the escape before |

**Comment by gpakosz** [comment]
I you don't have any output for list keys then it means you unbound mappings.

If you want to have a look at stock bindings, you can run `$ tmux -L test -f /dev/null list-keys`. Here's what I get:
```
$ tmux -L test -f /dev/null list-keys | grep copy-selection
bind-key    -T copy-mode    C-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    M-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi C-j               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi Enter             send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
```

And with `tmux_conf_copy_to_os_clipboard=true` I get:
```
$ tmux list-keys | grep copy-pipe
bind-key    -T copy-mode    C-w               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode    M-w               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi C-j               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi Enter             send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi y                 send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel pbcopy
```

**Comment by djvsrose** [comment]
Yes, I got the above key list even if I set tmux_conf_copy_to_os_clipboard=true. Any insight on why tmux_conf_copy_to_os_clipboard=true does not lead to the below key list? My other changes in .tmux.conf.loca seem to apply correctly.

**Comment by gpakosz** [comment]
You should try installing `reattach-to-user-namespace` then reload the configuration

**Comment by djvsrose** [comment]
I installed reattach-to-user-namespace through brew and I'm pretty sure it's there. Could you explain what do you mean by 'reload the configuration'? Thanks

**Comment by gpakosz** [comment]
Ok let's start again.

> I have to do 'tmux show-buffer | pbcopy' explicitly to get the content to OS clipboard

This means that you don't need `reattach-to-user-namespace`. The need for it depends on the version of macOS and likely 10.14 doesn't require it (but I don't remember which version requires it).

If you followed the installation instructions, you have your own `~/.tmux.conf.local` copy next to `~/.tmux.conf`. To makes things clear, `.tmux.conf.local` should be a plain file at the root of your home directory.

Then after having edited your `~/.tmux.conf.local` copy and set `tmux_conf_copy_to_os_clipboard=true`, you should reload the configuration with `<prefix> + r`. Reloading the configuration will take into account the new value for the `tmux_conf_copy_to_os_clipboard` variable and apply bindings.

After configuration has reloaded, you should have the following bindings:
```
$ tmux list-keys | grep copy-pipe
bind-key    -T copy-mode    C-w               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode    M-w               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi C-j               send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi Enter             send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi y                 send-keys -X copy-pipe-and-cancel pbcopy
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel pbcopy
```
This means that for example in `copy-mode-vi`, selecting text then hitting the `y` keep will trigger `copy-pipe-and-cancel pbcopy` which both saves the text in a tmux buffer **and** pipes it to `pbcopy`.

I'm not sure at which step things went off though 🤔

**Comment by gpakosz** [comment]
@djvsrose what's the status of copying to the macOS clipboard?

**Comment by djvsrose** [comment]
Sorry for the late reply. This still doesn't work on my MacOS. The steps are simple and I think I followed all of them but tmux_conf_copy_to_os_clipboard=true just doesn't give me the bindings.

**Comment by gpakosz** [comment]
What's the output of
```
$ tmux list-keys | grep copy-pipe
```
?

**Comment by djvsrose** [comment]
"tmux list-keys | grep copy-pipe" shows nothing

**Comment by gpakosz** [comment]
Can you please pull the `master` branch, quit tmux, launch it again and then paste the output of

```
$ cut -c3- ~/.tmux.conf | tmux_conf_copy_to_os_clipboard=true sh -sx _apply_bindings
```

?
This way we'll see exactly what's going on

**Comment by djvsrose** [comment]
930$im18E226-1:~>cut -c3- ~/.tmux.conf | tmux_conf_copy_to_os_clipboard=true sh -sx _apply_bindings
+ cat
+ set -e
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
+ __newline='
'
+ command -v perl
+ _apply_bindings
++ tmux list-keys
++ grep new-window
++ head -1
+ line='bind-key    -T prefix       c                 new-window'
+ prefix='bind-key    -T prefix       c                 '
+ column=46
+ tmux_conf_new_window_retain_current_path=false
++ tmux list-keys
++ grep -e 'new-window\(\s\+-c\s\+"#{pane_current_path}\|$\)'
+ IFS=
+ read -r line
+ '[' -z '' ']'
+ continue
+ IFS=
+ read -r line
+ tmux_conf_new_pane_retain_current_path=true
++ tmux list-keys
++ grep -e 'split\(-\|_\)window'
+ IFS=
+ read -r line
+ '[' -z '' ']'
+ continue
+ IFS=
+ read -r line
+ tmux_conf_new_pane_reconnect_ssh=false
++ tmux list-keys
++ grep -e 'split\(-\|_\)window'
+ IFS=
+ read -r line
+ '[' -z '' ']'
+ continue
+ IFS=
+ read -r line
+ tmux_conf_new_session_prompt=false
++ tmux list-keys
++ grep -e new-session
+ IFS=
+ read -r line
+ '[' -z 'bind-key    -T prefix       C-c               new-session' ']'
++ printf %s 'bind-key    -T prefix       C-c               new-session'
++ cut -c-46
++ sed -E -e 's/[^ \ta-zA-Z0-9,._+@%/-]/\\&/g'
+ left='bind-key    -T prefix       C-c               '
+ _is_enabled false
+ '[' xfalse = xenabled ']'
+ '[' xfalse = xtrue ']'
+ '[' xfalse = xyes ']'
+ '[' xfalse = x1 ']'
+ return 1
++ printf %s 'bind-key    -T prefix       C-c               new-session'
++ cut -c46-
++ awk '-F\"' 'BEGIN { OFS = FS } { for (i = 1; i <= NF; i+=2) { gsub(/#{.+}/, "\"&\"", $i) } print }'
++ sed -E -e 's/command-prompt -p new-session[^;]+/new-session/g'
+ right=' new-session'
+ eval 'tmux bind-key    -T prefix       C-c                 new-session'
+ IFS=
+ read -r line
+ tmux_conf_copy_to_os_clipboard=true
+ command -v pbcopy
+ command=pbcopy
+ command -v reattach-to-user-namespace
+ command='reattach-to-user-namespace pbcopy'
+ command -v xsel
+ command -v xsel
+ command -v xclip
+ command -v clip.exe
+ '[' -c /dev/clipboard ']'
+ '[' -n 'reattach-to-user-namespace pbcopy' ']'
+ for table in '""' '"-t emacs-copy"' '"-t vi-copy"'
++ tmux list-keys
++ grep -e 'copy-selection\|copy-pipe'
++ head -1
+ line=
+ '[' -z '' ']'
+ continue
+ for table in '""' '"-t emacs-copy"' '"-t vi-copy"'
++ tmux list-keys -t emacs-copy
++ grep -e 'copy-selection\|copy-pipe'
++ head -1
+ line=
+ '[' -z '' ']'
+ continue
+ for table in '""' '"-t emacs-copy"' '"-t vi-copy"'
++ tmux list-keys -t vi-copy
++ grep -e 'copy-selection\|copy-pipe'
++ head -1
+ line=
+ '[' -z '' ']'
+ continue

**Comment by gpakosz** [comment]
Thank you,

What we're seeing here is that `tmux list-keys` simply doesn't contain any `copy-selection`, `copy-selection-and-cancel`, `copy-pipe` or `copy-pipe-and-cancel` bindings.

Can you please upload the exact content of your `~/.tmux.conf` and `~/.tmux.conf.local` files?

**Comment by djvsrose** [comment]
I think I have copy-selection-and-cancel bindings. I just don't have copy-pipe-and-cancel

Here is the output for     tmux list-keys | grep copy-selection 

bind-key    -T copy-mode    C-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    M-w               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi C-j               send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi Enter             send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi y                 send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel

Please see that attached .zip file. Files being renamed from .* to _*   
Thanks!


[Archive.zip](https://github.com/gpakosz/.tmux/files/3311207/Archive.zip)

**Comment by gpakosz** [comment]
I'm running out of ideas.

In the output log above (I edited it to use code blocks, see GitHub markdown formatting),
```
++ tmux list-keys
++ grep -e 'copy-selection\|copy-pipe'
++ head -1
```
is empty.

But you're telling me that `tmux list-keys | grep copy-selection`. This is in contradiction of what the debug log says.

Can you please run `tmux list-keys | grep -e 'copy-selection\|copy-pipe'` and paste the exact output in a code block?

**Comment by djvsrose** [comment]
tmux list-keys | grep -e 'copy-selection\|copy-pipe' 's exact output is nothing. Nothing got output.
tmux list-keys | grep -e 'copy-selection|copy-pipe' will output all the lines with copy-selection.

**Comment by gpakosz** [comment]
Please use code formatting blocks otherwise `\` characters get swallowed

**Comment by djvsrose** [comment]
both report /usr/bin/grep

**Comment by gpakosz** [comment]
![image](https://user-images.githubusercontent.com/553208/59875174-59abea00-93a0-11e9-8e58-b32754c1cf6a.png)

**Comment by gpakosz** [comment]
```
→ ~ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

**Comment by djvsrose** [comment]
My grep is exact same version as yours but grep result is just opposite to yours. I have no idea why.

**Comment by gpakosz** [comment]
can you paste the output of `$ env`?
(⚠️ make sure you remove sensitive information before pasting, I'm interesting in `LC_ALL` or `LANG` environment variables)

**Comment by gpakosz** [comment]
and what's your shell?

**Comment by gpakosz** [comment]
and can you do
```
$ type grep
```

I suspect there's some aliasing taking place

**Comment by djvsrose** [comment]
You reminded me that I do have `export GREP_OPTIONS="-E --color=auto"` in my .bashrc file. Let me try removing that.

**Comment by gpakosz** [comment]
Ok you found the issue.

But also, my configuration shouldn't pretend `\|` is a thing `grep` has to understand. I'll make a commit that improves invocations of `grep` and I'll close this issue in the commit.

Thanks for your patience @djvsrose!

**Comment by djvsrose** [comment]
Yeah, this works perfectly once I remove it. Thank you so much for helping this out. :)

**Comment by gpakosz** [comment]
I'm not sure I'll commit today, but this will definitely help improving the stability of the conf!

Thanks again 🙏

**Comment by PKUFlyingPig** [comment]
I had the same issue on my MacOSX. 
when I run `tmux -L test -f /dev/null list-keys | grep copy-selection` I get
<img width="617" alt="image" src="https://user-images.githubusercontent.com/60659728/112324752-12c5f380-8cee-11eb-9eec-45e950238795.png">
but when I run `tmux list-keys | grep copy-pipe` I got nothing.
First I don't know if it has anything to do with my grep, when I run `which grep`, it says
<img width="600" alt="image" src="https://user-images.githubusercontent.com/60659728/112325464-ab5c7380-8cee-11eb-9c4d-27dce975020a.png">
but even after I `unalias grep`, it also doesn't work.
