### ISSUE TITLE
Wrong window highlighted as active

### ISSUE THREAD

**Issue by RomainTT** [gpakosz/.tmux#253]
I don't know what happened, but since today I have this bug:

![image](https://user-images.githubusercontent.com/12847715/59420464-3a73f200-8dcd-11e9-912b-31b8fcde6b13.png)

As you can see the wrong window is marked as active. I kept default configuration, and I am using the version 2b0cb0b43ce7b4d212d91415390db8faf1b421df
Tmux version is 2.9a.

When I use tmux without any configuration, there is no issue with the active window.

Do you have any idea of what’s going on ?

**Comment by gpakosz** [comment]
Hello @RomainTT 👋

I have good news for you: yes I know what's going on! 🎉

You want commit e1452f124247120f3c8f27411d062b81d9919fe2.
Just `git pull` the configuration.

**Comment by RomainTT** [comment]
So simple ! Thank you for your quick answer. I use this depository as a submodule and I missed its update. 

Problem solved !
