### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2

### ISSUE THREAD

**Issue by guhur** [gpakosz/.tmux#256]
I have:
```$ tmux source-file ~/.tmux.conf                                      
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2
```
Here is the log file associated to this command: 
[tmux.log](https://github.com/gpakosz/.tmux/files/3313679/tmux.log)

**Comment by guhur** [comment]
I don't what happened but the problem is magically solved - maybe related to a simple reboot

**Comment by nckalil** [comment]
I'm still getting this issue.
`'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1`

I'm running on a linux server via ssh

**Comment by guhur** [comment]
You obtained a 1, and me a 2. We don't have the same error. You can produce a tmux.log with: 

`cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > tmux.log 2>&1`

**Comment by nick-bull** [comment]
Had the same issue, I think it's related to what your default shell is - if you've changed it with `chsh` sometimes a reboot is needed for that to take effect, so your resolving comment makes sense if that was the case. Changing the line to the following worked for me (note `sh` changed to `zsh`):

cut -c3- ~/.tmux.conf | zsh -s _apply_configuration

**Comment by nick-bull** [comment]
Had the same issue, I think it's related to what your default shell is - if you've changed it with `chsh` sometimes a reboot is needed for that to take effect, so your resolving comment makes sense if that was the case. Changing the line to the following worked for me (note `sh` changed to `zsh`):

`cut -c3- ~/.tmux.conf | zsh -s _apply_configuration`
