### ISSUE TITLE
change statusbar background color

### ISSUE THREAD

**Issue by huberb** [gpakosz/.tmux#257]
i'm trying to change the background color of the status bar.
As you can see in my screenshot, it is black (default) 
I tried to change every color in the config file. 
I also did a search and replace on every occurence of '#000000', but the color stays the same
when tmux is open, i can set the color with 

:set status-style "bg=red"

however, this command does not have any effect when written inside the tmux.conf.local.

I would expect this setting to change the color in .tmux.conf:

tmux_conf_theme_message_fg='#323232'                    # black
tmux_conf_theme_message_bg='#000000'                    # yellow
tmux_conf_theme_message_attr='bold'

Changing this values does not have any visible effect.

<img width="619" alt="Screenshot 2019-06-23 at 11 23 21" src="https://user-images.githubusercontent.com/28535778/59974187-59326f80-95a9-11e9-8ddf-4adaaef88499.png">

Here's my complete config:
https://pastebin.com/kaAXQ63j

**Comment by huberb** [comment]
ok after some tinkering the color was applied.
Guess i had another tmux session open so the ne config wasn't loaded.

this can be closed. Also thanks for the awesome Repo!

**Comment by mamyn0va** [comment]
I have the same problem here. Changing tmux_conf_theme_message and restart tmux has no effect. I also tried to replace all '000000' occurrences by 'ff0000' and it works for some parts, but the status bg remains black.

**Comment by mamyn0va** [comment]
Finally I found the answer here : https://github.com/gpakosz/.tmux/issues/146
