### ISSUE TITLE
Chaos of Status line due to the crash of network

### ISSUE THREAD

**Issue by John-Yao** [gpakosz/.tmux#258]
![image](https://user-images.githubusercontent.com/22048231/60245563-72138b80-98ef-11e9-8c71-d3b164ceeec1.png)
My network is very unstable. Every time it crash and I reconnect the tmux's session. Some chaos is occured in the Status line

**Comment by gpakosz** [comment]
Hello @John-Yao 👋

Duplicated lines likely are caused by your use of Unicode characters in your status line, please see https://github.com/gpakosz/.tmux#troubleshooting

**Comment by John-Yao** [comment]
Thanks for your reply! My LC_CTYPE is "en_US.UTF-8". It may be not due to the LC_CYTPE
Our hour passed, the status line is normal again. So there  are  some reasons as mentioned it the screenshot, something is unready!

**Comment by gpakosz** [comment]
Choosing the proper locale is unrelated to tmux disagreeing with your terminal emulator or font about Unicode characters' width.

About commands not ready, there's pretty much nothing one can do to precent tmux from displaying this message.

What's your exact setup?
- OS
- shell
- terminal emulator

Are you ssh-ing into a remote computer?

What customizations did you make to this configuration?

**Comment by John-Yao** [comment]
OS:Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) 
shell: bash
terminal emulator: MobaXterm
Yes, I am using remote computer by ssh.
I using the default config in the repo.

**Comment by gpakosz** [comment]
is tmux running on the local or remote host?

**Comment by John-Yao** [comment]
the tmux is running on the remote host. Network crashed in local computer when using session of tmux. When i try to reconnect session of tmux(remote host), The chaos of status line occured.

**Comment by gpakosz** [comment]
`<.... not ready>` only happens when tmux launches the command the very first time, which doesn't correspond to the situation you're describing because when you're reattaching to the remote tmux session you're not starting the tmux server over

**Comment by John-Yao** [comment]
I meet the same situation(network crash) without using the configuration of the repo. The status line is working well.

**Comment by gpakosz** [comment]
"network crash" is too broadly defined

Then, 2 things are happening really
- tmux cannot reuse a previous result from the `#(cut -c3- ~/.tmux.conf | sh -s _root #{pane_tty} #D)` command
- the status line display is messed up

Usually, when the status line gets messed up, it's because of Unicode symbols or emojis used in the status line. It happens because tmux and the terminal emulator disagree on character's width.

About the command being not ready, it can be interesting to find why the command it taking a lot of time but it's hard to debug from here.

**Comment by John-Yao** [comment]
Thank for your reply!
I noticed that the state of session is attached(observed by tmux ls), which means the tmux session is not detach. Thus i detach the session and run 'tmux detach' in terminal. The chaos of status line disappear.
About how to reproduce the Chaos of status line.
Attach to a session and shutdown the network suddenly. When reconnect to the session. The chaos occur.

**Comment by gpakosz** [comment]
Can you remove `#{pairing}` from `tmux_conf_theme_status_right` in your `~/.tmux.conf.local` copy?

**Comment by John-Yao** [comment]
yes. I try the ops. It work well when the session detach by the crash of network. Thanks.

**Comment by gpakosz** [comment]
If this solves the multiple status line, then there's nothing I can do. You're facing `tmux` and `MobaXterm` disagreeing on width of Unicode characters. And the only option is to not use them at all.

**Comment by gpakosz** [comment]
@John-Yao hello

are we good?

**Comment by John-Yao** [comment]
Yeah, absolutely!
