### ISSUE TITLE
copy-to-clipboard doesn't work

### ISSUE THREAD

**Issue by pwnslinger** [gpakosz/.tmux#259]
Hi, 
I went through issue #32 , #105 but none of them solved this problem. So, currently I have these lines uncommented in ~/.tmux.conf.local:

```
tmux_conf_copy_to_os_clipboard=true
set -g mouse on
```
and also I've installed xclip. but when I'm working with mouse and after selecting highlighted section then pressing 'y' to yank to clipboard, it just types y in my shell (zsh).  I'd appreciate if you help me out if you have any suggestions or workaround this.

**Comment by gpakosz** [comment]
Hello @pwnslinger 👋

So you're running `tmux` on a Linux box where `xclip` is installed.

Can you please reload the configuration with `<prefix> + r` then paste the output of
```
$ tmux list-keys | grep -E 'copy-seleciton|copy-pipe'
```

Note that with the default configuration and mouse mode enabled, relaxing the mouse button (`MouseDragEnd1Pane`) triggers the copy/yank action already. As such pressing `y` doesn't correspond to yanking to clipboard (since nothing is selected anymore) and it seems normal to me that the key is sent to the shell.

**Comment by gpakosz** [comment]
@pwnslinger ping?

**Comment by gpakosz** [comment]
@pwnslinger any news?

**Comment by eL0ck** [comment]
Hi @gpakosz, I'll happy continue this if you're still willing to assist!

I have the same problem.  I hit `<prefix> m`.  See that mouse mode is toggled to `on` in the bottom display but am unable to use any mouse functions as per the demo gif in the README.

I'm using windows terminal with wsl/ubuntu.  `xclip` is installed.  I'm using the standard configuration (only C-a is unbound as the prefix).

The `tmux list-keys` command above returns no lines after the grep.

What do you think I have done wrong?

**Comment by gpakosz** [comment]
There was a typo in the command, can you try again?

Under WSL/Ubuntu, `xclip` being installed will cause troubles. Please uninstall it.
Then `list-keys` should give you:
```
$ tmux list-keys | grep -E 'copy-selection|copy-pipe'
bind-key    -T copy-mode    C-w               send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode    M-w               send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode-vi C-j               send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode-vi Enter             send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode-vi y                 send-keys -X copy-pipe-and-cancel clip.exe
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel clip.exe
```

**Comment by eL0ck** [comment]
thanks for your help.

I have the same bind-key settings as you expect.  I have compared the config running on Windows Terminal (WSL/Ubuntu shell) and the stock WSL/Ubuntu application.  The windows shell seems to account for the issues.

Using the WSL app terminal I am able to click and drag pane boundaries and highlight and select text with the ENTER key.   That selection is available in the system clipboard.  

Strangely, when pasting into an iPython shell.  I get an extra 4 spaces for each line **just as though I was pasting into VIM without `:set paste`**.  Is this something to do with `copy-mode-vi` ?

**Comment by eL0ck** [comment]
Ok, please excuse that last comment. 

It's clearly an IPython setting.  Like Vim, one must prepare the shell for multiline paste by toggling `%autoindent`.

I'm coming from a Mac and iTerm2 and haven't used `:set paste` in years.  The dotfiles are the same so I will have to investigate somewhere else for where paste mode is automatically managed on my Mac/iTerm.

Thanks for your help @gpakosz.  Your tmux config is excellent, it's just the windows terminal options that are a let down.

**Comment by gpakosz** [comment]
Yeah I'm afraid all you're describing is outside the realm of my configuration.

Once bindings are configured, all the heavy lifting is done by `tmux` piping the selected text to `clip.exe` which is supposed to transfer it to the system clipboard. And pasting from the system clipboard is also unrelated to the bindings settings.

**Comment by LaiKash** [comment]
Hello, I'm having this same issue with a Kali in a virtual box scenario. I am not sharing the clipboard, xclip installed and the output for 

> tmux list-keys | grep -E 'copy-selection|copy-pipe'

is as you sayed. I really don't know what is wrong. Thank you.
