### ISSUE TITLE
SSH to another tmux session

### ISSUE THREAD

**Issue by jjcasmar** [gpakosz/.tmux#260]
Im on a tmux session (t1) and I have connect via SSH to another machine and start there another tmux session (t2).  Now Im trying to detach from t2, but when I do C-b + d, I detach from t2. 
How can I detach from the remote tmux session?

**Comment by gpakosz** [comment]
Hello @jjcasmar,

> Now Im trying to detach from t2, but when I do C-b + d, I detach from t2.

Did you mean "I detach from t1".

In any case, I think what you want is pressing the prefix key twice.

**Comment by jjcasmar** [comment]
wow, that worked like a charm, thanks!
