### ISSUE TITLE
Where to find nice looking .tmux.conf.local examples?

### ISSUE THREAD

**Issue by dereklin** [gpakosz/.tmux#261]
This project is the top search result for "tmux config" github project.  After I set it up, I see the default look and feel of my regular terminal.  It's pretty disappointing considering that the readme is showing a nice dark mode.

Where can I find some nice looking example files that I can just copy/paste and get a nice looking terminal?

**Comment by thomb** [comment]
If you are looking for a theme for your _terminal_ I don't think you are looking in the right place.

This tmux config provides a status line, and some handy predefined shortcuts etc, but as far as I know it is theme agnostic and should use whatever the theme is for your terminal.

If you want a nice dark mode, maybe look at installing Solarized and using its dark variant

**Comment by dereklin** [comment]
@thomb Since the readme shows a very nice looking terminal.  I think there should be some instructions on how to get it.

I fiddled around within the display section in .tmux.conf.local:

        # window style
        tmux_conf_theme_window_fg='colour247'
        tmux_conf_theme_window_bg='colour236'

        # highlight focused pane (tmux >= 2.1), possible values are:
        #   - true
        #   - false (default)
        tmux_conf_theme_highlight_focused_pane=true

        # focused pane colours:
        tmux_conf_theme_focused_pane_fg='colour250'
        tmux_conf_theme_focused_pane_bg='black'               # light blue

It still doesn't look 100%.  In fact, it might have messed up the status line styles...

I just went over to solarized: https://github.com/seebi/tmux-colors-solarized, I appended the content in tmuxcolors-256.conf into .tmux.conf.  I don't think it's working...

Ideally I shouldn't have to struggle that much :) .  But maybe it's just a learning thing.  Maybe someone can be kind enough to share their nice looking display settings here...

**Comment by thomb** [comment]
So, let's start with you providing a couple screenshots with what isn't working for you and we can go from there.

I'm not a maintainer or the like, just someone who thinks this project is the bee knees.

**Comment by dereklin** [comment]
@thomb Thanks for the offer.  You are right that this project is the bee knees indeed.  I reset everything and the applied my changes.  Thing are looking better right now.  I'll play with it for sometime from here.  I'll reach out again if I run into other issues.
