### ISSUE TITLE
new-window -c '#{pane_current_path}' binding is not applied in .tmux.conf.local

### ISSUE THREAD

**Issue by saviola777** [gpakosz/.tmux#262]
In my `~/.tmux.conf.local` I have the following:

```
bind -n S-down new-window -c '#{pane_current_path}'
```

After starting `tmux` (or when sourcing `~/.tmux.conf`), the output of `tmux list-keys | grep new-window` is

```
bind-key    -T prefix       c                 new-window
bind-key    -T prefix       e                 new-window -n ~/.tmux.conf.local "sh -c '${EDITOR:-vim} ~/.tmux.conf.local && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"
bind-key    -T root         S-Down            new-window
```
If I use a static path instead of `#{pane_current_path}`, it works as expected.

If I source `~/.tmux.conf.local` directly, it works:

```
bind-key    -T prefix       c                 new-window
bind-key    -T prefix       e                 new-window -n ~/.tmux.conf.local "sh -c '${EDITOR:-vim} ~/.tmux.conf.local && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"
bind-key    -T root         S-Down            new-window -c "#{pane_current_path}"
```

Any idea what's going on here? Running tmux 2.9a and today's master branch of your repo.

**Comment by gpakosz** [comment]
Hello @saviola777 👋

You're facing a current limitation of the configuration. Whether a new window retains the current path is directed by the `tmux_conf_new_window_retain_current_path` value.

Depending on whether it's `false` or `true`, existing bindings are inspected and tweaked accordingly.
The code responsible for this finds your binding and decides to remove the `-c #{pane_current_path}` part.

For now, I have no solution to protect some bindings so as to let someone have different bindings for `new-window` and `new-window -c #{pane_current_path}`

**Comment by saviola777** [comment]
Well, that is embarrassing, it seems I simply missed that configuration directive when setting up my `.tmux.conf.local`. Changing it to `true` works perfectly well for my use case, thanks and sorry.

**Comment by gpakosz** [comment]
@saviola777 Well the need for "protected" bindings defined in `~/.tmux.conf.local` still holds imho 🙃
