### ISSUE TITLE
problem when open tmux

### ISSUE THREAD

**Issue by vpeopleonatank** [gpakosz/.tmux#263]
when i open tmux, it load slowly. and show error on status bar. i think problem start from line 170
`run 'cut -c3- ~/.tmux.conf | sh -s _apply_configuration'`

![2019-07-14-092728_1920x1080_scrot](https://user-images.githubusercontent.com/30976876/61178791-544c6300-a61f-11e9-8e05-1d860e7a2422.png)

**Comment by gpakosz** [comment]
Hello @vpeopleonatank 👋

Can you please tell me:
- your OS
- your terminal emulator
- your shell
- tmux version

If `<... not ready>` is what you refer to as "error on status bar" well it's not necessarily an error but a command that takes a bit of time so tmux decides to display this while waiting for a result to display.

Also did you modify the `.tmux.conf` file or your `~/.tmux.conf.local` copy?

**Comment by vpeopleonatank** [comment]
Thanks for your reply.
My OS: Manjaro Linux x86_64
Terminal: Termite v15
Shell: zsh 5.7.1
Tmux version: tmux 2.9a
I 'v just modified ` ~/.tmux.conf.local` 
with 2 loc
```
set -g bell-action none
set -g visual-bell off
```
But i found that something crashed inside my system after messing some configuration. 
Anw, thanks for ur help :lov

**Comment by gpakosz** [comment]
Are you still experimenting slowness?

**Comment by vpeopleonatank** [comment]
> Are you still experimenting slowness?

After reinstall manjaro, it starts approximately 1s.

**Comment by gpakosz** [comment]
@vpeopleonatank can you please try the `optimizations` branch?

Make sure you kill all `tmux` server and client processes. Startup time should be greatly reduced.

**Comment by vpeopleonatank** [comment]
After reinstalling ubuntu 18.04 again, it's startup time is fast again. Thanks for your works :D

**Comment by gpakosz** [comment]
@vpeopleonatank great!

I let you close the issue if we're done then 👍
