### ISSUE TITLE
status line not rendering correctly on ubuntu 19.04 

### ISSUE THREAD

**Issue by kyp0717** [gpakosz/.tmux#264]
My status bar at the bottom did not render.  Install on Dell XPS 15 (model 9570).
Not sure what happen.  It was fine on my other Dell which is a lattitude also on ubuntu 19.04.
Please advise.

**Comment by gpakosz** [comment]
Hello @kyp0717 

I suggest you compare your configurations.

Check your `.bashrc` or equivalent. Make sure `TERM` has proper value outside of `tmux`, e.g. `xterm-256color`.
