### ISSUE TITLE
cannot display characters except english 

### ISSUE THREAD

**Issue by HawkAaron** [gpakosz/.tmux#266]
1. ssh log into remote server, without tmux, vim can edit characters like chinese.
2. ssh log into remote server, open tmux, then chinese characters will be replaced by underlines.

How to display characters in tmux mode?

**Comment by gpakosz** [comment]
Hello @HawkAaron 

This seems to be a general tmux question. If you're still having problems with stock tmux configuration (when launching tmux with `tmux -f /dev/null`), then check the value of `TERM` as well as `vim` configuration etc...
