### ISSUE TITLE
Failed to work on ubuntu18.04

### ISSUE THREAD

**Issue by Fangyh09** [gpakosz/.tmux#267]
I run following commands, but it does take effect(still simple tmux environment when I type tmux).
```
$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

➜  ~ ls -a | grep tmux
.tmux
tmux-client-30590.log
tmux-client-31058.log
.tmux.conf
.tmux.conf.local
➜  ~ pwd
/disk1/home/user1

**Comment by gpakosz** [comment]
Hello @Fangyh09 

Did you clone the configuration while tmux was running?
If it's the case, then make sure you quit all tmux clients and relaunch tmux

**Comment by Fangyh09** [comment]
@gpakosz Yes.

**Comment by Fangyh09** [comment]
@gpakosz It works like magic.
