### ISSUE TITLE
Where are the definitions of builtin variables like hostname_ssh or username_ssh?

### ISSUE THREAD

**Issue by c02y** [gpakosz/.tmux#269]
I cannot find the definitions of builtin variable like `hostname_ssh` or `username_ssh` used by this repo, neither in official tmux repo or in this repo.

**Comment by gpakosz** [comment]
Hello @c02y,

The `hostname_ssh` and `username_ssh` are indeed not tmux variables. My configuration replaces them with call to scripts.

When you use them, and you look at the output of `tmux show -g status-right`, you should see `#(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} true #D)` and `#(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true #D)`.

Hope that helps.

**Comment by c02y** [comment]
OK, thanks.
