### ISSUE TITLE
Question marks being displayed on the status bar

### ISSUE THREAD

**Issue by RakshithNM** [gpakosz/.tmux#270]
I am running tmux 2.9a, the status bar has question marks. How can i fix that?
![Screenshot 2019-07-31 at 11 53 04 PM](https://user-images.githubusercontent.com/10560321/62237372-6fc0b780-b3ee-11e9-9dc1-ebf75138ecb1.png)

**Comment by gpakosz** [comment]
Hello @RakshithNM 

It's all in the [`README`](https://github.com/gpakosz/.tmux/blob/master/README.md#enabling-the-powerline-look).

**Comment by RakshithNM** [comment]
@gpakosz i have installed powerline symbols, but dont see them. How do i patch a font?

**Comment by RakshithNM** [comment]
@gpakosz figured it. After installation of the font i had to make iterm2 make it use the powerline symbols font.

**Comment by gpakosz** [comment]
Yep that's why `README.md` warns

> this highly depends on your operating system and your terminal emulator

I can't possibly document every possible setup out there 🤷‍♂️

I'm glad you solved it!

**Comment by gpakosz** [comment]
I updated `README.md` with a screenshot of iTerm2 settings in hope it helps the next users 🤞
