### ISSUE TITLE
Why can't I see the icon on the status bar??

### ISSUE THREAD

**Issue by unixbhaskar** [gpakosz/.tmux#271]
It must be simple ..but I am missing it . The status line showing powerline fine ...but icons are missing ...not showing.

**Comment by gpakosz** [comment]
Hello @unixbhaskar 👋

What icons are you talking about?

Can you please give details?
  - what OS are you running?
  - what's the terminal emulator?
  - what's the shell?
  - can you take a screenshot?

The animated gif has been recorded on macOS so the battery and lightning bolt "icons" are emojis.

**Comment by unixbhaskar** [comment]
Hi,
I am trying it on across different Linux distros. The terminal is "st" . The shell is "bash" . 

Well, you can have a look at the picture here :
[https://i.imgur.com/XjVs3rx.png](url)

**Comment by gpakosz** [comment]
IMHO it's related to your font setup

**Comment by gpakosz** [comment]
With a recent version of `bash`, [with the Powerline font installed properly](https://github.com/gpakosz/.tmux#enabling-the-powerline-look), then the following should print the right triangle symbol:
```
$ printf '%b' '\uE0B0'
```
![image](https://user-images.githubusercontent.com/553208/63466349-6235a500-c463-11e9-9981-3455f49c6864.png)
