### ISSUE TITLE
Pixelbook

### ISSUE THREAD

**Issue by kbm300** [gpakosz/.tmux#273]
I'm using this in linux app via chrome OS container.  I assume the reason I can't see the battery info is because the linux container is not receiving the battery details.  Is there any way this can work?

**Comment by gpakosz** [comment]
Hello @kbm300 👋

What does `uname -s` say?
Also, do you have a `/sys/class/power_supply`?

**Comment by gpakosz** [comment]
@kbm300 ping?

**Comment by cujomalainey** [comment]
power_supply is empty fyi on the pixelbook crostini container

**Comment by gpakosz** [comment]
@cujomalainey 👋

If `/sys/class/power_supply` is not visible within the Linux container then there's pretty much nothing that can be done
