### ISSUE TITLE
Cannot get transperency when using tmux

### ISSUE THREAD

**Issue by antenore** [gpakosz/.tmux#274]
I'm using tmux 2.9a with st on Linux

st is compiled with transparency support and it works when not used with tmux.

I cannot get transparency to work with tmux, what am I supposed to change in the config? 

Thanks!

**Comment by gpakosz** [comment]
Hello @antenore 👋

Does your transparency problem happens when you launch `tmux` with a stock configuration? Make sure you kill all `tmux` processes then launch
```
$ tmux -f /dev/null
```

**Comment by antenore** [comment]
No, with stock tmux it works.

If i set the window bg theme to none it works as well, but than most of my custom colors are not taken into account.

Just because, I guess, none is not parsed for the windows bg, so the tmux config is not parsed till the end.

**Comment by antenore** [comment]
Later I'll share my .dotfiles, I'm mobile now. Thanks for your support!

**Comment by gpakosz** [comment]
My configuration sets various `-style` variables, including `window-style` based on configuration variables found in `~/.tmux.conf.local`.

You may want to edit you `~/.tmux.conf.local` copy and change
```
# window style
tmux_conf_theme_window_fg='default'
tmux_conf_theme_window_bg='default'
```
to
```
# window style
tmux_conf_theme_window_fg='default'
tmux_conf_theme_window_bg='none'
```

**Comment by antenore** [comment]
Yes, this is what I've done

**Comment by antenore** [comment]
https://github.com/antenore/dotfiles/blob/master/tmux/.tmux.conf.local  

This is not the last version, it contains some error. Neither the fg and bg as you mentioned, I'll have a look later

**Comment by antenore** [comment]
> https://github.com/antenore/dotfiles/blob/master/tmux/.tmux.conf.local
> 
> This is not the last version, it contains some error. Neither the fg and bg as you mentioned, I'll have a look later

Now it is the last version.
Same behavior, and I get this error:

```
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1
```

**Comment by gpakosz** [comment]
I think you should start over with a clean `.tmux.conf` (you must not change it) and a clean `~/.tmux.conf.local` copy. From there, try to make transparency work and only that.

After all this configuration, by the mean of `~/.tmux.conf.local` variables, is just a different way to assign tmux variables. So whatever works with stock tmux should work with it.

**Comment by antenore** [comment]
Found...

I've update the .tmux.conf to your last version and set 

```
# window style
tmux_conf_theme_window_fg='default'
tmux_conf_theme_window_bg='default'

```

And now it works.

Thanks a lot!!!

**Comment by gpakosz** [comment]
Cool!

Enjoy 🙂
