### ISSUE TITLE
`cut -c3- ~/.tmux.conf | sh -s _apply_configuration` returned X

### ISSUE THREAD

**Issue by nick-bull** [gpakosz/.tmux#279]
In relation to #149, #201, #238 and #256, and due to this happening for both me and a colleague, running `.tmux.conf` failed for the following line:

`cut -c3- ~/.tmux.conf | sh -s _apply_configuration`

I think it's related to what default shell is set - mine was set to `bash`, and it was stubborn even after a reboot (even after `chsh` - go figure!). Changing the line to the following worked for me (note `sh` changed to `zsh`) (**EDIT**: don't do this, read @gpakosz's commentary below re branch `gh-254`):

`cut -c3- ~/.tmux.conf | zsh -s _apply_configuration`

Would this be worth a pull request? Or does this change have some side effects? There are other `| sh -c` lines that might also benefit from being changed to `| zsh -c`, although I haven't tested.

**Comment by gpakosz** [comment]
Hello 👋

No, `cut -c3- ~/.tmux.conf | zsh -s _apply_configuration` would make this configuration depend on `zsh` which is not needed and likely not the proper way to solve whatever is happening.

Can you please run
```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > /tmp/log.txt 2>&1
```
And upload the result?

**Comment by nick-bull** [comment]
@gpakosz You are right, of course zsh would be an extra dep - my bad! 


Here's some visuals too, the before (including a manually run `cut -c3- ~/.tmux.conf | sh -s _apply_configuration` command):

![sh-apply-config-before](https://user-images.githubusercontent.com/13588509/63840980-dac3c680-c979-11e9-8e4c-118ef16a7a8b.png)

and after running the `zsh`-ified command (`cut -c3- ~/.tmux.conf | zsh -s _apply_configuration`):

![sh-apply-config-after](https://user-images.githubusercontent.com/13588509/63840981-db5c5d00-c979-11e9-9259-ce3a178850c0.png)

**Comment by nick-bull** [comment]
Forgot to also include the [`/tmp/log.txt`](https://github.com/gpakosz/.tmux/files/3550026/log.txt), from running `cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > /tmp/log.txt 2>&1`

**Comment by gpakosz** [comment]
Alright, please try out the `gh-254` branch.

I'll do my best to merge what's currently in flight soon.

**Comment by nick-bull** [comment]
Thank you! Consider this issue solved for me when using branch `gh-254` - thanks for the incredibly fast responses too, you are a true open source hero :)

**Comment by nivv** [comment]
@gpakosz has te gh-254 branch been deleted? I still have this issue

**Comment by gpakosz** [comment]
@nivv The `gh-254` branch has been merged. Just use most recent `master` branch

**Comment by nivv** [comment]
Thanks! It worked after a reinstall!

lör 14 dec. 2019 kl. 13:17 skrev Gregory Pakosz <notifications@github.com>:
