### ISSUE TITLE
command is not sync when change path

### ISSUE THREAD

**Issue by thanhngvpt** [gpakosz/.tmux#283]
hi all.
I've changed the value of `tmux_conf_theme_status_right` in file ~/.tmux.conf.local as follow 
`tmux_conf_theme_status_right=' ☸ #(kubectl config current-context) | ⎇ #(git rev-parse --abbrev-ref HEAD) | ♰ #{username}#{root} | ☽ #{hostname} '` but when i change directory to other project, git banch is  not updated. What wrong with me? 
Any body can help me take a look. Many thank.

**Comment by gpakosz** [comment]
Hello @thanhngvpt 👋

You likely want `#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD)`.

**Comment by thanhngvpt** [comment]
@gpakosz more information is with command for getting the current k8s context is sync ok.

**Comment by gpakosz** [comment]
@thanhngvpt are we good?

**Comment by thanhngvpt** [comment]
@gpakosz it ok with me now, one minor is should check the cwd is a git repo or not to show it will better.

**Comment by gpakosz** [comment]
I don't understand your question. `git rev-parse --abbrev-ref HEAD` outputs nothing when not in a Git repository

**Comment by thanhngvpt** [comment]
<img width="155" alt="Screen Shot 2019-09-26 at 10 23 29 PM" src="https://user-images.githubusercontent.com/19367683/65701937-63826f00-e0ac-11e9-916b-bea47ba472e9.png">
<img width="122" alt="Screen Shot 2019-09-26 at 10 23 41 PM" src="https://user-images.githubusercontent.com/19367683/65701940-641b0580-e0ac-11e9-9ab6-8a5145c6779e.png">

**Comment by gpakosz** [comment]
Unfortunately, you can't obtain to have the blue segment not showing when there's nothing in it

**Comment by gpakosz** [comment]
In fact you can if you make the space part of the variable, like this:
```
tmux_conf_theme_status_left='#{?#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD),#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD) ,}|foo | bar '
```

**Comment by thanhngvpt** [comment]
Many thank.
