### ISSUE TITLE
[BUG] <S-Left> or <S-Right> will delete a line of content in vim

### ISSUE THREAD

**Issue by codeMonkeyss** [gpakosz/.tmux#284]

**Comment by gpakosz** [comment]
Hello @codeMonkeyss 

Can you please try whether you're facing the problem with stock tmux configuration?
By exiting all tmux sessions then re-launching with `tmux -f /dev/null`.

**Comment by gpakosz** [comment]
Please note that my configuration doesn't change `S-Left` and `S-Right` bindings
```
tmux list-keys | grep S-
bind-key -r -T prefix       S-Up              refresh-client -U 10
bind-key -r -T prefix       S-Down            refresh-client -D 10
bind-key -r -T prefix       S-Left            refresh-client -L 10
bind-key -r -T prefix       S-Right           refresh-client -R 10
```

**Comment by arturog** [comment]
It also happens to me:
- It removes the first line of a file
- It may set the file as "modifiable off"

**Comment by gpakosz** [comment]
@arturog can you please try with stock tmux configuration like described above?

**Comment by codeMonkeyss** [comment]
@gpakosz I try to launch with `tmux -f /dev/null`, and <S-Left/Right> do nothing.

**Comment by codeMonkeyss** [comment]
if the TERM value is xterm-256color, <S-Left/Right> is working properly.
So I modify .tmux.conf file.

`set -g default-terminal "xterm-256color" # colors!`

**Comment by gpakosz** [comment]
```
set -g default-terminal "xterm-256color"
```
is wrong.

See [tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ):
> Inside tmux TERM must be "screen", "tmux" or similar (such as "tmux-256color").
> Don't bother reporting problems where it isn't!

Make sure `TERM` is set to `xterm-256color` *outside* of tmux, then let my configuration set it to `screen-256color` *inside* of tmux.

**Comment by codeMonkeyss** [comment]
You are right. The `TERM` value shouldn't be set to `screen-256color`, should be set to `tmux-256color`. Thank you for solving my problem.
