### ISSUE TITLE
Cursor flickers for no reason

### ISSUE THREAD

**Issue by chrisjohnson** [gpakosz/.tmux#285]
I haven't traced down the exact culprit but I have totally eliminated 100% of my own config and just symlinked .tmux.conf and .tmux.conf.local right to your repo and I am getting cursor flicker that doesn't happen with vanilla tmux or my own home grown config

**Comment by chrisjohnson** [comment]
http://g.recordit.co/vbFnfcltZl.gif gif recording -- I'm giving no input to cause this

**Comment by gpakosz** [comment]
Hello @chrisjohnson 👋

I have no idea at that point. I suspect it's caused by the commands launched from the status line.
If it's the case, it means doing:

```
:set -g status-left ''
:set -g status-right ''
```

will stop the "flickering".

**Comment by kcalvinalvin** [comment]
Also noticing this. Is there any update?

**Comment by deoxykev** [comment]
I removed the battery indicator completely from the right status bar and the problem went away:

`~/.tmux.conf.local`
```
tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized}, %R , %d %b | #{username}#{root}'
```
