### ISSUE TITLE
select to copy to clipboard doesn't work with hyper terminal

### ISSUE THREAD

**Issue by chovy** [gpakosz/.tmux#288]
https://hyper.is/

**Comment by gpakosz** [comment]
Hello @chovy 👋

Sorry for not getting back to you earlier. Are you still using Oh My Tmux! ?

What's hyper terminal btw?

**Comment by chovy** [comment]
hyper terminal is a cross platform terminal app.

**Comment by gpakosz** [comment]
Hey @chovy 👋

And which platform are you using Hyper Terminal on?
