### ISSUE TITLE
All the vim mapping(like C-F1、C-F2、C-F3) become useless.

### ISSUE THREAD

**Issue by YangZhaoWeblog** [gpakosz/.tmux#292]
When I in tmux and start vim, I can't using the mpping that Ctrl-F1 Ctrl-F11......, How can I solve it???

**Comment by gpakosz** [comment]
Such problems happen when `TERM` doesn't have the proper value.

Verify `TERM` is set to `xterm-256color` outside of tmux and is `screen-256color` or `tmux-256color` inside of tmux.

Then verify your `.vimrc`.
