### ISSUE TITLE
Feature Request: Icon for mouse mode

### ISSUE THREAD

**Issue by mattysweeps** [gpakosz/.tmux#295]
I've been thinking of this for a while, so I'd thought I'd make an issue to discuss it. It would be very nice to have an icon displayed if mouse mode was enabled. This is particularly useful for nested tmux sessions.

When I scroll, mouse mode needs to be enabled on the inner-most tmux session.
When I copy, mouse mode needs to be on the outer-most tmux session.

Maybe there are other, better solutions for my copy/scroll issue, but a mouse icon couldn't hurt.

Has anyone done this/seen this?

**Comment by 0x326** [comment]
I think this character would be fitting: 🖰

**Comment by gpakosz** [comment]
![image](https://user-images.githubusercontent.com/553208/71372520-e97f5a80-25b4-11ea-85eb-db620e87c03d.png)

Maybe not 😅

**Comment by gpakosz** [comment]
So yeah `TWO BUTTON MOUSE (U+1F5B0)` doesn't show by default on macOS.

Maybe the emoji? 🖱

**Comment by 0x326** [comment]
@gpakosz That works for me

**Comment by gpakosz** [comment]
@0x326 Sure it depends on the font you're using. But in fact there are not such many standard fonts that have `U+1F5B0` at least according to https://www.fileformat.info/info/unicode/char/1f5b0/fontsupport.htm

**Comment by 0x326** [comment]
@gpakosz I mean, the emoji version is fine with me
