### ISSUE TITLE
Receiving Lost Server error shortly after starting a TMUX session

### ISSUE THREAD

**Issue by SchwifD** [gpakosz/.tmux#298]
[tmux-client-19.txt](https://github.com/gpakosz/.tmux/files/3889526/tmux-client-19.txt)
[tmux-server-21.txt](https://github.com/gpakosz/.tmux/files/3889527/tmux-server-21.txt)

(Is there a better way to show my logs?)

**Comment by SchwifD** [comment]
Switching to the WSL Debian Distro on the Microsoft Store seemed to fix this. I was originally using WSL Ubuntu.

**Comment by gpakosz** [comment]
Right then it's a WSL problem

**Comment by gpakosz** [comment]
@SchwifD IMHO it's a tmux / libevent bug that my configuration exacerbates, maybe by setting variables from a background processes.  And it won't be fixed. If you want to run Ubuntu, I suggest you use Ubuntu 18.04 in WSL
