### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 255

### ISSUE THREAD

**Issue by bigapple10027** [gpakosz/.tmux#300]
OS: Ubuntu 18.04.3
Tmux: 2.6 (Orginal comes with Ubuntyu 18.04.3)
.tmux branch: master (SHA ff0c1769dfab33e44ab6f07df50f581de39c2f85)
Terminal:  iTerm2
Shell: zsh
TERM has already been set to xterm-color256

Inside tmux, if I do:

`:source ~/.tmux.conf` then I got the error message:

'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 255

Then no desired color theme at all. I believe the .tmux.conf is partially applied because the key binding for ctrl-A is definitely working correctly. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/25491828/69732294-38ce8a00-10e0-11ea-8b06-3877d11c8f6e.png)

**Comment by gpakosz** [comment]
Can you please test with `a9b526c9a20619840cd1e08b8e0dcbae4486f944` (I force pushed `master`)

**Comment by bigapple10027** [comment]
@gpakosz Seems `a9b526c9a20619840cd1e08b8e0dcbae4486f944` is not a valid commit in the commit history. But yeah, I checked out one commit before HEAD of master, and it worked. No worries, I think it would be very helpful if you can tag the known good commit (for release) or call out the risky ones so that people won't be confused.

**Comment by gpakosz** [comment]
![image](https://user-images.githubusercontent.com/553208/69738282-267f3b00-1136-11ea-8580-46b8b5c26e59.png)

Can you please do
```
$ cd ~/.tmux
$ git fetch -p
$ git reset --hard origin/master
```
(beware with `git reset --hard` if you made change to the repository, which you shouldn't 😉)

**Comment by bigapple10027** [comment]
Just did. Verified there is no issue in a9b526c9a20619840cd1e08b8e0dcbae4486f944. So the broken master I pulled has been overwritten by this commit I guess? a9b52 is the forced push I guess?

**Comment by gpakosz** [comment]
yes

**Comment by gpakosz** [comment]
Are we good?

**Comment by Frederick888** [comment]
I got `'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127` using tmux 2.7 with [`a9b526c`](https://github.com/gpakosz/.tmux/commit/a9b526c9a20619840cd1e08b8e0dcbae4486f944). Is this related?

**Comment by gpakosz** [comment]
@Frederick888 👋

Can you please try commit 0ba20aa1f489311bc2892765b2fe3305a341476c 🙏

**Comment by Frederick888** [comment]
@gpakosz Still got the same error message I'm afraid.

**Comment by gpakosz** [comment]
@Frederick888 can you please make sure you kill all tmux server and client processes, then

1. launch tmux
2. if you get an error, from within tmux at shell prompt run `$ cut -c3- ~/.tmux.conf | sh -s _apply_configuration` and upload the output?

**Comment by Frederick888** [comment]
@gpakosz 
```
$ cut -c3- ~/.tmux.conf | sh -s _apply_configuration
sh: perl: not found
```
Ah, so that's why... I'm using OpenWRT and it hasn't got perl installed. After installing perl both a9b526c and 0ba20aa worked for me. Guess it's another package to compile next time :P

**Comment by gpakosz** [comment]
Ah yeah at the beginning I didn't depend on `perl`, but I needed look-ahead and look-behind regex features to implement `_apply_bindings()` in a way that's robust

**Comment by gpakosz** [comment]
I made the requirements explicit
