### ISSUE TITLE
Upgrade to Tmux 3.0 breaks everything

### ISSUE THREAD

**Issue by xircon** [gpakosz/.tmux#301]
Manjaro Unstable:
```
[2019-11-27T18:48:23+0000] [ALPM] upgraded tmux (2.9_a-4 -> 3.0-1)
```
With v3 none of the theming loads, plain bar at bottom
Downgrading to 2.9 fixes, don't know where to look for errors, sorry.

**Comment by Zebradil** [comment]
Had the same issue on Arch. Updating `.tmux` to the latest master solved the issue. Also see #254.

**Comment by xircon** [comment]
Thanks, that fixed it.

**Comment by dessalines** [comment]
This should be stickied somewhere on the readme.

**Comment by dessalines** [comment]
Figured out the temp fix. For arch users:

`sudo pacman -U /var/cache/pacman/pkg/tmux-2.9_a-4-x86_64.pkg.tar.xz`

**Comment by Zebradil** [comment]
But why?
Just update the plugin.
