### ISSUE TITLE
Getting invalid or unknown command bind-key -T in tmux 2.8

### ISSUE THREAD

**Issue by MadaraUchiha** [gpakosz/.tmux#303]
## Steps:
1. Updated the repo with `git pull`
2. Started a new tmux session with `tmux new-session -s name`

## Expected:
tmux session starts without errors

## Actual:
Got the following error:
```
/tmp/tmp.1ztDiEo2jg:9: invalid or unknown command: bind-key    -T prefix       "                 split-window -c '#{pane_current_path}'
```

Hitting CTRL+C on it will continue with the creation of the tmux session. Attaching to the session shows no error. Creating new panes works.

## Additional Info
- OS Version: Ubuntu 19.04
- tmux Version: tmux 2.8 (latest in apt)
- Shell: zsh

Note: I have not yet tried to install tmux 3.0 to see if it repros there, but it _is_ worth mentioning that 2.8 is the version supplied by `apt install tmux`.

**Comment by gpakosz** [comment]
Can you please tell me which commit you're using?

**Comment by MadaraUchiha** [comment]
1cf813f, current `master`.

**Comment by MadaraUchiha** [comment]
`git checkout master^` to return to one commit behind the current one works. I see no error when starting the session.

**Comment by gpakosz** [comment]
fixed, sorry I was tired yesterday and pushed crap 😐

**Comment by MadaraUchiha** [comment]
Confirmed! Thank you :)

**Comment by gpakosz** [comment]
You're welcome, enjoy!
