### ISSUE TITLE
is this something like error or it looks so?

### ISSUE THREAD

**Issue by azamet90** [gpakosz/.tmux#304]
![image](https://user-images.githubusercontent.com/44042178/70455062-8dadcf80-1ae6-11ea-84c9-055a2ee9da3c.png)
another picture:

![image](https://user-images.githubusercontent.com/44042178/70455102-a4ecbd00-1ae6-11ea-8a9d-2f100b26c01e.png)

**Comment by gpakosz** [comment]
Hello @azamet90 👋

What's your actual problem / question?

**Comment by azamet90** [comment]
> Hello @azamet90 wave
> 
> What's your actual problem / question?

hi thanks for answering!

my problem is on the status bar... the icons there... how can i change it? is it some missing charachters or is it just so?

**Comment by gpakosz** [comment]
Did you read `README.md` and did you create your `~/.tmux.conf.local` copy then customized that file?

**Comment by azamet90** [comment]
> Did you read `README.md` and did you create your `~/.tmux.conf.local` copy then customized that file?

i just did these steps:
```
$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

was there also something different extra i have to do more?

sorry for my bad english

**Comment by gpakosz** [comment]
Ok well I don't really get what you want when you say
> my problem is on the status bar... the icons there... how can i change it?

The screenshot you uploaded looks fairly normal to me.
But now that I'm giving it more thought, it seems we don't understand the same thing about "status bar".

In tmux, the status bar is the bottom colored line. What you seem to want to change is your "terminal's tab title". In which case, you need to edit `~/.tmux.conf.local` copy and change
```
tmux_conf_theme_terminal_title='#h ❐ #S ● #I #W'
```
to something that suits your tastes.

Don't forget to reload the configuration!
```

**Comment by azamet90** [comment]
> `~/.tmux.conf.local`

thank you very much this was i want to know
