### ISSUE TITLE
Statusbar issue

### ISSUE THREAD

**Issue by elcidowneador** [gpakosz/.tmux#305]
Hi,

I have a strange trouble with statusbar. The whole statusbar appear in green, but i'm using the same configuration (with .tmux.conf.local) that use in another user of the system thats work correctly. 

In this configuration i have enabled mouse and clipboard management, and in the user with the whole statusbar appears in green is working so i think that configuration is loading.

I attach two screenshots to see problem:

User with statusbar colors working
<img width="1668" alt="Screen Shot 2019-12-10 at 10 10 48" src="https://user-images.githubusercontent.com/48317223/70515701-0d16bf80-1b36-11ea-8f3c-2ae8401c557b.png">

User without statusbar colors working
<img width="1669" alt="Screen Shot 2019-12-10 at 10 10 32" src="https://user-images.githubusercontent.com/48317223/70515685-08520b80-1b36-11ea-93fa-f5949d93cc00.png">

My tmux version is 3.0a. Tried to make clean installation (without my custom configuration), tried to reinstalling tmux... and no luck.

**Comment by gpakosz** [comment]
Hello @elcidowneador 👋

Which commit of this configuration are you using?

**Comment by elcidowneador** [comment]
Hello @gpakosz 

Thanks for your fastest reply. The commit are using are f4fc273 (master). I'm using the same in both users.

**Comment by gpakosz** [comment]
tmux 3.0a works for me

Can you please run the following within a pane created in tmux 3.0a?
```
$ cut -c3- ~/.tmux.conf | sh -s _apply_configuration
```

**Comment by elcidowneador** [comment]
`$ cut -c3- ~/.tmux.conf | sh -s _apply_configuration
sh: line 672: /tmp/tmux.conf: Permission denied`

If apply less restrictive permissions to this file

`cut -c3- ~/.tmux.conf | sh -s _apply_configuration
Cannot complete in-place edit of /tmp/tmux.conf: failed to rename work file '/tmp/XXJnbH49' to '/tmp/tmux.conf': Permission denied, <> line 17.`

**Comment by elcidowneador** [comment]
Currently i'm trying to set TMUX_TMPDIR inside my homedir to fix this problem.

**Comment by gpakosz** [comment]
Can you please do `$ git fetch -p && git reset --hard`? In fact f4fc2730cf1a2ae26ebf3707548945a73cd74ff1 doesn't use `/tmp/tmux.conf`. It was a leftover from a commit I forced pushed. (looks like I have to stop doing that!)

**Comment by nemchik** [comment]
I'm also seeing the green bar at the bottom. I fetched and reset to ff0c176 and then tried `:source-file ~/.tmux.conf` and saw `'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 255`. I ran `cut -c3- ~/.tmux.conf | sh -s _apply_configuration` and saw
```
unknown key: \1
syntax error at -e line 1, near "!= ) "
syntax error at -e line 1, near ";}"
Execution of -e aborted due to compilation errors.
```
`tmux -V` shows `tmux 2.6` which is the latest in the Ubuntu repositories for `Ubuntu 18.04.3 LTS` (which is what I'm running).
After all that I still have the green bar. I used to have the multi-colored bar but I'm not sure which exact commit here resulted in the green bar. It was recent, maybe the gh-254 fix?

**Comment by gpakosz** [comment]
@nemchik please `$git fetch -p && git reset --hard origin/master` which should bring you to f4fc2730cf1a2ae26ebf3707548945a73cd74ff1

**Comment by nemchik** [comment]
I ran the command as recommended, here is the output
```
baines@yori:~/.tmux$ git fetch -p && git reset --hard origin/master
From https://github.com/gpakosz/.tmux
- [deleted]         (none)     -> origin/os-clipboard
HEAD is now at f4fc273 rewrote _apply_bindings() to support new tmux 3.0 bindings (4)
baines@yori:~/.tmux$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
baines@yori:~/.tmux$
```
Then I did ctrl+b and `:source-file ~/.tmux.conf` and got no errors and I now see multiple colors again (first screenshot in the OP). Thanks!

**Comment by elcidowneador** [comment]
Awesome @gpakosz 

Problem is now solved. Thank you.
