### ISSUE TITLE
tmux version `3.0a` do not work properly

### ISSUE THREAD

**Issue by wenma** [gpakosz/.tmux#306]
Upgrade tmux to version ```3.0a```, this ```.tmux.conf``` don't work properly,  so I downgrade to version ```2.9a```, everything is fine.

Are there plans to support the new version ?

**Comment by gpakosz** [comment]
Hello @wenma 👋

Did you update this configuration?
```
$ cd ~./tmux.conf
$ git fetch -p
$ git pull
```

**Comment by wenma** [comment]
@gpakosz thanks,  when I upgrade ```.tmux.conf```,  it works with tmux version 3.0a is totally fine.  Closed this issue.
