### ISSUE TITLE
reattach-to-user-namespace is not needed anymore since tmux 2.6

### ISSUE THREAD

**Issue by bric3** [gpakosz/.tmux#307]
See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/66

The following just works

```
$ echo "test" | pbcopy
$ pbpaste
test
```

**Comment by gpakosz** [comment]
Hello @bric3 👋

This configuration supports tmux >= 2.1 and will soon support "only" tmux >= 2.4.

If you're using tmux >= 2.6, just don't install `reattach-to-user-namespace` and this configuration won't make use of it.

**Comment by gpakosz** [comment]
Hey @bric3 👋

Are you ok with me closing this issue or do you want to discuss it further?

**Comment by bric3** [comment]
@gpakosz Hi sorry I totally missed this reply in december, sorry !!!
Yes it's ok to close this issue :)

Thanks again for this work it was really helpful!
