### ISSUE TITLE
incompatible with tmux3.0

### ISSUE THREAD

**Issue by Kur0x** [gpakosz/.tmux#310]
The latest release is `tmux 3.0a`. I installed `tmux 3.0`, found that the status line become original style. I switch to `tmux 2.9a`,fancy status line is back.
![image](https://user-images.githubusercontent.com/9768369/71462106-3cdbed80-27ed-11ea-80a2-1904c035ef8d.png)
![image](https://user-images.githubusercontent.com/9768369/71462124-51b88100-27ed-11ea-835a-0e1bf2b9aa34.png)

**Comment by gpakosz** [comment]
Hello @Kur0x 👋

Did you pull the configuration to the latest commit?

**Comment by Kur0x** [comment]
I'm using the master branch of `.tmux` and release version of `tmux3.0` (#bbcb199).

**Comment by gpakosz** [comment]
Can you please tell me which OS you're using? Which terminal emulator? 

The commit that's supposed to work with tmux `3.0` or `3.0a` is `f4fc2730cf1a2ae26ebf3707548945a73cd74ff1`.

Also once inside tmux, if it still doesn't work, can you please tell me what's the output of
```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
```

Thank you

**Comment by Kur0x** [comment]
I cloned again. It works. It seems that I accidentally overwrite the `.tmux` folder with the old version.
