### ISSUE TITLE
How close selection copy immediately when set mouse on?

### ISSUE THREAD

**Issue by zxdposter** [gpakosz/.tmux#311]
Tmux version: 3.0a
OS: macOS Catalina 10.15.2

**Comment by gpakosz** [comment]
Hello @zxdposter 👋

I'm sorry I don't understand the question

**Comment by zxdposter** [comment]
@gpakosz When mouse on, I select text will copy to clipboard immediately, I don't want copy immediately, how close it.

**Comment by gpakosz** [comment]
You want to adjust your `MouseDragEnd1Pane` bindings. By default, tmux uses `copy-selection-and-cancel`. In your `~/.tmux.conf.local` copy you can override that with:
```
bind-key    -T copy-mode    MouseDragEnd1Pane     send-keys -X copy-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane     send-keys -X copy-selection
```

**Comment by zxdposter** [comment]
Select text still copy to clipboard.

**Comment by zxdposter** [comment]
@gpakosz But I run this in cmd, it will be useful.
```bash
tmux bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection
tmux bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
```

**Comment by gpakosz** [comment]
If you want to disable both selection and copy to clipboard then something like

```
unbind-key    -T copy-mode    MouseDrag1Pane
unbind-key    -T copy-mode-vi MouseDrag1Pane
unbind-key    -T root         MouseDrag1Pane
```

**Comment by zxdposter** [comment]
Add this, Not I cannot select and highlight text.  @gpakosz

**Comment by gpakosz** [comment]
If you want the text to be selected then do not unbind `MouseDrag1Pane` but unbind `MouseDragEnd1Pane`.

Anyways, this is a general tmux support question, nothing specific to my configuration. I suggest you get familiar with copy-mode and bindings concepts.

**Comment by zxdposter** [comment]
I understand you, before you say, I already unbind MouseDragEnd1Pane, it work fine more I expect, in this way the highlight text will not disappear when I release mouse.
