### ISSUE TITLE
Nothing is getting loaded on  bottom bar

### ISSUE THREAD

**Issue by ayushmpb95** [gpakosz/.tmux#313]
Hi,
Things were working fine initially and I was able to see the battery bar and other features, but after I shut down the computer, everything is gone. Attaching the screenshot for further help.
<img width="1792" alt="Screenshot 2020-01-16 at 2 51 05 AM" src="https://user-images.githubusercontent.com/10811713/72472809-54fec580-380b-11ea-8c6d-0b6588a3666a.png">

Please help on it.
Thanks

**Comment by ayushmpb95** [comment]
ping @gpakosz

**Comment by thomb** [comment]
This is what vanilla tmux looks like, so it doesn't appear as though this session is picking up this config. 

First steps would be to check to see what your `tmux.config` looks like on this machine

**Comment by ayushmpb95** [comment]
Hi @thomb 
Thanks for your help, I deleted every tmux config file and basically re-ran all the steps back again and now it is showing all the things.
<img width="1792" alt="Screenshot 2020-01-16 at 10 01 21 AM" src="https://user-images.githubusercontent.com/10811713/72493482-2999cc00-3847-11ea-926e-9e7c7405a7e7.png">
