### ISSUE TITLE
When mouse mode is on, double clicking in guake opens a new tab

### ISSUE THREAD

**Issue by mralext20** [gpakosz/.tmux#315]
when using this tmux config in guake, a double click causes a new tab to open. this does not happen in gnome-terminal, nor does it happen with a normal tmux config.

**Comment by gpakosz** [comment]
Hello @mralext20 👋

My configuration doesn't do anything special with double click. I suspect the issue is elsewhere 🤷‍♂️

For the record, here's what I get for stock tmux:
```
$ tmux -f /dev/null list-keys | grep DoubleClick
bind-key    -T copy-mode    DoubleClick1Pane      select-pane \; send-keys -X select-word
bind-key    -T copy-mode-vi DoubleClick1Pane      select-pane \; send-keys -X select-word
```

`DoubleClick1Pane` is bound in `copy-mode` and `copy-mode-vi` only, and it implies mouse mode is enabled.

**Comment by uriel1998** [comment]
Necrobumping for the next person looking for something - this happened for me as well, but *only* when I had weechat running with `weechat.look.mouse` set to `on`.   Changing this selection made this behavior go away, confirming @gpakosz 's observation and suggesting a possible culprit for the next person to run into this.
