### ISSUE TITLE
Doesn't work for tmux >= 3

### ISSUE THREAD

**Issue by jan876** [gpakosz/.tmux#317]
I upgraded to tmux 3 on my mac Catalina, o-my-tmux doesn't work anymore. Is there any patch I can use?

**Comment by gpakosz** [comment]
Hello @jan876 👋

Make sure your clone is up to date. It definitely works with tmux >= 3.0

**Comment by paddyroddy** [comment]
once I updated my clone it worked fine

**Comment by jan876** [comment]
Worked with new update. Thanks.
