### ISSUE TITLE
Doesn't work on termite.

### ISSUE THREAD

**Issue by killmaster** [gpakosz/.tmux#32]
The status line doesn't show most of the time and most of the stuff doesn't allign.

**Comment by gpakosz** [comment]
Hmm, works for me?

I just installed it on Archlinux with `pacaur -S termite-git`.

![screenshot](https://cloud.githubusercontent.com/assets/553208/19812117/989f7a48-9d34-11e6-8e77-9ba56e33cf90.png)

**Comment by killmaster** [comment]
Did a fresh install, still same problem.
![screenshot from 2016-10-28 16-44-50](https://cloud.githubusercontent.com/assets/167298/19812546/e88bf5a6-9d2d-11e6-819f-c3a8aee43a29.png)

Also happens on gnome-terminal, but it works in st.

**Comment by gpakosz** [comment]
Try to double check the following:
  - `TERM` is set to `xterm-256color` outside of `tmux`
  - you're using an UTF-8 locale
  - `tmux_conf_theme_24b_colour` is set to `false` in `~/.tmux.conf.local` (not all terminal emulators support 24b colours)

**Comment by killmaster** [comment]
Just set the `TERM` to `xterm-256color`
The locale is UTF-8
`tmux_conf_theme_24b_colour` is set to `false`

The problem still occurs.

**Comment by gpakosz** [comment]
Are you sure you're running tmux version > 2.1 and you killed all tmux process?

Setting locale depends on your Linux distribution. I have `LANG=en_US.UTF-8`.

Beside that, I currently have no idea.

**Comment by killmaster** [comment]
My locale is `en_GB.utf8` and my tmux version is 2.3

**Comment by gpakosz** [comment]
I have tmux 2.3, termite v12-4-g7930760

**Comment by gpakosz** [comment]
Works for me when `TERM` is set to `xterm-termite` or `xterm-256color` outside of `tmux`. Inside tmux `TERM` is `screen-256color`. What's the value of `TERM` inside tmux on your side?

**Comment by killmaster** [comment]
Outside tmux it's `xterm-termite` and inside it's `screen-256color`

**Comment by gpakosz** [comment]
Worth trying to set `TERM` to `xterm-256color` outside of tmux, make sure all tmux processes are killed and relaunch?

**Comment by killmaster** [comment]
Same thing happens. I've tried moving the status line to the top and it works. It just doesn't work on the bottom.

**Comment by wbthomason** [comment]
I'm seeing the same problem. `tmux` v2.3, `termite` v12. `TERM` is `xterm-termite` outside `tmux`, `screen-256color` inside. Also on Arch. Locale is en_US.UTF-8. I can also confirm that there is no problem when I move the status line to the top.

**Comment by wbthomason** [comment]
The issue is not unique to this repo, though. Enabling just powerline in .tmux.conf (removing this repo entirely) presents the same sort of problem. I think this is on Termite's end.

**Comment by wbthomason** [comment]
As was corrected in the response to the termite issue I opened, this actually seems to stem from VTE.

**Comment by wbthomason** [comment]
Making things all the more interesting, things work perfectly fine for me on another Arch machine with the same versions of everything and environment variables.

**Comment by wbthomason** [comment]
Using `git bisect`, I think I've found the commit which started this behavior: [1503232](https://github.com/gpakosz/.tmux/commit/150323277382577f184e5cd87dfce2de5176264c). Unfortunately, this commit is pretty big, so I'm not sure *which* changes caused the problem yet.

**Comment by wbthomason** [comment]
Sorry for the flood of comments, but: I'm fairly certain that this behavior is related to the `#{pairing}` statusline variable. When I remove that from my config, I see no problems using the latest commit of this repo and Termite.

**Comment by gpakosz** [comment]
Well here is my suggestion: launch `tmux show -gv status-left` and `tmux show -gv status-right`. 

The default configuration should give you:
```
$ tmux show -gv status-left
#[fg=#000000,bg=#ffff00,bold] ❐ #S #[fg=#ffff00,bg=#ff00af,none]#[fg=#e4e4e4,bg=#ff00af,none] ↑#{?@uptime_d, #{@uptime_d}d,}#{?@uptime_h, #{@uptime_h}h,}#{?@uptime_m, #{@uptime_m}m,} #[fg=#ff00af,bg=default,none]

$ tmux show -gv status-right
#(cut -c3- ~/.tmux.conf | sh -s _uptime)#(cut -c3- ~/.tmux.conf | sh -s _battery)#[fg=#080808,bg=default,none]#[fg=#8a8a8a,bg=#080808,none]#[fg=none]#[bg=none]#[none]#{?client_prefix,⌨,}#[fg=none]#[bg=none]#[none]#{?session_many_attached,👓,}#{?@battery_status, #{@battery_status},}#{?@battery_hbar, #{@battery_hbar},}#{?@battery_percentage, #{@battery_percentage},} #[fg=#8a8a8a,bg=#080808,none]| %R #[fg=#8a8a8a,bg=#080808,none]| %d %b #[fg=#d70000,bg=#080808,none]#[fg=#e4e4e4,bg=#d70000,none] #(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} false #D)#[fg=none]#[bg=none]#[bold,blink]#(cut -c3- ~/.tmux.conf | sh -s _root #{pane_tty} #D)#[default]#[fg=#e4e4e4,bg=#d70000,none] #[fg=#e4e4e4,bg=#d70000,none]#[fg=#000000,bg=#e4e4e4,bold] #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} false #D) 

```

Now you can try to remove parts and reinject them with `tmux set -g status-left` and `tmux set -g status-right`.

If you suspect `#{pairing}` is the culprit, then
```
$ tmux set -g status-left ''
$ tmux set -g status-right '#{?session_many_attached,👓,}'
```
should be enough to reproduce the problem. Maybe even `tmux set -g status-right '👓'` which would tell you that VTE has troubles with Unicode symbols / emojis.

**Comment by wbthomason** [comment]
The battery information also seems to be part of the problem. Removing that and `#{pairing}` from the statusline makes this work on both my laptop and desktop. On the desktop, removing the battery info is unnecessary, since it doesn't print anything. I'll try the MWE you suggest later this evening.

**Comment by gpakosz** [comment]
Well that's exactly the same problem right?

```
tmux_conf_battery_status_charging='⚡'     # U+26A1
tmux_conf_battery_status_discharging='🔋'  # U+1F50B
```

I suggest you skim through your `~/.tmux.conf.local` copy and choose symbols that are not emojis.

**Comment by gpakosz** [comment]
If not a VTE issue, maybe upgrading to freetype 2.5+ would help, but really you're on your own there :)

**Comment by wbthomason** [comment]
So, I'm on freetype 2.6.3, and the emojis correctly render in vim/when I `cat` the `.tmux.conf.local` file in `termite`. This is why I didn't initially suspect that the symbols were causing this problem.

From the symptoms, I think the issue stems from redraws of the statusline. I'm not sure if this is handled by `tmux` or VTE, but I think it's not a problem with your config --- you just happen to trigger this bug in whatever actually has it.

Removing the symbols made this config usable again for me, but I'll try to allocate some time in the future to track down why it happens, looking through vte-ng.

**Comment by m3rcuriel** [comment]
Apparently also an issue on Terminator. Works perfectly when the status bar is moved to the top.

**Comment by gpakosz** [comment]
@wbthomason any news by chance?

**Comment by wbthomason** [comment]
Unfortunately not. I've started looking through vte-ng, but haven't had much time, and haven't found anything. Like I said in my previous comment, removing the emojis did fix the problem for me (@m3rcuriel even with the bar at the bottom). I'll try to find more time to keep looking.

**Comment by m3rcuriel** [comment]
So yeah this is an issue with wide characters, it would seem. Interesting that neovim actually had/has a similar bug.
