### ISSUE TITLE
username/root and hostname not changing on Ubuntu 18.04 with zsh

### ISSUE THREAD

**Issue by Halfwalker** [gpakosz/.tmux#320]
Testing your config - awesome work.  In a stock 18.04 virtualbox VM with zsh/zprezto installed, it works fine.  Except ... username doesn't switch to "root" and hostname doesn't change when ssh'ing to other systems.
Stock ssh, not mosh.

**Comment by gpakosz** [comment]
Hello @Halfwalker 👋

Works for me on Ubuntu 18.04 WSL.

- Does it work without `zsh/zprezto`?
- Is `ssh` aliased or shell function?

To troubleshoot the issue, can you please 
1. open a first tmux pane
2. type `$ tmux display -p '#{pane_tty}'` ← this will give you a result
3. ssh into a server
4. split pane
5. from the second pane, type `$ cut -c3- ~/.tmux.conf | sh -s _tty_info <insert tty obtained from previous command>`

**Comment by Halfwalker** [comment]
Did a  bit more testing on the minbase test VM, looks like it's something in zprezto.  Created a new user using bash, tmux works as expected, modifying the username/root and hostname cleanly.  Nice :)

Changed shell to /bin/zsh using bare ubuntu-installed .zshrc, tmux works as expected there too.

When enabling zprezto it doesn't work, so something in there is messing with it.  Running your setup above gives this (ssh'ing into another system, running the cut cmd on minbase) :

` halfwalker@minbase    ~  cut -c3- ~/.tmux.conf | sh -s _tty_info /dev/pts/4                           ✔ 
6655 halfwalker /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=6530 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO
 halfwalker@minbase    ~  `

Bleah - copy/paste doesn't get some of the nice characters.  Thanks for the quick response.

**Comment by gpakosz** [comment]
What seems to happen is that the "childmost" process running in the TTY is `gitstatusd-linux-x86_64` from which there's no ssh user / hostname to extract.

I'm not sure how I can prevent that to happen.

Can you please do the same experiment but with
```
$ ps -t <insert tty value here> -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
```
instead of
```
$ cut -c3- ~/.tmux.conf | sh -s _tty_info <insert tty value here>
```
?

**Comment by gpakosz** [comment]
Also can you please give the `optimizations` branch a try, I may have fixed the bug in there already as part of a refactor I'm not sure

**Comment by Halfwalker** [comment]
OK, that looks different.  Since the cmdlines were so long I piped it into `most` and wrapped the lines, hence the backslashes

` XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                    
halfwalker                        369     1 /bin/zsh -dfxc          exec >&4         echo $$         /home/halfwalker/.zprezto/mod\
ules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=32677 --num-threads=2 --max-num-\
staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         if [\
[ $? != (0|10) && $? -le 128 && -f /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-\
x86_64-static ]]; then           /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x8\
6_64-static --lock-fd=3 --parent-pid=32677 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-nu\
m-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         fi         echo -nE $'bye\x1f0\x1e'                               
halfwalker                        371   369 /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatu\
sd-linux-x86_64 --lock-fd=3 --parent-pid=32677 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --ma\
x-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO                                                                       
halfwalker                       6822 32677 ssh deano@halfwalker.local                                                             
halfwalker                      32677 32384 -zsh `

I'll test out the optimizations branch - just regular `git checkout optimizations` ?

**Comment by Halfwalker** [comment]
No joy with optimizations branch - this is the result of that ps cmd
`
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                    
halfwalker                      16924 16740 -zsh                                                                                   
halfwalker                      16972     1 /bin/zsh -dfxc          exec >&4         echo $$         /home/halfwalker/.zprezto/mod\
ules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=16924 --num-threads=2 --max-num-\
staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         if [\
[ $? != (0|10) && $? -le 128 && -f /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-\
x86_64-static ]]; then           /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x8\
6_64-static --lock-fd=3 --parent-pid=16924 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-nu\
m-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         fi         echo -nE $'bye\x1f0\x1e'                               
halfwalker                      16974 16972 /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatu\
sd-linux-x86_64 --lock-fd=3 --parent-pid=16924 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --ma\
x-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO                                                                       
halfwalker                      17586 16924 ssh xxxxx@halfwalker.local 
`

**Comment by gpakosz** [comment]
Can you please not wrap the lines?

Either branch is fine

**Comment by Halfwalker** [comment]
The lines are so long they go off the edge of the screen.  Unless I grab them in `most` and wrap them, you would miss the rest.  Let me try a tiny terminal screen and wide.

**Comment by Halfwalker** [comment]
Hah, that got it.  Can't read it on screen, but it wasn't wrapped :P  This is with optimizations branch.
`
 halfwalker@minbase    ~  ps -t /dev/pts/2 -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                             ✔ 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
halfwalker                      19658 19474 -zsh
halfwalker                      19725     1 /bin/zsh -dfxc          exec >&4         echo $$         /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=19658 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         if [[ $? != (0|10) && $? -le 128 && -f /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static ]]; then           /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static --lock-fd=3 --parent-pid=19658 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO         fi         echo -nE $'bye\x1f0\x1e'
halfwalker                      19727 19725 /home/halfwalker/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=19658 --num-threads=2 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=INFO                                                                                                                                                                                                
halfwalker                      19895 19658 ssh xxxxx@halfwalker.local
 halfwalker@minbase    ~      
`

**Comment by gpakosz** [comment]
Can you please use triple backticks to create a markdown code block?
```
like this
```

Because when I try to copy paste what you gave me into an editor now it's just a single line. While `ps`' output is multiline

**Comment by gpakosz** [comment]
Or redirect to a file and attach it?

**Comment by gpakosz** [comment]
@Halfwalker can you please give the `gh-320` branch a shoot?

**Comment by Halfwalker** [comment]
Bingo - that seems to fix it :)  What was the issue ?

Feature request ...  Make the username section another (selectable) color, and switch it to red when one becomes root.
Feature request ...  Have a table of hostnames with colors associated with them.  Use the appropriate hostname color when ssh'd into it.  Same for usernames.

**Comment by gpakosz** [comment]
> What was the issue ?

The `_tty_info()` helper uses `ps` to inspect what's running in a particular pane, using the target tty to filter out the list of processes. Then it gives this output to `awk` which detects which is the currently active process in that pane. The `awk` script failed to filter out daemon process,  == every process which ultimately descends from pid `1`.

> Feature request ...

Not sure how to do that nor to expose it as configuration variables. In any case please open another issue
