### ISSUE TITLE
issue when changing panes with iTerm2 on MacOS

### ISSUE THREAD

**Issue by thomasd3** [gpakosz/.tmux#325]
When I change the panes, sometimes the cursor is not active.

I remapped the hotkey to 'w', so for example I do c-W, right arrow and then sometimes, I can't type anything in the new pane's shell, but when I press return, I can use it normally.

how can I troubleshoot this?

**Comment by gpakosz** [comment]
Hello @thomasd3 👋

The first thing you should try is: does it happen with stock tmux?

To test it
```
$ tmux -f /dev/null -L test
```

**Comment by thomasd3** [comment]
It doesn't. I recently switched to this config, from the stock tmux (only config change I had was to remap c-B to c-W), and the problem appeared at that moment.

**Comment by gpakosz** [comment]
This configuration doesn't alter tmux in any profound way.

All in all, it just sets bindings, colors and settings like `status-left` and `status-right`.

I suggest you ask tmux folks.
