### ISSUE TITLE
issue with the mouse with iTerm2 on MacOS

### ISSUE THREAD

**Issue by thomasd3** [gpakosz/.tmux#326]
Today I have a new issue:
I have one pane that rings the bell anytime the mouse is moved, or trackpad used.

But the other pane is fine.. did I accidentally change a state in that pane?

**Comment by gpakosz** [comment]
Hey @thomasd3 👋

This really sounds like tmux support, which I'm usually not shy to address. But I have no idea about the link between mouse and bell 🤷‍♂️

**Comment by thomasd3** [comment]
from what I have found, all the mouse moves get sent to the console and, some of the values trigger the bell. I had one case where all the moves were printed in the console.

**Comment by gpakosz** [comment]
This configuration doesn't alter tmux in any profound way.

All in all, it just sets bindings, colors and settings like status-left and status-right.

Please look for tmux support or iTerm2 support.

**Comment by skyjia** [comment]
![image](https://user-images.githubusercontent.com/964311/89731966-e2db2000-da7d-11ea-9ec6-b234cfdb64a2.png)

Check the options as shown above. Hope it works. @thomasd3

**Comment by thomasd3** [comment]
I have exactly the same options.
