### ISSUE TITLE
CPU Usage is high and too slow at launching new server

### ISSUE THREAD

**Issue by marantz** [gpakosz/.tmux#327]
I am always thankful that I am using Tmux.

But CPU Usage is high and too slow at launching new server on my Mac Book Pro.
It take over 40 sec at new launch server and CPU Usage is over 80~90%.
The funny thing is that it's not happen on my another Mac Book Pro or Mac Book.

When I remove your .tmux.conf and .tmux.local, It's not happen

```console
tmux -f /dev/null -L test
``` 

I found that there are over 30 child process (or thread) when launching new tmux server.

```console
$ ps -ef | grep tmux
  501 93610     1   0 12:40AM ??         0:00.03 tmux new -s works
  501 93611 93610   0 12:40AM ??         0:09.09 tmux new -s works
  501 93612 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93613 93610   0 12:40AM ??         0:09.07 tmux new -s works
  501 93614 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93615 93610   0 12:40AM ??         0:09.02 tmux new -s works
  501 93616 93610   0 12:40AM ??         0:09.13 tmux new -s works
  501 93617 93610   0 12:40AM ??         0:09.07 tmux new -s works
  501 93618 93610   0 12:40AM ??         0:08.96 tmux new -s works
  501 93619 93610   0 12:40AM ??         0:08.99 tmux new -s works
  501 93620 93610   0 12:40AM ??         0:08.99 tmux new -s works
  501 93621 93610   0 12:40AM ??         0:09.08 tmux new -s works
  501 93622 93610   0 12:40AM ??         0:09.00 tmux new -s works
  501 93623 93610   0 12:40AM ??         0:09.02 tmux new -s works
  501 93624 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93625 93610   0 12:40AM ??         0:08.99 tmux new -s works
  501 93626 93610   0 12:40AM ??         0:08.96 tmux new -s works
  501 93627 93610   0 12:40AM ??         0:09.00 tmux new -s works
  501 93628 93610   0 12:40AM ??         0:09.07 tmux new -s works
  501 93629 93610   0 12:40AM ??         0:09.02 tmux new -s works
  501 93630 93610   0 12:40AM ??         0:09.06 tmux new -s works
  501 93631 93610   0 12:40AM ??         0:09.06 tmux new -s works
  501 93632 93610   0 12:40AM ??         0:09.05 tmux new -s works
  501 93633 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93634 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93635 93610   0 12:40AM ??         0:09.06 tmux new -s works
  501 93636 93610   0 12:40AM ??         0:09.12 tmux new -s works
  501 93637 93610   0 12:40AM ??         0:09.04 tmux new -s works
  501 93638 93610   0 12:40AM ??         0:09.03 tmux new -s works
  501 93639 93610   0 12:40AM ??         0:09.05 tmux new -s works
  501 93640 93610   0 12:40AM ??         0:09.03 tmux new -s works
```

**Comment by gpakosz** [comment]
Hello @marantz 

40s is indeed way too long.

`tmux new -s works` is definitely something you changed 🤔
- Can you make sure you didn't modify `.tmux.conf` and can you please temporarily get rid of your `~/.tmux.conf.local` copy?
- Can you double check your shell profile files? Are you using `zsh`?

**Comment by gpakosz** [comment]
Hello @marantz 👋

Any news?

**Comment by marantz** [comment]
Yes, I'm using zsh and It's same even if remove .tmux.conf.local.
and i'm always use your lastests .tmux.conf as well.

**Comment by marantz** [comment]
I found with excuting with`tmux -v`.

## Start Bind Key
1584959951.201136 cmd_parse_build_commands: bind-key -N "Send the prefix key" C-b send-prefix
1584959951.201151 cmdq_get_command: [bind-key/0x7f80134020c0] group 2
...
## Repeat group 
1584959951.347748 cmdq_get_command: [bind-key/0x7f80137290d0] group 728
1584959951.347752 cmdq_append <global>: queue [bind-key/0x7f80134020c0] (2)
...
## Repeat cmdq_append 
1584959951.348734 cmdq_append <global>: queue [bind-key/0x7f8013728cb0] (725)
1584959951.348737 cmdq_append <global>: [bind-key/0x7f80137290d0]
1584959951.348951 add peer 0x103003000: 8 (0x7f8014804c00)

I'll check bind key options.

**Comment by marantz** [comment]
Issue is resolved.

I had fixed my own `ulimits -n` and `ulimits -u` option for testing.

```console
> ulimit -n
256 (52484)
> ulimit -u
1392 (4096)
```

default ulimit setting is working well.
sorry about my miss.

**Comment by bezerker** [comment]
@marantz This has started occurring for me as well now. I'm not sure why or how as it's only recently started and I have not made any ulimit adjustments.... How did you come to the determination this was a ulimit thing?
