### ISSUE TITLE
Status bar falls into two lines after upgrading to Catalina

### ISSUE THREAD

**Issue by jaywhy13** [gpakosz/.tmux#329]
Hi,

After upgrading to Catalina, my status bar falls into the second line. I'm not sure why this happens. If I use Tmux on a fullscreen it works fine, but most terminals that are smaller than the full width of my screen causes the line to wrap. 

As seen from the screenshot, the white bar which shows the hostname falls into the second line.

![image](https://user-images.githubusercontent.com/779782/76433297-85398f00-638a-11ea-8bb3-c36a929f5513.png)

**Comment by gpakosz** [comment]
Hello @jaywhy13 👋

This is likely caused by the emoji(s) you're using on your status line.

**Comment by jaywhy13** [comment]
Interesting. I also noticed that if the text beside the emoji is a few letters shorter I don't run into the problem. Also, this only happens when I'm running Tmux in my terminal inside VS Code. It works fine in iTerm at any size.

**Comment by gpakosz** [comment]
There's pretty much nothing I can do. All this configuration does is easing configuring bindings and setting `status-left` and `status-right`

**Comment by jaywhy13** [comment]
Sorry, I was just hoping you could point me in the right direction. Outside of removing the emojis, which I'm hoping to save for last resort. I have very little understanding of how terminals work and why it would work in one setting (iTerm) and not another (inside VS Code). Is this something VS Code would need to fix, or it's something I need to do on my Mac?

**Comment by jaywhy13** [comment]
For anyone else landing on this issue. The problem isn't with **ALL** emojis. It's just the emojis that have more than one code point. An emoji like 🤵 is actually fine, but most of the emojis that have a different shade apparently use another code point to represent the shade. The darker version of the same emoji for instance (🤵🏽‍♂️) uses two code points. Github represents it as the female symbol.

**Comment by gpakosz** [comment]
Does VSCode have a setting to select the Unicode widths spec to use? Like iTerm2 does?

![](https://user-images.githubusercontent.com/553208/41241269-c5843f32-6d9c-11e8-85b9-664ca9abced3.jpg)
