### ISSUE TITLE
How to rollback?

### ISSUE THREAD

**Issue by netikras** [gpakosz/.tmux#33]
Hello,

How do I go back from your config to one of mine? I've removed ~/.tmux.conf* and restored my original config. Reloaded w/ C-a+r but I still see stausbar items in there (although key mapping is now restored).

**Comment by gpakosz** [comment]
Hello,

First make sure you reverse the installation steps:
```
$ cd
$ rm .tmux.conf*
$ rm -rf .tmux
```
You shouldn't have the `~./tmux.conf -> ~/.tmux/.tmux.conf` symlink anymore.

Then make sure you exit tmux until ever tmux process is gone, including the tmux server process.

Then restore your own `~/.tmux.conf` and restart tmux?

**Comment by netikras** [comment]
yeah.. I wonder why I have to restart tmux, i.e. why can't it reload the new configuration on the fly :/

Thanks anyway.

**Comment by gpakosz** [comment]
You should have been able to do it without restarting tmux indeed.
