### ISSUE TITLE
Unable to switch windows

### ISSUE THREAD

**Issue by atgmello** [gpakosz/.tmux#335]
Hi @gpakosz. First off, thank you very much for this amazing conf! I've just came across it today.

My issue is, I simply cannot switch windows when using it. Everything else works as expected, such as `<prefix> Tab` and even switching panes. However `<prefix> n` or `<prefix> p` simply gives me nothing. Unlinking the conf file brings me back to plain tmux and I have no problem creating and switching to next/previous windows at all.

I'm boggled. Any help is appreciated!

**Comment by atgmello** [comment]
> `<prefix> C-h` and `<prefix> C-l` let you navigate windows (default `<prefix> n` and `<prefix> p` are unbound)

Yet another case of not being thorough on the RTFM principle. I'll just leave this here.

**Comment by milani** [comment]
I struggle with this choice. Why the default bindings are unbounded?
