### ISSUE TITLE
Windows title and index are too close

### ISSUE THREAD

**Issue by willzhqiang** [gpakosz/.tmux#337]
I didn't know what I have done ,now the title seems too close to the next number, 
![image](https://user-images.githubusercontent.com/279170/78140100-0cdf5e80-745c-11ea-8167-1e0a2701f824.png)
but before that I remember it should look that, 
![image](https://user-images.githubusercontent.com/279170/78140025-f76a3480-745b-11ea-9c33-de507222b7ad.png)
Does anyone know what configuration controls this layout?

**Comment by gpakosz** [comment]
Hello @willzhqiang 👋

You likely played with `window-status-separator`. Set it back to space with
```
$ tmux set -g window-status-separator " "
```

**Comment by willzhqiang** [comment]
> Hello @willzhqiang 👋
> 
> You likely played with `window-status-separator`. Set it back to space with
> 
> ```
> $ tmux set -g window-status-separator " "
> ```

Yes, you are right, fixed it, thanks!
