### ISSUE TITLE
Trim `${pane_current_path}` if it's too long

### ISSUE THREAD

**Issue by serpro69** [gpakosz/.tmux#338]
Is it possible to trim the value of `#{pane_current_path}` if it becomes longer than a certain number of characters? Sometimes it overlaps over other panes if `pwd` path is too long.

Thanks for a great tmux config btw!

**Comment by gpakosz** [comment]
Hello @serpro69 👋

See `tmux`'s manual, the `FORMATS` section:
> A limit may be placed on the length of the resultant string by prefixing it by an `=`, a number and a colon. Positive numbers count from the start of the string and negative from the end, so `#{=5:pane_title}` will include at most the first five characters of the pane title, or `#{=-5:pane_title}` the last five characters.  A suffix or prefix may be given as a second argument - if provided then it is appended or prepended to the string if the length has been trimmed, for example `#{=/5/...:pane_title}` will append `...` if the pane title is more than five characters.

In other words, you can use e.g. `#{=/10/...:pane_current_path}` or `#{=/-10/...:pane_current_path}` depending on whether you want it prefixed or suffixed.

```
$ tmux display -p '#{pane_current_path}'
/Users/greedo
$ tmux display -p '#{=/10/...:pane_current_path}'
/Users/gre...
$ tmux display -p '#{=/-10/...:pane_current_path}'
...ers/greedo
```

**Comment by serpro69** [comment]
Thanks a lot @gpakosz !
