### ISSUE TITLE
Thank you & Requests for Improvements

### ISSUE THREAD

**Issue by mdigga39** [gpakosz/.tmux#341]
Hey All,

First, I want to thank you for the work so far! Great job! 

I had a couple of requests for things I would love to see added, edited or improved. Let me know if you would like separate issues for these. 

- Change the value for splitting panes vertically to `|` 
  - I have done this in my `.tmux.conf` myself, but I believe it is a simple edit from `_` and makes more sense

- Add the day to the right status line (i.e. Fri 17 April)
   - Made an edit in `./tmux.conf.local` to support this with `%a`

**Comment by gpakosz** [comment]
Hello @mdigga39 👋

To customize bindings to your preferences, redefine them at the end of your `~/.tmux.conf.local` copy.

Please do not change `~/.tmux.conf` otherwise you'll have to resolve merge conflict when updating this configuration to latest `master`.

**Comment by mdigga39** [comment]
Understood and will convert back to original. Thanks!
