### ISSUE TITLE
Prefix + r does not source .tmux.conf.local file

### ISSUE THREAD

**Issue by mdigga39** [gpakosz/.tmux#342]
Hey All,

I am noticing the following behavior and not quite sure whats going on. Hope you can help. 

I edited my `.tmux.conf.local` file and added a CPU and RAM monitor.  When I go to close out of the editor, I see the new module flash in the right status bar then disappear before the sourced message appears. 

Running `tmux source .tmux.conf` results in the same behavior (flashes then disappears). 
Running `tmux source .tmux.conf.local`, however, keeps the plugin showing as expected across all windows. The only issue is any new tmux sessions. 

![source file](https://user-images.githubusercontent.com/23265369/79612560-f1668b80-80ca-11ea-8f4e-8016cab73d74.gif)

Any and all help is appreciated! 

V/R - 
JDIG

**Comment by gpakosz** [comment]
Hello @mdigga39 👋

I don't know how you modified this configuration but you're not supposed to `tmux source ~/.tmux.conf.local`. It's not how it works.

**Comment by mdigga39** [comment]
Hey @gpakosz 👋🏼

Thanks for getting back so quickly! My local file is below. 

[mylocal.txt](https://github.com/gpakosz/.tmux/files/4504158/mylocal.txt)

I understand this is not the correct way to use this, however, I wanted to highlight the interesting difference. Running `tmux source ~/.tmux.conf.local` does seem to show this as I intended and did not seem to break anything as far as I'm aware. 

V/R - 
JDIG

**Comment by ZachTheDev** [comment]
I am having this same issue. Using the .tmux.conf causes the variable to load and quickly disappear after the message saying it was reloaded disappears.
But when I set the source to .tmux.conf.local it loads the variables and keeps them.

**Comment by ZachTheDev** [comment]
@gpakosz Can I get some help on this?
It is very weird for it to load then immediately disappear.

[My .conf](https://pastebin.com/Patrq6w4)
[My .conf.local](https://pastebin.com/b2HrGTwM)
It only shows up when I loved .conf.local. And that isn't what you said to do.

**Comment by vacuumboots** [comment]
I have this issue as well. 
I have not modified tmux.conf.local. 

When I reload tmux.conf, variables assigned in tmux.conf.local briefly appear in my status bar, 
and then disappear after the message saying that my conf was reloaded.

**Comment by ZachTheDev** [comment]
@vacuumboots I just made a new issue (#410) for this since this one is marked as invalid, in hopes that the owner will review the new issue.
