### ISSUE TITLE
bashtop is all messed up

### ISSUE THREAD

**Issue by chovy** [gpakosz/.tmux#344]
Install bashtop: https://github.com/aristocratos/bashtop#installation

same for ytop (same debian pp)

Beautiful outsijde of tmux but inside tmux graphs look like garbage.

![ytop](https://user-images.githubusercontent.com/27381/80429655-73ac3800-88a1-11ea-8de3-d81a3c009aa5.png)
![ytop-tmux](https://user-images.githubusercontent.com/27381/80429657-7444ce80-88a1-11ea-9104-9532415056e4.png)
![tmux](https://user-images.githubusercontent.com/27381/80429658-74dd6500-88a1-11ea-9e5d-dbdd4887ae14.png)
![bash](https://user-images.githubusercontent.com/27381/80429659-74dd6500-88a1-11ea-89c4-c6e50cf411be.png)

This seems to be a problem only on my server. with tmux + bashtop/ytop locally on my ubuntu 18.04 it works fine. but not over ssh terminal. I'm using hyper terminal.

**Comment by gpakosz** [comment]
Hello @chovy 👋

I'm sorry this is outside the scope of my configuration.

Make sure your `TERM` environment variable is properly set to `xterm-256color` outside of tmux and `screen-256color` inside.
