### ISSUE TITLE
Not able to use tmux plugin syntax #{network_bandwidth}

### ISSUE THREAD

**Issue by CodeBreaker444** [gpakosz/.tmux#345]
Right Status line is not accepting default tmux syntax for loading this plugin : https://github.com/xamut/tmux-network-bandwidth

**Comment by souhaiebtar** [comment]
@CodeBreaker444 

install tpm
by just 
`git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm`
than add 
`run -b '~/.tmux/plugins/tpm/tpm'`
in the line 172 (empty line) in the `~/.tmux/.tmux.conf` (the line is 172 in version with the commit hash `d6f0f647dd68561ed010f83d8d226383aebfb805`)

than open `.tmux.conf.local` file and add in the end, i added:

```
set -g @tpm_plugins '          \
   xamut/tmux-network-bandwidth \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tpm             \
 '
```

also in the same file `.tmux.conf.local`, edit the line that start with 
`tmux_conf_theme_status_right=` by adding `#{network_bandwidth}`
this is my line 

```
tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{network_bandwidth} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname}'
```

after that  run tmux by using `tmux`
than install tpm plugin using `ctrl+b` (prefix for tmux) than `I` (capital i),

if it didn't work in the first time (like it did for me), make sure to close `tmux`
and relaunch it using `tmux -vv` for outping log, than close tmux again
and launch it normally without any option, just `tmux`

thanks goes to @taybin @kleinjm @Glitches 
references: [1][1]  [2][3] [3][4]

[1]: https://github.com/gpakosz/.tmux/issues/228
[3]: https://github.com/gpakosz/.tmux/issues/276
[4]: https://github.com/gpakosz/.tmux/issues/206

**Comment by CodeBreaker444** [comment]
> @CodeBreaker444
> 
> install tpm
> by just
> `git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm`
> than add
> `run -b '~/.tmux/plugins/tpm/tpm'`
> in the line 172 (empty line) in the `~/.tmux/.tmux.conf` (the line is 172 in version with the commit hash `d6f0f647dd68561ed010f83d8d226383aebfb805`, it may change in the future)
> 
> than open `.tmux.conf.local` file and add in the end, i added:
> 
> ```
> set -g @tpm_plugins '          \
>    xamut/tmux-network-bandwidth \
>    tmux-plugins/tmux-sensible   \
>    tmux-plugins/tpm             \
>  '
> ```
> 
> also in the same file `.tmux.conf.local`, edit the line that start with
> `tmux_conf_theme_status_right=` by adding `#{network_bandwidth}`
> this is my line
> 
> ```
> tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{network_bandwidth} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname}'
> ```
> 
> after that run tmux by using `tmux`
> than install tpm plugin using `ctrl+b` (prefix for tmux) than `I` (capital i),
> 
> if it didn't work in the first time (like it did for me), make sure to close `tmux`
> and relaunch it using `tmux -vv` for outping log, than close tmux again
> and launch it normally without any option, just `tmux`
> 
> ![image](https://user-images.githubusercontent.com/15350774/80928484-a623cc80-8d9c-11ea-8760-b41862954989.png)
> 
> thanks goes to @taybin @kleinjm @Glitches and especially to @gpakosz and the folks of [**tpm**](https://github.com/tmux-plugins/tpm)
> references: [1](https://github.com/gpakosz/.tmux/issues/228) [2](https://github.com/gpakosz/.tmux/issues/276) [3](https://github.com/gpakosz/.tmux/issues/206)

Great! it's working. The Readme told not to edit the .tmux.conf and instead edit .tmux.conf.local which is misleading if we want to use a plugin. I hope, this issue will get fixed in the future. Thank you so much.

**Comment by souhaiebtar** [comment]
@CodeBreaker444 first it's not misleading because modifying the `.tmux.conf.local` is more than sufficient for every case this project was developed for, the use case that you tried to add was not intended from the start, this project (as i understand it) give you an enable/disable config for tmux with very cool features that are already to use (only need to enable them), your request is about adding a feature, also this is not a bug or an issue in anyway, for sure integrating other plugins can be easier but this is again not what this project was meant to be from the start, thanks again to @gpakosz for this great project
