### ISSUE TITLE
How can I show a pane variable in the status bar?

### ISSUE THREAD

**Issue by arturog** [gpakosz/.tmux#346]
Hello, first of all, fantastic work!  I use your .tmux.conf on all my hosts and it's simply awesome.  

Question: how can I show the output of `docker-machine active` for the *current pane* on the status bar, next to the hostname?  Or, alternatively, the variable `$DOCKER_MACHINE_NAME`?

Thanks!

**Comment by samwise-uber** [comment]
+1 to this - I'd like to show the current git branch for the current pane in the status bar.

**Comment by gpakosz** [comment]
Hello @arturog 👋

There's no general way to achieve what you want.
