### ISSUE TITLE
window status not expected when status bg set to "default"

### ISSUE THREAD

**Issue by Core00077** [gpakosz/.tmux#347]
Thank you so much for your configuration, which looks really nice and tide, and have so much features.

As I was modifing my tmux config, I noticed that when bg is set to default, it'll be transparent like this.(Works on Konsole and Yakuake)
![image](https://user-images.githubusercontent.com/28624864/81042221-391a4f00-8ee2-11ea-987f-d11fbdecd615.png)

However, when `tmux_conf_theme_status_bg='default'`, the window status as well as current window status looks a little awkward. 

I have set `tmux_conf_theme_window_status_current_bg` and `tmux_conf_theme_window_status_bg` to 'default' to make it look not so weird. (It's still a little bit weird though)

![image](https://user-images.githubusercontent.com/28624864/81043963-e478d300-8ee5-11ea-991b-18a09edbdc30.png)

When I tried to set `tmux_conf_theme_window_status_current_bg` to cyan, this background covers the separator on the right.

![image](https://user-images.githubusercontent.com/28624864/81045928-d62cb600-8ee9-11ea-8470-63818d1333a3.png)

I was expecting each `window status` to have a separator on the right, and its color should match with their background color. Like this picture (except for the direction went wrong). The current window has a cyan background with black foreground, all the other windows' bg remain black with white fg.
![image](https://user-images.githubusercontent.com/28624864/81043366-b050e280-8ee4-11ea-8319-2fc3929ab74c.png)

**Comment by gpakosz** [comment]
Hello @Core00077 👋

Can you please try the `gh-347` branch?

**Comment by Core00077** [comment]
Sure, I'll look into it.

**Comment by Core00077** [comment]
No luck, the problem remains the same after I reload my config and killed tmux-server.  y

![image](https://user-images.githubusercontent.com/28624864/81138655-59571600-8f95-11ea-8584-cc47fcf0a3d8.png)

Here's some of my config in `.local` file.

```
tmux_conf_theme_window_status_fg='#8cd0d3'             
tmux_conf_theme_window_status_bg='#000000'            
tmux_conf_theme_window_status_attr='none'

...

tmux_conf_theme_window_status_current_fg='#000000'      
tmux_conf_theme_window_status_current_bg='#8cd0d3'     
tmux_conf_theme_window_status_current_attr='none'
```

**Comment by gpakosz** [comment]
I pushed more fixes to the `gh-347` branch. But I'm not sure I'm trying to achieve what you're trying to achieve.

If it still doesn't do what you expect, please compare what ou configure in your `~/.tmux.conf.local` and the output of
```
$ tmux show -gw window-status-style
```
```
$ tmux show -gwv window-status-format
```
```
$ tmux show -gwv window-status-current-style
```
```
$ tmux show -gwv window-status-current-format
```
```
tmux show -gv status-style
```

**Comment by gpakosz** [comment]
Here's what I have now when setting `tmux_conf_theme_status_bg='colour1'`

![image](https://user-images.githubusercontent.com/553208/81156651-7506f000-8f86-11ea-938e-e6860fbacfc1.png)

**Comment by Core00077** [comment]
Weird thing happens. When setting `status_bg=colour1`, it works as a charm.
![image](https://user-images.githubusercontent.com/28624864/81157989-1f4c3b00-8fba-11ea-9338-38144e73a547.png)

However, when I change it to `default`, it goes back to the old way. Seems like the color of window's separators is determined by `status_bg`.

![image](https://user-images.githubusercontent.com/28624864/81158441-8ec22a80-8fba-11ea-932d-bef8f715d9ee.png)

**Comment by gpakosz** [comment]
> Seems like the color of window's separators is determined by `status_bg`.

Well yes and I believe it's what makes sense?
You want the `fg` of the separator to be the `bg` of what's before, and what's before is not governed by `windows-status-style` but by `status-style`.

**Comment by gpakosz** [comment]
Let me debug more. I can now reproduce the problem when I set `tmux_conf_theme_status_bg='default'`

**Comment by gpakosz** [comment]
`default` is tricky, I think you should `tmux_conf_theme_status_bg=terminal`

**Comment by gpakosz** [comment]
I pushed some more fix, can you please try again with `tmux_conf_theme_status_bg=terminal`?

**Comment by Core00077** [comment]
Hey! Thanks a lot! The keyword `terminal` got this. It's almost the same as I expected. 
The thing is, the is a black span before `current window status`, which is unrelated to the color of `window_status_current_fg`.
![image](https://user-images.githubusercontent.com/28624864/81176013-1453d380-8fd7-11ea-9ee0-2df89b06387f.png)
I also tried with other colors like white, as well as setting `status_left_bg=white`, it still remains black.
![image](https://user-images.githubusercontent.com/28624864/81176612-f5097600-8fd7-11ea-8a66-42a5c3d0704d.png)

**Comment by gpakosz** [comment]
Even with the latest commit? commit `0704964a030ef17a5a34f6607811498b76d9b760`? (you need to reload the conf)

**Comment by Core00077** [comment]
I'm pretty sure I reload the conf with the latest commit. Not sure what went wrong.
![image](https://user-images.githubusercontent.com/28624864/81180196-41a38000-8fdd-11ea-8c11-cefd5527f013.png)

**Comment by gpakosz** [comment]
What's the output of
```
tmux show -gwv window-status-current-format
```
and
```
tmux show -g gwv window-status-current-style
```

**Comment by gpakosz** [comment]
Never mind. I managed to enable transparency in iTerm2 on macOS and it seems I'm facing what you're facing. Will investigate more

**Comment by Core00077** [comment]
![image](https://user-images.githubusercontent.com/28624864/81181129-909de500-8fde-11ea-989b-9da663ec9cef.png)

**Comment by Core00077** [comment]
ok

**Comment by gpakosz** [comment]
It seems `#[reverse]` doesn't play well with transparency

**Comment by gpakosz** [comment]
Not sure I can do anything about it

**Comment by Core00077** [comment]
Well, thank you anyway! I'll try something else. If anything works, I'll post it here.
