### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by friederbluemle** [gpakosz/.tmux#348]
Thank you for the nice tmux configuration!

It's rather unusual to have a _repository_ name start with a dot, i.e. hiding it from a regular `ls` by default. Is it possible to rename it? For example to `tmux-config`?

**Comment by gpakosz** [comment]
Hello @friederbluemle 👋

Well I like it it's hidden by default when I use it. But you can name if the way you want when cloning anyways:
```
$ git https://github.com/gpakosz/.tmux.git tmux-config
```
