### ISSUE TITLE
gpakosz Tmux theme is not running

### ISSUE THREAD

**Issue by gsbuosi** [gpakosz/.tmux#350]
Hello Gregory,

I used to used your Tmux theme in my Parrot OS sometime ago but, since I reinstall my system to LMDE 4 and installed your Tmux theme is not working, I'm doing exactly what is described in the GitHub repository for the installation process:

$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .

But when execute tmux command in my Linux Terminal, this what I got:
![image](https://user-images.githubusercontent.com/65083456/81479500-0631cd00-91fa-11ea-9324-621531ec20c8.png)

So, what I can do to run your theme in my system?

Best regards.-

**Comment by gpakosz** [comment]
Hello @gsbuosi 👋

What's the version of tmux?

**Comment by gpakosz** [comment]
Also, once inside tmux, can you please run

```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
```

and paste the (long) output here?

**Comment by gsbuosi** [comment]
Hi Gregory,

gsbuosi@samsung:~$ tmux -V
tmux 2.8

And attached the command output.

gsbuosi@samsung:~$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
cut: /home/gsbuosi/.tmux.conf: No such file or directory
gsbuosi@samsung:~$

Regards.-

Saludos.-

Ing. Gabriel Buosi
gsbuosi@gmail.com
https://www.linkedin.com/in/gsbuosi <https://www.linkedin.com/in/>
https://keyserver.mattrude.com/search/vindex/fingerprint/0x877E01A55EB4E459
Public Key Server -- Get "0x877e01a55eb4e459 "

**Comment by gpakosz** [comment]
```
/home/gsbuosi/.tmux.conf: No such file or directory
```
It seems for a reason or another that
- either you didn't clone the repository in your home folder
- either you creating the `~/.tmux.conf` symlink failed

**Comment by gsbuosi** [comment]
Hi Gregory,

I don't read your comment before, but my solution was similar.

I delete from my pakage system Tmux and ~/.tmux.conf also.

Install everything from the beginning cloning the repository in my home folder and voala, everything start working as expected.

So, I'm closing this issue.

Regards.-
