### ISSUE TITLE
How to get window current status sub-seperators

### ISSUE THREAD

**Issue by dotpyfe** [gpakosz/.tmux#352]
In one of the screenshots on the readme there are black separators between the window number and title

<img width="475" alt="Screen Shot 2020-05-14 at 9 21 04 AM" src="https://user-images.githubusercontent.com/772864/81953067-75297000-95c4-11ea-9df1-4ed603c19668.png">

i was wondering how this could be set in the .tmux.conf.local ?

**Comment by gpakosz** [comment]
Hello @dotpyfe 👋

This is an old screenshot and inserting these separators is no more automatic.
But you can still achieve the result by editing your `~/.tmux.conf.local` copy:
```
tmux_conf_theme_window_status_format='#I \uE0B1 #W'
tmux_conf_theme_window_status_current_format='#I \uE0B1 #W'
```

**Comment by dotpyfe** [comment]
got it - works great! thanks!
