### ISSUE TITLE
tmux vim show display not correctly or not show changed code instantly 

### ISSUE THREAD

**Issue by snsnsjsn** [gpakosz/.tmux#354]
hi ,i found that when i edit code , and the edited code not show instantly
just like here
![image](https://user-images.githubusercontent.com/11435527/82139242-0f094b00-9859-11ea-89b0-47954efc7c96.png)
![image](https://user-images.githubusercontent.com/11435527/82139267-33fdbe00-9859-11ea-9f5a-09547c8e9b86.png)

i need quit and open again to get the right code display , it is very strange !

anybody have found like the bug?

here is picture when i quit and open the file again
![image](https://user-images.githubusercontent.com/11435527/82139332-948cfb00-9859-11ea-9946-3d5f33a4b88e.png)

**Comment by gpakosz** [comment]
Hello @snsnsjsn,

Chances are very high this problem is unrelated to my tmux configuration.
Can you reproduce the problem when launching tmux with its default configuration?

```
$ tmux -L test -f /dev/null
```

**Comment by snsnsjsn** [comment]
hi, thanks for your help , i test 
`$ tmux -L test -f /dev/null`
and it is ok ,
so i will check my tmux configuration.
if find the unrelated setting i will paste here

**Comment by snsnsjsn** [comment]
i find that when edit code it will delay some times liek 5 second to dislpay correct ?

![image](https://user-images.githubusercontent.com/11435527/88246992-cc3b7780-ccce-11ea-859e-18ba245dc8d1.png)

**Comment by gpakosz** [comment]
Hello @snsnsjsn 👋

The only thing related to display in my configuration is `tmux_conf_theme_24b_colour`. What's the value in your `~/.tmux.conf.local` copy?

**Comment by snsnsjsn** [comment]
> Hello @snsnsjsn 👋
> 
> The only thing related to display in my configuration is `tmux_conf_theme_24b_colour`. What's the value in your `~/.tmux.conf.local` copy?

hello 
45 tmux_conf_theme_24b_colour=false

**Comment by gpakosz** [comment]
Hey @snsnsjsn 👋

Make sure you check the value of `TERM`. It should be `xterm-256color` outside tmux and `screen-256color` inside tmux.
