### ISSUE TITLE
client prefix in status right causing line wrap

### ISSUE THREAD

**Issue by 58bits** [gpakosz/.tmux#355]
I have a hunch this is a problem with the new Windows Terminal application (Windows Terminal latest and WSL 2), but thought I'd post here initially to see if there might be an easy fix. 

Until recently, the `#{?client_prefix,$tmux_conf_theme_prefix,}` setting in status_right was working fine - showing the little keyboard symbol when the tmux prefix key was pressed.

However, what's happening now is that status_right is being pushed to the right by a single character, causing the entire status line to wrap, and tmux to shift up a line. 

Attached are screen shots showing before and after pressing the prefix key.

<img width="667" alt="status-line-before" src="https://user-images.githubusercontent.com/405612/82163202-cc388900-98d3-11ea-99ff-776d3c832b64.png">

<img width="667" alt="status-line-after" src="https://user-images.githubusercontent.com/405612/82163207-d5295a80-98d3-11ea-855a-a76f7ded7d1c.png">

Thoughts or suggestions greatly appreciated (and thanks for the wonderful tmux settings).

**Comment by minaz912** [comment]
Adding more info here: this seemingly started happening with the v0.11.13333.0 Windows Terminal Update https://github.com/microsoft/terminal/releases/tag/v0.11.1333.0

I did not personally have time to look into why, but as a workaround you could set:
`tmux_conf_theme_prefix=' '` or another symbol, which fixes it for me.

**Comment by 58bits** [comment]
Apparently fix here - https://github.com/microsoft/terminal/pull/5934 so closing here.
