### ISSUE TITLE
Provide details on how string interpolation / templating works in tmux.conf.local

### ISSUE THREAD

**Issue by mboratko** [gpakosz/.tmux#356]
Thanks for making this, and my apologies if this is already explained elsewhere, but after ~ an hour of searching I was still unable to determine if the string templating language used in `tmux.conf.local` is something native to tmux or something unique defined by this package.

Either way, would you be able to point me toward some documentation explaining how it works?

Specifically, I was trying to set up part of the status bar so that:
- If the computer has a battery, display the battery status.
- If not, display the uptime.

Here was what I attempted:
```
uptime_string='#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m ,}'
battery_string='#{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},}'
tmux_conf_theme_status_left=' #S | '
tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{?battery_bar, #{battery_string}, #{uptime_string}} , %R | #{username}#{root} | #{hostname} '
```

This didn't work - both the battery_string and uptime_string were displayed.

**Comment by gpakosz** [comment]
Hello @mboratko 👋

Sorry for not getting back you to you earlier.

> I was still unable to determine if the string templating language used in `tmux.conf.local` is something native to tmux or something unique defined by this package.

It's a bit of both. The conditional syntax is tmux.
The only thing that Oh My Tmux! does is replacing e.g. `#{battery_bar}` by `#(cut -c3- ~/.tmux.conf | sh -s _battery_bar)`.
You can see the result of all this with
```
$ tmux show -gv status-left
```
and
```
# tmux show -gb status-right
```

> Specifically, I was trying to set up part of the status bar so that:
>
> - If the computer has a battery, display the battery status.
> - If not, display the uptime.

Start with
```
#{?uptime_m,foo,bar}
```
Then replace the if and else parts and you get:
```
tmux_conf_theme_status_right="#{?uptime_m,#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,},#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},}}"
```

**Comment by gpakosz** [comment]
And after testing it myself, I'm realizing there's a tiny bug that prevents it from working 😅

Please try the `gh-356` branch.

**Comment by gpakosz** [comment]
Hey @mboratko 👋

Did you try the `gh-356` branch by chance?
