### ISSUE TITLE
status bar exceeds one line and wrapped into second line causes flickering

### ISSUE THREAD

**Issue by shelper** [gpakosz/.tmux#357]
if i set `tmux_conf_battery_bar_length=5` i have:
![wrapped](https://user-images.githubusercontent.com/546163/82330471-e4320a80-99b0-11ea-82e9-08332be92a65.png)

i have to set it to 0 so that the status bar does not wrap to another line as below
![unwrapped](https://user-images.githubusercontent.com/546163/82330674-252a1f00-99b1-11ea-8e7c-089fe8b0766c.png)

see the battery indicate has an interval that is way larger. the boxes are not next to each other

**Comment by bfellers** [comment]
I also had to do this.  Running In latest windows terminal connected to ubuntu 18.04 on wsl 2.

**Comment by gpakosz** [comment]
@shelper  @bfellers 👋

Are you using Windows Terminal?

**Comment by bfellers** [comment]
Yes, I replaced all config options ending with _attr to be "none", "none,none", or "none,none,none" depending on what was already there.  Is there something else I need to do?

**Comment by gpakosz** [comment]
> I replaced all config options ending with _attr to be "none", "none,none", or "none,none,none"

This doesn't really make sense 🤷‍♂️ In particular `"none,none"` or `"none,none,none"`

What you're facing is a bug in Windows Terminal that is reported to have been patched. Please try to update it.

**Comment by shelper** [comment]
updating to terminal 1.0 and it is find now, closing it

**Comment by bfellers** [comment]
Updating also fixed for me.
