### ISSUE TITLE
Theme not working in Tmux 3

### ISSUE THREAD

**Issue by JSybrandt** [gpakosz/.tmux#358]
My existing ohmytmux conf is no longer working in Tmux 3.
The keybindings work fine, but the theme customization are lost.

I reinstalled ohmytmux just in case, no luck

**Comment by gpakosz** [comment]
Hello @JSybrandt 👋

This configuration definitely works with tmux 3.
Make sure you're up to date and reload the configuration (or kill all tmux processes to be sure)

**Comment by JSybrandt** [comment]
Yeah, I'm noticing it works on one machine and not another now. Thanks
