### ISSUE TITLE
Unexpected synchronization across machines and sessions

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [gpakosz/.tmux#360]
I have a tmux session on my local machine:

```bash
tmux new -s local
```
Then in another terminal, I connect to a remote machine and start a new session there:

```bash
ssh -L8888:localhost:8888 ubuntu@123.345.678.1
tmux new -s remote
```

In each of these sessions, **ALL** commands are being replicated i.e. synchronized, so I create a new window in `remote` and it also appears in `local`. It is not just one window or pane, but the entire sessions, so if I create and rename a new window (`<prefix> c` and `<prefix> ,`), it is in both sessions. Navigation to other windows also synchronizes.

The only perhaps odd thing I am doing is ssh-connecting to `remote` with a port exposed (above, 8888 for the Jupyter notebook server). The "synchronize" icon :dark_sunglasses: does not appear in the status bar.

While synchronization is a cool idea, it is dangerous for it to happen when unintended (and unaware!) while I was cleaning up, with things like `sudo rm -rf ...`  :sweat_smile: 

Any ideas how it happened and how to prevent it?

**Comment by gpakosz** [comment]
Hello @Nicholas-Mitchell 

> The "synchronize" icon 🕶️ does not appear in the status bar

Are you sure you're not referring to the `#{pairing}` indicator that lights up when multiple clients are attached to a session? (`tmux_conf_theme_pairing='👓 '          # U+1F453` in your `~/.tmux.conf.local` copy).

This is different from an indicator that tells whether `synchronize-panes` is currently on.
For that, you can e.g. add `#{?pane_synchronized,🔒 ,}` to your status line.

**Comment by Nicholas-Mitchell** [comment]
Sorry, used the wrong word, but in any case - there are neither of those symbols. Here is my current status bar (default from when I installed):

```
mux_conf_theme_status_left=' ❐ #S | ↑#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '
tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b |\
 #{username}#{root} | #{hostname} '
```

--- 
But how can these sessions be synchronised at all, being on different machines with different names?

**Comment by gpakosz** [comment]
> But how can these sessions be synchronised at all, being on different machines with different names?

> Any hints on how to debug this?

I have no idea 🤷‍♂️
I'm using "nested" sessions all the time and I never experienced what you describe.
I doubt `ssh` port forwarding has anything to do with it.
Look into your terminal emulator and see if it has tmux integration of some sort.
Otherwise start over and introduce changes gradually until the problem appears again.

**Comment by Nicholas-Mitchell** [comment]
Ok, thanks - I will see if it happens again.

----

**Regarding nested sessions** - are these done on a single machine only? I assume you unset `$TMUX` then? Otherwise I get this:
![image](https://user-images.githubusercontent.com/12820901/83237709-a2197d80-a195-11ea-9b2b-793282af9abd.png)

Otherwise, how do you enforce bindings to be sent to the (most) nested session? I tried using nested sessions like this: start local sessions, connect to a remote machine via ssh, open new session on remote machine (getting a second nested status bar at the bottom)...  but `<prefix>` was always sent to the first session on my local machine.

**Comment by gpakosz** [comment]
I don't do it locally. Only through ssh like you described:
- run tmux locally
- ssh into a machine
- start tmux there

**Comment by Nicholas-Mitchell** [comment]
Have you seen this nested-tmux setup?

https://github.com/aleclearmind/nested-tmux

Would it be a reasonable feature request, to add that to your configuration? :)

**Comment by gpakosz** [comment]
I don't want to add support for this. This is niche and I personally believe it's better to just rely on tmux's sessions which you can name the way you want without complicating things

**Comment by Nicholas-Mitchell** [comment]
Fair enough  :)

**Comment by Nicholas-Mitchell** [comment]
So I found a nice solution for me that doesn't affect anything (at least that I use) from your setup, by adding a snippet at the bottom of `~/.tmux.conf.local`:

![image](https://user-images.githubusercontent.com/12820901/83263275-a1491180-a1be-11ea-86da-42da739d788f.png)

So the localhost has a status bar, the first window holds an SSH session onto an AWS machine, where the `remote` tmux session is running... but I am still "active" in the localhost session - meaning all keys are caught by the localhost session. Pressing `Ctrl-F12` (see the bindings in the snippet below) makes the active session the `remote` session, so all `<prefix>` are sent to the remote session. No need to double-press `<prefix>` or anything else. It acts exactly as the root session on localhost.

Additionally, it kind of *grays out* the localhost status bar (although colours should be adapted to this repo's setup):

![image](https://user-images.githubusercontent.com/12820901/83263698-4d8af800-a1bf-11ea-813f-49272284e441.png)

Here is what you can simply paste at the bottom of `~/tmux.conf.local` to get this feature:


```bash
# Attempt to make nested sessions work nicely                                                                                                             
#Variables                                                                                                                                                
color_status_text="colour245"
color_window_off_status_bg="colour238"
color_light="white" #colour015                                                                                                                            
color_dark="colour232" # black= colour232                                                                                                                 
color_window_off_status_current_bg="colour254"
#                                                                                                                                                         
bind -T root C-F12  \
  set prefix None \;\
  set key-table off \;\
  set status-style "fg=$color_status_text,bg=$color_window_off_status_bg" \;\
  set window-status-current-format "#[fg=$color_window_off_status_bg,bg=$color_window_off_status_current_bg]$separator_powerline_right#[default] #I:#W# #\
[fg=$color_window_off_status_current_bg,bg=$color_window_off_status_bg]$separator_powerline_right#[default]" \;\
  set window-status-current-style "fg=$color_dark,bold,bg=$color_window_off_status_current_bg" \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S \;\

bind -T off C-F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  set -u window-status-current-style \;\
  set -u window-status-current-format \;\
  refresh-client -S

wg_is_keys_off="#[fg=$color_light,bg=$color_window_off_indicator]#([ $(tmux show-option -qv key-table) = 'off' ] && echo 'OFF')#[default]"
set -g status-right "$wg_is_keys_off #{sysstat_cpu} | #{sysstat_mem} | #{sysstat_loadavg} | $wg_user_host"

```

Sources:
* https://gist.github.com/samoshkin/05e65f7f1c9b55d3fc7690b59d678734
* https://www.freecodecamp.org/news/tmux-in-practice-local-and-nested-remote-tmux-sessions-4f7ba5db8795/

**Comment by gpakosz** [comment]
Colorful 🤩

But what was the problem with "synchronized" remote and local sessions?

**Comment by Nicholas-Mitchell** [comment]
Haha... The colours can be a little distracting when squashed together like that - was only for the screenshots!

Unfortunately I didn't get to a root cause... Trying various ordering of setting up remote sessions lead to even weirder results, like each key press being echoed in a single pane, so trying to "exit", I'd get `eexxiitt`.

I use stock Terminator and bash. Couldn't find any tmux interference from terminator and didn't look into bash.

**Comment by Just-Insane** [comment]
@Nicholas-Mitchell Is this still working for you? I can't seem to get the C-F12 keybind to not capture the C-a keybind when trying to open a new tab on the remote machine. It does change the status bar grey though.

I have pasted this config into both `~/.tmux.conf.local` on the local machine and `~/.tmux.conf.remote` on the remote machine, as issues on the source repo indicate that might be needed.

**Comment by Nicholas-Mitchell** [comment]
@Just-Insane - it does still work fine for me, but the (perhaps unsatisfying) truth is that I stopped using nested sessions.
I found it became easier to simply have two/three **terminal** tabs open locally: one for localhost and one for the remote machine.

---

I use `C-d` as my prefix, because i use `C-a` and `C-e` for start/end-f-line navigation. That works fine for me and is always respected, in local and nested remote sessions. I can't really help any further, but here is my config for that switch, in case it helps:

```
# replace C-b and C-a by C-d instead of using both prefixes
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-d
bind C-d send-prefix
```
