### ISSUE TITLE
Full hostname 

### ISSUE THREAD

**Issue by ww7** [gpakosz/.tmux#361]
Currently config print only truncated hostname (-s) for SSH, can you please add a possibility to show full hostname?

I mean add condition `.tmux.conf` and variable at `.tmux.conf.local`

I have many hosts with the same subdomain at different domains - in tmux it shows the same hostname (subdomain name)

**Comment by anandawebservices** [comment]
A quick fix is to remove the -s flag here:

https://github.com/gpakosz/.tmux/blob/d6f0f647dd68561ed010f83d8d226383aebfb805/.tmux.conf#L576

**Comment by gpakosz** [comment]
Hello @ww7 👋

Can you please give a concrete example of the different full hostnames you're connecting to?

**Comment by ww7** [comment]
Often I setup webservers what host different domains, and for hostname I use subdomain, like `cp.awesome.edu` or `cp.good.weather`, for both cases shell and Tmux truncate hostname to short `cp`, what confuse because 5 `cp` in same time. If this has a reason, I request a possibility set Tmux to show full hostname.

Maybe this better to resolve with .bashrc/.zshrc `export PS1="$(hostname -f):~$ "`

**Comment by gpakosz** [comment]
Can you please give the `gh-361` branch a try?

**Comment by ww7** [comment]
Works! Thanks!
