### ISSUE TITLE
xshell tmux alway pause 

### ISSUE THREAD

**Issue by snsnsjsn** [gpakosz/.tmux#362]
![image](https://user-images.githubusercontent.com/11435527/83596017-29039700-a596-11ea-86a8-b4e5b3e6d61b.png)

when ctrl b to 1tab ,and stuck like image 

when senconds after , will be normal like this
![image](https://user-images.githubusercontent.com/11435527/83595978-15583080-a596-11ea-8efe-6d976e7b899e.png)

**Comment by gpakosz** [comment]
Hello @snsnsjsn 👋

Looks like you're using Windows Terminal Preview right?

Cany ou reproduce the error without this configuration?

**Comment by snsnsjsn** [comment]
i not only use windows shell ,but also xshell to linux , and i have install this config for vim 
https://github.com/amix/vimrc

it will occur the display problem all the paltform.
here is the problem screen recorder
![落地](https://user-images.githubusercontent.com/11435527/101455334-5bd77f00-396d-11eb-805a-d5c2ce2e6ea7.gif)

**Comment by gpakosz** [comment]
Hey @snsnsjsn 👋

I'm sorry I have no idea at that point.
Does the problem happen when you don't load Oh My Tmux?!
```
$ tmux -L test -f /dev/null
```
?

**Comment by snsnsjsn** [comment]
> Hey @snsnsjsn 👋
> 
> I'm sorry I have no idea at that point.
> Does the problem happen when you don't load Oh My Tmux?!
> 
> ```
> $ tmux -L test -f /dev/null
> ```
> 
> ?

i have try your suggestions,
and it is ok 

so ?

**Comment by gpakosz** [comment]
You verify the value of `TERM`. It should be set to `xterm-256color` outside of tmux, and inside tmux Oh My Tmux sets it to `screen-256color`.
