### ISSUE TITLE
SSH hostnames not shown when using sshpass

### ISSUE THREAD

**Issue by mikeage** [gpakosz/.tmux#363]
Given a command line like:

`sshpass -p FOO ssh root@1.2.3.4`

Both the username and hostname are blank. When running a regular ssh session, it does work.

(I realize that sshpass is often an anti-pattern, but I work with many embedded developer devices for which it's easier to use this than to keep copying keys after each software update)

**Comment by gpakosz** [comment]
Hello @mikeage 👋

I don't have much time these days but I'll have a look soon.

**Comment by gpakosz** [comment]
Hello @mikeage 👋

Can you try the `gh-363` branch please?

**Comment by mikeage** [comment]
perfect, thank you!
