### ISSUE TITLE
Slow startup on Mac

### ISSUE THREAD

**Issue by maxi8815** [gpakosz/.tmux#365]
Hi! I recently installed this awesome configuration, I really love it, but it takes up to 5-8 seconds to startup when I type 'Tmux' and hit Enter.
I have a MacBook Air 2018, son I assume it should work fast.
I leave the configuration empty and the startup is instant.

Thanks in advance.

**Comment by gpakosz** [comment]
Hello @maxi8815 👋

Can you give the `optimizations` branch a try?
Also, what tmux version are you using?

**Comment by maxi8815** [comment]
I'm using tmux 3.1b, what do you mean with optimizations branch?  

Thanks!

**Comment by gpakosz** [comment]
(We'll get to the `optimization` branch later)

Are you using `zsh`?
And can you paste the output of 
```
$ command -v sh
```

**Comment by maxi8815** [comment]
$ command -v sh , gives me:
/bin/sh

I'm using bash.

Thanks.

**Comment by gpakosz** [comment]
Can you please paste the output of
```
$ ln -s /bin/sh
```

**Comment by maxi8815** [comment]
I have no output with this one.

**Comment by gpakosz** [comment]
Dammit I meant
```
$ ls -l /bin/sh
```

**Comment by maxi8815** [comment]
haha now gives me this:

-rwxr-xr-x  1 root  wheel  31440 May 27 21:24 /bin/sh

**Comment by gpakosz** [comment]
Thank you

For now I have no idea of what can take so much time to initialize 😐

To test with the `optimizations` branch:
```
$ cd ~/.tmux
$ git checkout optimizations
```

**Comment by maxi8815** [comment]
Ok thank you.

**Comment by gpakosz** [comment]
I conclude the `optimizations` branch solves it for you?

**Comment by maxi8815** [comment]
Not really, it gave me an error:
error: Your local changes to the following files would be overwritten by checkout:
	.tmux.conf
Please commit your changes or stash them before you switch branches.

But I don't want to bother you, is not a big deal, its a couple of seconds to wait.

**Comment by gpakosz** [comment]
Right,

> `error: Your local changes to the following files would be overwritten by checkout:
.tmux.conf`

Means you likely introduced the slowness yourself by changing `~/.tmux.conf` and you're not supposed to do that.

Please try again with a pristine `~/.tmux.conf` and see if startup is still slow

**Comment by maxi8815** [comment]
Ok you were right, I restore the original Tmux.conf but I keep having 2-3secs to open Tmux, I execute the optimizations command:

Branch 'optimizations' set up to track remote branch 'optimizations' from 'origin'.
Switched to a new branch 'optimizations'

what should I do next?

**Comment by gpakosz** [comment]
Relaunch tmux processes, both server and client.

**Comment by maxi8815** [comment]
Ok I have done that, but it takes 3-4 secs to open, if I delete the Tmux.conf and run Tmux, it opens instantly.

**Comment by gpakosz** [comment]
I don't reproduce that delay here.
It's expected it takes longer than a blank conf but I can't reproduce that much delay.

**Comment by maxi8815** [comment]
Don't worry, I really like this configuration, I'm going to use it anyway. Thanks for your support!
