### ISSUE TITLE
unable to re-bind <prefix>-c

### ISSUE THREAD

**Issue by diracs-delta** [gpakosz/.tmux#366]
Hello! Thanks for this awesome repo. Saved me unbelievable amounts of hassle doing server-side work. Before I talk about the issue, here's a listing of the steps I've taken.

I've verified that I'm using the latest version of `.tmux.conf`.
I've reproduced this issue across the `st` and `xterm` terminals.
I've run `cut -c3- ~/.tmux.conf | sh -s _apply_configuration`, with no output in stdout or stderr.

I want to create new panes and windows in the directory of my current pane. I followed the stack exchange post [here](https://stackoverflow.com/questions/49743319/can-i-override-next-session-binding-prefix-in-tmux), and appended the following lines to `.tmux.conf.local`.

```
# create new window in current dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
```

However, I launch `tmux` in `~/`, and then `cd` into `~/Repos`, and then type `<prefix>-c`, the new window is still in `~/`.

Let me know if you all can reproduce this issue. Here's the rest of my `.tmux.conf.local`.

```
# -- user customizations -------------------------------------------------------

# increase history size
set -g history-limit 10000

# prev/next window
unbind l
bind -n C-l next-window
bind -n C-h previous-window
bind C-l send-keys C-l \; run 'sleep 0.1' \; clear-history

# create new window in current dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
```

**Comment by gpakosz** [comment]
Hello @diracs-delta 👋

Forget redefining bindings and instead update your `~/.tmux.conf.local` copy and set `tmux_conf_new_window_retain_current_path=true`.

**Comment by diracs-delta** [comment]
Thanks @gpakosz ! That fixed the issue. Closing.
