### ISSUE TITLE
Powerline status fonts are not showing up

### ISSUE THREAD

**Issue by nitin-gyany** [gpakosz/.tmux#367]
I am running a xfce-terminal with the Ubuntu 20.04, latest zsh and OhMyzsh, tmux 3.0a, latest OhMyTmux. Everything is updated to the last stable version.
The terminal colors are xterm-256colors and I have verified with on the CLI by printing all colors.
On zsh the special characters that make up the Powerline are seen beautifully.
Once Tmux is run, all these special characters on zsh and Tmux status line disappear. The Tmux status line shows the background colors in their 256 color glory, but the special characters are missing.

The output of printf '%b\n' '\ue0b0\ue0b1\ue0b2\ue0b3' is only underscores inside tmux. Outside, it is proper. 

I made changes to the config file to enable unicode, 256 colors etc. (after using an empty .tmux.conf) but nothing is working.

**Comment by gpakosz** [comment]
Hello @nitin-gyany 👋

This is clearly a `TERM` or `tmux` problem, unrelated to this configuration.

I'm pretty sure you will face the same issue if you do the `printf` test again after having launched `tmux` with `tmux -f /dev/null -L test`.

Make sure `TERM` is `xterm-256color` outside of `tmux`, and is `screen-256color` or `tmux` inside of `tmux.

**Comment by nitin-gyany** [comment]
>> Make sure TERM is xterm-256color outside of tmux, and is screen-256color or tmux inside of `tmux.
It is. 
I am pretty sure that it is outside of OhMyTmux configuration. Where can I check for tmux related issues?

**Comment by nitin-gyany** [comment]
I got the issue resolved by running tmux -u. Followed - 
[(https://github.com/powerline/powerline/issues/255#issuecomment-13969191)]
Thank you.

**Comment by gpakosz** [comment]
Ah yeah I assumed you were using a `UTF-8` locale.
