### ISSUE TITLE
Incorrect use of -c in window split ("returned 1")

### ISSUE THREAD

**Issue by yggdr** [gpakosz/.tmux#368]
Trying to split a window (e.g. `<prefix> "`) gives the error
`'cut -c3- ~/.tmux.conf | sh -s _split_window /dev/pts/23 -v -c ' returned 1`

Manual testing gives this:
```
# cut -c3- ~/.tmux.conf | sh -s _split_window /dev/pts/23 -v -c
tmux: option requires an argument -- c
usage: split-window [-bdefhIPv] [-c start-directory] [-e environment] [-F format] [-l size] [-t target-pane] [command]
```
without -v -c it seems to work

```
# tmux -V
tmux 3.1a
```

**Comment by gpakosz** [comment]
Hello @yggdr 👋

Can you please try with tmux `3.1b` and an updated `master` branch of Oh My Tmux! ?
