### ISSUE TITLE
bug about reload tmux config

### ISSUE THREAD

**Issue by rmGFW** [gpakosz/.tmux#369]
this error came out after i reload my tmux config in a session 
`cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127`

but if i start a new session . no such error

**Comment by gpakosz** [comment]
Hello @rmGFW 👋

Does the problem still exist with the current `master` branch?

Please make sure you kill all tmux processes with `tmux kill-server` or `pkill -f tmux` 🙏
