### ISSUE TITLE
maximize_pane doesn't work if other session has a maximized window.

### ISSUE THREAD

**Issue by amosbird** [gpakosz/.tmux#37]
Toggling maximize_pane() has no effect when other session already contains a maximized window.

**Comment by gpakosz** [comment]
Hello @amosbird, thanks for the report.

Can you please try whether the `fix-maximize_pane` branch fixes it for you?

**Comment by amosbird** [comment]
@gpakosz I get `cut -c3- ~/.tmux.conf | sh -s _maximize_pane 1 %9' returned 1` when toggling `maximize_pane` while there is one existing in another session.

**Comment by gpakosz** [comment]
I'll give it another try tonight. Can you please tell me which version of tmux you're using?

**Comment by amosbird** [comment]
@gpakosz I use the nearly latest tmux `tmux 2.4`.

**Comment by gpakosz** [comment]
I confirm I can reproduce with `tmux 2.4` but at that point I didn't investigate what changes between `2.3` and `2.4`

**Comment by gpakosz** [comment]
I forced pushed the `fix-maximize_pane` branch. Can you please give it another try?

**Comment by amosbird** [comment]
It works as expected. Thanks :-) . BTW, what is the correct way to override key bindings? I'd like to do this,
```
bind 3 split-window -v
bind 2 split-window -h
bind 1 toggle_maximize_pane
```

Currently I override them directly in .tmux.conf which may not be a good choice for future upgrade.

**Comment by gpakosz** [comment]
Just move that at the end of `.tmux.conf.local`, there's a dedicated section for overrides

**Comment by gpakosz** [comment]
See [this comment](https://github.com/gpakosz/.tmux/issues/25#issuecomment-241560561) for a detailed explanation of the `cut -c3- ~/.tmux.conf | sh -s` thing.

**Comment by amosbird** [comment]
yeah, i know. That's why I feel a bit weird. `split-window` may also need options for directory settings and maybe ssh sessions. I wonder if it could be more user friendly. e.g. We could define a set of functions for overriding.

**Comment by gpakosz** [comment]
Well I'll first close this PR with the fix then I'll think about further customization.
