### ISSUE TITLE
Help: Powerline status not displayed on mintty running on WSL 2

### ISSUE THREAD

**Issue by karnn** [gpakosz/.tmux#370]
I am trying to get the powerline status bar to show on my mintty terminal running ubuntu 20.04. I replaced the tmux.conf with tmux.conf.local from this repo and uncommented the lines for powerline symbols. Mintty has `$TERM` set to `xterm-256color` and inside `tmux.conf` I do `set -g default-terminal "screen-256color"`. After restarting tmux or after doing `tmux source-file ~/.tmux.conf` I still get the basic tmux status bar. I went through past issues and also searched README.md for a solution but I can't figure out what is going wrong.

I'd really appreciate any help. Thanks!

**Comment by jooray** [comment]
you need both tmux.conf and tmux.conf.local from this repo. tmux.conf.local is a customization.

**Comment by gpakosz** [comment]
Hello @karnn 👋

> I replaced the `tmux.conf` with `tmux.conf.local` from this repo and uncommented the lines for powerline symbols

Please read setup instructions again 😉

**Comment by karnn** [comment]
> Hello @karnn 
> 
> > I replaced the `tmux.conf` with `tmux.conf.local` from this repo and uncommented the lines for powerline symbols
> 
> Please read setup instructions again

Stupid me. I cloned the git folder into another directory than my home folder and only copied the .conf.local file as per instructions. Sorry about that. I didn't notice there were two files .conf and .conf.local
