### ISSUE TITLE
Does not display advanced color prompt, troubleshooting section did not help

### ISSUE THREAD

**Issue by jooray** [gpakosz/.tmux#371]
Hi,
I have two machines, one is macOS and the other is Linux. They share the same .tmux.conf and .tmux.conf.local - I have a slightly customized .tmux.conf.local, but tried with your version too.

Linux:
```
$ echo $TERM
xterm-color
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ tmux -V
tmux 3.1b
```

macOS has the same locale, same tmux version, same config.

Linux prompt looks like this:
<img width="1433" alt="Screenshot 2020-07-08 at 18 55 41 " src="https://user-images.githubusercontent.com/1028688/86947892-b6657880-c14c-11ea-84db-a119e0c810e7.png">

macOS prompt looks like this:
<img width="1427" alt="Screenshot 2020-07-08 at 18 55 51 " src="https://user-images.githubusercontent.com/1028688/86947915-bf564a00-c14c-11ea-8ec9-0bf4da841ba8.png">

The terminal is exactly the same, I ssh to the Linux machine from the same terminal. Patched fonts are correct.

**Comment by jooray** [comment]
Seems to work again, I don't know why though :(

**Comment by gpakosz** [comment]
In your Linux screenshot, you can see it's the 21st session being created. Likely a stray tmux server process was still running.
