### ISSUE TITLE
useless bar at the bottom of tmux in full-screen mode

### ISSUE THREAD

**Issue by jerabaul29** [gpakosz/.tmux#372]
I have noticed something strange.

When I open a tmux, it takes all (or near all) of my window, which I am happy with:

![small_tmux](https://user-images.githubusercontent.com/8382834/87164290-e6d22180-c2c8-11ea-9984-fe36322a3109.png)

However, if I open tmux, and then put the terminal into full-screen mode (or the other way around, makes no difference), I can observe an inert, useless bar at the bottom:

![large_tmux](https://user-images.githubusercontent.com/8382834/87164387-0701e080-c2c9-11ea-8d01-11f561722f5b.png)

This is a bit annoying, as this means I loose '1 line' of code span ^^. Strangely this does not seem to happen (or at least to a much lesser extent) if I just maximize the window without using full screen mode:

![maximized_tmux](https://user-images.githubusercontent.com/8382834/87164929-b343c700-c2c9-11ea-9b40-f4236abef6a4.png)

Any idea:

- where this comes from
- how to fix that

?

I am asking on this repo as I only use tmux with the present configuration.

**Comment by gpakosz** [comment]
Hello @jerabaul29 👋

The gap at the bottom of the screen exists because the screen height is not a multiple of your font size.

**Comment by jerabaul29** [comment]
Aaah that is why 😊 . Many thanks for the explanation!
