### ISSUE TITLE
question: is it possible to display relative line number in copy mode

### ISSUE THREAD

**Issue by slarsar** [gpakosz/.tmux#374]
if there was relative line number on the left side of copymode, then we can move cursor to expected location faster.

![image](https://user-images.githubusercontent.com/46400566/87530509-01d6d400-c6c3-11ea-927e-7c859941b52f.png)

**Comment by slarsar** [comment]
relative line number  like vim: 
![image](https://user-images.githubusercontent.com/46400566/87530787-65f99800-c6c3-11ea-8184-5e30080d4e0c.png)

**Comment by gpakosz** [comment]
Hello @slarsar 👋

AFAIK, `tmux` just can't do that.

**Comment by slarsar** [comment]
thank you. :smile:
