### ISSUE TITLE
How can I disable the theming?

### ISSUE THREAD

**Issue by heraldofsolace** [gpakosz/.tmux#375]
I am writing a plugin that provides a theme and I want to disable the theming provided by this plugin. Basically my plugin is just a .tmux file that sets the `status-left` and `status-right` options.

I added this at the end of `.tmux.conf.local`

```
run-shell '/path/to/my/plugin.tmux
```
But it does not work. I tried adding to the end of `.tmux.conf.local`

```
set-option -g status-left ""
set-option -g status-right ""
```
It still doesn't work.

Is there any way i can achieve this?

**Comment by gpakosz** [comment]
Hello @heraldofsolace 👋

You likely want to edit your `~/.tmux.conf.local` copy and set `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` to empty values:
```
tmux_conf_theme_status_left=
tmux_conf_theme_status_right=
```

**Comment by heraldofsolace** [comment]
Thanks.
