### ISSUE TITLE
how to change setting?

### ISSUE THREAD

**Issue by jiang-yuan** [gpakosz/.tmux#378]

**Comment by jiang-yuan** [comment]
I change the prefix to crtl+x and delete the following lines:
set -g prefix2 C-a                        # GNU-Screen compatible prefix
bind C-a send-prefix -2

and run unbind C-a
But when I press crtl + a, the cursor cannot move to the strat of line.

**Comment by gpakosz** [comment]
Hello @jiang-yuan 👋

Do not alter `~/.tmux.conf`, only edit your ~/.tmux.conf.local copy and add:
```
set -gu prefix2
unbind C-a
```

Then reload your configuration.

Then run `cat -v`. Hitting `C-a` should print `^A`. If it's not the case then it means you didn't reload your tmux configuration, or your shell is not configured to be in Emacs mode.

If you're using Bash and it is not configured to be in Emacs mode, you can use
```
$ set -o emacs`
```

I just tried it on macOS with Bash and it works for me.

**Comment by jiang-yuan** [comment]
Thank you.
I usually only use 1 session.
Each time I type 'tmux', it create a new session.
I want to go into my existing session. How to change it?

**Comment by jiang-yuan** [comment]
> 
> 
> Hello @jiang-yuan 👋
> 
> Do not alter `~/.tmux.conf`, only edit your ~/.tmux.conf.local copy and add:
> 
> ```
> set -gu prefix2
> unbind C-a
> ```
> 
> Then reload your configuration.
> 
> Then run `cat -v`. Hitting `C-a` should print `^A`. If it's not the case then it means you didn't reload your tmux configuration, or your shell is not configured to be in Emacs mode.
> 
> If you're using Bash and it is not configured to be in Emacs mode, you can use
> 
> ```
> $ set -o emacs`
> ```
> 
> I just tried it on macOS with Bash and it works for me.

Thank you.
I usually only use 1 session.
Each time I type 'tmux', it create a new session.
I want to go into my existing session. How to change it?
