### ISSUE TITLE
Adding custom status elements

### ISSUE THREAD

**Issue by klmr** [gpakosz/.tmux#38]
Is it possible to add custom status elements without overriding `.tmux.conf` — i.e. inside the `.tmux.conf.local`?

Case in point, I’d like to add [dickeyxxx/tmux-spotify-info][]. If I’m reading the `.tmux.conf` correctly this isn’t currently possible. Could this maybe be added?

Here’s a quick’n’dirty example of an implementation. The delimiters are a bit tricky so I left them out for now:

```diff
diff --git a/.tmux.conf b/.tmux.conf
index 3abdffb..8884bd5 100644
--- a/.tmux.conf
+++ b/.tmux.conf
@@ -211,6 +211,10 @@ run 'cut -c3- ~/.tmux.conf | sh -s apply_configuration'
 #       tmux_conf_theme_mode_attr=${tmux_conf_theme_mode_attr:-bold}
 #       tmux setw -g mode-style fg=$tmux_conf_theme_mode_fg,bg=$tmux_conf_theme_mode_bg,$tmux_conf_theme_mode_attr
 #
+#       # extra status lines
+#       tmux_conf_extra_left=${tmux_conf_extra_left:-}
+#       tmux_conf_extra_right=${tmux_conf_extra_right:-}
+#
 #       # status line
 #       tmux_conf_theme_status_fg=${tmux_conf_theme_status_fg:-colour253} # white
 #       tmux_conf_theme_status_bg=${tmux_conf_theme_status_bg:-colour232} # dark gray
@@ -218,7 +222,7 @@ run 'cut -c3- ~/.tmux.conf | sh -s apply_configuration'
 #
 #       tmux_conf_theme_session_fg=${tmux_conf_theme_session_fg:-colour16}  # black
 #       tmux_conf_theme_session_bg=${tmux_conf_theme_session_bg:-colour226} # yellow
-#       status_left="#[fg=$tmux_conf_theme_session_fg,bg=$tmux_conf_theme_session_bg,bold] ❐ #S #[fg=$tmux_conf_theme_session_bg,bg=$tmux_conf_theme_status_bg,nobold]$left_separator_black"
+#       status_left="#[fg=$tmux_conf_theme_session_fg,bg=$tmux_conf_theme_session_bg,bold] ❐ #S #[fg=$tmux_conf_theme_session_bg,bg=$tmux_conf_theme_status_bg,nobold]$left_separator_black$tmux_conf_extra_left"
 #       if [ x"`tmux -q -L tmux_theme_status_left_test -f /dev/null new-session -d \; show -g -v status-left \; kill-session`" = x"[#S] " ] ; then
 #         status_left="$status_left "
 #       fi
@@ -303,7 +307,7 @@ run 'cut -c3- ~/.tmux.conf | sh -s apply_configuration'
 #         status_right_hostname="#[fg=$tmux_conf_theme_hostname_bg,nobold]${status_right_hostname}$right_separator_black#[fg=$tmux_conf_theme_hostname_fg,bg=$tmux_conf_theme_hostname_bg,bold] #h "
 #       fi
 #
-#       status_right="${status_right_prefix}${status_right_battery}${status_right_time}${status_right_date}${status_right_username}${status_right_hostname}"
+#       status_right="${status_right_prefix}${tmux_conf_extra_right}${status_right_battery}${status_right_time}${status_right_date}${status_right_username}${status_right_hostname}"
 #       tmux set -g status-right-length 64 \; set -g status-right "$status_right"
 #
 #       # clock
```

With this, I can just add the following line to my `.tmux.conf.local`:

```bash
tmux_conf_extra_right='#(~/.tmux/tmux-spotify-info)'
```

Ideally this would be an array and `.tmux.conf` would add the necessary delimiters.

[dickeyxxx/tmux-spotify-info]: /dickeyxxx/tmux-spotify-info

**Comment by gpakosz** [comment]
Hello Konrad

The point of the recent major rewrite is exactly to provide this flexibility.

There's no auto upgrade path though. Most of the syntax of `.tmux.conf.local` changed.

Please start overt, and customize [`tmux_conf_theme_status_left`](https://github.com/gpakosz/.tmux/blob/8390d37ed8b9436e4f282e1548bf53275bea52f9/.tmux.conf.local#L158) or [`tmux_conf_theme_status_right`](https://github.com/gpakosz/.tmux/blob/8390d37ed8b9436e4f282e1548bf53275bea52f9/.tmux.conf.local#L159) to your needs.

**Comment by klmr** [comment]
This is awesome news, even if it means re-configuring tmux (I haven’t customised a lot anyway). I hadn’t seen the recent changes … my version was somewhat (\*cough\*) outdated.

**Comment by gpakosz** [comment]
Hope you like the new stuff then!

**Comment by gpakosz** [comment]
@klmr did you manage to configure your status line at will in the end?

**Comment by klmr** [comment]
I’ve just noticed that I forgot to reply to this age-old issue. Anyway, obviously everything worked beautifully. Thank you very much for all the work you’ve put into this.
