### ISSUE TITLE
please add detailed steps on copying to x11 clipboard

### ISSUE THREAD

**Issue by RafalSkolasinski** [gpakosz/.tmux#380]
It would be very useful to have more detailed step by step instructions on how to copy to X11 Clipboard selected text using mouse mode (from a single pane).

Thanks

**Comment by waldauf** [comment]
UT(F:)G ;]

```
# For binding 'y' to copy into tmux buffer and 'Enter' into X clipboard
## https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -i -f -selection primary | xclip -i -selection clipboard" '\;' send -X clear-selection
```

**Comment by gpakosz** [comment]
Hello @RafalSkolasinski and @waldauf 👋

There are instructions in your `~/.tmux.conf.local` copy:
```
# -- clipboard -----------------------------------------------------------------

# in copy mode, copying selection also copies to the OS clipboard
#   - true
#   - false (default)
# on macOS, this requires installing reattach-to-user-namespace, see README.md
# on Linux, this requires xsel or xclip
tmux_conf_copy_to_os_clipboard=false
```

You need to
- install `xsel` or `xclip` first
- edit your `~/.tmux.conf.local` copy and set `tmux_conf_copy_to_os_clipboard=true`
- enable mouse mode with `<prefix>` + `m`

Then upon selecting some text with the mouse:
- tmux will enter copy mode
- and copy the selected text to a tmux buffer *and* the OS clipboard if `tmux_conf_copy_to_os_clipboard=true`

Hope that helps!

**Comment by waldauf** [comment]
Hello @gpakosz,

thank you for adding information. I was lazy as @RafalSkolasinski and just copied my part of `.tmux.conf.local` without explaining what wasn't the right access. My setting enables multi-selecting of text with the mouse without immediate text copying. Because we know that someone doesn't hit the text on the first attempt. :D So you mark your text and after hit "enter" will be text copied. 

All is described in this [article](https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b), which I found. 

For more I'm adding a part which enables mark block of text:
```
# Visual mode - rectangle block
bind-key -T copy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle

```

**Comment by gpakosz** [comment]
Are we good @RafalSkolasinski ?

**Comment by RafalSkolasinski** [comment]
Yes, thanks @gpakosz! It was so long I even forgot I asked the question. I ended up not really using tmux though as tilix kind-of give me everything I need but I guess a note on this in somewhere will help confused ppl in the future :+1:

**Comment by gpakosz** [comment]
@RafalSkolasinski I'll think about it. So far I've avoided duplicating information between `~/.tmux.conf.local` and `README.md`

**Comment by RafalSkolasinski** [comment]
Probably one place is enough, I am sorry, I don't remember now exactly what was my problem. It's possible I got it working the way it's meant to work with `tmux` but it was still not as easy as with `tilix` panes.

What I was looking for  was basically that if I have two panes (two columns) to be able to just
- LMB select piece of text
- single shortcut to copy it into clipboard
without any copy / normal mode tweaks. 

Probably that's just not the way tmux works so don't mind my rambling :)
