### ISSUE TITLE
Use tmux-256color instead of screen-256color

### ISSUE THREAD

**Issue by MoetaYuko** [gpakosz/.tmux#382]
`tmux-256color` has additional support for italics over `screen-256color`

Ref: https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round

**Comment by tuxruffian** [comment]
I was able to get italics working with:
```bash
$TERM=xterm-256color
```
by adding the following to `~/.tmux.conf.local`:
```tmux
set -g default-terminal "tmux"
```
