### ISSUE TITLE
Tmux long commands rewrites same line

### ISSUE THREAD

**Issue by maxi8815** [gpakosz/.tmux#383]
When using Tmux with 2 vertical panes if I paste a long line, it writes to same line instead of continuing to the next.
For example:
Instead of this:
[root@server ~]$ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd│
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

This happens:

dddddddddddderver ~]$ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

Thanks in advance.

**Comment by maxi8815** [comment]
Can you please help me?

**Comment by maxi8815** [comment]
Any help?

**Comment by gpakosz** [comment]
Hello @maxi8815 👋

Can you confirm it works as you expect with tmux stock setting?
You can try launching a stock tmux server with
```
$ tmux -f /dev/null -L test
```

**Comment by maxi8815** [comment]
Yes it does, it seems to be a problem relate to pane "writable" screen size, for example if I zoom a pane when writing keeps the pane size like before I zoomed it.

**Comment by gpakosz** [comment]
Hello @maxi8815 👋

I don't reproduce your problem. Double check your terminal emulator settings. And make sure the `TERM` environment variable is set to `xterm-256` color outside of tmux, and `screen-256color` inside of tmux.

**Comment by maxi8815** [comment]
Ok I realize that this behavior happens on remote servers, I tried locally and it works like charm. I set screen-256color on the remote server but it doesn't work. Any ideas?

**Comment by maxi8815** [comment]
Ok I think I found the problem, on remote servers the stty rows and columns are not being updated, can you help me with this?

**Comment by maxi8815** [comment]
Any ideas?

**Comment by gpakosz** [comment]
Nope 🤷‍♂️

I suggest you try the `#tmux` IRC channel on freenode or the `tmux-users` mailing list.
