### ISSUE TITLE
"tmux" Window With History/Log

### ISSUE THREAD

**Issue by efaden** [gpakosz/.tmux#387]
So just installed the dot file and am having a weird behavior I'm not sure how to disable.  It seems like I have a window (always number 1) that is named "tmux" that has what appears to be the tmux log in it.  I don't really need that window and I'd like to disable it, but I can't seem to figure out how.  If I remove the .tmux file it goes back to normal without it, so it's something in the .tmux file.  I'm using iTerm2 on OSX.  Any ideas?  Thanks

**Comment by gpakosz** [comment]
Hello @efaden 👋

From your description, I have really no idea of what that could be 🤷‍♂️

Are you sure you didn't modify the `~/.tmux.conf` and the `~/.tmux.conf.local` files?

**Comment by gpakosz** [comment]
Hey @efaden 👋

Any news?
