### ISSUE TITLE
iTerm2 compatibility

### ISSUE THREAD

**Issue by radaniba** [gpakosz/.tmux#39]
Hello guys

I am having some issues running `.tmux` on iterm2 Build 3.0.12

I have random duplicate status bar like shown in this screen shot attached here

It works perfectly with native Term app though

![screen shot 2016-11-20 at 9 43 41 am](https://cloud.githubusercontent.com/assets/1666443/20464895/4c81deec-af06-11e6-8c15-401611d4429d.png)

**Comment by gpakosz** [comment]
I've always been running iTerm2 without an itch :(

I'm currently using `Build 3.0.20161116-nightly`. Which version of tmux are you using?

**Comment by radaniba** [comment]
Hi @gpakosz I am using tmux 2.3

**Comment by gpakosz** [comment]
Weird that's the version I've been using to develop the configuration. Worth trying upgrading iTerm2 ?

**Comment by radaniba** [comment]
Hmm weird indeed

I am running the latest version of iterm2, tmux 2.3 and zsh with prezto as my shell.

I still cannot understand this beaviour looked at the conf file and it seems fine to me :/

**Comment by gpakosz** [comment]
Does it work in iTerm2, tmux 2.3 and just bash?

**Comment by radaniba** [comment]
No, still duplicating the lines for some reason, besides Term is using zsh as default and it works just fine, but I spot an error message or warning

![screen shot 2016-11-20 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/1666443/20466387/6fdcdbbe-af27-11e6-8324-258c3dbb9025.png)

**Comment by gpakosz** [comment]
This is not an error message or warning. This is what tmux prints when the output of a command is not ready yet at the time of printing the status line.

**Comment by gpakosz** [comment]
In fact if the screenshot above is what you get with `Term.app`, then I wouldn't say it works just fine. It seems to me it's the very same bug that fails to overdraw the status line and instead draws it on the next line

**Comment by radaniba** [comment]
It was an issue with iTerm2 actually, removed it completely and reinstalled , now it works perfectly fine

**Comment by LockeAG** [comment]
Sorry guys but is happening to me:

ZSH: Antigen
Theme: https://github.com/sindresorhus/pure
iTerm: Build 3.1.20170323-nightly
TMUX: tmux 2.3

![Screen](https://www.dropbox.com/s/51xbxr3hfmsvhea/Screenshot%202017-03-23%2003.14.03.png?dl=0)
