### ISSUE TITLE
Changing window jumps marker

### ISSUE THREAD

**Issue by mustaqimM** [gpakosz/.tmux#390]
Hi there,

I had one minor issue with the way the `tmux_conf_theme_window_status_current_format` is set
https://github.com/gpakosz/.tmux/blob/d6f0f647dd68561ed010f83d8d226383aebfb805/.tmux.conf#L862

The text jumps around when switching windows because of added spaces between referenced variables:
[Original with spaces jumps around](https://streamable.com/eup7dx)
[No jump](https://streamable.com/hvfmeo)

Thanks so much for this excellent project

**Comment by gpakosz** [comment]
Hello @mustaqimM 👋

I'll have a look

**Comment by gpakosz** [comment]
Hey @mustaqimM 👋

Can you give the `gh-390` branch a try please? Make sure you reload the configuration with `<prefix>` + `r`.

**Comment by mustaqimM** [comment]
@gpakosz That seems to work while keeping a space between windows, thank you!

**Comment by gpakosz** [comment]
Are we good then? If so I'll merge the branch and close the issue

**Comment by mustaqimM** [comment]
@gpakosz yes, it's working well, thank you
