### ISSUE TITLE
Vim theme will have some trouble

### ISSUE THREAD

**Issue by link-ding** [gpakosz/.tmux#391]
once I open tmux my vim theme will have some color problem
![image](https://user-images.githubusercontent.com/49264539/90970494-37d06900-e549-11ea-9f8d-4dca9036b9fc.png)

**Comment by gpakosz** [comment]
Hello @link-ding 👋

Make sure the `TERM` environment variable is properly configured.
It should be `xterm-256color` outside of tmux and `screen-256color` or `tmux-256color` inside tmux.
