### ISSUE TITLE
How to in uninstll this theme

### ISSUE THREAD

**Issue by link-ding** [gpakosz/.tmux#392]

**Comment by afcidk** [comment]
Simply remove the `.tmux.conf` file in your home directory should work, you could also remove the `.tmux` directory if you want.

**Comment by hello-wn** [comment]
> Simply remove the `.tmux.conf` file in your home directory should work, you could also remove the `.tmux` directory if you want.

didn't work for me.... I removed `.tmux.conf` file and `.tmux` directory, but still get into this theme....
OMG.....

**Comment by hello-wn** [comment]
Anybody can help me remove the theme? I just wanna get back to the default theme.....
I've deleted all tmux config files, but still get into this theme.

**Comment by hello-wn** [comment]
> Anybody can help me remove the theme? I just wanna get back to the default theme.....
> I've deleted all tmux config files, but still get into this theme.

Finally, I make it!!!
```tmux kill-server```
ref link: [here](https://stackoverflow.com/questions/38295615/complete-tmux-reset)
