### ISSUE TITLE
How I can create a new built-in variable

### ISSUE THREAD

**Issue by clsaavedra** [gpakosz/.tmux#394]
Hello,

It's a grate tmux configuration settings, I would like add new features like show the K8s current context or the AWS profile configuration and I would like to know who I can create new build-in variables to add this new features.

Thanks in advance. Best regards.

**Comment by gpakosz** [comment]
Hello @clsaavedra 👋

Please have a look at the `gh-394` branch.
The starting point is to turn your `~/.tmux.conf.local` copy into a polyglot:

```
# : << EOF

...

# -- 8< ------------------------------------------------------------------------

# EOF
#
# foo() {
#   echo "foo"
# }
#
# "$@"
```

⚠️ You need to pay much attention to the `#` characters and the last line containing `# "$@"`.

Then within e.g. `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right` you can call your function with `#(cut -c3- ~/.tmux.conf.local | sh -s foo)`.

That's all I have for now. I'll think about implementing automatic variable discovery from functions defined in `~/.tmux.conf.local`.

**Comment by gpakosz** [comment]
Hello @clsaavedra 👋

I force pushed the `gh-394` branch.
No need to insert `#(cut -c3- ~/.tmux.conf.local | sh -s foo)` anymore in `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right`. Just use `#{foo}`.

Make sure to update your `~/.tmux.conf.local` copy with the instructions given above 👆

**Comment by gpakosz** [comment]
Hello @clsaavedra 👋

Did you get the chance to try the `gh-394` branch?

**Comment by clsaavedra** [comment]
Yes, I did and it is working fine, Thanks
