### ISSUE TITLE
change window can't work

### ISSUE THREAD

**Issue by test0103** [gpakosz/.tmux#395]
<prefix> C-h not work
only <prefix> C-l work
I uesing system is  Debian10 , Using default conf without any change

**Comment by gpakosz** [comment]
Helo @test0103 👋

Can you please paste the output of
```
$ tmux list-keys | grep -F 'C-h'
```
and
```
$ tmux list-keys | grep -F 'C-l'
```

**Comment by myy1966** [comment]
@test0103 Is the terminal you are using is mobaxterm? I found C-h doesn't work in mobaxterm but works in windows terminal.

**Comment by gitcl0ne** [comment]
I am also on Debian 10, had same issue.  Change the line in `.tmux.conf` file to `bind -r C-p previous-window` and `Ctrl b` `Ctrl p` will change to previous window.  Let me know if this helps.

**Comment by gpakosz** [comment]
Please edit your `~/.tmux.conf.local` copy to override / customize bindings further
