### ISSUE TITLE
Not being able to swap back between the “Mouse menus” of tmux and gnome-shell?

### ISSUE THREAD

**Issue by Colmmm** [gpakosz/.tmux#396]
I am not sure if this is a general issue of tmux or one that is specific to this configuration.

The gnome-shell mouse menu that I am referring to is this one which you get when right clicking your mouse:
![image](https://user-images.githubusercontent.com/42407985/92131404-dd16f700-edfd-11ea-8f84-4cd4b3ff89e3.png)

The tmux mouse menu that I am referring to is then this one below which I get from right clicking my mouse after doing C-m (turning on mouse mode).
![image](https://user-images.githubusercontent.com/42407985/92131444-ebfda980-edfd-11ea-8453-79d39fe3e439.png)

My problem is that once I turn off mouse mode again via <prefix>-m, right clicking my mouse gives neither menu, where as you would expect it to show the gnome one.

**Comment by gpakosz** [comment]
Hello @Colmmm 👋

Are you using `C-m` or `<prefix>-m` which is either `C-b-m` or `C-a-m` with this configuration?

**Comment by Colmmm** [comment]
Hello @gpakosz!

Apologies I got confused with my notation, I mean `<prefix>-m` (not `C-m`) to toggle between on/off of the mouse mode.

**Comment by gpakosz** [comment]
Can you try to reproduce the behavior without this configuration?

E.g. by launching
```
$ tmux -f /deev/null -L test
```

**Comment by Colmmm** [comment]
So creating a minimal mouse toggle tmux config with the following in it:
`# Toggle mouse on
bind-key M \
  set-option -g mouse on \;\
  display-message 'Mouse: ON'

# Toggle mouse off
bind-key m \
  set-option -g mouse off \;\
  display-message 'Mouse: OFF'`

And launching a session with it, and once I toggle the mouse mode on, I will get the "tmux mouse menu" thereafter with the `right_click` of the mouse regardless if you switch back to the mouse menu being off. 

So this being different to the behaviour of this .tmux config which shows no menu at all when you `right_click` the mouse when mouse mode is off, if that is made clear?

Besides I forgot about the usage of  doing `shift ` which over runs the current mouse config and then pressing `right_click` of the mouse which brings up the "gnome mouse menu" regardless of what tmux config you have or whether mouse menu is on/off. So a quick fix for getting round this, but the behaviour still isn't ideal but its a fairly minor problem so feel free to close this issue.

Also thanks for your work on this btw!

**Comment by gpakosz** [comment]
> And launching a session with it, and once I toggle the mouse mode on, I will get the "tmux mouse menu" thereafter with the right_click of the mouse regardless if you switch back to the mouse menu being off.

This doesn't really make sense and it's definitely something my configuration has control over.

Well let's reason outside of my configuration, that does nothing fancy regarding mouse.

- When tmux mouse mode is off (which is the default both in stock tmux and in my configuraion) → tmux menus won't appear because mouse bindings won't trigger.
- When tmux mouse mode is on → tmux menus will appear, as well as engaging copy mode when clicking and dragging.

But for this, tmux needs to receive the mouse events. It's way possible that gnome-shell intercepts them.

You can simplify your testing by avoiding key bindings and type `$ tmux set -g mouse on` or `$ tmux set -g mouse off` right in your terminal.

In doubt, remove your `/.tmux.conf` symlink (I also assume you didn't change anything in `~/.tmux.conf`) and start over with `$ tmux kill-server` or `$ pkill -f tmux`.

**Comment by iam-TJ** [comment]
This affects other terminals too. Here I'm using Xubuntu 20.04 amd64 (Ubuntu + XFCE4) and `xfce4-terminal` and `bash`.

`xfce4-terminal` on its own provides a mouse right-click context menu. After starting `tmux` this remains the case. Then I enable mouse-mode with `<prefix>-m` and now the right-click produces the custom tmux context menu. Using `shift`+right-click produces the original xfce4-terminal context menu. I then do `<prefix>-m` once more and no longer get the tmux custom menu on mouse right-click. It also doesn't produce the original xfce4-terminal context menu  but does when combined with the `shift` key.

If I exit tmux back to the original bash shell it generates unexpected codes on all mouse actions including movement. The characters displayed have a clear button-down button-up form but the actual characters shown are different for each test cycle of `tmux` >  `<prefix>-m` > `<prefix>-m` > `exit`  e.g: `#9'#9` and what I've found is if I clear the randomly generated characters from the shell command-line using `Ctrl+c` what is generated by more mouse button presses changes if the mouse has also been moved.

**Comment by gpakosz** [comment]
Hello @iam-TJ 👋

This is really external to Oh My Tmux!, which can't affect tmux behavior in a profound way.
Can you please check if you're still having the problem when launching tmux with its stock configuration?
```
$ tmux -L test -f /dev/null
```
Then
```
$ tmux -L test set -g mouse on
```
Then try to use tmux menus?

**Comment by iam-TJ** [comment]
@gpakosz Yes; I was just coming back to report that there's a tmux issue about generating random characters:

https://github.com/tmux/tmux/issues/2462

but that seems to infer that this shouldn't happen when mouse mode is off before exit so I've added a comment there.

**Comment by iam-TJ** [comment]
Another related tmux issue:

https://github.com/tmux/tmux/issues/2328

**Comment by gpakosz** [comment]
@iam-TJ Thanks for the links to the tmux issues.

Well @Colmmm I'm afraid all this is external to Oh My Tmux!
