### ISSUE TITLE
The root indicator is always blink

### ISSUE THREAD

**Issue by aofei** [gpakosz/.tmux#397]
## The problem

Somehow, the root indicator in the status bar started to keep blinking, even when it was a non-root user. I believe I didn't make any configuration changes, except to `git pull` this repo.

And, removing the `blink` in `tmux_conf_theme_root_attr='bold,blink'` temporarily solved my problem, but it also disabled the blinking feature when being root user.

## My setup

```bash
$ uname -a
Linux as-server 5.8.7-arch1-1 #1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000 x86_64 GNU/Linux

$ tmux -V
tmux 3.1b

$ ssh -V
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by gpakosz** [comment]
Hello @aofei 👋

Did you reload the configuration after issuing `git pull`?

**Comment by aofei** [comment]
Yes, I did. And I even rebooted the system, but the problem still exists.

**Comment by gpakosz** [comment]
Can you please paste the output of `tmux show -gv status-right`?

**Comment by aofei** [comment]
```
#[fg=#080808,bg=default,none]#[fg=#8a8a8a,bg=#080808,none]#[fg=none]#[bg=none]#[none]#{?client_prefix,⌨ ,}#[fg=none]#[bg=none]#[none]#{?session_many_attached,👓 ,}#[fg=none]#[bg=none]#[none]#{?pane_synchronized,🔒,} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} #[fg=#8a8a8a,bg=#080808,none] %R #[fg=#8a8a8a,bg=#080808,none] %d %b #[fg=#d70000,bg=#080808,none]#[fg=#e4e4e4,bg=#d70000,none] #(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} false #D)#[fg=none]#[bg=none]#[bold,blink]#{?#{==:#(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} #D),root},!,}#[inherit] #[fg=#e4e4e4,bg=#d70000,none]#[fg=#000000,bg=#e4e4e4,bold] #(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} false #h #D)
```

**Comment by gpakosz** [comment]
I can't reproduce it on my Archlinux box.

Can you please try to split your window into panes and reproduce the commands like in the screenshot?
![image](https://user-images.githubusercontent.com/553208/92716808-9bd39980-f35f-11ea-8e14-6a191ad5fccb.png)

Split your window in 3 panes, use `tmux display -p '#{pane_tty}` to know each pane's TTY value. In the first pane, be a regular user. In the second pane, switch to root with `sudo -i`. In the third pane, use `ps` to inspect the process tree for each TTY.

**Comment by aofei** [comment]
You can see the upper right corner of the pic, where there is a flashing vertical bar (just flashed out).

![3BB35C84-F56B-45E8-8C97-AA99B1F9CA85](https://user-images.githubusercontent.com/5037285/92718302-39e15700-f394-11ea-9225-65266bd443aa.png)

**Comment by gpakosz** [comment]
Alright it seems process tree inspection works correctly but that I introduced bugs in theming.

Can you please try the `gh-397` branch please? Checkout the branch and reload the configuration with `<prefix> + r` which will adjust `status-right`.

**Comment by aofei** [comment]
Yes, the `gh-397` doesn't have this problem. 👍

**Comment by gpakosz** [comment]
Right merging it. Thanks for the report 🤝
