### ISSUE TITLE
Status bar theme does not show arrow (>) in ubuntu 20.04

### ISSUE THREAD

**Issue by akashrpo** [gpakosz/.tmux#404]
All the fields have square and rectangle shape

**Comment by gpakosz** [comment]
Hello @akashrpo 👋

You likely lack a font that supports powerline symbols. Please see https://github.com/gpakosz/.tmux#enabling-the-powerline-look

**Comment by akashrpo** [comment]
The powerline pre-patched font is working for vim status bar and zsh prompt but not for tmux status bar.
I had followed the below URL for powerline pre-patched font:
https://www.tecmint.com/powerline-adds-powerful-statuslines-and-prompts-to-vim-and-bash/

**Comment by gpakosz** [comment]
- What's your OS, your shell, and your terminal emulator?

- Did you relaunch the configuration with `<prefix>` + `r` after having edited your `~/.tmux.conf.local` copy?

- Is `TERM` set to `xterm-256color` outside of tmux, and `screen-256color` inside?

- **Outside of tmux**, does the following print the proper character?
  ```
  $ cut -c3- ~/.tmux.conf | sh -s _decode_unicode_escapes '\uE0B0'
  ```

**Comment by akashrpo** [comment]
OS: Ubuntu 20.04.1 LTS, Shell: ohmyzsh, terminal emulator:  gpakosz/.tmux 
I did relaunch the config but didn't edit anything there
yes
It prints an arrow with % symbol (>%) both inside and outside of tmux

**Comment by akashrpo** [comment]
Thanks, it is now solved.

**Comment by gpakosz** [comment]
Do you mean you changed the codepoints?

If that's the case it's because you're using the old version of Powerline symbols in your pre-patched font. Codepoints changed overtime.

**Comment by akashrpo** [comment]
I changed these lines in .tmux.conf.local:
```
tmux_conf_theme_left_separator_main='\uE0B0'
tmux_conf_theme_left_separator_sub='\uE0B1'
tmux_conf_theme_right_separator_main='\uE0B2'
tmux_conf_theme_right_separator_sub='\uE0B3'
```
earlier it was blank.
