### ISSUE TITLE
Automatically create new session

### ISSUE THREAD

**Issue by keyute** [gpakosz/.tmux#406]
Hello, how do I automatically create a new session if there are no other sessions to attach to when using `tmux attach` by editing .tmux.conf.local only?

**Comment by Saul-Dickson** [comment]
What I'm guessing you want to do is similar to this:

`[[ $(tmux ls) == *"window"* ]] && tmux attach || tmux`

This shell command first asks tmux to list any running sessions. If there are any, it runs `tmux attach`, if not it will instead run `tmux`, creating  a new session of tmux. I don't know how to do this by editing .tmux.conf.local, I'd actually recommend going to StackOverflow or some other forum site to ask about that, but this solution can be put at the bottom of any shell's rc file (.zshrc, .bashrc, etc.) to launch tmux automatically in this way. The command for doing that is as follows:

`tmuxlist=$(tmux ls) && [[ $tmuxlist == *"(attached)"* ]] || $([[ $tmuxlist == *"window"* ]] && tmux attach || tmux)`

This command will ask tmux to list any running sessions, windows, etc., the output to the variable `tmuxlist`. It will then check if any sessions are attached; if not, it will check if there are any running sessions at all. If there are, it will attach your client to it, if there aren't it will open a new session; if there is a session attached, the command will exit.

**Comment by gpakosz** [comment]
Hello @keyute 👋

Not sure why it's important to do that from your `~/.tmux.conf.local` copy only, but you may try adding
```
if -F '#{session_id}' '' new-session
```

**Comment by gpakosz** [comment]
Hey @keyute 👋

Did you try what I suggested?

**Comment by keyute** [comment]
yep, works great. thanks!
