### ISSUE TITLE
Users have to wait up to 60 seconds after `tmux kill-server` because of `sleep $interval;`

### ISSUE THREAD

**Issue by Frederick888** [gpakosz/.tmux#407]
After `tmux kill-server`, users have to wait for up to 60s before starting tmux again due to `sleep` calls like

https://github.com/gpakosz/.tmux/blob/67d1c23dcabe96b85ca3906d4a70c71e4859a558/.tmux.conf#L1174

This is because `sleep` command is blocking, and the `trap` has to wait until `sleep` finishes to execute. For example:

```bash
sh -c "trap 'exit 0' TERM; while :; do sleep 5; printf 'foo\\n'; done"
```

Run `kill <pid>` right after a `foo` is printed, one has to wait for 5s before the process actually exits.

A workaround is to use jobs and `wait`. For example:

```bash
sh -c "trap 'exit 0' TERM; while :; do sleep 5 & printf 'foo\\n'; wait %%; done"
```

This time after a `kill <pid>` the process exits immediately.

**Comment by gpakosz** [comment]
Hello @Frederick888 👋

Thanks for the report. I'll have a look at your suggestion.

The `master` branch of tmux has a fix for this AFAIK
```
commit d52ac7d027e40b34e7089addc4f905d03d9c1b16
Author: Nicholas Marriott <nicholas.marriott@gmail.com>
Date:   Fri Jun 12 10:31:12 2020 +0000

    Do not wait on shutdown for commands started with run -b.
```

**Comment by Frederick888** [comment]
@gpakosz Thank you, that's good to know. I guess I can try backporting that commit :)

**Comment by gpakosz** [comment]
Hey @Frederick888 👋

I tried your suggested workaround in Debian Buster and tmux `3.1b` and it doesn't work. I believe the real issue is that tmux is not killing jobs spawned with `run-shell -b` upon quitting in the first place

**Comment by gpakosz** [comment]
Hey @Frederick888 👋

I believe I properly worked around the problem for tmux `<3.2`. Can you please give it a try?

**Comment by Frederick888** [comment]
@gpakosz Yup, can confirm it works! Thanks!
