### ISSUE TITLE
After upgrading, the hostname is replaced by a %+number

### ISSUE THREAD

**Issue by cfsmp3** [gpakosz/.tmux#409]
On the bottom right I used to have 

user+hostname

now it's

user+number

If it helps - it works OK when I'm SSH'ed to a different server (I don't mean it's about SSH, just that it seems to depend on maybe a different hostname).
My hostname is not FQDN, but I tried to set it to a full thing with domain etc but that didn't help.

**Comment by gpakosz** [comment]
@cfsmp3 What solved it?

**Comment by cfsmp3** [comment]
Unclear. It went away. I'll reopen if it happens again.
