### ISSUE TITLE
copy mode doesn't work

### ISSUE THREAD

**Issue by aznshodan** [gpakosz/.tmux#41]
I was able to go to copy mode but the vim binding doesn't seem to work. I tried pressing 'v' in copy mode but it won't highlight the parts i want to copy. Also the top right box is stuck at 0/0.

**Comment by gpakosz** [comment]
Which version of tmux are you using?

I can see two reasons to your problem:
  - either you're using tmux `HEAD` in which they changed the way to configure bindings and I didn't updated this configuration yet
  - either before launching tmux, `$VISUAL` or `$EDITOR` is not set to `vim`

**Comment by aznshodan** [comment]
I did set $EDITOR to vim in ~/.bashrc. I'm using tmux 2.3. 

I uncommented the lines and it works now. thank you.

**Comment by gpakosz** [comment]
Please read https://github.com/gpakosz/.tmux#enabling-the-powerline-look
