### ISSUE TITLE
Output too much information will fail

### ISSUE THREAD

**Issue by github-h** [gpakosz/.tmux#411]
Use `tmux show -g` in TMUX or `ls` in files with more directories. 
This method will output more information in the window, and TMUX will not display normally. 

How can I adjust the configuration file, such as buffer. Make TMUX output normally.

**Comment by gpakosz** [comment]
Hello @github-h 👋

I'm not sure how familiar with tmux but I suggest you read about copy mode.

I don't know if you noticed it in `README.md` but I recommend the [tmux 2
Productive Mouse-Free Development](https://pragprog.com/book/bhtmux2/tmux-2) book.

**Comment by github-h** [comment]
Thanks for your help, I didn't find the answer I wanted in copy mode. 

I still need to go to the TMUX main project to look for help. Thanks again.
