### ISSUE TITLE
Problem when zooming pane

### ISSUE THREAD

**Issue by maxi8815** [gpakosz/.tmux#412]
Hi guys, Im having a problem when zooming a pane, when zoomed keeps size and it doesn't use all screen:

Without zoomed pane:

![image](https://user-images.githubusercontent.com/44240034/94712413-d78acf00-031f-11eb-8cad-232be2a7b5e6.png)

With zoomed pane:

![image](https://user-images.githubusercontent.com/44240034/94712493-ef625300-031f-11eb-9de6-00dc327cecb8.png)

As you can see in the zoomed pane, it is not using the entire screen, it is using just the size it was before zoom.

Any ideas?

Thanks in advance!

**Comment by gpakosz** [comment]
Hello @maxi8815 👋

Reflow works for me.

![image](https://user-images.githubusercontent.com/553208/94713631-5d703f80-034b-11eb-8782-551e15a4d861.png)

![image](https://user-images.githubusercontent.com/553208/94713649-63662080-034b-11eb-8da9-51d4e037aea8.png)

**Comment by maxi8815** [comment]
Im using iTerm2, could be a problem?

**Comment by gpakosz** [comment]
Works in iTerm2 as well here
