### ISSUE TITLE
Binding a key to multiple commands is not working

### ISSUE THREAD

**Issue by matthias-wright** [gpakosz/.tmux#413]
Hi Everyone,

**Problem:**
I configured my tmux such that when I press `<prefix> + g`, a new window is opened and a command is executed in the new window.
I put this into my `.tmux.conf.local`: 
```tmux
bind g new-window \; send-keys -t "$pane" 'ls -l' Enter
```
However, when I press `<prefix> + g`, tmux only opens a new window but does not execute the `ls -l` command. 

This shortcut works without oh-my-tmux.

**What I tried:**
- Comment out the settings `set -sg repeat-time 600` and `set -s escape-time 10` from `.tmux/.tmux.conf`
- Use different keys other than `g`

**Infos:**
- Ubuntu 18.04.5 LTS
- Tmux 2.6
- Gnome-Terminal

Has anyone gotten this to work?

Thanks!

**Comment by gpakosz** [comment]
Hello @matthias-wright 👋

Does it work with stock tmux?

**Comment by gpakosz** [comment]
Hello @matthias-wright 👋

I added it verbatim to my `~/.tmux.conf.local` copy
```
bind g new-window \; send-keys -t "$pane" 'ls -l' Enter
```
and it works for me, as in "it creates a new window and executes `ls -l`".

However, I find the command dubious. What do you think `$pane` will expand to?

**Comment by gpakosz** [comment]
Asking the obvious, did you reload the configuration with `prefix` + `r` after changing your `~/.tmux.conf.local` copy?

**Comment by matthias-wright** [comment]
Hey @gpakosz,
Thanks for the response.

If I leave off the "$pane", the command does not work (even in my old setting without oh-my-tmux).
Yes, I tried reloading and also to create a new session altogether.

Which tmux version do you have?

**Comment by gpakosz** [comment]
I'm running tmux HEAD.

```
bind g new-window \; send-keys 'ls -l' Enter
```

works for me

**Comment by matthias-wright** [comment]
I updated my tmux to version 3.1b and now it works. Thanks @gpakosz !

**Comment by gpakosz** [comment]
Great.

I let you close the issue then. Happy tmuxing
