### ISSUE TITLE
Pane doesn't restore from maximized state

### ISSUE THREAD

**Issue by willheryanto** [gpakosz/.tmux#415]
# Background

Heya! 

I found a little weird things happening from maximized command:

- It cannot restore from maximized pane
- It can maximized a "dead pane"

_P.S: Sorry I turn off the theme from your build. Personally I love the bare looks of tmux =)._

# Steps to reproduce

1. Split the pane either vertical `<prefix> -` or horizontal `<prefix> _`.
<img width="1440" alt="Screen Shot 2020-10-03 at 00 24 54" src="https://user-images.githubusercontent.com/48509017/94951636-dec3ff80-050e-11eb-85a2-e79ba8d49e00.png">

2. Maximized one of the pane `<prefix> +`.
<img width="1440" alt="Screen Shot 2020-10-03 at 00 25 09" src="https://user-images.githubusercontent.com/48509017/94951653-e683a400-050e-11eb-936c-ce806b2be9ef.png">

3. When you try to restore `<prefix> +`, it'll throw `Can't maximize with only one pane`.
<img width="1440" alt="Screen Shot 2020-10-03 at 00 25 46" src="https://user-images.githubusercontent.com/48509017/94951771-159a1580-050f-11eb-8cea-dcd2a20c3780.png">

4. When you try get back to first window, you can actually maximize the "dead pane".
<img width="1440" alt="Screen Shot 2020-10-03 at 00 28 22" src="https://user-images.githubusercontent.com/48509017/94951954-601b9200-050f-11eb-9a55-a0148dd4fe27.png">

<img width="1440" alt="Screen Shot 2020-10-03 at 00 29 04" src="https://user-images.githubusercontent.com/48509017/94952023-73c6f880-050f-11eb-9b36-6edb5fcfaaa4.png">

# Infos

- OS: MacOS Catalina 10.15.7
- Terminal: iTerm2
- Tmux 3.1b
- Using the latest `master` branch

**Comment by gpakosz** [comment]
Hey @willheryanto 

I'll look into it!

**Comment by gpakosz** [comment]
Hey @willheryanto 👋

Can you please try the `gh-415` branch?

**Comment by willheryanto** [comment]
Hi @gpakosz!

Confirmed `gh-415` fix the bug. Thank you for fast resolution! 😄

**Comment by gpakosz** [comment]
Thanks for the report @willheryanto 🤝
