### ISSUE TITLE
<prefix> e (edit configuration) does not work

### ISSUE THREAD

**Issue by cheunjm** [gpakosz/.tmux#416]
Cloned fresh repo, didn't change .tmux.conf nor .tmux.conf.local

Everything works fine, except when I try to edit .tmux.conf.local config by using <prefix> e, the terminal blinks for a second with a new tab /Users/.../.tmux.conf.local and goes away.

This is what I have from .tmux.conf:
```
bind e new-window -n "~/.tmux.conf.local" "sh -c '\${EDITOR:-vim} ~/.tmux.conf.local && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"
```

I have oh-my-zsh set up, and $EDITOR is set as mvim.

**Comment by gpakosz** [comment]
Hello @cheunjm 👋

From your description, I understand that  the `~/.tmux.conf.local` file doesn't exist?

**Comment by cheunjm** [comment]
Hi @gpakosz , thanks for the amazing work!

Sorry if I wasn't clear, both ~/.tmux.conf and ~/.tmux.conf.local exists, but <prefix> e is not working

**Comment by gpakosz** [comment]
I just tried to install MacVim with `brew install macvim` and `brew install macvim` and neither formula provides a `mvim` executable.

Does `mvim` exist on your system?

**Comment by gpakosz** [comment]
Ok I installed MacVim to reproduce your problem.

It's because `mvim` forks and opens the GUI

**Comment by cheunjm** [comment]
@gpakosz Thanks for testing it out for me. I'll try to swap mvim with vi and let you know if it helps

**Comment by gpakosz** [comment]
Can you please try the `gh-416` branch while keeping `EDITOR` set to `mvim`?

**Comment by cheunjm** [comment]
I can confirm that it now works on gh-416 while keeping the EDITOR set to mvim.

Thanks a lot!
