### ISSUE TITLE
tmux 2.4  bind-key changes

### ISSUE THREAD

**Issue by RedGreatApe** [gpakosz/.tmux#42]
In tmux version 2.4 there were some changes to key bindings (at least for vi-copy mode)
(I think commit: 76d6d3641f271be1756e41494960d96714e7ee58 for https://github.com/tmux/tmux)

of the ones that I am aware, is that the name for the key table 'vi-copy' was changed to 'copy-mode-vi' and to trigger the commands need to use the send-keys command

workaround (for users) is to rewrite the keybindings in .tmux.conf.local
examples:
unbind-key -T copy-mode-vi Escape
bind-key -T copy-mode-vi Escape send-keys -X cancel

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

**Comment by gpakosz** [comment]
Hello, I noticed they changed things in tmux `2.4`. I started looking into it but I decide how I want to handle both `< 2.4` and `>= 2.4` versions.

I'll keep you posted!

**Comment by gpakosz** [comment]
See branch `2.4`. That's very much WIP though since tmux folks doesn't seem to be done with new bindings implementation yet.
