### ISSUE TITLE
Status and command line position broken on WSL2 + ConEmu in Windows 

### ISSUE THREAD

**Issue by zeroarst** [gpakosz/.tmux#420]
without .tmux, tmux works ok.

with .tmux, after a few seconds (I think it redraws every 10 secs), the command line's position is broken.
Also if I keep pressing ctrl+b, the status line keeps adding, and removed after redrew,  the command line's position is also broken.
![2020-10-28 11_39_27-royliao@DESKTOP-M80IRA2_ ~](https://user-images.githubusercontent.com/1834837/97380513-eeb6df80-1912-11eb-9adc-06518b4df130.png)

**Comment by gpakosz** [comment]
Hello @zeroarst,

ConEmu and tmux are likely disagreeing on Unicode characters width, see https://github.com/gpakosz/.tmux#troubleshooting

In your `~/.tmux.conf.local` copy, try changing `tmux_conf_theme_prefix` to something else, e.g.
```
tmux_conf_theme_prefix=^
```

**Comment by zeroarst** [comment]
Thanks for the reply. I ended up using Cmder and it works fine.

**Comment by gpakosz** [comment]
Ok closing then.

FYI Windows Terminal also works.

**Comment by zeroarst** [comment]
Just a note for others who might come across the same issue.
Just tried Mintty and Windows Terminal both work perfect for tmux_conf_theme_prefix and displaying arrow on status bar.
https://github.com/gpakosz/.tmux/issues?q=arrow

With Cmder and ConEmu, it status line issue can be fixed by setting tmux_conf_theme_prefix to other characters.
but if you want to enable arrow, that cause issues.
![image](https://user-images.githubusercontent.com/1834837/97439973-931c3e80-1972-11eb-96da-9f2292878c24.png)
