### ISSUE TITLE
tmux don't delete text

### ISSUE THREAD

**Issue by gsbuosi** [gpakosz/.tmux#421]
tmux don't delete text instead the prompt is moved to right until stop to move it.

I've a short video where this behavior can appreciate it, how can I share it with?

**Comment by gpakosz** [comment]
@gsbuosi Hello 👋

Are you sure this is related to Oh My Tmux?

Do you reproduce the problem if you launch tmux with
```
$ tmux -L test -f /dev/null
```
?

**Comment by gsbuosi** [comment]
Hi Gregory,

With this command sequence the error is not reproduced.

**Comment by gpakosz** [comment]
Can you please make sure `TERM` is set to `xterm-256color` outside of tmux?

Also can you please tell me what's your OS and terminal emulator?

**Comment by gsbuosi** [comment]
My .zshrc haven't xterm-256color.

My OS is Linux | ElementaryOS, running io.elementary.terminal as terminal emulator

**Comment by gpakosz** [comment]
Try setting `TERM` outside of tmux then. `xterm-256color` is a good default in nearly all terminal emulators

**Comment by gsbuosi** [comment]
Thanks for the support Gregory, this ticket could be closed.

**Comment by gpakosz** [comment]
You're welcome
