### ISSUE TITLE
Empty `hostname_ssh` and `username_ssh`

### ISSUE THREAD

**Issue by LM1LC3N7** [gpakosz/.tmux#422]
Hello,

I use `fish` as primary shell and have clone your (*awesome*) work.
Everything seems to work except for `hostname` and `username_ssh`.

What I expect to see (from readme):
![image](https://user-images.githubusercontent.com/14235706/98099249-398ea500-1e87-11eb-8aff-3c83adfc3ddb.png)

What I actually see:
![image](https://user-images.githubusercontent.com/14235706/98099263-3e535900-1e87-11eb-8028-030520e7e42a.png)

I tried executing the following command that works:

```bash
cut -c3- ~/.tmux.conf | sh -s _username
lmilcent
```

Thanks for your help!

**Comment by gpakosz** [comment]
Hello @LM1LC3N7 👋

If you used `#{hostname_ssh}` and `#{username_ssh}`, then they are empty unless you're connecting to a remote host.

It seems my latest commit replaced `#{hostname}` to `#{hostname_ssh}` and `#{username}` to `#{username_ssh}` in my latest commit.

**Comment by LM1LC3N7** [comment]
Thanks for your fast answer!
Indeed I have updated `hostname_ssh` to `hostname` and it works well.
