### ISSUE TITLE
Battery Percentage Status Wrong

### ISSUE THREAD

**Issue by robbyki** [gpakosz/.tmux#424]
Thank you for an incredible project. Any idea why I would be getting a very wacky battery level percentage left value? Here is my value:
```
tmux_conf_theme_status_right=" #{prefix}#{pairing}#{synchronized}#(/usr/bin/tmux-mem) | #{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} | %R , %d %b | #{username}#{root} | #{hostname} "
```

![image](https://user-images.githubusercontent.com/1027357/98289957-f1e74680-1f76-11eb-87a6-d5dc7dc47be3.png)

**Comment by gpakosz** [comment]
Hello @robbyki 👋

That's indeed very wrong 🤯

Can you please tell me which OS you're using?

**Comment by robbyki** [comment]
sure -> `Red Hat Enterprise Linux Workstation release 7.8`

**Comment by gpakosz** [comment]
Just to be sure, does the problem happen if you remove the `#(/usr/bin/tmux-mem)` call?

**Comment by gpakosz** [comment]
Also, within tmux, can you please paste the output of
```
$  cut -c3- ~/.tmux.conf | sh -sx _battery_info
```
please?

**Comment by robbyki** [comment]
```
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ tr -cd '[:digit:].'
++ cut '-d ' -f2
++ awk -F . '{print $1 * 100 + $2}'
+ _tmux_version=301
+ command -v pkill
+ _battery_info
+ count=0
+ charge=0
+ case "$_uname_s" in
++ find /sys/class/power_supply -maxdepth 1 -iname '*bat*'
+ IFS=
+ read -r batpath
+ '[' -z /sys/class/power_supply/BAT0 ']'
+ grep -i -q device /sys/class/power_supply/BAT0/scope
++ grep -qi discharging /sys/class/power_supply/BAT0/status
++ echo true
+ discharging=true
+ bat_capacity=/sys/class/power_supply/BAT0/capacity
+ '[' -r /sys/class/power_supply/BAT0/capacity ']'
+++ cat /sys/class/power_supply/BAT0/capacity
++ awk -v charge=0 -v capacity=45143 'BEGIN { print charge + capacity / 100 }'
+ charge=451.43
+ count=1
+ IFS=
+ read -r batpath
+ '[' 1 -ne 0 ']'
++ awk -v charge=451.43 -v count=1 'BEGIN { print charge / count }'
+ charge=451.43
```

**Comment by gpakosz** [comment]
It seems there's something funny in the way the kernel reports battery info.

According to https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power, the value for `capacity` should be between `0` and `100`

![image](https://user-images.githubusercontent.com/553208/98291916-288b8400-1fac-11eb-9b22-778a8717d4bd.png)

Maybe you're hitting https://bugzilla.redhat.com/show_bug.cgi?id=1318845 ?

**Comment by robbyki** [comment]
Thanks for checking! clearly a bug. Just noticed that my system is showing 100% remaining after being on battery for about an hour.

**Comment by gpakosz** [comment]
See if you can upgrade the kernel
