### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1

### ISSUE THREAD

**Issue by thylakoids** [gpakosz/.tmux#425]
.tmux: 8c342ed
tmux version: 3.1b
run `cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > tmp.txt 2>&1` inside tmux , the last line is:
```
command too long
```

**Comment by gpakosz** [comment]
Hello @thylakoids 👋

Can you please paste the whole content of `$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration`?

**Comment by thylakoids** [comment]
`cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > tmp.txt 2>&1`:
[tmp.txt](https://github.com/gpakosz/.tmux/files/5527592/tmp.txt)

**Comment by gpakosz** [comment]
Can you please give me the exact CentOS version for reference?

The `gh-425` should fix it. Can you please give it a try?

**Comment by thylakoids** [comment]
Thanks for your reply.

1. The exact OS version:

    ```
    $ lsb_release -a
    LSB Version:	:core-4.1-amd64:core-4.1-noarch
    Distributor ID:	CentOS
    Description:	CentOS Linux release 7.6.1810 (Core)
    Release:	7.6.1810
    Codename:	Core
    ```

1. I tried `gh-425`, it does not work, the output was different through.

    `cut -c3- ~/.tmux.conf | sh -sx _apply_configuration > tmp.txt 2>&1`:
 
    [tmp.txt](https://github.com/gpakosz/.tmux/files/5529054/tmp.txt)

**Comment by gpakosz** [comment]
```
protocol version mismatch (client 7, server 8)
```

This means you have a tmux server process running that's older than the tmux client process.
Make sure you kill all tmux process and restart.

**Comment by thylakoids** [comment]
Thanks for the help, I will try it later(There are other users on this computer) and tell you the result.

**Comment by thylakoids** [comment]
After reinstall tmux, now it works boths on `gh-425` and `8c342ed`.

Thanks for the help.

**Comment by gpakosz** [comment]
Interesting that you don't face the command too long anymore 🤔

**Comment by thylakoids** [comment]
The new version of tmux is 2.8. Does this relate? 

I am not a sudo user on that server, it's hard for me to try every combination to debug the problem.
If I ever had the chance, I'll reproduce it and let you know.:smile:
