### ISSUE TITLE
Failed in WSL-ubuntu20.04

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [gpakosz/.tmux#427]
![image](https://user-images.githubusercontent.com/28779327/99063670-cb14ba00-25df-11eb-9731-9bdbeec165f6.png)

**Comment by gpakosz** [comment]
Hello @wangwenqiangGitHub 👋

This is a known problem cause by `tmux` and your terminal emulator disagreeing on Unicode symbols width.

Change
```
tmux_conf_theme_prefix="⌨"
```
To e.g.
```
tmux_conf_theme_prefix="^"
```

**Comment by wangwenqiangGitHub** [comment]
> Hello @wangwenqiangGitHub 👋
> 
> This is a known problem cause by `tmux` and your terminal emulator disagreeing on Unicode symbols width.
> 
> Change
> 
> ```
> tmux_conf_theme_prefix="⌨"
> ```
> 
> To e.g.
> 
> ```
> tmux_conf_theme_prefix="^"
> ```

Still failed in WSL

**Comment by gpakosz** [comment]
Then maybe the up arrow in `tmux_conf_theme_status_left`.

Really, you should just use Windows Terminal.

**Comment by wangwenqiangGitHub** [comment]
thanks， 

> Then maybe the up arrow in `tmux_conf_theme_status_left`.
> 
> Really, you should just use Windows Terminal.

This tmux has been used for many years, it is very easy to use, and the configuration is simple, thank you, I will switch to another system to use.

**Comment by gpakosz** [comment]
BTW If you don't like Windows Terminal there's also wsltty
