### ISSUE TITLE
How to change time zone in status bar?

### ISSUE THREAD

**Issue by counterbeing** [gpakosz/.tmux#429]
I'd like to use UTC as my time zone in the status bar. This might be useful to those that spend a lot of time looking at logs.

I looked around and found that you're passing `%R` as the format. But I can't figure out where to add the `TZ='utc'` to make the setting take. Maybe this could be a local variable that if blank results in your base system timezone?

Thanks!

P.S. Happy to make a PR, just not sure where to actually adjust the config. If you point that out, I'd happily add this backwards compatible feature.

**Comment by gpakosz** [comment]
Hello @counterbeing 👋

So you want the tmux status line to display time in UTC **but** you want the `date` command to display local time?

**Comment by gpakosz** [comment]
Anyways,

`%+R` corresponds to the time. 
`%d %b` correspond to day and months.
In fact `tmux` pass them to `strtfime(3)` (see the manual).

It doesn't seem possible to ask `tmux` to change the timezone but you can edit `tmux_conf_theme_status_right` in your `~/.tmux.conf.local` copy to replace `%d %b` by:
```
tmux_conf_theme_status_right="... #(date -u '%d %b') ..."
```
Hope that helps!

**Comment by counterbeing** [comment]
Awesome! Thanks so much @gpakosz! I've been using this tmux layout for years, and it's been amazing. Really brightens up a terminal! I'm going to give this a go tonight. I'll close this as it sounds like you've probably hit the nail on the head.

Thanks again!

**Comment by fakeProgrammer0** [comment]
> Anyways,
> 
> `%+R` corresponds to the time.
> `%d %b` correspond to day and months.
> In fact `tmux` pass them to `strtfime(3)` (see the manual).
> 
> It doesn't seem possible to ask `tmux` to change the timezone but you can edit `tmux_conf_theme_status_right` in your `~/.tmux.conf.local` copy to replace `%d %b` by:
> 
> ```
> tmux_conf_theme_status_right="... #(date -u '%d %b') ..."
> ```
> 
> Hope that helps!

Hi @gpakosz  I use `tmux_conf_theme_status_right=".. #(TZ=Asia/Shanghai date +'%R | %b %d') ... "` , but it doesn't work
