### ISSUE TITLE
Touch pad was  error

### ISSUE THREAD

**Issue by mylamour** [gpakosz/.tmux#43]
![image](https://cloud.githubusercontent.com/assets/12653147/21336641/b4d85496-c6a1-11e6-9ba8-195cd8241ab9.png)

when i use my touch pas to switch panel,  C-a + m is already.

**Comment by gpakosz** [comment]
I'm sorry I don't understand the problem you're having

**Comment by gpakosz** [comment]
ping @mylamour

**Comment by mylamour** [comment]
i use xshell to connect my server, and follow your tutorial to config my tmux, but when i try to use it with C-a + m , i touched my laptop touchpad, And something went wrong. 
I am really sorry for the late replay.

**Comment by gpakosz** [comment]
This seems to be related to the value of `TERM`. Make sure `TERM` is set to `xterm-256color` outside of `tmux`.

**Comment by gpakosz** [comment]
@mylamour I saw you reacted to my comment above with 👍 

Does it mean setting `TERM` to `xterm-256color` outside of `tmux` solved it?

**Comment by mylamour** [comment]
sometimes, it also has a problem, but now, it;s work well, i don't know what wrong with it, but my classmater has a same problem. also, when he restart tmux,  it's ok.  so , maybe 256 isn't the problem. and i can't realization it ,  but yours tmux.conf,  perfect. thanks.
