### ISSUE TITLE
does not swap window as expected in tmux 3.0a in ubuntu 20.04

### ISSUE THREAD

**Issue by akashrpo** [gpakosz/.tmux#430]
Hi,
I used to earlier swap the tmux window and place it in the proper position as needed. However, in ubuntu 20.04 tmux version 3.0a  when I use the command "swap-window -t +1" it swaps the window but my position stays in the fix position i.e my view does not swap along with my window i.e if I swap window 2 and 3 currently being on 2 window then after the swap of window 2 and 3 I stay at window 2 only and does not move to window 3 along with my window. This is not the case in my other Debian Buster with tmux version 2.8.
In ubuntu 20.04 tmux version 3.0a
![image](https://user-images.githubusercontent.com/64877812/100078509-9b7c7200-2e69-11eb-9520-20c379c32d3a.png)
After the swap
![image](https://user-images.githubusercontent.com/64877812/100078556-a8996100-2e69-11eb-8d01-892ba8ef4b41.png)
In Debian Buster tmux version 2.8
![image](https://user-images.githubusercontent.com/64877812/100078690-c8308980-2e69-11eb-89d3-31c68fc806aa.png)
After the swap (Expected Result)
![image](https://user-images.githubusercontent.com/64877812/100078725-d2528800-2e69-11eb-8927-1a06fc09c2e2.png)

**Comment by gpakosz** [comment]
Hello @akashrpo 👋

This looks like a tmux support question.
Oh My Tmux! has no influence on the behavior of `swap-window`.

Can you please launch tmux with
```
$ tmux -L test -f /dev/null
```
And confirm tmux `3.0a` has the same behavior without Oh My Tmux!?

**Comment by akashrpo** [comment]
Hi @gpakosz 
Yes, it is indeed a tmux support question.

Launching the tmux with
`$ tmux -L test -f /dev/null`
on both the OS produced different results as described above.

**Comment by akashrpo** [comment]
I have raised the issue in tmux repo:
https://github.com/tmux/tmux/issues/2479
