### ISSUE TITLE
opening nvim inside of tmux overwrites the tmux status bar

### ISSUE THREAD

**Issue by rhaynes74** [gpakosz/.tmux#431]
Hi folks, when using this setup, if I run nvim inside of tmux the status bar for tmux gets overwritten with the nvim status bar, and it doesn't revert after closing nvim.   Suggestions?

**Comment by gpakosz** [comment]
Hello @rhaynes74 👋

Can you verify the behavior doesn't happen when using the stock configuration, by e.g. launching tmux the following way:
```
$ tmux -L test -f /dev/null
```

Thank you

**Comment by rhaynes74** [comment]
Hi Gregory - thanks for the message.   Would be difficult for me to test again, I changed my config quite a bit.  Removing tmuxline seemed to fix it.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by gpakosz** [comment]
Hey @rhaynes74 👋

Alright. Feel free to reopen.
