### ISSUE TITLE
fim crashes in tmux with this configuration . works fine without configuration ..

### ISSUE THREAD

**Issue by ashutoshmjain** [gpakosz/.tmux#435]
fim ( image viewer) crashes when I try to open an image after showing the image for a second with following error message 

amj@desko:~$ fim Pictures/dp.jpg
ioctl VT_GETSTATE: Inappropriate ioctl for device (not a linux console?)
ioctl VT_GETSTATE: Inappropriate ioctl for device

This behavior is only if I have the configuration on. I bak out the .tmux.conf , everything works fine. 

fim is also working fine on console without tmux. 

I am using Ubuntu 18 (Mate) and booting to console. No GUI.

**Comment by gpakosz** [comment]
Hello @ashutoshmjain 👋

Can you please tell me the value of `TERM` outside and inside tmux when not using Oh My Tmux! please?

**Comment by ashutoshmjain** [comment]
@gpakosz Greg. - Thanks for the quick response . Really appreciate all the work !

$ echo $TERM = linux  #on terminal right after log in 
$ echo  $TERM = screen-256 colours  # inside the tmux.. 

btw , I tested setting up terminal to linux in .tmux.conf.local  .. but it  didn't work. fim still continued to crash with error .  When I bak-ed out .tmux.conf  ..everything worked well. Thus I raised the issue .. 

Thanks again for support  ..

**Comment by gpakosz** [comment]
Hey @ashutoshmjain 👋

Can you please keep `.tmux.conf` and comment out the following line
```
set -g default-terminal "screen-256color" # colors!
```
This is AFAIK the only thing Oh My Tmux! does different compared to launching tmux without it.

**Comment by ashutoshmjain** [comment]
done. .. 

Now $TERM inside tmux is `screen`  .. before tmux is same `linux` ,   but fim still crashed with same error.  I logged out and tested again just to make sure all the parameters are sourced fine. But no luck. ..

**Comment by gpakosz** [comment]
Hmm 🤔

And you're certain fim works within tmux without Oh My Tmux?

Indeed, when I launch it with a stock configuration `TERM` is `screen` by default
```
$ tmux -L test -f /dev/null
```

**Comment by ashutoshmjain** [comment]
Absolutely  .. just tested again after bak-ing out the .tmux.conf  ; it worked in all its glory :-)

**Comment by gpakosz** [comment]
Damn!

I don't have a setup ready at hand to test it myself

**Comment by ashutoshmjain** [comment]
btw. .. same  behaviour on nixOS as well. .. I have a lab machine dedicated to figuring out nix ... 

I will test it on Mac and let you know .. 

No hurry. ..its not critical issue .  I can always look at pics in second terminal  or detach the session for a minute. 

 Take your time when ever you get your hands  on fim.  - Thanks

**Comment by gpakosz** [comment]
So in fact I have a BunsenLabs Lithium VM in Virtualbox.

I booted in TTY mode and installed fim.
- Outside of tmux, displaying an image works fine
- Inside tmux, launched with `tmux -f /dev/null` to skip Oh My Tmux!, fim displays the image but I get to see the 2 errors
  ```
  ioctl VT_GETSTATE: Inappropriate ioctl for device (not a linux console?)
  ioctl VT_GETSTATE: Inappropriate ioctl for device
  ```
- Inside tmux, launched with Oh My Tmux!, fim displays the image
  ```
  ioctl VT_GETSTATE: Inappropriate ioctl for device (not a linux console?)
  ioctl VT_GETSTATE: Inappropriate ioctl for device
  ```

To make sure there are errors, I launched `$ fim ./image.jpg 2>/tmp/err.txt`

**Comment by gpakosz** [comment]
The difference I can observe, with and without Oh My Tmux!, seems to be the way the screen is redrawn after fim exits. But in any case, redirecting errors with `2 >/tmp/err.txt` tells me there are the same errors in both cases

**Comment by ashutoshmjain** [comment]
I repeated the on same lines ..

-  First - exactly same. 
- In second `tmux -f /dev/null ` , I get no error. Pic continues to display. 
- In third , I get the errors as shown by you and pic stops displaying . I can still pass commands to fim but pic doesn't come back.

**Comment by ashutoshmjain** [comment]
No worries  .. could be my machine.  Let me uninstall tmux and  try again .

**Comment by gpakosz** [comment]
Which version of tmux are you using btw?

Also when you redirect `stderr` to a log file, are there errors even when it apparently works?

**Comment by ashutoshmjain** [comment]
My tmux version is 2.6 . 

Yes , you are right. , the `stderr` shows same in both the cases  (with config and with ` -f  /dev/null `

**Comment by ashutoshmjain** [comment]
I guess , its a tmux issue then . In case of no config , the error doesn't show up on screen ; with config - it does .  Or may be I need to do something with the fim config to have it play nice with tmux  .. 

closing the issue  .. thanks a ton for your time . really appreciate .
