### ISSUE TITLE
Not sure how to enter VI copy mode

### ISSUE THREAD

**Issue by lemiesz** [gpakosz/.tmux#436]
So I am running `tmux next-3.3`. I type `ctrl + b [` to enter copy mode. However I am not sure how to use the VIM key bindings. 

Am i using the wrong version of tmux or is there something wrong with my configuration

**Comment by gpakosz** [comment]
Hello @lemiesz 👋

Did you `export VISUAL=vim` or `export EDITOR=vim` before launching tmux?

**Comment by lemiesz** [comment]
hey I did not. Should that go in my zshrc or in my .tmux.conf.

**Comment by gpakosz** [comment]
That would be `.zshrc`

**Comment by lemiesz** [comment]
Nice that fixed it. so i can use VI keybinds. 

Now how can I get those to be copied to my clipboard?

**Comment by lemiesz** [comment]
Is there anyway to navigate my terminal output using VI style binding, but not in copy mode. Rather to just edit what it is im writing in my command

**Comment by gpakosz** [comment]
Launch
```
$ tmux list-keys
```

To see all the bindings.
You can use `<prefix> + `H`, `<prefix>` + `J`, `<prefix>` + `K`, `<prefix>` + `L` to navigate panes, etc...
