### ISSUE TITLE
tmux immediately closes

### ISSUE THREAD

**Issue by strowk** [gpakosz/.tmux#437]
In my ~/.zshrc I'm running tmux like this 
```
[[ $TERM != "screen" ]] && exec tmux
```
Since I installed `.tmux`, it crashes every time.
Is it supposed to happen and I should run it somehow differently?

**Comment by gpakosz** [comment]
Hello @strowk 

I believe you created a fork bomb 💣

With Oh My Tmux, within tmux `TERM` is set to `screen-256color`.
You way want to try
```
[[ "$TERM" != "screen"* ]] && exec tmux
```

**Comment by Anu-bhav** [comment]
Hello all,

I don't really know if this will help you but I've been using this tricks for quite some time now. It autostarts tmux when I open my zsh shell. 

![image](https://user-images.githubusercontent.com/41940586/102673333-27ee2c00-41ad-11eb-852e-9230d7b75f5f.png)

**Comment by strowk** [comment]
ZSH_TMUX_AUTOSTART and plugin tmux did not work for me - it had an unintended consequences that whenever I start new terminal, instead of creating new session it apparently tried to join existing one. Very weird behavior - new window would start from some random folder (one of those I already had open before). 

Then I tried approach with asterisk and it worked, thanks!
