### ISSUE TITLE
Changing to config files in ~.config/tmux

### ISSUE THREAD

**Issue by ThSGM** [gpakosz/.tmux#439]
I prefer to keep my tmux configuration files in .config/tmux according to the [XDG Directory Specifications](https://wiki.archlinux.org/index.php/XDG_Base_Directory). Is there an easy way to do this? 

I suppose that we could go and replace all the hardcoded ~/.tmux.conf references in the .tmux.conf file but I was hoping for a more elegant way.

**Comment by gpakosz** [comment]
Hello @ThSGM 👋

I explored the idea of having the location of `.tmux.conf` and `.tmux.conf.local` configurable in the `gh200-gh221` branch.

To use it you would need to somewhat launch tmux the following way
```
$ TMUX_CONF=/foo/bar/tmux.conf TMUX_CONF_LOCAL=/foo/bar/tmux.conf.local tmux -f /foo/bar/tmux.conf
```
or
```
$ TMUX_CONF=/foo/bar/tmux.conf TMUX_CONF_LOCAL=/foo/bar/tmux.conf.local sh -c 'tmux -f $TMUX_CONF'
```

The branch is way behind `master`.
I wasn't sure I would ever merge it but I see tmux `3.2` is going to try `$XDG_CONFIG_HOME/tmux/tmux.conf` as well as `~/.config/tmux/tmux.conf`.

I'm still not sure how I'll handle this.

In the meantime, your best bet is to symlink `~/.tmux.conf`.

**Comment by elisiano** [comment]
By no mean an ideal solution but why not put the files where you prefer and create symlinks where this repo expects them?

**Comment by gpakosz** [comment]
@elisiano indeed the current solution is to clone the repository anywhere you want provided you:
- the `~/.tmux.conf` exists
- you have a valid `~/.tmux.conf.local` copy (or a symlink to a valid copy)

**Comment by ThSGM** [comment]
> By no mean an ideal solution but why not put the files where you prefer and create symlinks where this repo expects them?

@elisiano and @gpakosz 

Indeed this is what I currently do. It is just an effort to try to clean up the number of files in my home directory. With the XDG Specifications, it makes sense to shuffle everything into .config/tmux though.

**Comment by gpakosz** [comment]
> With the XDG Specifications, it makes sense to shuffle everything into .config/tmux though.

Well yes and no. Only tmux `3.2` understand XDG and it's a Linux thing only

**Comment by wren** [comment]
@gpakosz Are you sure about that? I'm on tmux 3.1c and on a Mac, and my config is at `~/.config/tmux/tmux.conf`. Everything is working as expected.

**Comment by gpakosz** [comment]
@wren You're right it's in `3.1c`

**Comment by wren** [comment]
@gpakosz Ah, that makes sense. There's also a bunch of terminal apps that I use that support XDG even though I'm on a Mac.

Anyway, I have a hastily modified version of your script in my dotfiles (in order to have a custom location). I've been thinking about sending over a proper PR to add the functionality. If that's something you might be open to, I'm happy to talk through implementation details to iron something out. Do you think that's something you'd be interested in?

**Comment by dycw** [comment]
> By no mean an ideal solution but why not put the files where you prefer and create symlinks where this repo expects them?

I believe the overall impetus is to keep a clean home directory.

**Comment by gpakosz** [comment]
Hey @wren 👋

I have multiple branches in the work so PR not really welcome as it's going to create more merge burden than anything else.
Thanks anyway

**Comment by wren** [comment]
> Hey @wren 👋
> 
> I have multiple branches in the work so PR not really welcome as it's going to create more merge burden than anything else.
> Thanks anyway

Ok, makes sense. Thanks for the response.

**Comment by jhogendorn** [comment]
I'd really like to see this happen as well. Happy to do a PR or whatever is appropriate to help.

**Comment by charlie39** [comment]
@gpakosz i am on 3.3a and i think ```tmux.conf.local``` is only referenced from tmux.conf so if all the hard links to t```mux.conf.local``` in ```tmux.conf``` are changed than it should work no? This is how it is working for me. as per the man page
Also Using simple variables to hold  file paths would be convenient. 

from the man page :

```

     -f file       Specify an alternative configuration file.  By default, tmux loads the system configuration file
                   from /etc/tmux.conf, if present, then looks for a user configuration file at ~/.tmux.conf,
                   $XDG_CONFIG_HOME/tmux/tmux.conf or ~/.config/tmux/tmux.conf.

                   The configuration file is a set of tmux commands which are executed in sequence when the server
                   is first started.  tmux loads configuration files once when the server process has started.  The
                   source-file command may be used to load a file later.
```

So tmux can see configuration files under ```$XDG_CONFIG_HOME/tmux``` or
```~/.config/tmux```

Once that's detected ```source-file ``` can be used to source the ```tmux.conf.local``` from
 ```tmux.conf```.

**Comment by gpakosz** [comment]
Can you please try the `gh-200+221+439+586` branch?

**Comment by latipun7** [comment]
I have tried, but it's not picked all my local config. Keybindings and some UI is picked. Tried with default `tmux.conf.local` is also still broken.

Default local config with `sed` hack:
![image](https://user-images.githubusercontent.com/20012970/211246684-504e3b8e-7717-49cb-9871-a45309b97d97.png)

Default local config with that branch:
![image](https://user-images.githubusercontent.com/20012970/211246990-de0bac00-9b26-4242-86d7-810b55169f56.png)

My local config with `sed` hack:
![image](https://user-images.githubusercontent.com/20012970/211246846-4fadb31a-2f47-408f-a182-694a652c8d3d.png)

My local config with that branch:
![image](https://user-images.githubusercontent.com/20012970/211246925-ddeffa97-4769-4f62-a4f3-48828780f902.png)

**Comment by gpakosz** [comment]
Hello @latipun7 👋

The `~/.local/share/` location is not a location supported by `tmux`, see the manual
```
     -f file       Specify an alternative configuration file.  By default, tmux loads the system configuration file from /usr/local/etc/tmux.conf, if present, then looks for a user configuration file at
                   ~/.tmux.conf, $XDG_CONFIG_HOME/tmux/tmux.conf or ~/.config/tmux/tmux.conf.
```

You may want to export `TMUX_CONF` and `TMUX_CONF_LOCAL` before launching tmux.

How are you launching tmux btw?

**Comment by gpakosz** [comment]
Hello @latipun7 

Can you please explain
- Where is the Oh my tmux! repository cloned
- Which symlinks are created

After having switched to the `gh-200+221+439+586` branch commit `1591e944012c7883f186c26e2ef846a177d96867`, and made sure `.tmux.conf` is unmodified can you please make sure all tmux processes are killed, then launch tmux, and then paste the result of
```
$ env | grep TMUX
```

Thank you

**Comment by latipun7** [comment]
- tmux version: tmux 3.3a
- `~/.local/share/oh-my-tmux` is just `git clone https://github.com/gpakosz/.tmux.git ~/.local/share/oh-my-tmux`
- I symlink only the main tmux config
  ```sh
  ln -s -f ~/.local/share/oh-my-tmux/.tmux.conf ~/.config/tmux/tmux.conf
  cp ~/.local/share/oh-my-tmux/.tmux.conf.local ~/.config/tmux/tmux.conf.local
  ```

`.tmux.conf` is unmodified.

```sh
❯ env | rg TMUX
TMUX=/tmp/tmux-1000/default,9781,0
TMUX_CONF=/home/latipun/.config/tmux/tmux.conf
TMUX_CONF_LOCAL=/home/latipun/.config/tmux/tmux.conf.local
TMUX_PANE=%0
TMUX_PLUGIN_MANAGER_PATH=/home/latipun/.local/share/tmux/plugins
ZSH_TMUX_CONFIG=/home/latipun/.config/tmux/tmux.conf
ZSH_TMUX_TERM=screen-256color
_ZSH_TMUX_FIXED_CONFIG=/home/latipun/.local/share/oh-my-zsh/plugins/tmux/tmux.extra.conf
```

**Comment by gpakosz** [comment]
Are you on the correct commit? You should see a `TMUX_EXECUTABLE` environment variable

**Comment by gpakosz** [comment]
After having launched tmux, can you please paste the output of the following command please?
```
$ cut -c3- "$TMUX_CONF" | sh -sx _apply_configuration
```

**Comment by latipun7** [comment]
I didn't set `TMUX_EXECUTABLE`, my tmux bin is at default `/usr/bin/tmux`

```sh
❯ cut -c3- "$TMUX_CONF" | sh -sx _apply_configuration
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ set +H
+ set +H
+ printf ''
+ sed -E s///
+ '[' -z /tmp/tmux-1000/default,12645,0 ']'
++ printf %s /tmp/tmux-1000/default,12645,0
++ cut -d, -f1
+ TMUX_SOCKET=/tmp/tmux-1000/default
+ '[' -z '' ']'
++ lsof -a -U -Fp /tmp/tmux-1000/default
++ perl -n -e 'print if s/^p//g'
+ TMUX_PID=
++ lsof -b -w -a -d txt -p '' -Fn
++ perl -n -e 'do {print; last } if s/^n((?:.(?!dylib$|so$))+)$/\1/g'
+ TMUX_EXECUTABLE=
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ '' -S /tmp/tmux-1000/default -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
main: line 184: : command not found
+ _tmux_version=
+ command -v pkill
+ _apply_configuration
++ tmux display -p '#{window_active}'
++ true
+ window_active=
+ '[' -z '' ']'
+ command -v perl
+ command -v sed
+ command -v awk
+ '[' -lt 240 ']'
main: line 1481: [: -lt: unary operator expected
+ command -v reattach-to-user-namespace
+ case "$_uname_s" in
+ _apply_24b
+ tmux_conf_theme_24b_colour=auto
+ _apply_theme
+ tmux_conf_24b_colour=true
+ '[' xtrue = xauto ']'
+ _is_true true
+ '[' xtrue = xtrue ']'
+ wait
+ apply_24b=true
+ '[' xtrue = xtrue ']'
+ case "$TERM" in
+ _apply_bindings
+ rm -f /tmp/log.txt
++ mktemp
+ exec
+ cfg=/tmp/tmp.4nQXu0kdKK
+ trap 'rm -f $cfg*' EXIT
+ tmux list-keys
+ '' -S /tmp/tmux-1000/default list-keys
+ grep -vF tmux.conf.local
+ grep -E 'new-window|split(-|_)window|new-session|copy-selection|copy-pipe'
main: line 184: : command not found
+ rm -f /tmp/tmp.4nQXu0kdKK
+ _apply_plugins
+ tmux_conf_update_plugins_on_launch=true
+ tmux_conf_update_plugins_on_reload=true
+ tmux_conf_uninstall_plugins_on_reload=true
+ tmux run -b 'cut -c3- "/home/latipun/.config/tmux/tmux.conf" | sh -s __apply_plugins "" "true" "true" "true"'
+ '' -S /tmp/tmux-1000/default run -b 'cut -c3- "/home/latipun/.config/tmux/tmux.conf" | sh -s __apply_plugins "" "true" "true" "true"'
main: line 184: : command not found

```

**Comment by gpakosz** [comment]
Do you have `lsof`?

**Comment by latipun7** [comment]
yes I do have `lsof`

**Comment by gpakosz** [comment]
If you installed it just know that explains why it was not working before. I need to figure out what to do when `lsof` is not available. I'll keep you posted

**Comment by latipun7** [comment]
I'm sorry, I didn't notice your full comments.
I didn't update to the `9149b2e89f718cbc019ece9526416e7d628f8c3b` commit yet.

After updating it, now it is works even without `TMUX_EXECUTABLE` set. Thank you :pray:

**Comment by gpakosz** [comment]
It now works because you installed `lsof` 🙂

**Comment by latipun7** [comment]
Oh my... lol, so that's a required for the config to run properly. I thought it was for debugging.

Dem right, after uninstalling `lsof`, the config back to broken state.

**Comment by latipun7** [comment]
- uninstalled `lsof`
- **didn't set `TMUX_EXECUTABLE`**
- update the commit
- run tmux and **Works!**

after launching tmux, the `TMUX_EXECUTABLE` is properly detected and set.
But I noticed that the weather widget is not updated, always empty string.

My weather widget at `tmux.conf.local`:
```sh
# weather() {
#   curl -fsm3 'wttr.in/Godean?format=%l:+%c%t+%w+(%m+%M)\n' || printf '\n'
#   # sleep 900  # commented out the sleep, still not updating
# }
```

**Comment by gpakosz** [comment]
Commit `394e06a4cb71ea3840b8e762771d28258b2ab32e` should fix custom variables.

**Comment by latipun7** [comment]
Thank you, @gpakosz :tada: 
**Now it works!** I didn't notice any problem.

**Comment by gpakosz** [comment]
Thanks @latipun7 for the tests, appreciated 👍

I'll do more testing myself and wait for the dust to settle before merging

**Comment by latipun7** [comment]
Yeah, thank you. I'll wait for this to be merged :rocket: 

Here's the complete env now (`ZSH_TMUX*` is from [`oh-my-zsh` plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux)):
```sh
❯ env | rg TMUX
TMUX=/tmp/tmux-1000/default,44186,0
TMUX_CONF=/home/latipun/.config/tmux/tmux.conf
TMUX_CONF_LOCAL=/home/latipun/.config/tmux/tmux.conf.local
TMUX_EXECUTABLE=/usr/bin/tmux
TMUX_PANE=%0
TMUX_PLUGIN_MANAGER_PATH=/home/latipun/.local/share/tmux/plugins
ZSH_TMUX_CONFIG=/home/latipun/.config/tmux/tmux.conf
ZSH_TMUX_TERM=screen-256color
_ZSH_TMUX_FIXED_CONFIG=/home/latipun/.local/share/oh-my-zsh/plugins/tmux/tmux.extra.conf
```
