### ISSUE TITLE
Clock does not switch to 12hr

### ISSUE THREAD

**Issue by NeckBeardPrince** [gpakosz/.tmux#44]
I have
`tmux_conf_theme_clock_style='12'`

But the clock is still in 24hr.
I know, dirty American.

**Comment by gpakosz** [comment]
Works for me. Did you try to reload the configuration? e.g. by hitting `<prefix> + r` ?

**Comment by gpakosz** [comment]
ping @NeckBeardPrince

**Comment by NeckBeardPrince** [comment]
Sorry, yup. Same thing.
It's okay, i'm going to redo a lot of my tmux setup and configs.
So maybe I missed something. Thanks for the help.
