### ISSUE TITLE
Functions can't be used in status

### ISSUE THREAD

**Issue by DennisGaida** [gpakosz/.tmux#442]
I'm trying to use `#{loadavg}` in `tmux_conf_theme_status_left`, but it's empty. When I manually insert `#(cut -d' ' -f1 < /proc/loadavg)` into the status it works flawlessly.

Similarly I tried `#{weather}` which results in a all-black statusbar.

What can I do to debug?

Using tmux 2.3 using the default config (and local config), just inserting loadavg or weather.

**Comment by gpakosz** [comment]
Hello @DennisGaida 👋

Apparently commit `788ffd8e6f51d268a502c94e563f5bef32bec882` brakes all this.

Can you please confirm using commit `41af713ff786ae2ea38ec52f7d7ef258ccd9fb9c` makes it work again?
```
$ cd ~/.tmux
$ git checkout 41af713ff786ae2ea38ec52f7d7ef258ccd9fb9c
```
Then hit `<prefix>` + `r`

**Comment by gpakosz** [comment]
Hey @DennisGaida 👋

I confirm commit `788ffd8e6f51d268a502c94e563f5bef32bec882` was a source of breakge.
I wanted to fix it rapidly.

On my side, I confirmed `#{weather}` is working with:
```
tmux_conf_theme_status_right=" #{prefix}#{mouse}#{pairing}#{synchronized}#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} #[inherit]#{weather}, %R , %d %b | #{username_ssh}#{root} | #{hostname_ssh} "
```
or
```
tmux_conf_theme_status_right="#{weather}"
```

Once you put `#{weather}` in `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right`, when you use `$ tmux show -gv status-left` or `$ tmux show -gv status-right` you should see it's bee replaced by `#(cut -c3- ~/.tmux.conf.local | sh -s weather)`.

If you don't have a `~/.tmux.conf.local` copy, custom variables won't work.

Feel free to open another issue if it still doesn't work for you.

**Comment by DennisGaida** [comment]
Yeap, works 😀 Nice quick fix. I'm using a `.tmux.conf.local`.
