### ISSUE TITLE
Variables introduced through tmp plugins can't be used

### ISSUE THREAD

**Issue by DennisGaida** [gpakosz/.tmux#444]
Plugins via tpm in general are working.

I'm trying to use variables introduced through plugins in the status and thought this might be related to #442 which is fixed, but the fix doesn't work for custom plugins (for me).

I tried two plugins:

- `set -g @plugin 'xamut/tmux-network-bandwidth'`
- `set -g @plugin 'tmux-plugins/tmux-cpu'`

Both `#{cpu_percentage}` (or `#{cpu_icon}`) & `#{network_bandwidth}` are empty for me in the status. Other built-in function (such as `loadavg`) work. This might be system related for me, but I don't know how to debug these issues.

**Comment by DennisGaida** [comment]
On further inspection I also get weird behaviors with custom variables in the `.tmux.config.local`.

I defined a test-function:
```
# loadavgadj() {
#   printf 'X'
# }
```

referencing it via `#{loadavgadj}` yields an empty result. Also `#{online}` always yields ✘, though executing it on the shell yields ✔
```
$  ping -t 1 -c 1 1.1.1.1 >/dev/null 2>&1 && printf 'y' || printf 'n'
y% 
```

**Comment by DennisGaida** [comment]
I got `set -g @plugin 'tmux-plugins/tmux-net-speed'` working, its variable `#{net_speed}` works. So maybe not a general problem, but plugin specific? Still yields the question why custom variables (such as my test-function) don't work.

**Comment by gpakosz** [comment]
Hello @DennisGaida 👋

When I take commit `4bf9263fbded44928ca9bf95333582503c73b584`, and I edit my `~/.tmux.conf.local` copy to have
```
set -g @plugin 'tmux-plugins/tmux-cpu'
```
and
```
tmux_conf_theme_status_right="#{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage}"
```
The plugin seems to work correctly.

For your custom function problem, can you please print the output of
```
$ tmux show -gv status-right
```
and
```
$ tmux show -gv status-left
```
?

**Comment by DennisGaida** [comment]
Alright, then those two plugins are simply not working on my config.

On the custom functions:
```
$ tmux show -gv status-right
#(/home/pi/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#(nice cut -c3- ~/.tmux.conf | sh -s _loadavg)#[fg=#080808,bg=#080808,none]#[fg=#8a8a8a,bg=#080808,none] #{@loadavgadj}
```
Really interesting that I see the  `sh -s _loadavg` there even though not configured?

and the relevant config
```
tmux_conf_theme_status_right=" #{loadavgadj} "
# -- custom variables ----------------------------------------------------------
# # /!\ do not remove the following line
# EOF
#
# loadavgadj() {
#   printf 'X'
# }
#
# weather() {
#   curl -m 1 wttr.in?format=1 # 2>/dev/null;
#   sleep 900 # sleep for 15 minutes, throttle network requests whatever the value of status-interval
# }
#
# online() {
#   ping -t 1 -c 1 1.1.1.1 >/dev/null 2>&1 && printf '✔' || printf '✘'
# }
#
# "$@"
# # /!\ do not remove the previous line
```

**Comment by gpakosz** [comment]
> Really interesting that I see the sh -s _loadavg there even though not configured?

Hmm your `loadavgadj()` function is clashing with builtin features. Best is to use another function name for your tests.

Can you please set
```
tmux_conf_theme_status_right="#{online}"
```
Reload the configuration and give me the output of
```
$ tmux show -gv status-right
```
?

**Comment by DennisGaida** [comment]
The statusbar (right) displays ✘ even though I am online.

```
$ tmux show -gv status-right
#(/home/pi/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#[fg=#080808,bg=#080808,none]#[fg=#8a8a8a,bg=#080808,none] #(cut -c3- ~/.tmux.conf.local | sh -s online)
```

**Comment by gpakosz** [comment]
Can you please do
```
$ tmux refresh-client
```
And see if the status bar changes.

Then paste the output of
```
$ tmux show -gv status-interval
```

And finally paste the output of
```
$ cut -c3- ~/.tmux.conf.local | sh -sx online
```

**Comment by DennisGaida** [comment]
Tried `$ tmux refresh-client` as well as `: refresh-client` which didn't seem to do much if anything.

```
$  tmux show -gv status-interval
10
```

what's going on with that extra `%` at the end? Same output as my above example `$  ping -t 1 -c 1 1.1.1.1 >/dev/null 2>&1 && printf 'y' || printf 'n'`
```
$  cut -c3- ~/.tmux.conf.local | sh -sx online
+ cut -d  -f1
+ grep model name /proc/cpuinfo
+ wc -l
+ :
+ online
+ ping -t 1 -c 1 1.1.1.1
+ printf ✘
✘%     
```

**Comment by gpakosz** [comment]
So it looks `ping -t 1 -c 1.1.1.1` is unreachable from your network.

Maybe the timeout is too low in which case you can try `-t 2` or more?

**Comment by gpakosz** [comment]
`1.1.1.1` is Cloud Flare's DNS IP address. You may want to use `8.8.8.8` which is Google's one. Or any other IP address on the internet

**Comment by DennisGaida** [comment]
Now I feel stupid. Yes, that does the trick:

`ping -t 10 -c 1 1.1.1.1 >/dev/null 2>&1 && printf '✔' || printf '✘'` works

Maybe adjust the example `.local` file to a larger timeout so others don't run into this simple problem?

Secondly: When renaming my function to something not including `loadavg`, e.g. `avgadj` it also works. This should be amended in the comment that you shouldn't name functions like existing functions.

For comepleteness here is the function I was trying to add that works now since this is a multi-core system:
```
# loadadj() {
#   echo "scale=2;$(cut -d' ' -f1 < /proc/loadavg) / $(grep 'model name' /proc/cpuinfo | wc -l)" | bc -l
# }
```

**Comment by gpakosz** [comment]
Good to know things are resolved.

I'll see how I refactor `.tmux.conf` and `.tmux.conf.local` to address the 2 problems
