### ISSUE TITLE
tmux wttr syntax

### ISSUE THREAD

**Issue by Rahulsharma0810** [gpakosz/.tmux#446]
I want a customized weather indicator

Traditionally this works,
```
#(curl -m 1 'wttr.in?format=3' 2>/dev/null; sleep 900)
```

I want to change this to the following format 

```
#(curl -m 1 'http://wttr.in/?format=%l:+%c+%t%20%w+%f%20%m+%M' 2>/dev/null; sleep 900)
```
But tmux reload giving syntax error.

**Comment by gpakosz** [comment]
Hello @Rahulsharma0810 👋

You have two options:
- either you use `#(curl -m 1 'http://wttr.in/?format=%%l:+%%c+%%t%%20%%w+%%f%%20%%m+%%M' 2>/dev/null; sleep 900)` and you double the `%` because in tmux configuration you have to escape `%` with `%`
- you update your `~/.tmux.conf.local` copy (see the provided sample one) and you adapt the `weather()` function to use your custom format and they you use `#{weather}`

**Comment by Rahulsharma0810** [comment]
I uncomment this https://github.com/gpakosz/.tmux/blob/master/.tmux.conf.local#L394

```/Users/rvs/.tmux.conf.local:394: unknown command: weather()```

**Comment by gpakosz** [comment]
You shouldn't remove the comments 🙂

The comments are what make the polyglot work:
- for tmux they are just comments
- but when you use `cut -c3- ~/.tmux.conf.local | sh` it removes the first 3 columns and it becomes a valid shell script

**Comment by Rahulsharma0810** [comment]
Great, 

now, I am using 
```# weather() {
#   curl -m 1 http://wttr.in/\?format="%%l:+%%c%%20+%%t%%20%%w+%%f%%20%%m+%%M\n" 2>/dev/null
#   sleep 900 # sleep for 15 minutes, throttle network requests whatever the value of status-interval
# }
```

importing like this

```
tmux_conf_theme_status_right="#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},}, #{weather}, %R , %d %b | #{username}#{root} | #{hostname} "

```
The curl response in following format
![image](https://user-images.githubusercontent.com/9934859/104300894-0a328f00-54ed-11eb-9720-1d76a6841e3b.png)

But strangely tmux status bar shows

![image](https://user-images.githubusercontent.com/9934859/104301037-33ebb600-54ed-11eb-9511-f7f6a2ae0342.png)

**Comment by gpakosz** [comment]
+18℃ you lucky!

**Comment by Rahulsharma0810** [comment]
```
# weather() {
#   curl -m 1 http://wttr.in/\?format="%l:+%c%20+%t%20%w+%f%20%m+%M\n" 2>/dev/null
#   sleep 900 # sleep for 15 minutes, throttle network requests whatever the value of status-interval
# }
```

This Works, no need to escape % I think because of "".

@gpakosz thanks for the quick reply and great configurations.

**Comment by gpakosz** [comment]
Sure,

If you use the local function in `~/.tmux.conf.local` no need to escape `%`. It's not because of the quoting but because this part is not interpreted by tmux itself.

If you use `#()`, then you need to escape `%` with `%%` though.
