### ISSUE TITLE
Reuse battery color palette for other components.

### ISSUE THREAD

**Issue by hongyilyu** [gpakosz/.tmux#447]
Hi, thanks for the wonderful tmux configurations!
I'm trying to reuse the battery color palette to display other numbers and change color based on input.
For example, I would like to display CPU usage and memory usage using tpm and let the color change based on the current usage.
Is there an easy way to output color based on number like what you do for battery percentage? 
Thanks
<img width="462" alt="image" src="https://user-images.githubusercontent.com/21372855/104521990-df127300-55b2-11eb-9753-56cdb6858577.png">

**Comment by techcaotri** [comment]
@LHY-iS-Learning : this might be "a little bit" late to your question but I manage to get the color for CPU usage and GPU usage by using the variables output by TPM and use it on `tmux_conf_theme_status_right`  variable of `tmux.conf.local` as below:
```
...
tmux_conf_theme_status_right="CPU: #{cpu_fg_color}#[bold]#{cpu_percentage}#[fg=default,nobold] #{cpu_temp_fg_color}#{cpu_temp}#[fg=default] GPU:#{gpu_fg_color}#[bold]#{gpu_percentage}#[fg=default,nobold] #{gpu_temp_fg_color}#{gpu_temp}#[fg=default], #{prefix}#{mouse}#{pairing}#{synchronized}#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} "
...
```
