### ISSUE TITLE
Colours for battery_percentage based on charge

### ISSUE THREAD

**Issue by Smirl** [gpakosz/.tmux#450]
# Summary 

This might be a **new feature request** as I can't see how it would be done with configuration.

It would be nice to be able to set the colour of the battery percentage based on the charge. Red low charge, Green fully charged, etc.

I know there are various options such as the battery_vbar, etc. But it would be nice to know when there is low battery.

**Comment by Smirl** [comment]
This isn't super urgent as the `battery_vbar` does an ok job of the rough amount of battery.
![image](https://user-images.githubusercontent.com/5792870/105631043-48f90b00-5e44-11eb-82c1-14df7270e1fb.png)

**Comment by gpakosz** [comment]
Hello @Smirl 👋

That's what the default configuration do
![image](https://user-images.githubusercontent.com/553208/105638345-7361bd00-5e72-11eb-8b3f-c4aa5333a79e.png)

It's a bit of a hack though at the text right after the bar will inherit the color of the charge level

**Comment by Smirl** [comment]
Ah cool. Putting `battery_vbar` before `battery_percentage` did the trick.

```diff
diff --git a/.tmux.conf.local b/.tmux.conf.local
index 8fc9f53..35d4dfe 100644
--- a/.tmux.conf.local
+++ b/.tmux.conf.local
@@ -228,7 +228,7 @@ tmux_conf_theme_right_separator_sub="\uE0B3"  #   PowerlineSymbols.otf font, see
 #     - #{username}
 #     - #{username_ssh}
 tmux_conf_theme_status_left=""
-tmux_conf_theme_status_right="#{prefix}#{mouse}#{pairing}#{synchronized} | #(kubectl config current-context) | #(kubectl nss) | ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,} , #{loadavg} | %Y-%m-%d , %R | #{?battery_status,#{battery_status},}#{?battery_percentage, #{battery_percentage},} #{battery_vbar}"
+tmux_conf_theme_status_right="#{prefix}#{mouse}#{pairing}#{synchronized} | #(kubectl config current-context) | #(kubectl nss) | ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,} , #{loadavg} | %Y-%m-%d , %R | #{?battery_status,#{battery_status},} #{battery_vbar}#{?battery_percentage, #{battery_percentage},}"
```
