### ISSUE TITLE
Saving sessions

### ISSUE THREAD

**Issue by Flamme13** [gpakosz/.tmux#452]
Is it possible to add https://github.com/tmux-plugins/tmux-resurrect or something similar to the default config?
Perhaps there is another solution to the problem of saving sessions? For example, as in vim commands `mks` and `so`.

**Comment by gpakosz** [comment]
Hello @Flamme13 👋

Oh my tmux! now comes with TPM integration. Look at the sample `.tmux.conf.local` file and follow the instructions to enable plugins

**Comment by Flamme13** [comment]
I apologize and thanks for the tip. I did not notice this October commit.

**Comment by gpakosz** [comment]
Hwy @Flamme13 👋

No worries. Tell me how it goes!

**Comment by gpakosz** [comment]
Hey @Flamme13 👋

How is it going?

**Comment by Flamme13** [comment]
Hi, everything is fine. Thanks for your help and the config in general.

**Comment by gpakosz** [comment]
You're welcome. Happy tmuxing!
