### ISSUE TITLE
printing control character

### ISSUE THREAD

**Issue by florian-hild** [gpakosz/.tmux#454]
In my terminal session this character "^[OP" is printing once a while. Often four times like "^[OP^[OP^[OP^[OP" specially when I'm in the vim editor and then the help.txt opens.
I can reproduce this character if I write "read" command in the terminal and then press num button on the keyboard.

I measured the time and it looks like it prints this every 4 minutes
`hild@vmhild:~$ date && read`
`Do 11. Feb 15:05:26 CET 2021`
`^[OP^[OP^[OP^[OP`
`hild@vmhild:~$ date && read`
`Do 11. Feb 15:09:28 CET 2021`
`^[OP^[OP^[OP^[OP`
`hild@vmhild:~$ date`
`Do 11. Feb 15:13:33 CET 2021`

Does anybody have an idea where this comes from?

**Comment by gpakosz** [comment]
Hello @florian-hild 👋

Does it happen outside of tmux?

Or does it happen with stock tmux configuration?
```
$ tmux -L test -f /dev/null
```

**Comment by florian-hild** [comment]
I just tried it and the problem appears not outside of tmux, but it also appears with stock settings

**Comment by florian-hild** [comment]
That's strange because I never had this with tmux in the past. Maybe there is something with my environment.
I'm using at the moment a minimal arch linux installation without gui. There is almost nothing installed on it.

**Comment by gpakosz** [comment]
@florian-hild Curious about the reason but sounds external to Oh My Tmux!
