### ISSUE TITLE
Unable to escape copy-mode-vi

### ISSUE THREAD

**Issue by dycw** [gpakosz/.tmux#456]
Hi, thanks for a great plugin! After finding this, I threw away 5 years of my own configuration and kept <50 lines in a `.tmux.conf.local` ([link](https://github.com/dycw/dotfiles/blob/9ff4209b1630476196899ac3f6bfdb92bf427af4/home/.tmux.conf.local)).

I'm having trouble *reliably* escaping copy-mode. I understand it's meant to be the `Escape` key? For example: 

```bash
09:47 ~
❯
```

Hit `prefix` then `Enter` to enter copy-mode (notice it says `[0/3]` to the right):

```bash
09:47 ~                                                                                                            [0/3]
❯
```

Navigate + visual mode to select some text. Hit `y` to yank. Hit `Escape`; nothing.

Am I doing something wrong?

Setups tried: Alacritty on Ubuntu, GNOME terminal on Ubuntu, Alacritty on WSL, default Ubuntu terminal on WSL.

**Comment by gpakosz** [comment]
Hello @dycw 👋

Please have a look at
```
$ tmux list-keys | grep cancel
```

Also make sure the plugins you enabled ton interfere with copy-mode.

**Comment by dycw** [comment]
Hi @gpakosz , I have narrowed down my problems to my use of Alacritty. I am experiencing more issues that just `tmux`.

Thank you, I will close this now.
