### ISSUE TITLE
After kernel update to my OS this tmux confugration crashes

### ISSUE THREAD

**Issue by lemiesz** [gpakosz/.tmux#457]
For the past year or so I have been using this configuration with tmux 2.8. It worked fine, however after a system update to my machine today, it has stooped working.  

I get the notification "this configuration required tmux 2.3+". 

Anyone know whats up?

**Comment by lemiesz** [comment]
Even downgrading to 2.3 seems to give me the same message

**Comment by gpakosz** [comment]
Hello @lemiesz 👋

Can you please tell me which operating system you're using and the tmux version?
```
$ tmux -V
```

Then
```
$ cut -c3- ~/.tmux.conf | sh -sx
```

**Comment by lemiesz** [comment]
Im on Amazon Linux 2 which is like a 

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2:-:internal"
HOME_URL="https://amazonlinux.com/"
VARIANT="internal"
``` 

tmux -V  
```
tmux.orig 2.8
```
Although I also have a `tmux 2.3` version installed that does the same thing. 
 
 
 The second command gives me 
 ```
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ tr -cd 0123456789.
++ cut '-d ' -f2
++ awk -F . '{print $1 * 100 + $2}'
+ _tmux_version=2
+ command -v pkill
 ```

**Comment by gpakosz** [comment]
```
$ tmux -V
tmux.orig 2.8
```
So you aliased or symlinked `tmux`?

In any case, can you please try the `gh-457` branch? This should improve version detection and fix the problem you're facing.

**Comment by gpakosz** [comment]
Hey @lemiesz 👋

Did you find the time to give the `gh-457` branch a try by chance?

**Comment by lemiesz** [comment]
Sorry i kept forgetting to do this. Yes that worked thanks alot
