### ISSUE TITLE
battery info shows more than 100%

### ISSUE THREAD

**Issue by fujisan43** [gpakosz/.tmux#460]
Battery info shows more than 100%.
[https://imgur.com/gallery/yQLAhwU](https://imgur.com/gallery/yQLAhwU)

**Comment by gpakosz** [comment]
Hello @fujisan43 👋

What's your OS?

**Comment by fujisan43** [comment]
Hi,
I use Fedora install in WSL (Windows Subsystem for Linux).

**Comment by gpakosz** [comment]
Can you please tell me what's in `/sys/class/power_supply`?

Also, can you please run
```
$ cut -c3- ~/.tmux.conf | sh -sx _battery_info
```
And paste the result here?

**Comment by fujisan43** [comment]
Right now my battery is full and tmux shows 156%. It doesn't go above 156.
And when the battery level is below 100%, tmux shows the correct level.

❯ ll /sys/class/power_supply/*/*
lrwxrwxrwx 1 root root 0 Mar 5 15:28 /sys/class/power_supply/AC1/device ->
../../../ACPI0003:00
-r--r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/AC1/online
lrwxrwxrwx 1 root root 0 Mar 5 15:28 /sys/class/power_supply/AC1/subsystem
-> ../../../../../../../class/power_supply
-r--r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/AC1/type
-rw-r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/AC1/uevent
-rw-r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/BAT1/alarm
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/capacity
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/capacity_level
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/cycle_count
lrwxrwxrwx 1 root root 0 Mar 5 15:28 /sys/class/power_supply/BAT1/device ->
../../../PNP0C0A:00
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/energy_full
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/energy_full_design
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/energy_now
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/manufacturer
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/model_name
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/power_now
-r--r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/BAT1/present
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/serial_number
-r--r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/BAT1/status
lrwxrwxrwx 1 root root 0 Mar 5 15:28 /sys/class/power_supply/BAT1/subsystem
-> ../../../../../../../class/power_supply
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/technology
-r--r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/BAT1/type
-rw-r--r-- 1 root root 4.0K Mar 5 15:28 /sys/class/power_supply/BAT1/uevent
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/voltage_min_design
-r--r--r-- 1 root root 4.0K Mar 5 15:28
/sys/class/power_supply/BAT1/voltage_now
❯ more /sys/class/power_supply/BAT1/capacity
156
❯ more /sys/class/power_supply/BAT1/capacity_level
Normal


❯ cut -c3- ~/.tmux.conf | sh -sx _battery_info
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ tr -cd 0123456789.
++ cut '-d ' -f2
++ awk -F . '{print $1 * 100 + $2}'
+ _tmux_version=301
+ command -v pkill
+ _battery_info
+ count=0
+ charge=0
+ case "$_uname_s" in
++ find /sys/class/power_supply -maxdepth 1 -iname '*bat*'
+ IFS=
+ read -r batpath
+ '[' -z /sys/class/power_supply/BAT1 ']'
+ grep -i -q device /sys/class/power_supply/BAT1/scope
++ grep -qi discharging /sys/class/power_supply/BAT1/status
++ echo false
+ discharging=false
+ bat_capacity=/sys/class/power_supply/BAT1/capacity
+ '[' -r /sys/class/power_supply/BAT1/capacity ']'
+++ cat /sys/class/power_supply/BAT1/capacity
++ awk -v charge=0 -v capacity=156 'BEGIN { print charge + capacity / 100 }'
+ charge=1.56
+ count=1
+ IFS=
+ read -r batpath
+ '[' 1 -ne 0 ']'
++ awk -v charge=1.56 -v count=1 'BEGIN { print charge / count }'
+ charge=1.56

**Comment by gpakosz** [comment]
Looks like WSL report wrong battery charge and capacity.

According to https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power, capacity should be between `0` and `100`.

**Comment by gpakosz** [comment]
The `gh-460` branch should work around the problem. Can you please try it?

**Comment by fujisan43** [comment]
Yes, it works now.

Thank you.

**Comment by gpakosz** [comment]
Ok I will merge the branch. That's just a work around though
