### ISSUE TITLE
tmux version parsing proposal

### ISSUE THREAD

**Issue by antenore** [gpakosz/.tmux#462]
First of all thanks so much for your work.

From time to time tmux is released with strange version prefixes, like now, on fedora, is `tmux next-3.3`.

This is far from being your problem, whoever release tmux  (up or downstream), should be consistent with the versioning naming convention.

Maybe there's a simple solution that may serve your version parsing needs

```bash
 $ echo 'tmux next-3.3' | awk -F'[^0-9]*' '{print ($2+0) * 100}'
300
$ tmux -V | awk -F'[^0-9]*' '{print ($2+0) * 100}'
300
```

I didn't test on all platform, but that awk syntax should work everywhere (tested on AIX, Solaris and a bunch of Linux distros).

Finally, I won't submit a PR because this change is ridiculously too small to claim anything :-)

Encore merci!

**Comment by antenore** [comment]
I forgot the `.`

```
$ echo 'tmux next-3.3' | awk -F'[^0-9\.]*' '{print ($2+0) * 100}'
330
```

:-p

**Comment by gpakosz** [comment]
Hello @antenore 👋

Thanks for spotting the regression introduced by commit `8aefa1e79809de7f69259ea91299313cca7579f7`.

Your solution doesn't work when people renamed the tmux executable to e.g. `tmux.orig`. I created branch `gh-462`.

**Comment by antenore** [comment]
Nice! Thanks
