### ISSUE TITLE
How can I disable tmux_conf_theme_mouse

### ISSUE THREAD

**Issue by CVirus** [gpakosz/.tmux#467]
Good day and thanks for this fantastic effort.

 I was wondering how can I disable `tmux_conf_theme_mouse` ? If I set it to `""`; the default `↗` is used and if I set it to ` `, it takes unnecessary space.

Thanks a lot in advance!

**Comment by gpakosz** [comment]
Hello @CVirus 👋

If you want no mouse indicator, the proper way is to remove `#{mouse}` from `tmux_conf_theme_status_right` in your `~/.tmux.conf.local` copy.

**Comment by CVirus** [comment]
Thanks a lot! Now I feel really stupid :D

**Comment by gpakosz** [comment]
That was not my intention! Happy Oh my tmuxing!
