### ISSUE TITLE
<'cut -c3- ~/.tmux.conf | sh -s _battery' not ready> in status bar after update tmux to 3.2

### ISSUE THREAD

**Issue by slawqo** [gpakosz/.tmux#470]
I have such error instead of battery bar in the status bar after last upgrade of tmux to 3.2 on Arch Linux

**Comment by gpakosz** [comment]
Hello @slawqo 👋

I can't reproduce the issue. Can you please make sure you restarted all tmux processes after upgrading?

**Comment by slawqo** [comment]
Hi,
Thx for checking that. I did restart all tmux sessions for sure. But now I don't that issue anymore. So it can be closed. Thx :)
