### ISSUE TITLE
Logging Issue using tmux-logging

### ISSUE THREAD

**Issue by Anu-bhav** [gpakosz/.tmux#471]
Hi, 

I want to log the entire tmux session with all the different windows and panes, however when i'm using the tmux-logging plugin, it is logging only the pane that I run the command <prefix>+shift+p

For each new pane I have to run the command again and it created many different files. Can you help me figure out how to log the entire session.

**Comment by gpakosz** [comment]
Hekki @Anu-bhav 👋

I'm sorry I don't use `tmux-logging`. Please reach out to the plugin author(s).

**Comment by Anu-bhav** [comment]
Hi @gpakosz 

Thank you anyway and I just want to say that I've been a fan of this project since I started using tmux about 2yrs ago. Thank you for the great work.
