### ISSUE TITLE
prefix or mouse status does not appear in status bar

### ISSUE THREAD

**Issue by fujisan43** [gpakosz/.tmux#474]
When I hit `C-a`, the symbol ⌨ (U+2328) should appear in place of `#{prefix}` on the right side of the status bar, but it doesn't.
Same problem when I hit `C-a m` to switch to mouse mode, the symbol ↗ (U+2197) should also appear in place of `#{mouse}`.
Is there anything that I should configure so they can appear correctly?

**Comment by gpakosz** [comment]
Hello @fujisan43 👋

What version of tmux are you using?

When you type
```
$ cut -c3- ~/.tmux.conf | sh -s _decode_unicode_escapes '\u2197'
```
in your terminal, is the `↗` symbol being displayed?

Also can you please paste the output of
```
$ tmux show -gv status-right
```

**Comment by fujisan43** [comment]
Hi Gregory

Here is the info you asked.

$ tmux -V
tmux 3.1c

Here I have an empty line followed by the arrow and %
$ cut -c3- ~/.tmux.conf | sh -s _decode_unicode_escapes '\u2197'

↗%

$ tmux show -gv status-right
#(printf '\n'; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime;
sleep 60; done)#[fg=#080808,bg=#080808,none]#[fg=#8a8a8a,bg=#080808,none]
#[fg=#080808]#[bg=none]#[none]#{?client_prefix,⌨ ,
}#[fg=#080808]#[bg=none]#[none]#{?mouse,↗ ,
}#[fg=none]#[bg=none]#[none]#{?session_many_attached,⚇
,}#[fg=none]#[bg=none]#[none]#{?pane_synchronized,⚏
,}#{?battery_status,#{battery_status},}#{?battery_bar,
#{battery_bar},}#{?battery_percentage, #{battery_percentage},}
#[fg=#8a8a8a,bg=#080808,none] %R #[fg=#8a8a8a,bg=#080808,none] %d %b
#[fg=#d70000,bg=#080808,none]#[fg=#e4e4e4,bg=#d70000,none] #(cut -c3-
~/.tmux.conf | sh -s _username #{pane_tty} false
#D)#[fg=none]#[bg=none]#[bold,blink]#{?#{==:#(cut -c3- ~/.tmux.conf | sh -s
_username #{pane_tty} #D),root},!,}#[default]#[fg=#e4e4e4,bg=#d70000,none]
#[fg=#e4e4e4,bg=#d70000,none]#[fg=#080808,bg=#e4e4e4,bold] #(cut -c3-
~/.tmux.conf | sh -s _hostname #{pane_tty} false false #h #D)

**Comment by gpakosz** [comment]
What happens if you do

```
$ tmux set -g status-right '{?client_prefix,⌨ ,}{?mouse,↗ ,}'
```

Does hitting prefix show the keyboard symbol in status right?

**Comment by fujisan43** [comment]
![image](https://user-images.githubusercontent.com/10160128/116243385-2f2ed300-a767-11eb-9091-1910c24f19e3.png)

**Comment by fujisan43** [comment]
and hitting `C-a` does nothing.

**Comment by gpakosz** [comment]
I'm sorry this should have been
```
$ tmux set -g status-right '#{?client_prefix,⌨ ,}#{?mouse,↗ ,}'
```

**Comment by fujisan43** [comment]
![image](https://user-images.githubusercontent.com/10160128/116247176-e11bce80-a76a-11eb-8320-72e8fabb9191.png)

nothing appears.

**Comment by gpakosz** [comment]
> nothing appears

Yes and hitting the prefix key should display the keyboard symbol

**Comment by fujisan43** [comment]
yes, you're right.

**Comment by gpakosz** [comment]
So it works?

**Comment by fujisan43** [comment]
No, when I reload with `C-a r`, hitting the prefix does not appear.
I think the problem is the shell i'm using, zsh.
I don't have the problem with bash. Are you using bash?
[see here](https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol)

**Comment by fujisan43** [comment]
Here it doesn't work (zsh)
![image](https://user-images.githubusercontent.com/10160128/116260702-352cb000-a777-11eb-9018-8fb4f9ab223e.png)

Here it works (bash)
![image](https://user-images.githubusercontent.com/10160128/116260726-3bbb2780-a777-11eb-99cd-c73c73ff15b7.png)

It's the only difference I see.

**Comment by gpakosz** [comment]
I'm using zsh as well

**Comment by gpakosz** [comment]
Your uptime is 24 days, did you upgrade tmux without relaunching the server? Can you try starting all tmux processes over?

**Comment by fujisan43** [comment]
No killing all tmux processes does not solve the problem.

**Comment by fujisan43** [comment]
Ok I made a mistake when setting the foreground color.
Black on black gives nothing! 
Sorry! :confounded:

**Comment by gpakosz** [comment]
😅 I let you close the issue then
