### ISSUE TITLE
View .sxl file in MacOS+iterm2+tmux

### ISSUE THREAD

**Issue by mikewebb70** [gpakosz/.tmux#475]
Hey Gregory and others..HI!

I’m trying to view .sxl file output from  'curl v3.wttr.in/Western+Australia.sxl' in a oh-my-tmux session and it doesn’t render.  In a plain zsh+iterm2 session it views fine.

The following work fine in both iterm2 and iterm2+tmux: ‘
 curl wttr.in/Albany+Western+Australia' 
 curl v2d.wttr.in/Albany+Western+Australia
 curl v2.wttr.in/Albany+Western+Australia

Project page https://github.com/chubin/wttr.in

Other then that, loving my terminal sessions with your tmux bling.  Awesome work thanks

Mike

**Comment by gpakosz** [comment]
Hello @mikewebb70 👋

Works for me 🤷‍♂️
![image](https://user-images.githubusercontent.com/553208/116273584-2992b680-a782-11eb-9be6-c5329caef856.png)

Please make sure `TERM` is set to `xterm-256color` outside of tmux and to `screen-256color` inside tmux.

**Comment by mikewebb70** [comment]
Yep 'curl wttr.in/Albany+Western+Australia' works fine for both you and me.  The one that is the issue is viewing .sxl files that are generated by:

curl v3.wttr.in/Western+Australia.sxl

works fine in iterm2+zsh  but doesn't render in tmux.

cheers

**Comment by gpakosz** [comment]
Oh well, tmux doesn't support Sixel. See https://github.com/tmux/tmux/issues/1613

**Comment by mikewebb70** [comment]
I had just loaded a vanilla tmux session and had the same results.  Was googling the issue but your swift reply answered everything.  This is an issue with underlying tmux.  Closing this issue 

keep up the good work
