### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127 

### ISSUE THREAD

**Issue by rumanbsl** [gpakosz/.tmux#478]
After doing the usual installation process, this is what I get when tmux loads. when I run `cut -c3- ~/.tmux.conf | sh -s _apply_configuration` manually then It works. I am running tmux version `3.2`

**Comment by gpakosz** [comment]
Hello @rumanbsl 👋

Can you please verify you're running the latest commit (unmodified) from the `master` branch?

And can you please tell me which OS and shell you're using?

**Comment by rumanbsl** [comment]
Hi, after a restart, the problem does not seem to persist anymore. Strange that, it needed a system restart. Nonetheless, it is working now 🎉. 

Thank you very much for replying this quickly and thank you a lot for such a great tool. Closing...
