### ISSUE TITLE
<'printf ' '; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done' not ready>

### ISSUE THREAD

**Issue by DennisGaida** [gpakosz/.tmux#479]
Running version tmux 2.8. I did not have this problem with the exact same configuration with tmux 2.3

I get the following line in the status bar: `<'printf ' '; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done' not ready>    | 17:21 [...]`

Checking line 1273 I see 
```
1273 #       elif [ $_tmux_version -gt 240 ]; then
1274 #         status_right="#(printf '\n'; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep $interval; done)$status_right"
1275 #       else
1276 #         status_right="#(nice cut -c3- ~/.tmux.conf | sh -s _uptime)$status_right"
```
Apparently my previous version of tmux was using the version at line 1276, now I am using line 1274 which produces the error. However I don't know how to debug the issue any pointers what can be the problem?

**Comment by gpakosz** [comment]
Hello @DennisGaida 👋

Can you please make sure you restarted the tmux server process after upgrading? The best way to do so is to kill all tmux processes. Rebooting will also do it

**Comment by DennisGaida** [comment]
This is actually two separate systems. I restarted the tmux server process multiple times / rebooted as well.

When I comment out (or better said `$_tmux_version -gt 290` in line 1273) I don't get the stated error. Line 1274 is causing the error but again I don't know what I can do to debug.

**Comment by gpakosz** [comment]
I can't reproduce on Debian Buster with tmux 2.8.

What's your OS?

**Comment by DennisGaida** [comment]
Also Debian buster, though `Raspbian GNU/Linux 10 (buster)`

**Comment by gpakosz** [comment]
Well the `printf` call is there to give output, tmux shouldn't display a not ready message

**Comment by DennisGaida** [comment]
`#(/home/pi/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#(printf ' '; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done)#[fg=#080808,bg=#080808,none]#[fg=#8a8a8a,bg=#080808,none] #[fg=none]#[bg=none]#[none]#{?client_prefix, , }#[fg=none]#[bg=none]#[none]#{?mouse, , }#[fg=none]#[bg=none]#[none]#{?session_many_attached,P ,}#[fg=none]#[bg=none]#[none]#{?pane_synchronized,⚏ ,} #[fg=#8a8a8a,bg=#080808,none]| %R #[fg=#8a8a8a,bg=#080808,none]| 猪 #(cut -c3- ~/.tmux.conf.local | sh -s cpu)#(cut -c3- ~/.tmux.conf.local | sh -s mem)#[fg=#8a8a8a,bg=#080808,none]| #(/home/pi/.tmux/plugins/tmux-weather/scripts/weather.sh) #[fg=#8a8a8a,bg=#080808,none]| #{?@uptime_d, #{@uptime_d}d,}`

**Comment by gpakosz** [comment]
Can you please try to disable the continuum plugin?

**Comment by DennisGaida** [comment]
Disabled as-in not load them anymore? I have removed most of them from the status:

status-right: `#(/home/pi/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#(printf ' '; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done)#[fg=#080808,bg=#080808,none]#[fg=#8a8a8a,bg=#080808,none] #[fg=none]#[bg=none]#[none]#{?client_prefix, , }#[fg=none]#[bg=none]#[none]#{?mouse, , }#[fg=none]#[bg=none]#[none]#{?session_many_attached,P ,}#[fg=none]#[bg=none]#[none]#{?pane_synchronized,⚏ ,} #[fg=#8a8a8a,bg=#080808,none]| %R #[fg=#8a8a8a,bg=#080808,none]| #{?@uptime_d, #{@uptime_d}d,}`

I don't know why the continuum script is in there. I then tried disabling the continuum plugin and status-right is fixed. Now I am really wondering why continuum is in there as I didn't add it to status-right. My actual status-right configuration is:

`tmux_conf_theme_status_right=" #{prefix}#{mouse}#{pairing}#{synchronized} , %R , 猪 #{cpu}#{mem}, #{net_speed}, #{weather}, #{?uptime_d, #{uptime_d}d,} "` ( no continuum).

**Comment by gpakosz** [comment]
Both Oh my tmux! and TPM plugins will alter either `status-left` or `status-right` to launch background treatments.

Are you saying disabling the continuum plugin fixes the "not ready" issue?

**Comment by DennisGaida** [comment]
Really insightful explanation, thanks!

Running `gh-479` with plugins enabled and I'll report back whether I see any issues.

**Comment by DennisGaida** [comment]
Haven't seen any issues so far, my vote goes for merge and close this issue.

Side note: You should check out Oh my Posh (https://github.com/jandedobbeleer/oh-my-posh) since the names are so similar. I think I'm only using "oh my ..." tools from now on.

**Comment by clarsen** [comment]
tmux 3.0a on ubuntu 20.04LTS
using bd171fabc3934273856364bf85ec72b92c0d4094 oct 8, 2024.

I'm seeing this issue recently since updating from older .tmux ( cb13ee2cdd87d3996923773ee37b0cd777ea825e didn't have issue - but I don't have a more narrow range).  The first time tmux starts up, status line displays in middle
```
-20690/default' display -p '#{pid}')" = x"1612110" ]; do nice cut -c3- '/home/ctlarsen/.tmux.conf' | sh -s _uptime; sleep 60; done' not ready>
```
and it persists that way for minutes.

I added an echo into the "#(...)" tmux shell command and the status line flashes an error briefly on start up but clears: 

```
diff --git a/.tmux.conf b/.tmux.conf
index 1c996ca..2c340cf 100644
--- a/.tmux.conf
+++ b/.tmux.conf
@@ -1502,7 +1502,7 @@ run 'cut -c3- "$TMUX_CONF" | sh -s _apply_configuration'
 #       elif [ "$_tmux_version" -ge 3200 ]; then
 #           tmux run -b "trap '[ -n \"\$sleep_pid\" ] && kill -9 \"\$sleep_pid\"; exit 0' TERM; while [ x\"\$(\"$TMUX_PROGRAM\" -S '#{socket_path}' display -p '#{l:#{pid}}')\" = x\"#{pid}\" ]; do nice cut -c3- '$TMUX_CONF' | sh -s _uptime; sleep $interval & sleep_pid=\$!; wait \"\$sleep_pid\"; sleep_pid=; done"
 #       elif [ "$_tmux_version" -ge 2800 ]; then
-#         status_right="#(while [ x\"\$(\"$TMUX_PROGRAM\" -S '#{socket_path}' display -p '#{l:#{pid}}')\" = x\"#{pid}\" ]; do nice cut -c3- '$TMUX_CONF' | sh -s _uptime; sleep $interval; done)$status_right"
+#         status_right="#(echo; while [ x\"\$(\"$TMUX_PROGRAM\" -S '#{socket_path}' display -p '#{l:#{pid}}')\" = x\"#{pid}\" ]; do nice cut -c3- '$TMUX_CONF' | sh -s _uptime; sleep $interval; done)$status_right"
 #       elif [ "$_tmux_version" -gt 2400 ]; then
 #         status_right="#(while :; do nice cut -c3- '$TMUX_CONF' | sh -s _uptime; sleep $interval; done)$status_right"
 #       else

```

**Comment by gpakosz** [comment]
Hello @clarsen 👋

I added back the `echo` calls that I removed too hastily
