### ISSUE TITLE
maximized pane doesn't show [maximized] status anymore.

### ISSUE THREAD

**Issue by amosbird** [gpakosz/.tmux#48]
![](https://ptpb.pw/lczx.jpg)

I'm not sure if fish shell has something to do with this issue.

**Comment by gpakosz** [comment]
Which version of `fish` are you using?

**Comment by amosbird** [comment]
it's `2.4.0`

**Comment by gpakosz** [comment]
Works for me :(

**Comment by amosbird** [comment]
hmm, this may be related to `tmux 2.4`.

**Comment by gpakosz** [comment]
Hmm I have a work in progress branch called `2.4`.

I'll give tmux `HEAD`/`2.4` another try soon.
