### ISSUE TITLE
Does it support tmux 3.2?

### ISSUE THREAD

**Issue by ashkan-leo** [gpakosz/.tmux#481]
I am having problems using these configuration with tmux 3.2. I have been using them on previous versions with no problem. After upgrading to 3.2, now none of the functionalities work. Tmux starts on default configurations and I get no error or warnings. I am running on Mac OS 11.3.1. Any help is appreciated.

**Comment by Just-Insane** [comment]
I am also seeing the same issue. I have a basic green bar along the top and various fixes on other issues are not working.

**Comment by Just-Insane** [comment]
@ashkan-leo I appear to have resolved this issue by removing all tmux config (backup the `.tmux.conf.local` file first):

```bash
~/.tmux.conf
~/.tmux (existing git directory)
~/.tmux.conf.local
```

Then I reinstalled this config:

```bash
cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .
```

I then overwrote the new `.tmux.conf.local` file with my previous `.tmux.conf.local` config.

It all appears to be working now.

**Comment by ashkan-leo** [comment]
I'll close the issue. I got it fixed by reinstalling! Thanks for the great work!
