### ISSUE TITLE
How could I make background color transparent

### ISSUE THREAD

**Issue by f7753** [gpakosz/.tmux#483]
![image](https://user-images.githubusercontent.com/5338550/118928710-30be7600-b976-11eb-8c19-9e69db902bcb.png)

For my case, the current background color is solid, could I change to transparent?

**Comment by f7753** [comment]
WSL Terminal, Ubuntu 20.04

**Comment by gpakosz** [comment]
Hello @f7753,

AFAIK tmux doesn't support `#rrggbbbaa` colors. For fake transparency, either use `default` or `color0`.
