### ISSUE TITLE
Unicode characters do not render/transform

### ISSUE THREAD

**Issue by steven10172** [gpakosz/.tmux#486]
Im currently using `iTerm2` and after switching to zsh, and enabling powerline fonts I have the ability to see powerline characters, but the tmux status bar does not render them and instead prints the unicode characters.

What I see: <img width="1249" alt="Screen Shot 2021-05-28 at 8 45 42 PM" src="https://user-images.githubusercontent.com/1575003/120057153-bcc74200-bff5-11eb-93a2-3b88dc47e4ef.png">

I have confirmed:
- $TERM outside of tmux is `xterm-256color`
- $TERM inside of tmux is `screen-256color`
- Powerline symbols render inside and outside of tmux

```
$ cut -c3- ~/.tmux.conf | sh -s _decode_unicode_escapes '\ue0b0\ue0b1\ue0b2\ue0b3'
%  <-- renders appropriately

$ tmux -V
tmux 2.8

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
```

Note: if I manually replace the unicode strings [here](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf.local#L197) with the rendered character everything works as expected

**Comment by gpakosz** [comment]
Hello @steven10172 👋

Works for me. Can you please paste the part of your `~/.tmux.conf.local` that uses the powerline symbols?
Here's mine
```
tmux_conf_theme_left_separator_main="\uE0B0"  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub="\uE0B1"   #   you only need fonts patched with
tmux_conf_theme_right_separator_main="\uE0B2" #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub="\uE0B3"  #   PowerlineSymbols.otf font, see README.md
```

Also do you have any TPM plugin enabled?

**Comment by steven10172** [comment]
I do not, I simply followed the install instructions and only uncommented those 4 lines to enable powerline characters.

```
# status left/right sections separators
#tmux_conf_theme_left_separator_main=""
#tmux_conf_theme_left_separator_sub="|"
#tmux_conf_theme_right_separator_main=""
#tmux_conf_theme_right_separator_sub="|"
tmux_conf_theme_left_separator_main="\uE0B0"  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub="\uE0B1"   #   you only need fonts patched with
tmux_conf_theme_right_separator_main="\uE0B2" #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub="\uE0B3"  #   PowerlineSymbols.otf font, see README.md
```

**Comment by gpakosz** [comment]
Can you please try 2 things separately?
- either use single quotes, e.g. `='\uE0B0'
- either double the backslash. e.g. = "\\uE0B0"

**Comment by steven10172** [comment]
Both of those cause the symbols to render as expected, thanks!

**Comment by gpakosz** [comment]
I'm still curious why `"\uE0B0"` works for me though 🤔
