### ISSUE TITLE
Weird behavior recently 

### ISSUE THREAD

**Issue by souvikhaldar** [gpakosz/.tmux#487]
Recently I see that when I try to run `tmux` I face the following issue using the latest kitty terminal, but it used to be smooth earlier:
![image](https://user-images.githubusercontent.com/20991754/121637940-d06bb180-caa7-11eb-99d0-faa6880469f3.png)

**Comment by 812lcl** [comment]
Same issue, the latest tmux version and MacOS iterm2

**Comment by souvikhaldar** [comment]
> Same issue, the latest tmux version and MacOS iterm2

It seems it was happening because there was a running session already. So I killed the server ( `tmux kill-server`) and restarted and it worked fine.
