### ISSUE TITLE
device /dev/pts not ready

### ISSUE THREAD

**Issue by Steven0668** [gpakosz/.tmux#49]
What's wrong is this? How to fix it?
![pts_err](https://cloud.githubusercontent.com/assets/22025679/21960753/0f3d8e04-db30-11e6-9620-56a2f3d24c14.png)

**Comment by gpakosz** [comment]
Which OS are you using? Which bash version and which version of tmux?

**Comment by gpakosz** [comment]
This issue is related to width of Unicode symbols. This is fixed in an upcoming branch.

**Comment by jcchikikomori** [comment]
This occurs on TermuxArch for Android
