### ISSUE TITLE
Pane border colour when pane synchronisation is on

### ISSUE THREAD

**Issue by Kristijan** [gpakosz/.tmux#490]
Hi All,

In later versions on tmux (I'm not entirely sure when it was introduced), the default configuration will change the pane border colour to red when pane synchronisation is turned on. I find this a lot clearer when working with multiple panes to determine the sync state, rather than relying on the indicator in the right-status bar.

Is it possible for this to be added as an override option?

Apologies if this isn't the correct place to raise a feature request.

**Comment by gpakosz** [comment]
Hello @Kristijan 👋

This has been introduced in tmux `3.2`.

I guess you can override `pane-active-border-style` in your own `~/.tmux.conf.local` copy:
```
set -g pane-active-border-style '#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,fg=green}}'
```

**Comment by Kristijan** [comment]
Thanks for the advice @gpakosz 

So that does exactly what I want it to do if I run that in an existing tmux session.

However, if I put it into my `~/.tmux.conf.local` and start-up tmux, it does not. If I create a number of panes, and then `:source-file ~/.tmux.conf` I can see that it initially sets the pane colour to green/red (depending on my current sync state), but then resets it back to the default theme colour of pale blue. Is there something post the sourcing of the custom configuration that may reset the pane colours?

**Comment by gpakosz** [comment]
Well in fact after `~/.tmux.source.local` is sourced, the `_apply_theme()` logic kicks in.

Use this
```
tmux_conf_theme_pane_active_border="#{?pane_in_mode,$tmux_conf_theme_colour_9,#{?synchronize-panes,$tmux_conf_theme_colour_16,$tmux_conf_theme_colour_4}}"
```

Which I believe will become the new default if it works in tmux `2.4`

**Comment by Kristijan** [comment]
> Well in fact after `~/.tmux.source.local` is sourced, the `_apply_theme()` logic kicks in.
> 
> Use this
> 
> ```
> tmux_conf_theme_pane_active_border="#{?pane_in_mode,$tmux_conf_theme_colour_9,#{?synchronize-panes,$tmux_conf_theme_colour_16,$tmux_conf_theme_colour_4}}"
> ```
> 
> Which I believe will become the new default if it works in tmux `2.4`

Perfect, this is working exactly how I like it. Really appreciated the quick feedback :)
