### ISSUE TITLE
This .tmux.conf is unworkably slow on my MacBook

### ISSUE THREAD

**Issue by Skitelman** [gpakosz/.tmux#492]
I'm not sure exactly when this happened but sometime over the weekend I noticed that `tmux` was hogging all of the resources on my computer and just making everything unbearably slow. I uninstalled and removed this `.tmux.conf` from my machine. Reinstalling `tmux` wokred fine but reinstalling this `.tmux.conf` continued the issue. would love to use this again but it is not workable for me now. Curious if anyone else is having issues. Posting my specs below:
```
tmux 3.2a
fish, version 3.2.2
iTerm2 3.4.8
macOS Big Sur Version 11.3.1
MacBook Pro (15-inch, 2019)
Processor 2.6 GHz 6-Core Intel COre i7
Memory 32 GB 2400 MHz DDR4
Graphics Radeon Pro 555X 4 GB, Intel UHD Graphics 630 1536 MB
```

**Comment by maxi8815** [comment]
Same here.  It's unusable now, any ideas?   Its something related with:

sh -c cut -c3- ~/.tmux.conf | sh -s _username /dev/ttys008 false %7
sh -c cut -c3- ~/.tmux.conf | sh -s _root /dev/ttys008 ! %7
sh -c cut -c3- ~/.tmux.conf | sh -s _hostname /dev/ttys008 false %7

It's strange cause this is start to happen yesterday and no updates where done in the last days.

**Comment by gpakosz** [comment]
Hello @Skitelman and @maxi8815 👋

I'm sorry I can't reproduce what you're experiencing.

What's your value for `status-interval`?
```
$ tmux show -gv status-interval
10
```

**Comment by maxi8815** [comment]
This is the error that shows up when starting, and freeze my Mac:


![](https://user-images.githubusercontent.com/44240034/125199399-709a2f00-e23c-11eb-9406-3613831699b7.jpg)

**Comment by gpakosz** [comment]
This issue looks similar to #499 

Is the following slow for you?
```
$ date && ps -t /dev/ttys000 && date
Tue Jul 13 08:48:11 CEST 2021
  PID TTY           TIME CMD
14212 ttys000    0:00.03 login -fp gpakosz
14213 ttys000    0:00.12 -zsh
14242 ttys000    0:00.01 tmux
Tue Jul 13 08:48:11 CEST 2021
```

**Comment by maxi8815** [comment]
It takes about 35 seconds to execute.

**Comment by gpakosz** [comment]
While I suspect the following is instant
```
$ date && ps -t ttys000 && date
```

**Comment by maxi8815** [comment]
Yes Gregory it's instant, what should I do?

**Comment by gpakosz** [comment]
I don't know yet.

It's clearly external to tmux and Oh my tmux! and I would like to pinpoint the exact root cause

**Comment by maxi8815** [comment]
Oh I see, thanks anyway, I'll follow this issue.

**Comment by gpakosz** [comment]
What shell are you using btw @maxi8815?

**Comment by gpakosz** [comment]
@Skitelman can you please do the `ps` test above please?

**Comment by Skitelman** [comment]
Thanks for looking at this! This is the result of the test

**Comment by gpakosz** [comment]
@Skitelman and with `ps -t /dev/ttys000` please?

**Comment by Skitelman** [comment]
```
$ date && ps -t /dev/ttys000 && date
Tue Jul 13 14:47:58 EDT 2021
  PID TTY           TIME CMD
25396 ttys000    0:00.08 login -fp sam.ghitelman
25397 ttys000    0:00.18 -fish
25632 ttys000    0:00.01 tmux
Tue Jul 13 14:47:58 EDT 2021
```

**Comment by gpakosz** [comment]
@Skitelman hmm the result with `/dev/ttys000` is instant. So something else is the reason why things are slow for you. Unfortunately I can't reproduce the issue.

**Comment by gpakosz** [comment]
@maxi8815 Which shell are you using btw?

Can you try to make an exhaustive list of what's installed on your mac by chance?

**Comment by maxi8815** [comment]
Hey there! I'm using bash, here is a list of installed software:

Safari.app
Alfred 4.app
Proxifier.app
Mac@IBM App
Mac@IBM Enrollment.app
Cisco
Unsplash Wallpapers.app
Amazon Chime.app
Cisco Jabber.app
Visual Studio
Notion.app
Karabiner-EventViewer.app
Karabiner-Elements.app
VirtualBox.app
zoom.us.app
Mac@IBM Notifications.app
Magnet.app
Falcon.app
Microsoft Teams.app
Notion Web
The Unarchiver.app
Bear.app
Spark.app
Pocket.app
Save to
iTerm.app
UniFi-Discover.app
UniFi.app
Amphetamine.app
Simplenote.app
Sublime Text.app
MotionPro.app
Slack.app
Home Assistant.app
Code42.app
Microsoft Excel.app
Google Chrome.app
Itsycal.app
1Password 7.app
Microsoft Remote
Dropover.app
Evernote.app
Utilities
Firefox.app
Telegram.app
WhatsApp.app
SmoothScroll.app
Cisco Webex
Microsoft OneNote.app
Microsoft Outlook.app
Microsoft PowerPoint.app
Microsoft Word.app

**Comment by gpakosz** [comment]
@maxi8815 Thanks for the list. Unfortunately nothing inspires me.

Can you check if `$PS0` is defined?
```
$ echo "$PS0"
```

**Comment by maxi8815** [comment]
No It's not, I run the command, but there was no output.
