### ISSUE TITLE
.tmux.conf.local cannot be loaded recently

### ISSUE THREAD

**Issue by ujkuo** [gpakosz/.tmux#493]
Environment and setting:
macOS X Bug Sur version 11.4
tmux version 3.2
zsh version 5.8 (x86_64-apple-darwin19.6.0)
iTerm2 version 3.4.8, without enabling "Use Unicode version 9+ widths" in iTerm2's Preference > Profiles > Text
echo $TERM shows xterm-256color outside tmux and screen-256color inside.

As title, I have used tmux for a long time. Recently after some updates such as oh-my-zsh and macOS, the tmux seems to get in trouble as below.
![截圖 2021-06-29 上午10 36 48](https://user-images.githubusercontent.com/62895600/123728525-e9f16380-d8c5-11eb-9190-36d2655a76b6.png)

I have tried to re-install tmux, iTerm2 and re-source tmux files but nothing change. I found that .tmux.conf could be executed successfully by doing some test such as modifying setting in .tmux.conf, but the .tmux.conf.local file seems to failed to load successfully, which could be found by the un-modified status-bar. The user defined overrides command is written in .tmux.conf as same as the default file.

I am wondering what happens in the tmux. Although tmux is still working but I am missing the pretty theme...

**Comment by gpakosz** [comment]
Hello @ujkuo,

Please start the installation over then tell me if you're still having problem.
This means exiting tmux, making sure no tmux process is still running, deleting your `~/.tmux` clone, your `~/.tmux.conf.local` copy and the `~/.tmux.conf` symlink.

**Comment by ujkuo** [comment]
Hello @gpakosz ,
After doing so, the configure executes successfully. Thank you so much!
