### ISSUE TITLE
A red flash, perhaps of error, in status bar when launching tmux

### ISSUE THREAD

**Issue by reportaman** [gpakosz/.tmux#496]
When I launch tmux, it's status line flashes with a message in red. The screenshot is below:

![Screen Shot 2021-07-04 at 1 10 23 PM](https://user-images.githubusercontent.com/71736629/124398222-6ec6ed80-dcc9-11eb-86a8-f7c37756e25a.png)

I am using macOS BigSur 11.4 ARM-64 with zsh on Alacritty terminal.

After flashing this message at launch, status line goes back to normal, as if nothing happened.

**Comment by reportaman** [comment]
Perhaps if this is expected & valid, then is there a way to delay the drawing of entire status line till all fields have reached a stable state?

**Comment by gpakosz** [comment]
Hello @reportaman 👋

This is a tmux limitation.

**Comment by reportaman** [comment]
@gpakosz 👋 Thanks for the info. I filed this ticket on tmux to zenify their redraws: https://github.com/tmux/tmux/issues/2774

Btw, thanks for such a wonderful statusline! I used to dread opening tmux before this.

**Comment by gpakosz** [comment]
@reportaman Can you try the `gh-496` branch?

Please kill all tmux processes entirely, then switch to the `gh-496` branch, then launch tmux again and tell me if you're still seeing the "<... not ready>" message 🙏

**Comment by gpakosz** [comment]
So! This will be solved in the next tmux version.

**Comment by reportaman** [comment]
@gpakosz Tmux has added the patch x2.diff.txt mentioned in https://github.com/tmux/tmux/issues/2774#issuecomment-879433977 to main trunk. Can you please updating status-format to leverage it? I don't know what files to edit in .tmux

Thanks!

**Comment by reportaman** [comment]
@gpakosz I don't see this anymore on latest tmux next-3.3

**Comment by Frederick888** [comment]
With 67b1d38a87e40c09c75fd49a728e80b5f7bdc505 I now notice that username and hostname keep flickering after tmux has fully started up. May I know if you guys also have this issue? If not I guess I'll need to check my config.

**Comment by gpakosz** [comment]
Hello @Frederick888  👋

I'm using tmux 3.2a on macOS with iTerm2. I don't see any flickering but that might be terminal emulator dependent.

What's your OS and terminal emulator?

**Comment by Frederick888** [comment]
@gpakosz Kitty under macOS and Arch Linux, Konsole under Arch Linux.

With the following additional configurations appended to the default `.tmux.conf.local`, it starts to flicker every 5-10s when having ~10 windows (but I stayed in one window):
```tmux
set -g status-keys vi
set -g mode-keys vi

set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind a send-keys C-a

if -b '[[ "$TERM" =~ -(256color|kitty)$ ]]' 'set -g default-terminal tmux-256color'
if -b '[[ "$TERM" == "linux" ]]' 'set -g default-terminal screen-256color'
```

If I add more stuff to the status bar, it happens more often, e.g. on top of the configurations above, add:

```tmux
set -g @plugin 'tmux-plugins/tmux-cpu'
tmux_conf_theme_status_right=" #{prefix}#{mouse}#{pairing}#{synchronized}#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},}#{?battery_percentage, ,}, #{cpu_fg_color}#{cpu_icon} #{cpu_percentage} , %R , %d %b | #{username}#{root} | #{hostname} "
```

And btw it now also flickers a lot when switching between windows/panes, which did not happen using ed0b83a1184929ec967921d0db6bb0c4e6e9a2c5.

**Comment by gpakosz** [comment]
I reverted the commit. It was not worth it anyways
