### ISSUE TITLE
how to set pane name {hostname}

### ISSUE THREAD

**Issue by songhao8080** [gpakosz/.tmux#497]
![image](https://user-images.githubusercontent.com/10607039/124712287-b3ed5880-df31-11eb-8a69-66e025e86842.png)

**Comment by gpakosz** [comment]
Hello @songhao8080 👋

You can try adding the following line to your `~/.tmux.conf.local` copy
```
setw -g automatic-rename-format "#{?pane_in_mode,[tmux],#{?#{m:*ssh,#{pane_current_command}},#(cut -c3- ~/.tmux.conf | sh -s _hostname #{pane_tty} true false #h #D #{window_activity}),#{pane_current_command}}}#{?pane_dead,[dead],}"
```

**Comment by gpakosz** [comment]
Hello @songhao8080 👋

Did you have the chance to try it?
