### ISSUE TITLE
Help: No username when running tmux in a docker container with alpine

### ISSUE THREAD

**Issue by Looooopy** [gpakosz/.tmux#498]
Hi 

I have tried to get things working by installing tmux in a docker image and apply your config for tmux and wonder how you are getting the username because when I do a ```whoami``` I get the username but i cant get a username in the right corner in status bar (See picture below).

![tmux-nousername](https://user-images.githubusercontent.com/16755871/125106033-73cbd880-e0df-11eb-8aab-2c30b6b43283.png)

**Comment by Looooopy** [comment]
More info:

Found some a issue where some investigated was done,  you asked them to do this cmd

     cut -c3- ~/.tmux.conf | sh -s _username
     
in **ubuntu** it outputs correctly

but in **alpine** i get this error

```
>   ~/.tmux$ cut -c3- ~/.tmux.conf | sh -s _username

ps: unrecognized option: t
BusyBox v1.33.1 () multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

        -o COL1,COL2=HEADER     Select columns for display
        -T                      Show threads
```

So I suppose alpine is different in this way handling ps!
Do you know of a workaround that don't include changing OS?

**Comment by gpakosz** [comment]
Hello @Looooopy 👋

Indeed Oh my tmux! doesn't support BusyBox. I think you can try installing the `procps` package.

**Comment by Looooopy** [comment]
> Hello @Looooopy 👋
> 
> Indeed Oh my tmux! doesn't support BusyBox. I think you can try installing the `procps` package.

Ok I will try, thanks for the info

**Comment by Looooopy** [comment]
Yes it did work now!

Thanks again for the tip!
