### ISSUE TITLE
Config not completely loaded

### ISSUE THREAD

**Issue by klmr** [gpakosz/.tmux#5]
I’m following the instructions from the readme file to install the configuration. However, when I then start `tmux`, it seems like not all of the configuration was loaded. Most strikingly, the powerline-inspired status bar isn’t displayed. Other options, such as `renumber-windows`, are also not enabled. Starting via `tmux -f ~/.tmux.conf` makes no difference.

In fact, I cannot see any difference before and after soft-linking `~/.tmux/.tmux.conf` into `~`.

`tmux -V` outputs:

```
tmux 1.9a
```

In fact, this `.tmux` config used to work, and I think it stopped working after the `tmux` version was updated on the system (RHEL 6).

In case that helps, `tmux -vvv` outputs

```
got 207 from server
got 203 from server
got 204 from server
```

**Comment by gpakosz** [comment]
For a start, upstream tmux 1.9a is very buggy to the point I don't even understand why authors don't bother releasing a stable 1.9.1. E.g. Debian ships a [very much patched tmux 1.9](http://metadata.ftp-master.debian.org/changelogs//main/t/tmux/tmux_1.9-6~bpo70+1_changelog).

Unfortunately, I don't have access to RHEL 6 and I'm not familiar with it but http://pkgs.repoforge.org/tmux/ seems to indicate tmux 1.6.1 is the official version. If you compiled tmux from upstream 1.9a sources, you may want to use [patched sources from debian](https://packages.debian.org/wheezy-backports/tmux).

Finally, `tmux -vvv` should produce a `tmux-server-PID.log` in which you can get more information about what's going wrong when loading `~/.tmux.conf`.

When tmux starts fine, I have the same lines as you in `tmux-client-PID.log`

    got 207 from server
    got 203 from server
    got 204 from server

Please post the content of `tmux-server-PID.log` so that we can figure out which line in `.tmux.conf` causes problems.

**Comment by klmr** [comment]
Bizarrely, the `tmux-server-PID.log` file isn’t generated for me. Thanks about the info regarding 1.9a. I’ll speak to IT about downgrading, or using the patched version.

**Comment by gpakosz** [comment]
Could it be a mismatch between a tmux server already running and a more recent tmux client?

**Comment by klmr** [comment]
That’s exactly what happened, apologies. After killing everything, I now reproducibly get a hang when starting a new tmux instance (nothing is every displayed). Here’s what the server log file looks like:

The client log now contains only one entry: https://www.ebi.ac.uk/~rudolph/dropbox/tmux-server-7626.log

```
got 210 from server
```

**Comment by gpakosz** [comment]
In order to help me figure out what's going on, can you please try to comment either

- https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L32

or

- https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L107-108

Thanks

**Comment by klmr** [comment]
Okay. Commenting out either still hangs the client. The client log is empty.

Server log for commented out line 32: https://www.ebi.ac.uk/~rudolph/dropbox/tmux-server-21358.log

Server log for commented out line 107–108: https://www.ebi.ac.uk/~rudolph/dropbox/tmux-server-22919.log

**Comment by gpakosz** [comment]
Thanks for trying.

I missed you likely want to also disable https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L141 along with https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L32

In any case, if you have time to spare on the issue, you want to comment every non trivial line in `.tmux.conf`: another candidate is https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L152

The last resort would be commenting out https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L151 which would prevent you from getting a nice theme but would exhibit the hangs happens there.

**Comment by klmr** [comment]
The hang still exists even when I comment out *all* the aforementioned lines. The server log can be found here: https://www.ebi.ac.uk/~rudolph/dropbox/tmux-server-33497.log (client log is once again empty).

In case that matters, once I start `tmux`, the command does nothing, but it also cannot be interrupted by <kbd>Ctrl</kbd>+<kbd>C</kbd>. The only way is to open a  new terminal and kill the process.

**Comment by gpakosz** [comment]
According to the server log, there's an error with `job error 0x1202560: [ -f ~/.tmux.conf.local ], pid 33498`

Can you please try to `cp ~/.tmux/.tmux.conf.local ~/` or `touch ~/.tmux.conf.local` ?

**Comment by klmr** [comment]
`~/.tmux.conf.local` already exists, and doing `[ -f ~/.tmux.conf.local ]` manually in the shell doesn’t raise an error. However, when using the canonical path here instead of `~`, I get a different error log (but still the same behaviour):

```
job error 0xfc2d90: [ -f /nfs/gns/homes/rudolph/.tmux.conf.local ], pid 51095
job died 0xfc2d90: [ -f /nfs/gns/homes/rudolph/.tmux.conf.local ], pid 51095
cmdq 0xfc1580: source-file /nfs/gns/homes/rudolph/.tmux.conf.local (client -1)
loading /nfs/gns/homes/rudolph/.tmux.conf.local
```

After that, it does load the `.tmux.conf.local` (which it didn’t before) so that’s good. However, there are more errors later on. The whole log is at https://www.ebi.ac.uk/~rudolph/dropbox/tmux-server-51094.log.

**Comment by gpakosz** [comment]
The purpose of https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L153 is to unset variables that are meant to be used only during the parsing of `.tmux.conf`. If you comment the line, behavior should be equivalent.

That being said, that's a lot of commenting already without circling down the exact reason for hangs.

As I said, sadly tmux 1.9a means nothing. If you could ask IT which sources / RHEL package they used, I could compile it and debug it on my own. Even if I setup a RHEL6 VM, without knowing where your tmux 1.9a comes from I'm afraid I can't do much.

You could also compile tmux HEAD locally as a test: if everything works again, that means there's a bug in tmux I may be able to workaround from within `.tmux.conf` by doing/writing things a bit differently but I would put little hope in that. Compiling tmux is just a matter of:

    $ git clone git://git.code.sf.net/p/tmux/tmux-code tmux
    $ cd tmux
    $ ./autogen.sh
    $ ./configure
    $ make
    $ ./tmux -S /tmp/tmux-HEAD

**Comment by klmr** [comment]
Not sure if this helps (I feel honestly clueless here) but the version of tmux we’re using is the one from Portage/ebuild: https://packages.gentoo.org/package/app-misc/tmux

For now I’m going to give the self-installed tmux a whirl. Thanks for all your effort.

**Comment by gpakosz** [comment]
So, I just used Vagrant to boot CentOS 6.6 (which should be the same as RHEL 6.6).

I installed libevent 2.0 (while the system provided libevent is 1.4 and incompatible with tmux) and tmux 1.9a:

    $ sudo yum install -y gcc ncurses-devel git


    $ wget http://iweb.dl.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz
    $ tar -xvzf libevent-2.0.22-stable.tar.gz
    $ cd libevent-2.0.22-stable
    $ ./configure
    $ make
    $ sudo make install
    $ cd ..


    $ wget http://downloads.sourceforge.net/tmux/tmux-1.9a.tar.gz
    $ tar -xvzf tmux-1.9a.tar.gz
    $ cd tmux-1.9a
    $ ./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    $ make
    $ sudo make install
    $ cd ..


    $ sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/tmux.conf'
    $ sudo ldconfig


    $ git clone https://github.com/gpakosz/.tmux.git
    $ ln -s ~/.tmux.conf/.tmux.conf .


Then launching tmux works as expected. All in all, that doesn't explain much why you're experiencing issues (maybe a bug between tmux and libevent?). But at least this should get you started compiling and installing tmux from source.

**Comment by klmr** [comment]
I did some more experimenting by starting off with an empty config, and then adding one item at a time.

I can reproducibly crash tmux on startup as soon as any item is added that is trying to execute some external command.

For instance, adding in the line

```conf
if 'which -s reattach-to-user-namespace' 'set -g default-command "tmux rename-window initializing; tmux set -w automatic-rename; reattach-to-user-namespace $S
```

Crashes tmux. `ps x` displays:

```
⟩⟩⟩ ps x
  PID TTY      STAT   TIME COMMAND
30162 ?        S      0:00 tmux -u -vvv
30164 ?        Ss     0:00 tmux -u -vvv
30165 ?        Z      0:00 [which] <defunct>
…
```

Note the “defunct” `which`. The tmux-server log contains the line

```
job error 0x235acf0: which -s reattach-to-user-namespace, pid 30165
```

Removing the above line and adding

```conf
run 'tmux bind -t vi-choice K start-of-list 2> /dev/null'
run 'tmux bind -t vi-choice J end-of-list 2> /dev/null'
```

results in:

```
⟩⟩⟩ ps x
  PID TTY      STAT   TIME COMMAND
12890 ?        S      0:00 tmux -u -vvv
12892 ?        Ss     0:00 tmux -u -vvv
12893 ?        Z      0:00 [sh] <defunct>
…
```

Again, note the “defunct” `sh`. The tmux-server file contains:

```
job error 0x108cad0: tmux bind -t vi-choice K start-of-list 2> /dev/null, pid 12893
```

… and so on. It appears that tmux is simply unable to execute external commands at all, and/or somehow loses control of them. I have absolutely no clue what might cause this. This regardless of whether I’m using the installed tmux or a self-compiled one.

**Comment by gpakosz** [comment]
Can you please confirm you get a hang with a defunct `sh` process when `.tmux.conf` only contains the following line?

    run 'tmux bind -t vi-choice K start-of-list 2> /dev/null'

Also, when compiling `tmux` from source, can you confirm you followed the steps above, linking it to upstream `libevent-2.0.22-stable` ? Can you launch `ldd ./tmux` on the built `tmux` and paste the result please?

**Comment by klmr** [comment]
Okay. Using libevent-2.0.22 fixed it. For some reason, the server accidentally had the unstable libevent-2.1 installed.

For the record, I can confirm that the single config line you posted above *still* cause the bug when using libevent-2.1.5-beta5.

Thanks a lot for your patience in figuring this out.

**Comment by gpakosz** [comment]
No problem, happy to help.

I'm adding this for further reference: http://sourceforge.net/p/levent/bugs/350/

**Comment by hanxi** [comment]
There have small error in https://github.com/gpakosz/.tmux/issues/5#issuecomment-87792080

```bash
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s ~/.tmux/.tmux.conf .
```

**Comment by gpakosz** [comment]
Updated
