### ISSUE TITLE
terminal/tmux extended keys support breaks with this config

### ISSUE THREAD

**Issue by rameshsanth** [gpakosz/.tmux#500]
I use iTerm 3.4.8 and tmux 3.2 on redhat linux 7.8

Problem :
If i launch tmux with this tmux config ( with or without .tmux.confi.local), the extended-keys support is lost.
even after i disconnect from tmux and try extended keys on the iTerm, its gone. Its as if somehow the extended keys was disabled in the terminal itself. I have to close that terminal and open a new tab or window to get the extended keys.

Without this config, just a simple .tmux.conf, extended keys work just fine inside Tmux and even after disconnecting from Tmux.

**Comment by rameshsanth** [comment]
i have this in my .tmux.conf.local.
set -g default-terminal "xterm-256color" # colors! iTerm recommended

# to be set when CSI u keyboard mode is on. Works with iTerm.
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

**Comment by gpakosz** [comment]
Inside tmux, `$TERM` and as such `default-terminal` should be `screen-256color` or `tmux-256color`. Never `xterm-256color`. See https://github.com/tmux/tmux/wiki/FAQ

![image](https://user-images.githubusercontent.com/553208/125995074-9e428a14-855a-438f-bcdc-c4938d561857.png)

Oh my tmux! does nothing about extended keys. As such, I don't know why you're facing what you're reporting:
> It's as if somehow the extended keys were disabled in the terminal itself. I have to close that terminal and open a new tab or window to get the extended keys.

**Comment by rameshsanth** [comment]
> Hello @rameshsanth 👋
> 
> Inside tmux, `$TERM` and as such `default-terminal` should be `screen-256color` or `tmux-256color`. Never `xterm-256color`. See https://github.com/tmux/tmux/wiki/FAQ
> 
> ![image](https://user-images.githubusercontent.com/553208/125995074-9e428a14-855a-438f-bcdc-c4938d561857.png)
> 
> Oh my tmux! does nothing about extended keys. As such, I don't know why you're facing what you're reporting:
> 
> > It's as if somehow the extended keys were disabled in the terminal itself. I have to close that terminal and open a new tab or window to get the extended keys.

I will try with TERM set to screen-256color. However I don't think the issue I reported is related to it.
If you have this setup, please try it out.. 
I'll attach some console log and screenshots describing the issue.
I understand this issue sounds like it is not related to the config file.. However, the fact is extended keys work properly inside tmux without this repo's tmux config file and just the ones i provided above which includes xterm-256color.

THe minute i launch TMUX with this config, the extended keys stop working altogether even after i detach from Tmux..

**Comment by gpakosz** [comment]
> If you have this setup, please try it out..

You're mentioning iTerm `3.4.8` which is AFAIK a macOS terminal emulator and RedHat `7.8`.

What gives?

**Comment by rameshsanth** [comment]
iTerm runs on my macbook. I ssh to a linux server running RHEL and launch tmux there. I have iterm hotkey to launch the ssh & attach tmux session.

Tmux is acting very weird.. I just can't pinpoint the reason for this issue. I'll try to narrow down this issue further and reopen.

**Comment by rameshsanth** [comment]
Thanks for your time. Really appreciate your time and effort.
