### ISSUE TITLE
uptime display wrong with macos 11.4

### ISSUE THREAD

**Issue by huhongbo** [gpakosz/.tmux#501]
Tmux 3.2a MacOS 11.4 zsh shell

when using tmux the uptime always show 51y
![image](https://user-images.githubusercontent.com/1218296/126148713-3879fff0-de21-4207-9c72-a3555e0f80e6.png)

I manual run the script
cut -c3- ~/.tmux.conf | sh -s _uptime 
and the uptime will become the right utpime
![image](https://user-images.githubusercontent.com/1218296/126148965-559d4e16-c6e1-48ff-ae5d-74640a802ef0.png)

I haven't found an issue related to it, and could anyone help with the problem?  
Thanks

**Comment by gpakosz** [comment]
Hello @huhongbo 👋

Sorry for the late reply. Does the problem still exist with the latest commit of Oh my tmux!? (commit `ed0b83a1184929ec967921d0db6bb0c4e6e9a2c5` from the `master` branch)

**Comment by gpakosz** [comment]
Did you enable TPM plugins by chance?

**Comment by huhongbo** [comment]
I didn't enable the TPM plugins

**Comment by gpakosz** [comment]
I can't explain why it wouldn't work the first time if running `$ cut -c3- ~/.tmux.conf | sh -s _uptime` works.

Can you please exit tmux, make sure all tmux process are gone and then launch the following **before launching tmux**:
```
$ cut -c3- ~/.tmux/conf | sh -sx _uptime
```
Then paste the output here?

**Comment by huhongbo** [comment]
❯ cut -c3- ~/.tmux.conf | sh -sx _uptime
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Darwin
++ tmux -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
+ _tmux_version=320
+ command -v pkill
+ _uptime
+ case "$_uname_s" in
++ sysctl -q -n kern.boottime
++ awk '-F[ ,:]+' '{ print $4 }'
+ boot=1630067502
++ date +%s
+ now=1630332499
+ awk -v boot=1630067502 -v now=1630332499 '
    BEGIN {
      uptime = now - boot
      y = int(uptime / 31536000)
      dy = int(uptime / 86400) % 365
      d = int(uptime / 86400)
      h = int(uptime / 3600) % 24
      m = int(uptime / 60) % 60
      s = int(uptime) % 60

      system("tmux  set -g @uptime_y " y + 0 " \\; " \
                   "set -g @uptime_dy " dy + 0 " \\; " \
                   "set -g @uptime_d " d + 0 " \\; " \
                   "set -g @uptime_h " h + 0 " \\; " \
                   "set -g @uptime_m " m + 0 " \\; " \
                   "set -g @uptime_s " s + 0)
    }'
no server running on /private/tmp/tmux-501/default

not only the first time. I just manual run the cut -c3- ~/.tmux.conf | sh -s _uptime the uptime will be correct, but after 60 seconds (the default interval ) the uptime will become the wrong one, I just don't know how should I working to debug it.

**Comment by gpakosz** [comment]
I have no idea 🤷‍♂️

If launching `cut -c3- ~/.tmux.conf | sh -s _uptime` works, then there's no reason it doesn't work in the general case.

You can try using the `show-message` command, e.g.
```
$ tmux show-message | grep uptime
16:29: client-299 command: set-option -g @uptime_s 30
16:29: client-299 command: set-option -g @uptime_m 26
16:29: client-299 command: set-option -g @uptime_h 7
16:29: client-299 command: set-option -g @uptime_d 16
16:29: client-299 command: set-option -g @uptime_dy 16
16:29: client-299 command: set-option -g @uptime_y 0
...
```

**Comment by huhongbo** [comment]
Just update
I do some debug and find out the boot time somehow will get 0 cause the problem, but still don't known the reason

**Comment by huhongbo** [comment]
No, I'm using macbook pro. The output seems is empty value so + 0 = 0 cause the problem. But I cannot find out why cannot execute sysctl -q -n kern.boottime, It's fine to execute sysctl  when I using the terminal, just like I manual run the script.

**Comment by huhongbo** [comment]
I just close the issue , It's seems not related to the .tmux script and somethings with the tmux or env problem

**Comment by gpakosz** [comment]
Please keep me posted if you find out the reason!

**Comment by ximik3** [comment]
I have exactly the same behavior on my Mac M3 (Sonoma 14.4.1) but this issue seem to be introduced on later Mac OS versions:
[https://discussions.apple.com/thread/255523260?sortBy=best](https://discussions.apple.com/thread/255523260?sortBy=best)
