### ISSUE TITLE
The key bind I had set up in zshrc is not working in tmux session

### ISSUE THREAD

**Issue by codehia** [gpakosz/.tmux#502]
I had set up a key binding for accepting autosuggest suggestions, `bindkey '^ ' autosuggest-accept` Which works in the normal shell, however once in `tmux` this doesn't work anymore.

I suspect it might have something to do with `set -g terminal-overrides "$TERM:RGB"`  in the `tmux.conf.local`

**Comment by gpakosz** [comment]
Hello @codehia 👋

There's no `set -g terminal-overrides "$TERM:RGB"` in the `.tmux.conf.local` sample file that ships with Oh my tmux! 🤷‍♂️

Can you try launching tmux without this configuration?
- open a new terminal, make sure you're not within tmux already
- launch `$ tmux -L test -f /dev/null` to launch a tmux server and client with stock configuration
- see if your binding works

**Comment by codehia** [comment]
I had added the terminal override, that's why it was my suspect, and removing it was still not fixing it, however, turns out the issue was in the zshrc, with the ordering of the keybinding. fixed the issue.
