### ISSUE TITLE
Disable bell

### ISSUE THREAD

**Issue by house-of-vanity** [gpakosz/.tmux#504]
Hello, i'm looking a way to disable bell completely. I've tried 
```
set -g bell-action none
set -g visual-bell off
```
It doesn't work and my window name gets underlined. Is it possible to disable bell?

**Comment by gpakosz** [comment]
Hello @house-of-vanity 👋

You're mentioning bell but I suspect what you're after is changing the style for windows with activity.

Try editing your `~/.tmux.conf.local` copy and set
```
tmux_conf_theme_window_status_activity_attr="none"
```

**Comment by house-of-vanity** [comment]
> Hello @house-of-vanity 👋
> 
> You're mentioning bell but I suspect what you're after is changing the style for windows with activity.
> 
> Try editing your `~/.tmux.conf.local` copy and set
> 
> ```
> tmux_conf_theme_window_status_activity_attr="none"
> ```

You're right! It works. Thanks!
