### ISSUE TITLE
Unable to use vi bindings in copy mode

### ISSUE THREAD

**Issue by serpro69** [gpakosz/.tmux#505]
Hi,

Was using your configs for awhile now on ubuntu 20.04 and everything was great, but I also haven't updated anything for ~ a year maybe.
Today tried setting this up on a Windows laptop (Ubuntu 20.04 under WSL2) and can't get the copy mode to work.

I enter the copy mode with `<prefix> + Enter` and can see the yellow line number indicator in top right. But I can't select anything or move around even. Any thoughts what could be missing?
The installation is fresh without any changes. The only thing I did was add `set -g default-shell /usr/bin/zsh` to `~/.tmux/.tmux.conf` file.

**Comment by gpakosz** [comment]
Hello @serpro69 

You must not modify `~/.tmux/.tmux.conf`. If you want to override things, please do it in your own `~/.tmux.conf.local` copy.
Also about Zsh, this should be picked up automatically without adding any `set -g default-shell`. Did you configure Zsh as your default shell outside of tmux?

Finally, about vim bindings in copy mode, you can either
- `export VISUAL=vim` or `export EDITOR=vim` as part of your `.zshrc`
- edit your `~/.tmux.conf.local` copy and uncomment
  ```
  #set -g status-keys vi
  #set -g mode-keys vi
  ```

**Comment by serpro69** [comment]
Hey, thanks for a very quick response :)

My editor was already set to vim:
```
echo $EDITOR
vim
```

I think I've found the issue though. I was using `tmux` as the login shell instead of zsh. That's why I also had to set `default-shell` option in `tmux.conf`. Setting zsh as login shell and then running tmux makes things work again :) 
Just need to figure out now a good way to automatically run tmux on login after zsh has been loaded. Any tips on how to best approach that? Or do you simply run `tmux` command in your `(.bash|.zsh)rc` file?

**Comment by gpakosz** [comment]
I don't use tmux as a login shell.

Likely you can run it this way `EDITOR=vim SHELL=/usr/bin/zsh tmux`
