### ISSUE TITLE
TPM overriding Urlview binding

### ISSUE THREAD

**Issue by bjesus** [gpakosz/.tmux#507]
The readme says that the keybinding for Urlview is prefix+U, however this is also the keybinding for TPM's update plugins action. Indeed, pressing prefix+U makes TPM try to update my plugins instead of Urlview opening.

Is this a bug, or is there something wrong with my configuration? How are these keybindings supposed to work?

**Comment by gpakosz** [comment]
Hello @bjesus 👋

You're right there's a clash between lauching Urlview and updating TPM plugins.

The Urlview binding came first. Not sure how I will proceed
- either I'll update the Urlview binding to use a lowercase u
- either I disable the TPM binding (if possible) as Oh my tmux! supports updating plugins on launch or conf reload (see `.tmux.conf.local`)

**Comment by bjesus** [comment]
Thanks for looking into this! 

Personally I don't have a preference regarding which one changes, but just wanted to point out tht it seems like TPM has the binding configurable - https://github.com/tmux-plugins/tpm/blob/master/tpm#L63

**Comment by gpakosz** [comment]
And to be honest I'm also doubting the usefulness of Urlview and Facebook Pathpicker 🤔

**Comment by gpakosz** [comment]
Hello @bjesus 👋

Can you please try the `gh-507` branch?

**Comment by bjesus** [comment]
This works great for me - `u` for updating and `U` for Urlview!
