### ISSUE TITLE
Weird terminal behavior

### ISSUE THREAD

**Issue by milanaleksic** [gpakosz/.tmux#51]
Hi, would you know what could be cause of the behavior as shown in the screenshot?

I have used tmux for years but I moved to your config and suddenly it started behaving... awkwardly as you can see, with double/tripple status bar etc.
![2017-01-30-102306_1920x1080_scrot](https://cloud.githubusercontent.com/assets/50055/22417796/561a595e-e6d6-11e6-80be-cc626ad248d6.png)

I am using latest Ubuntu 16.10 with latest bash, tmux 2.2 and latest code of gpakosz/.tmux

**Comment by gpakosz** [comment]
This is caused by VTE not rendering Unicode symbols / emojis properly.

If you take the `.tmux.conf.local` file from the `non-unicode-symbols` branch, this should work around the problem. Please keep me posted.

**Comment by milanaleksic** [comment]
I can confirm that indeed if all unicode characters are removed functionality remains, coolness is gone :( but everything works :+1:

Feel free to close this issue since it's something that is not a real-life problem. 

P.S. If you do know of a way how to make vte work properly with unicode please share :)

**Comment by gpakosz** [comment]
Try on a case by case basis. Typically, the keyboard symbol I used to signal the prefix indicator is troublesome as depending on the font it may take the width of two chars and that's likely what makes VTE go off

**Comment by luisdavim** [comment]
@milanaleksic try using font awesome icons instead.

**Comment by oswinfox** [comment]
Hello, I'am experience the same issue... I am using Arch. 

I see you said: 'If you take the .tmux.conf.local file from the non-unicode-symbols branch, this should work around the problem.' But i cannot find the non-unicode-symbols branch... Does it still exist? 

Thanks

**Comment by gpakosz** [comment]
See the `upcoming` branch

**Comment by oswinfox** [comment]
Ok it works!!! This is perfect, thank you so much ^^
