### ISSUE TITLE
Post .tmux hook

### ISSUE THREAD

**Issue by poetaman** [gpakosz/.tmux#511]
.tmux runs everything after user's configuration. At times user would want some shell script to run after .tmux is done executing its commands. So the request is to add a ``post_hook_script`` variable, which if not empty, will be run using ``tmux run-shell $post_hook_script``. This way user will be able to override something that .tmux sets by default.

Practical example: I am coding a script that parses popular color schemes, and applies it to tmux. I want to use it in conjunction with .tmux. But if I have the script run at the end of my .tmux.conf.local, the foreground & background colors from it are overridden by .tmux (perhaps because .tmux applies its own commands at the very end). Such a variable would allow overriding some of .tmux's changes at the last moment...

**Comment by gpakosz** [comment]
Hello @reportaman 👋

Not sure I want to add such a way to extend Oh my tmux!

About your practical, imho the proper way to go is to do your parsing job then assign `tmux_conf_theme_xxx` variables accordingly

**Comment by gpakosz** [comment]
Disabling theming altogether might be too brutal and should be a separate issue. I'm sure people will want some bits but not some others

**Comment by gpakosz** [comment]
About a "hook" (note this won't be a tmux hook), Oh my tmux! TPM integration runs TPM and its plugins in the background which means
- either the hook fires before TPM and its plugins finish altering the configuration
- either the hook fires after TPM and its plugins finish and then there will be an amount of time during which tmux has started but the things you want to do as part of the hook won't be applied

**Comment by NeckBeardPrince** [comment]
@gpakosz Any chance of this getting worked on? and #536

**Comment by gpakosz** [comment]
Hello @NeckBeardPrince 👋

[As I mentioned above](https://github.com/gpakosz/.tmux/issues/511#issuecomment-946429641), I don't believe I can come up with a satisfying behavior for a "post config" hook.

Here what could happen:
- The "post config" hook fires before `_apply_plugins()`: the hook fires while TPM is being downloading and installing plugins. This means the configuration can be changed by TPM plugins after the hook has fired
- The "post config" hook fires after `_apply_plugins()`: the hook fires after TPM has finished downloading and installing plugins. This means you'll be able to interact with the first created window/pane before the hook has fired
