### ISSUE TITLE
Check for internet connection before updating plugins

### ISSUE THREAD

**Issue by arush-sal** [gpakosz/.tmux#513]
This has been a big issue and hassle as if I start tmux without connecting to a network the plugin updation stage fails and none of the plugins work after that. Hence the should be some form of a check to determine if the system has a working internet or not before trying to update the plugins.

**Comment by gpakosz** [comment]
Hello @arush-sal 👋

Can you please try the `gh-513` branch?

**Comment by arush-sal** [comment]
@gpakosz the added code change definitely does works, but for some weird reason, it's not activating the installed plugin(s). In my test performed it didn't activate the `ressurect` plugin which restores all of the sessions, windows, and panes.

**Comment by gpakosz** [comment]
I pushed a fixup commit, can you please try again?

**Comment by arush-sal** [comment]
![giphy](https://user-images.githubusercontent.com/8846519/131359045-2e08760c-b0d9-47da-a3c7-5ac4f3b90af2.gif)
