### ISSUE TITLE
new-window -c '#{pane_current_path}' binding is replaced with only new-window

### ISSUE THREAD

**Issue by shubidubapp** [gpakosz/.tmux#514]
This was also mentioned at another issue (262) it has been more then 2 years since it was closed so I have decided to bring this in a new issue. No need to send a notification to original issue author since they solved their problem.

It seems like we still can not have different bindings new-window with or without `-c '#{pane_current_path}'` as configuration removes the -c binding and re adds it if `tmux_conf_new_window_retain_current_path` is true.

Now I would like to have 2 bindings where one of them retains the current path and the other one doesnt. I can only think of one solution which is to find and disable perl code where it removes the current path option. Which is a solution that only works for me. So as gpakosz mentioned in the issue 262, we need a way to protect bindings. A solution that comes to my mind is altering the perl regex(? im not sure what they are called) where it will not match if a binding has a certain change. 

This should be the original regex where it matches with any binding as long as it has `-c "#{pane_current_path}"`
`s/\bnew-window\b([^;}\n]*?)(?:\s+-c\s+((?:\\\\\")?|\"?|'?)#\{pane_current_path\}\2)/new-window\1/g`

My most instant approach was to edit it so it will not match if there are multiple "space" characters between -c and "#{pane_current_path}" so the \s+ will be only \s but it didn't work. for some reason. Are there any other work around you can suggest?

**Comment by gpakosz** [comment]
Hello @shubidubapp 👋

This is still a limitation and I have no proper solution for protecting some bindings.

I'll give it more thought.

**Comment by gpakosz** [comment]
Hello @shubidubapp 👋

Can you please try the `gh-514` branch that allows you to set the following configuration variables to `disabled`
  - `tmux_conf_new_window_retain_current_path`
  - `tmux_conf_new_pane_retain_current_path`
  - `tmux_conf_new_pane_reconnect_ssh`
  - `tmux_conf_new_session_prompt`
  - `tmux_conf_copy_to_os_clipboard`

**Comment by shubidubapp** [comment]
Hello @gpakosz

Thanks for the information. I will be trying it out.

**Comment by gpakosz** [comment]
No worry!

I forgot to push a fixup commit to the `gh-514` branch that fixes an obvious mistake in `_is_disabled()`.

About debugging, it's a big icky but doable. What I do is replace
```
# _apply_bindings() {
#   cfg=$(mktemp) && trap 'rm -f $cfg*' EXIT
...
```
by
```
# _apply_bindings() {
#   cfg=/tmp/tmux.conf
#.  exec 2 >/tmp/log.txt
#.  set -x
...`

And every time I reload the conf I can inspect `/tmp/log.txt`

**Comment by shubidubapp** [comment]
Yup last commit fixed the problem and the "disabled" key is actually a pretty good idea. Thank you for the fix.

**Comment by imcaizheng** [comment]
Hi, I ran into some sort of syntax error when `tmux_conf_new_window_retain_current_path` is set to `true`. Can reproduce the error even with the latest commit of the master branch.

Removing [these two lines](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L747-L748) temporarily fixed the error for me. Does anyone know the root cause of this issue?

**Comment by gpakosz** [comment]
@imcaizheng Can you please open a separate issue in which you detail your configuration? OS? tmux version? Thanks!

**Comment by imcaizheng** [comment]
@gpakosz I open a new issue here https://github.com/gpakosz/.tmux/issues/541

**Comment by gpakosz** [comment]
Hello here can you please try the `gh-571` branch?
