### ISSUE TITLE
Uptime for ssh server in active pane

### ISSUE THREAD

**Issue by mattboy9921** [gpakosz/.tmux#515]
Hi, I'm not the greatest when it comes to this level of scripting. I've taken a look at how `_uptime()` and `_hostname()` work in `.tmux.conf` but it is way over my head on where to start to somehow combine them.

Basically, I'm just looking for a way to have the uptime show for the machine I'm currently SSHed into in any given pane rather than just the host computer (in my case it is just another VM I use to connect to each of the others).

**Comment by gpakosz** [comment]
Hello @mattboy9921 👋

What you're asking is difficult to generalize, can only be achieved with a specific setup and certainly won't be lightweight.

What you're asking is (restricting the solution to Linux hosts to simplify explanations)
1. for the active pane, determine whether the process running is `ssh` or not (basically what `_username()` and `_hostname()` do)
2. if the process running is `ssh`, connect to the proper host with the proper username
3. and run `cut -d" " -f1 < /proc/uptime` there

For step 2 and 3, it means configuring your ssh setup to use keys instead of passwords. You may even set things up to connect to the hostname using a specific user that's only allowed to run the command in step 3.

I believe it's just simpler to run a tmux session on the remote host itself.

![image](https://user-images.githubusercontent.com/553208/133152000-62b0c920-b2a7-45b6-b5df-52c1a45f9a30.png)

**Comment by mattboy9921** [comment]
First, thank you so much for the speedy reply @gpakosz!

I see. So a bit more on my setup, I do use keys for every server. I have one key they all share and use the same username for all of them. So that might not be an issue for me.

I prefer to have a single tmux session on my "host", rather than have it run on every machine. Essentially, I configured a VM that I always SSH into, that runs tmux with all the customizations, then within that I can open up any of my other servers via SSH in that. Then, from wherever I log into the SSH VM, I can see the same set of open windows/panes. Allows me to pick up where I left off. 

I'm trying to figure out the way it works by looking at the `_hostname()` function. I'd love to try executing the parts of the function to see what they return but I don't really understand where the code gets executed. Is it just bash? I guess what I am asking is if there is any documentation or guide on how to get started if I tried to write my own function to do this?

**Comment by gpakosz** [comment]
I gave it a shot. I don't recommend it. It's nor fast nor generalizable.

You'll need the `gh-515` branch then you can edit your `~/.tmux.conf.local` copy:

```
...

tmux_conf_theme_status_right="#{uptime_ssh #{pane_tty}}"

...

# online() {
#   ping -c 1 1.1.1.1 >/dev/null 2>&1 && printf '✔' || printf '✘'
# }
#
# uptime_ssh() {
#   tty=$1
#
#   shift $#
#   eval "$(cut -c3- ~/.tmux.conf)"
#   tty_info=$(_tty_info "$tty")
#   command=${tty_info#*:}
#   command=${command#*:}
#
#   ssh_or_mosh_args=$(_ssh_or_mosh_args "$command")
#   if [ -n "$ssh_or_mosh_args" ]; then
#     conf=$(ssh -G $ssh_or_mosh_args 2>/dev/null | grep -E '^user |^hostname ')
#     [ -z "$conf" ] && conf=$(ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" $ssh_or_mosh_args 2>&1 | grep '^user |^hostname ')
#     username=$(echo "$conf" | awk '/^user / { print $2; exit }')
#     hostname=$(echo "$conf" | awk '/^hostname / { print $2; exit }')
#
#     boot=0
#     now=$(ssh "$username@$hostname" 'cut -d" " -f1 < /proc/uptime')
#
#     awk -v boot="$boot" -v now="$now" '
#       BEGIN {
#         uptime = now - boot
#         y = int(uptime / 31536000)
#         dy = int(uptime / 86400) % 365
#         d = int(uptime / 86400)
#         h = int(uptime / 3600) % 24
#         m = int(uptime / 60) % 60
#         s = int(uptime) % 60
#
#         printf "%dy %dh %dm", d, h, m
#       }'
#   fi
# }
#
# "$@"
# # /!\ do not remove the previous line
```

**Comment by gpakosz** [comment]
@mattboy9921 👋

Did you give it a try by chance?

**Comment by mattboy9921** [comment]
I'm sorry, I've been so busy the past few days it fell off my radar. I will try it out today and let you know :)

**Comment by gpakosz** [comment]
I merged the `gh-515` branch into `master`.

The following commit is needed:
```
commit 1cd8ed93d33f3ad4384d486bc6092507a0bb7713
Author: Gregory Pakosz <gregory.pakosz@gmail.com>
Date:   Wed Sep 15 23:01:32 2021 +0200

    added support for arguments to custom variables defined in ~/.tmux.conf.local
```

You can proceed to edit your `~/.tmux.conf.local` copy with:
```
..

tmux_conf_theme_status_right="#{uptime_ssh #{pane_pid} #{pane_tty}}"

...

# online() {
#   ping -c 1 1.1.1.1 >/dev/null 2>&1 && printf '✔' || printf '✘'
# }
#
# _pane_info() {
#   pane_pid="$1"
#   tty="${2##/dev/}"
#   case "$_uname_s" in
#     *CYGWIN*)
#       ps -al | tail -n +2 | awk -v pane_pid="$pane_pid" -v tty="$tty" '
#         ((/ssh/ && !/-W/) || !/ssh/) && $5 == tty {
#           user[$1] = $6; parent[$1] = $2; child[$2] = $1
#         }
#         END {
#           pid = pane_pid
#           while (child[pid])
#             pid = child[pid]
#
#           print pid":"user[pid]":"command[pid]
#           file = "/proc/" pid "/cmdline"; getline command < file; close(file)
#           gsub(/\0/, " ", command)
#           "id -un " user[pid] | getline username
#           print pid":"username":"command
#         }
#       '
#       ;;
#     *)
#       ps -t "$tty" -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command= | awk -v pane_pid="$pane_pid" '
#         NR > 1 && ((/ssh/ && !/-W/) || !/ssh/) {
#           user[$2] = $1; parent[$2] = $3; child[$3] = $2; pid=$2; $1 = $2 = $3 = ""; command[pid] = substr($0,4)
#         }
#         END {
#           pid = pane_pid
#           while (child[pid])
#             pid = child[pid]
#
#           print pid":"user[pid]":"command[pid]
#         }
#       '
#       ;;
#   esac
# }
#
# _ssh_or_mosh_args() {
#   case "$1" in
#     *ssh*)
#       args=$(printf '%s' "$1" | perl -n -e 'print if s/(.*?)\bssh\b\s+(.*)/\2/')
#       ;;
#     *mosh-client*)
#       args=$(printf '%s' "$1" | sed -E -e 's/.*mosh-client -# (.*)\|.*$/\1/' -e 's/-[^ ]*//g' -e 's/\d:\d//g')
#       ;;
#   esac
#
#  printf '%s' "$args"
# }
#
# uptime_ssh() {
#   pane_pid="$1"
#   pane_tty="$2"
#
#   pane_info=$(_pane_info "$pane_pid" "$pane_tty")
#   command=${pane_info#*:}
#   command=${command#*:}
#
#   ssh_or_mosh_args=$(_ssh_or_mosh_args "$command")
#   if [ -n "$ssh_or_mosh_args" ]; then
#     conf=$(ssh -G $ssh_or_mosh_args 2>/dev/null | grep -E '^user |^hostname ')
#     [ -z "$conf" ] && conf=$(ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" $ssh_or_mosh_args 2>&1 | grep '^user |^hostname ')
#     username=$(echo "$conf" | awk '/^user / { print $2; exit }')
#     hostname=$(echo "$conf" | awk '/^hostname / { print $2; exit }')
#
#     boot=0
#     now=$(ssh "$username@$hostname" 'cut -d" " -f1 < /proc/uptime')
#
#     awk -v boot="$boot" -v now="$now" '
#       BEGIN {
#         uptime = now - boot
#         y = int(uptime / 31536000)
#         dy = int(uptime / 86400) % 365
#         d = int(uptime / 86400)
#         h = int(uptime / 3600) % 24
#         m = int(uptime / 60) % 60
#         s = int(uptime) % 60
#
#         printf "%dd %dh %dm", d, h, m
#       }'
#   fi
# }
#
# "$@"
# # /!\ do not remove the previous line
```

**Comment by mattboy9921** [comment]
@gpakosz With the latest commits to `gh-532`, it looks like the SSH uptime isn't showing anything other than 0h 0m 0s

**Comment by gpakosz** [comment]
Hmm seems to work for me. Are you sure the host you're sshing to is configured to accept ssh keys? It won't work with password based authentication

**Comment by mattboy9921** [comment]
Yes, all my hosts use a key on port 22, I don't have anything with password authentication. Are there any unusual settings I need on on the SSH config on the remote host?

**Comment by gpakosz** [comment]
Nope

**Comment by gpakosz** [comment]
What does the following print?
```
$ ssh <remote hostname> cut -d" " -f1 < /proc/uptime
```

**Comment by mattboy9921** [comment]
It gives a permission error:
![image](https://user-images.githubusercontent.com/15326668/141006560-96f1a498-6f16-4537-aeab-0e9c9b6812bd.png)

**Comment by gpakosz** [comment]
Well if your ssh keys are not in a standard location and you need to pass `-i` then `uptime_ssh()` won't work

**Comment by mattboy9921** [comment]
I have linked the key to `~/.ssh/id_rsa`. Now it seems to be working! My bad 🤦 

Is it possible for me to have it swap between the host uptime and the ssh host uptime depending on if I'm on the host or the ssh host?

**Comment by gpakosz** [comment]
Sure, you just need to adjust the `uptime_ssh()` function to your own needs

For example
```
# uptime_ssh() {
#   pane_pid="$1"
#   pane_tty="$2"
#
#   pane_info=$(_pane_info "$pane_pid" "$pane_tty")
#   command=${pane_info#*:}
#   command=${command#*:}
#
#   ssh_or_mosh_args=$(_ssh_or_mosh_args "$command")
#   if [ -n "$ssh_or_mosh_args" ]; then
#     conf=$(ssh -G $ssh_or_mosh_args 2>/dev/null | grep -E '^user |^hostname ')
#     [ -z "$conf" ] && conf=$(ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" $ssh_or_mosh_args 2>&1 | grep '^user |^hostname ')
#     username=$(echo "$conf" | awk '/^user / { print $2; exit }')
#     hostname=$(echo "$conf" | awk '/^hostname / { print $2; exit }')
#
#     boot = 0
#     now=$(ssh "$username@$hostname" 'cut -d" " -f1 < /proc/uptime')
#   else
#     case "$(uname -s)" in
#       *Darwin*|*FreeBSD*)
#         boot=$(sysctl -q -n kern.boottime | awk -F'[ ,:]+' '{ print $4 }')
#         now=$(date +%s)
#         ;;
#       *Linux*|*CYGWIN*|*MSYS*|*MINGW*)
#         boot=0
#         now=$(cut -d' ' -f1 < /proc/uptime)
#         ;;
#       *OpenBSD*)
#         boot=$(sysctl -n kern.boottime)
#         now=$(date +%s)
#     esac
#   fi
#
#   awk -v boot="$boot" -v now="$now" '
#     BEGIN {
#       uptime = now - boot
#       y = int(uptime / 31536000)
#       dy = int(uptime / 86400) % 365
#       d = int(uptime / 86400)
#       h = int(uptime / 3600) % 24
#       m = int(uptime / 60) % 60
#       s = int(uptime) % 60
#
#       printf "%dd %dh %dm", d, h, m
#     }'
# }
```

**Comment by mattboy9921** [comment]
This works perfectly! I did note that if any of my servers show as 0h, it usually comes from an offending entry in the known hosts file. Once that is fixed, seems to be working flawlessly. Thank you so much for your help!

**Comment by ww7** [comment]
@gpakosz, thank you!

How often `uptime_ssh` will be called?

**Comment by gpakosz** [comment]
@ww7 When tmux refreshes the status bar

**Comment by ww7** [comment]
@gpakosz how often tmux refreshes the status bar?

**Comment by ww7** [comment]
Thanks! Default value of redraw status line (interval) is 10 seconds.

**Comment by ww7** [comment]
Example not works with SSH on custom ports, tweaked part:
```
#     conf=$(ssh -G $ssh_or_mosh_args 2>/dev/null | grep -E '^user |^hostname |^port ')
#     [ -z "$conf" ] && conf=$(ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" $ssh_or_mosh_args 2>&1 | grep '^user |^hostname |^port ')
#     username=$(echo "$conf" | awk '/^user / { print $2; exit }')
#     hostname=$(echo "$conf" | awk '/^hostname / { print $2; exit }')
#     port=$(echo "$conf" | awk '/^port/ { print $2; exit }')
#
#     boot=0
#     now=$(ssh "$username@$hostname" -p$port 'cut -d" " -f1 < /proc/uptime')
```

**Comment by ww7** [comment]
@gpakosz can you please very shortly explain why fallback (with ProxyCommand) needed and in which cases
```
#     conf=$(ssh -G $ssh_or_mosh_args 2>/dev/null | grep -E '^user |^hostname |^port |^identityfile ')
#     [ -z "$conf" ] && conf=$(ssh -T -o ControlPath=none -o ProxyCommand="sh -c 'echo %%username%% %r >&2'" $ssh_or_mosh_args 2>&1 | grep '^user |^hostname |^port |^identityfile ')
```

**Comment by gpakosz** [comment]
Old versions of SSH
