### ISSUE TITLE
Can't change select-pane binding?

### ISSUE THREAD

**Issue by lihaosky** [gpakosz/.tmux#517]
Hi,

Thanks for the awesome config! I was trying to bind select pane to different keys rather then <prefix> + H etc.

I tried to configure it in multiple ways in .tmux.conf.local as well as trying to change .tmux.conf but none worked.
```
bind -n M-h select-pane -L
bind -n C-h select-pane -L
```
Is this a known issue?

I'm using iTerm2 3.4.8 and tmux 3.2a

Thanks!

**Comment by gpakosz** [comment]
Hello @lihaosky 👋

Do the bindings work without Oh my tmux!?

You can try launching it this way:
```
$ tmux -L test -f /dev/null
```

**Comment by lihaosky** [comment]
Without Oh my tmux! 
`tmux list-keys` shows `select-pane -L` is `<prefix> LEFT`. But this doesn't work either... Put other bindings also doesn't work.

With Oh my tmux! `<prefix> h` works but even if I change `bind -r h select-pane -L` to something else, still only `<prefix> h` works to select left pane. 

Weird...

**Comment by gpakosz** [comment]
So, `bind C-h select-pane -L` works for me and `bind M-h select-pane -L` works if I use the right option key on my Macbook Pro keyboard.

I suggest you make it work without Oh my Tmux! first as there's no reason this configuration breaks it.

Look into iTerm and macOS settings.

Good luck!

**Comment by lihaosky** [comment]
Thanks. It's working now. I mistaken `pane` and `window`.
