### ISSUE TITLE
tmux_conf_new_session_prompt option does not work

### ISSUE THREAD

**Issue by s1n7ax** [gpakosz/.tmux#518]
In the configuration I have `tmux_conf_new_session_prompt=true`. How ever when I create a new session `tmux new-session` it never prompts to enter a session name.

**Comment by gpakosz** [comment]
Hello @s1n7ax 👋

1. Did you reload the configuration after setting `tmux_conf_new_session_prompt=true` in your `~/.tmux.conf.local` copy?
2. Can you please paste the output of `tmux lsk | grep new-session` after having reloaded the configuration?

**Comment by s1n7ax** [comment]
@gpakosz 
I edited the configuration using <c-b>e. After save and close I think it resourced the config. I tried `tmux kill-server` also.

```
tmux lsk | grep new-session
bind-key    -T prefix       C-c                  command-prompt -p new-session "new-session -s \"%%\""
bind-key    -T root         MouseDown3StatusLeft display-menu -T "#[align=centre]#{session_name}" -t = -x M -y W Next n "switch-client -n" Previous p "switch-client -p" '' Renumber N "move-window -r" Rename n "command-prompt
-I \"#S\" \"rename-session -- '%%'\"" '' "New Session" s "command-prompt -p new-session \"new-session -s \\\"%%\\\"\"" "New Window" w new-window
```

In the `.tmux.config` I see a lot of commented lines. Am I supposed to uncomment those?

**Comment by gpakosz** [comment]
> ```
> tmux lsk | grep new-session
> bind-key    -T prefix       C-c                  command-prompt -p new-session "new-session -s \"%%\""
> ```

Maybe there's a misunderstanding.
As far as I can tell, setting `tmux_conf_new_session_prompt=true` in your `~/.tmux.conf.local` copy works and when you use `<prefix> + C-c`, then you'll be prompted when creating a new session.

However, you won't be prompted if you e.g. do `: new-session` in command mode.

> In the .tmux.config I see a lot of commented lines. Am I supposed to uncomment those?

What's `.tmux.config`?

**Comment by s1n7ax** [comment]
Oh. ok. got it. <c-b><c-c> works. I thought i supposed to prompt when using `tmux new`
