### ISSUE TITLE
ssh hostname shows IP address instead of hostname

### ISSUE THREAD

**Issue by amanvm** [gpakosz/.tmux#519]
Hi,

Unlike in your GIF, sshing shows IP address in the hostname field instead of hostname... Is there a way to get around that?

Here are the contents of my ``~/.ssh/config``

```
Host debianlinux
    Hostname 10.211.55.10
Host archlinux
    Hostname 10.211.55.8
```

Here's the screenshot:
![Screen Shot 2021-09-27 at 12 27 13 PM](https://user-images.githubusercontent.com/25681815/134973612-dbcf14ae-cf26-4a7e-81e9-58817a5b53b1.png)

**Comment by amanvm** [comment]
As a sidenote, am running Arch linux and Debian linux as virtual machine on my Mac computer. Not sure if that matters.

The command I typed to login is ``ssh amanmehra@archlinux`` & ``ssh amanmehra@debianlinux``. So I guess, all that is needed is a translation of 10.211.55.10 -> debianlinux, and 10.211.55.8 -> archlinux. Both of which seems to be possible by looking up ``~/.ssh/config``...

**Comment by gpakosz** [comment]
Hello @amanvm 👋

I suspect your `~/.ssh/config` somewhat looks like this
```
Host archlinux
  HostName 10.211.55.8
  User amanmehra
...
```

If it's the case, then currently there's no way to display `archlinux` as Oh my tmux! doesn't parse `~/.ssh/config` nor `/etc/ssh/ssh_config` and it seems out of scope to do so reliably.

**Comment by amanvm** [comment]
@gpakosz I have another idea then... You can find the exact command that is running in the pane, and use that to parse instead! Point me to the code where you do this parsing... That way when user enters ``>>ssh amanmehra@debianlinux``, oh my tmux will see ``ssh amanmehra@debianlinux`` as a string to parse from...

**Comment by amanvm** [comment]
@gpakosz ``When you do ssh archlinux, what Oh my tmux! does is parsing`` does that mean all of the commands I enter are seen by oh my tmux? I have wanted to do something similar, it would be great if you could point me to the code . And yes Hello 👋 :)

**Comment by gpakosz** [comment]
> does that mean all of the commands I enter are seen by oh my tmux?
Yes and no. There's no hook. But given a TTY, Oh my tmux! does its best to know which is the command being run in that TTY. This is achieved by `_tty_info()`. Then `_ssh_or_mosh_args()` extracts the parameters given to `ssh` or `mosh` and use that along with `ssh -G`.

Parsing `ssh <something>` is fragile. You need to handle many cases:
>      ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface] [-b bind_address] [-c cipher_spec] [-D [bind_address:]port] [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
>          [-i identity_file] [-J destination] [-L address] [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
>          [-w local_tun[:remote_tun]] destination [command]

I think it's far easier to work around the problem by updating your `/etc/hosts` file instead of modifying `~/.ssh/config` and wanting to parse the ssh command

**Comment by amanvm** [comment]
@gpakosz Yes, editing ``/etc/hosts`` file & removing the corresponding lines from ``~/.ssh/config`` works! Given I am the admin of my own machine, I have permissions to edit ``/ etc/hosts``. For machines where one doesn't permission to edit ``/etc/hosts`` (like work environment), I guess it makes sense to just display the IP address in hostname field & I will stick with ``~/.ssh/config`` there. Thanks!!
