### ISSUE TITLE
"set -s escape-time 0" and Windows Subsystem for Linux

### ISSUE THREAD

**Issue by bubble-joe** [gpakosz/.tmux#52]
This configuration makes tmux unusable under [WSL](https://msdn.microsoft.com/commandline/wsl/about).
Commenting out "set -s escape-time 0" solves the issue.

**Comment by gpakosz** [comment]
Hello, thanks for the report. I'll look into it. I didn't bother with WSL yet since it doesn't support UTF-8 yet

**Comment by gpakosz** [comment]
Also, can you please define "makes tmux unusable" ?

**Comment by bubble-joe** [comment]
I can't scroll the buffer back unless I revert escape-time to 500.

If escape-time is set to 0, pressing C -b then PgUp simply outputs  `[5~`

**Comment by gpakosz** [comment]
Did you explicitly bind `PgUp`? or is it a default binding?

**Comment by bubble-joe** [comment]
It's a default binding.

**Comment by gpakosz** [comment]
I honestly don't remember what I solved when setting `escape-time` to `0` instead of the `500` default value. I need time to figure this out :)

**Comment by bubble-joe** [comment]
No worries, that's exactly what I did.

[Screenshot of the issue](http://i.imgur.com/SBP4KBC.jpg)
