### ISSUE TITLE
The feature "maximize any pane to a new window with" is already a built-in part of tmux

### ISSUE THREAD

**Issue by trallnag** [gpakosz/.tmux#521]
The default keybinding is `prefix + !`. So it is not really a new feature as long as we are not talking about old versions of tmux that don't support it.

Just wanted to point that out

**Comment by gpakosz** [comment]
Hello 👋

Thanks for pointing that out!

Please let me quote `README.md`

> The "maximize any pane to a new window with `<prefix> +`" feature is different
from builtin `resize-pane -Z` as it allows you to further split a maximized
pane. It's also more flexible by allowing you to maximize a pane to a new
window, then change window, then go back and the pane is still in maximized
state in its own window. You can then minimize a pane by using `<prefix> +`
either from the source window or the maximized window.
