### ISSUE TITLE
How to fix vim colors on mac terminal

### ISSUE THREAD

**Issue by GenaANTG** [gpakosz/.tmux#523]
### Issue description

First of all i want respect you for this config. <3
And question is: **How to fix background highlight in normal vim mode?**
Outside of tmux i have no those highlights.

<img width="722" alt="Screenshot 2021-10-08 at 15 15 31" src="https://user-images.githubusercontent.com/12715550/136557296-43b99e6d-26d6-459e-9e61-313db250d9fd.png">

### Required information

Please provide the following information:

* tmux version: tmux 3.2a
* Platform: Darwin i386
* $TERM inside and outside of tmux: outside -> xterm-256color; inside -> screen-256color

**Comment by GenaANTG** [comment]
<img width="529" alt="Screenshot 2021-10-09 at 23 54 52" src="https://user-images.githubusercontent.com/12715550/136673536-92e8628e-f36c-4317-8cf0-3b32917e03f7.png">

**Comment by GenaANTG** [comment]
@gpakosz Thanks mate! When VIM is running without tmux i have no those background highlights. Do you think that problem is with VIM only?

**Comment by GenaANTG** [comment]
On mac you can fix it with next setting for tmux: set -g default-terminal "xterm-256color"

**Comment by gpakosz** [comment]
Except https://github.com/tmux/tmux/wiki/FAQ starts with

> Inside tmux TERM must be "screen", "tmux" or similar (such as "tmux-256color").
Don't bother reporting problems where it isn't!
> 
> Outside, it should match your terminal: particularly, use "rxvt" for rxvt
and derivatives.
