### ISSUE TITLE
Did somebody see a splash message at startup like this? nothing is wrong but the splash,a little annoying

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [gpakosz/.tmux#529]
![image](https://user-images.githubusercontent.com/2133400/139678394-c70bd6ca-fcde-4a80-bd44-3df8623c0c06.png)
will disappear quickly, I must record the screen and play it slowly to cut this screen.

MacOS, tmux 3.2 , most recent conf version.

**Comment by gpakosz** [comment]
Hello @FinallyFinancialFreedom 👋

This is currently  a tmux limitation. The next version of tmux behaves slightly differently and this won't happen anymore.

**Comment by FinallyFinancialFreedom** [comment]
thank you , should i update tmux to 3.3-rc?

**Comment by gpakosz** [comment]
Your choice.

As you noticed, this `<... not ready>` "flash" is harmless and happens only briefly when starting tmux with Oh my tmux!
