### ISSUE TITLE
Unbind C-a via .tmux.conf.local

### ISSUE THREAD

**Issue by bubble-joe** [gpakosz/.tmux#53]
Hi,
How can I disable the GNU-Screen compatible prefix via .tmux.conf.local?
Thanks

**Comment by gpakosz** [comment]
```
set -gu prefix2
unbind C-a
```

**Comment by bubble-joe** [comment]
Thanks!

**Comment by seagle0128** [comment]
Sorry. I know this has been closed, but the solution from @gpakosz doesn't work in my tmux. Any idea?

Ubuntu 16.04
tmux 2.1

**Comment by hqythu** [comment]
I tried to use those settings to disable C-a prefix on tmux 1.9 (on a server, which means I can't upgrade my tmux version), and I get the following:

> Can't unset global option: prefix2.

How can I do?

**Comment by gpakosz** [comment]
I'm sorry this configuration doesn't support tmux `1.9`.

**Comment by miguno** [comment]
For others arriving here via Internet search:

```
set -gu prefix2
unbind C-a
```
from https://github.com/gpakosz/.tmux/issues/53#issuecomment-276544577 works for me on tmux v3.1 and v3.2.
