### ISSUE TITLE
TPM blows up on Ubuntu 18.04

### ISSUE THREAD

**Issue by linsomniac** [gpakosz/.tmux#531]
First off, loving Oh My Tmux!

It's working great on Ubuntu 20.04.  On 18.04 however, with tmux 2.6-3, if I install fresh and uncomment the "copycat" line in the ".tmux.conf.local" file (via PREFIX-e), it says it's installing TPM, and then tmux exits.  If I run tmux again, it starts, runs a couple seconds and displays TPM message, and then exits again.  If I then comment it out again, I can start tmux.

If I build the tmux 20.04 package on 18.04 (3.0a-2) and install it, the uncomment the "copycat" line, tmux will start fine.

I'm assuming this is a tmux issue, but wanted to document it here.  Not really sure how track it down any further than just upgrading tmux, which in my case is a fine solution.

**Comment by gpakosz** [comment]
Hello @linsomniac 👋

This is caused by tmux/tmux@7ba5ad4cfb49a5de3971f823ba5d08d4760480c2.

I pushed the `gh-531` branch that should fix it for tmux `2.6`. Can you please give it a try?

**Comment by linsomniac** [comment]
I checked out gh-531 and reverted back to the stock Ubuntu 18.04 tmux package and it works just fine!  Thanks so much!

**Comment by gpakosz** [comment]
@linsomniac I fixed even more things for tmux `2.6`, can you please the `gh-532` branch a try and eventually report issues in #532?

**Comment by gpakosz** [comment]
I merged the `gh-532` branch.

Thanks for the sponsorship! ❤️

**Comment by linsomniac** [comment]
Sorry, I didn't get a chance to look at this until tonight.  I pulled master and it has the gh-532 changes in it, and it looks good in my little bit of testing.  I had seen that "variables not expanding in the bar" a few times when I was experimenting with things, but didn't really track it down.  In fact, when I logged into my 18.04 box to try the new code, I did a "tmux attach" and it was showing the "y h m d" in the lower left.  I did a Prefix-r and it updated to the actual values.  Then I exited tmux entirely and restarted and things look good.

Thanks for working on this.  My primary "home" laptop is a Chromebook that I love, and if I'm doing work on it I'm usually connecting to one of my work machines and running a screen.  But screen has some real issues, so this past weekend I decided to finally make the switch to tmux happen.  I tried making my own config, which was ok.  But I really like what you've done with this project and decided to try scrapping my custom config for it.

I'm so thankful for you putting this together.

**Comment by gpakosz** [comment]
> Sorry, I didn't get a chance to look at this until tonight

That's ok. The `master` was so broken for tmux `2.6` that it was worth merging fast and eventually waiting for other issues to be reported.

> I'm so thankful for you putting this together.

You're welcome! Happy tmuxing
