### ISSUE TITLE
Variables not rendering

### ISSUE THREAD

**Issue by mattboy9921** [gpakosz/.tmux#532]
I just tried to pull the latest changes (first time doing this for .tmux), but any variable I try to show in my status bar is missing.

![image](https://user-images.githubusercontent.com/15326668/140952559-8893fb88-cba8-4eff-994d-a11b02ad564d.png)

I've confirmed I have the correct `$TERM` variable set in my `.bashrc`, nothing has changed but pulling changes. I even deleted everything and started from scratch with the same results. 

I'm running Ubuntu 18.04.6, latest updates.

**Comment by gpakosz** [comment]
Hello @mattboy9921 👋

Can you please reload the configuration with `<prefix> + r`?

**Comment by mattboy9921** [comment]
Hi @gpakosz 

I just tried that and am still no luck. I am able to change other things, like adding a new section. Any literal text will show but not variables.

**Comment by gpakosz** [comment]
@mattboy9921 isn't it because you're using what we discussed in #515?

If yes, try using the most recent version of the script I gave in #515 (I remember having edited it to accommodate for implementation changes in Oh my tmux!)

**Comment by mattboy9921** [comment]
@gpakosz I did just try the script, but it just gives a blank section with no text in it. Regardless of what I put, any variables seem to just not show. It's like they're invisible. And the far right one shows as `%0` or `%1`.

**Comment by gpakosz** [comment]
Found the problem.

In the meantime please use commit `df46ab2ba97d7022cfe15d16a59baf3156b299b8`

**Comment by mattboy9921** [comment]
Can confirm, df46ab2ba97d7022cfe15d16a59baf3156b299b8 is working for me.

**Comment by gpakosz** [comment]
I pushed a fix in the `gh-532` branch

**Comment by mattboy9921** [comment]
Using `gh-532`, all the variables seem to work. I am testing the `#{uptime_ssh #{pane_pid} #{pane_tty}}` but it's just showing 0h 0m 0s the whole time.

**Comment by gpakosz** [comment]
Yeah I'm fixing those atm

**Comment by gpakosz** [comment]
Pushed yet another commit

**Comment by gpakosz** [comment]
@mattboy9921 Can we please finish making sure the stock config is working before reopening #515 if the custom `#{uptime_ssh}` function doesn't work anymore?

I see in your original screenshot that uptime values for current host don't work

**Comment by mattboy9921** [comment]
@gpakosz The stock config is working as far as I can tell. The regular uptime variable is working as it should as is everything else.

**Comment by gpakosz** [comment]
@mattboy9921 Cool let's move on #515
