### ISSUE TITLE
reconnect  ssh not working

### ISSUE THREAD

**Issue by unix2dos** [gpakosz/.tmux#535]
set `tmux_conf_new_pane_reconnect_ssh=true`,   opened a new panel, and it flashed,  and panel couldn't be opened.

set `tmux_conf_new_pane_reconnect_ssh=false`, panel can be opened.

**Comment by gpakosz** [comment]
Hello @unix2dos 👋

Can you please try the `gh-535` branch?

**Comment by gpakosz** [comment]
Well I'll merge the fix as I don't want other users to live with the bug. Feel free to reopen

**Comment by unix2dos** [comment]
checkout branch `gh-515`,  the problem is solve, thanks.
