### ISSUE TITLE
Feature: option to disable theming

### ISSUE THREAD

**Issue by poetaman** [gpakosz/.tmux#536]
As per https://github.com/gpakosz/.tmux/issues/511#issuecomment-951807852, please add an option to disable theming of panes and borders. That will 1) enable user to use another plugin that could handle theming in a more automated way, and/or 2) save user time/effort to change terminal theme in two places (one in their terminal emulator settings, and another in .tmux.conf.local of .tmux).

> Example plugin that could do dynamic theming is showcased here: https://github.com/tmux/tmux/pull/2931#issuecomment-951294667

**Comment by gpakosz** [comment]
Hello @poetaman 👋

I know I'm coming back late with a solution. You can try the `gh-536` branch if you still need to disable theming

**Comment by poetaman** [comment]
Hi @gpakosz 👋👋

Not a problem, I'll give it a try in next 24 hours, and report back.

**Comment by gpakosz** [comment]
See the new `.tmux.conf.local` sample, add `tmux_conf_theme=disabled` to your `~/.tmux.conf.local` copy

**Comment by gpakosz** [comment]
Hello @poetaman,

Did you get the chance to test the branch?

**Comment by poetaman** [comment]
@gpakosz I looked at the branch. It does disable the theming. Though it also changes the contents of status bar from using utf characters to something simpler?

**Comment by gpakosz** [comment]
I'm not sure what you call "from using utf characters to something simpler".

It does decode unicode character escapes with
```
_decode_unicode_escapes() {
  printf '%s' "$*" | perl -CS -pe 's/(\\u([0-9A-Fa-f]{1,4})|\\U([0-9A-Fa-f]{1,8}))/chr(hex($2.$3))/eg' 2>/dev/null
}
```
e.g. it transforms `\u0061` to `a`:
```
$ cut -c3- ~/.tmux.conf | sh -s _decode_unicode_escapes '\u0061'
a%

**Comment by poetaman** [comment]
Look at the screenshots below:

<img width="711" alt="Screenshot 2023-01-02 at 12 12 38 AM" src="https://user-images.githubusercontent.com/71736629/210207219-cf780d21-706d-4bb4-b1db-0ba6f35209ed.png">
<img width="711" alt="Screenshot 2023-01-02 at 12 13 19 AM" src="https://user-images.githubusercontent.com/71736629/210207227-4290efef-8adc-4019-8df9-b5e02b864b57.png">

Also, is there a way to route global/window option array ``pane-colours`` to derive color for different elements of .tmux status bar? Tmux added pane-colors array to be able to set and get global/window/pane 16 color palette.

**Comment by poetaman** [comment]
Check the tmux feature here: https://github.com/tmux/tmux/issues/2815#issuecomment-897142885

**Comment by gpakosz** [comment]
I don't see anything special in the screenshot.

When you disable theming, Oh my tmux! doesn't use `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right` any more.

The second screen just looks like the default `status-left` and `status-right` values.

**Comment by poetaman** [comment]
@gpakosz Got it, it does return what I see. There is one more intention: to adapt the theme of status bar on the fly as I change the tmux pane-colours array. What would that take? A step that could be needed for that is to keep using ``tmux_conf_theme_status_left`` and ``tmux_conf_theme_status_right`` but have a 16-color scheme that picks colors from global or window ``pane-colours`` array (if set).

**Comment by gpakosz** [comment]
> Also, is there a way to route global/window option array pane-colours to derive color for different elements of .tmux status bar? Tmux added pane-colours array to be able to set and get global/window/pane 16 color palette.

I didn't know about `pane-colours` until you mentioned it. I tried the following
```
$ tmux set -g status-right '#[fg=colour1]foo'
```
Then
```
$ tmux set -g 'pane-colours[1]' '#ffffff'
```
And it didn't change the colour in `status-right` (with my terminal theme, I expected the colour to change from red to white).

But the following kinda works
```
$ tmux set -g status-right '#[fg=#{pane-colours[1]}foo'
```
Then changing `pane-colours[1]` updates `status-right` accordingly. But that's just because of how tmux variables work and that's not how I expected `pane-colours` to work. 

In any case, Oh my tmux! is not the proper place to implement such a thing.
