### ISSUE TITLE
Architecture is i386 inside tmux on a M1 Mac

### ISSUE THREAD

**Issue by koichirose** [gpakosz/.tmux#537]
Running `arch` inside tmux returns `i386` instead of `arm64`.
This only happens if I use the `.tmux.conf` from this repo, so I found out that removing this fixes the issue:
https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L1450

I'm not sure what it does. `$default_shell` in my case is `/bin/zsh`

**Comment by gpakosz** [comment]
Hello @koichirose 👋

The line you're mentioning is only executed when `reattach-to-user-namespace` is installed.

Can you please paste the output of
```
$ command -v reattach-to-user-namespace
```

With modern macOS and tmux, there's no need to use this`reattach-to-user-namespace` anymore. Just uninstall it.

**Comment by koichirose** [comment]
Confirmed, I removed `reattach-to-user-namespace` and now the arch command correctly returns `amd64`.
Thank you very much!

**Comment by gpakosz** [comment]
Now I'm curious!

Did you freshly install `reattach-to-user-namespace` on a M1 Mac? Why? Did `README.md` make you believe you needed it?

**Comment by koichirose** [comment]
I did not! I migrated from my previous Intel Mac.
But yes, this would make me believe that it is needed:
https://github.com/gpakosz/.tmux/blob/master/README.md?plain=1#L115
Plus the whole section below about installing `reattach-to-user-namespace`

**Comment by gpakosz** [comment]
I see. I'll revisit `README.md`.

Happy tmuxing!
