### ISSUE TITLE
a453b7f makes prompt disappear after Ctrl-l

### ISSUE THREAD

**Issue by Frederick888** [gpakosz/.tmux#538]
Since a453b7f, after hitting <kbd>Ctrl</kbd><kbd>l</kbd>, Zsh prompt is also gone with command history, the whole pane becomes empty.

I tested this using Kitty/macOS built-in Console with tmux 3.2a.

I'm using [pygmalion](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/pygmalion.zsh-theme) theme from oh-my-zsh, not sure if this is relevant.

**Comment by gpakosz** [comment]
Hello @Frederick888 👋

Interesting. I'm using macOS and Oh my zsh and iTerm2. With `send-keys -R` I still get to see a prompt.

I'll revert to sending `C-l`.
