### ISSUE TITLE
Statusline is kinda broken on WSLTTY with installed fonts and tmux config.

### ISSUE THREAD

**Issue by cyb3rm4n** [gpakosz/.tmux#539]
What am i doing wronmg?
![изображение](https://user-images.githubusercontent.com/1812907/145175826-33af61be-bbfd-499d-b2d0-5ee0a91f5333.png)

**Comment by gpakosz** [comment]
Hello @cyb3rm4n 👋

By broken you mean the colors?

In any case I recommend using Windows Terminal nowadays.

**Comment by cyb3rm4n** [comment]
i mean its not as on the screenshots with arrow-like symbols

**Comment by gpakosz** [comment]
Please read installation instructions in `README.md`.

Make a copy the `.tmux.conf.local` file in your home directory then look at settings in this file.

Still, Windows Terminal works better than WSLTTY.

**Comment by cyb3rm4n** [comment]
![изображение](https://user-images.githubusercontent.com/1812907/145266711-bd1740f7-2add-4fed-b93e-ccf11012d4ef.png)
still don't work as excepted, but fonts are great.

**Comment by gpakosz** [comment]
Did you edit your `~/.tmux.conf.local` copy to enable powerline symbols?

**Comment by cyb3rm4n** [comment]
got it! now its fixed! Thank you!

**Comment by gpakosz** [comment]
@cyb3rm4n Are we good?

**Comment by cyb3rm4n** [comment]
@gpakosz tes, you can close the issue
