### ISSUE TITLE
Exit code when I start tmux

### ISSUE THREAD

**Issue by OlaoluwaM** [gpakosz/.tmux#540]
![image](https://user-images.githubusercontent.com/37044906/145256913-ab4cb7f6-ed50-4d59-a6ab-7ad5d0199686.png)

I get this whenever I start a new tmux session, which is done automatically thanks to ohmyzsh. What does this error mean and how can I resolve it? Thanks!

**Comment by gpakosz** [comment]
Hello @OlaoluwaM 👋

It means a tpm plugins failed to initialize.
Please make sure you Oh my tmux is up to date and reload the configuration with `<prefix> + r`. Then disable plugins in your `~/.tmux.conf.local` copy to identify the faulty plugin

**Comment by OlaoluwaM** [comment]
Thanks for the quick response! The error seems to disappear only when I have commented out all my plugins

Also, I noticed that only after I press `CTRL + C` after the exit code message shows up, that the plugins load. Does that mean anything?

**Comment by gpakosz** [comment]
Can you tell me what OS you're using, what version of tmux, and which plugins?

**Comment by OlaoluwaM** [comment]
OS: Fedora Workstation 35
Tmux: 3.2a
Plugins: tmux-resurrect, tmux-cpu, tmux-continuum, extrakto, tmux-urlview, tmux-network-bandwidth

**Comment by gpakosz** [comment]
Did you manage to do the following checks?
- disable all plugins and see if the error disappears
- if yes, enable plugins one by one until the error appears again

**Comment by OlaoluwaM** [comment]
Yes! I followed the checks

**Comment by OlaoluwaM** [comment]
> Thanks for the quick response! The error seems to disappear only when I have commented out all my plugins
> 
> Also, I noticed that only after I press `CTRL + C` after the exit code message shows up, that the plugins load. Does that mean anything?

Here are my observations

**Comment by gpakosz** [comment]
Ah yes sorry.

Can you please make sure you'r using commit `96d085eaa702a5c2b003961e46aa5378d7e6d93e` from the `master` branch then run this from within a tmux pane?
```
$ cut -c3- ~/.tmux.conf | sh -sx __apply_plugins "" true true true
```

**Comment by OlaoluwaM** [comment]
![image](https://user-images.githubusercontent.com/37044906/145684199-4ac744eb-19fa-41fb-9b1d-7c81f28b859d.png)

**Comment by OlaoluwaM** [comment]
This is the output of `cut -c3- ~/.tmux.conf | sh -sx __apply_plugins "" true true true`

![image](https://user-images.githubusercontent.com/37044906/145684226-2e582f0c-dc0b-46ac-bc1c-243c8bad5a32.png)

**Comment by OlaoluwaM** [comment]
Still getting the error when I startup tmux, I even recopied the `.tmux.conf` file from the new commit

**Comment by gpakosz** [comment]
And now can you please launch
```
$ tmux set -g @plugin dummy && cut -c3- ~/.tmux.conf | sh -sx __apply_plugins "" true true true
```

This should clone tpm into `~/.tmux/plugins/tpm`, install plugins and there also should be ` ~/.tmux/plugins/tpm_log.txt` file

**Comment by OlaoluwaM** [comment]
![image](https://user-images.githubusercontent.com/37044906/145689599-0b4ce659-ec99-4225-89ed-08a06283619e.png)

**Comment by OlaoluwaM** [comment]
![image](https://user-images.githubusercontent.com/37044906/145689605-e2ffff40-501b-4968-bb27-dee0a539af04.png)

**Comment by OlaoluwaM** [comment]
Error persists :(

**Comment by OlaoluwaM** [comment]
Here is the contents of the `~/.tmux/plugins/tpm_log.txt` file

![image](https://user-images.githubusercontent.com/37044906/145703223-fa1b39a7-b630-4e0e-adbd-e2f2776d9c17.png)

**Comment by gpakosz** [comment]
Are the screenshot you shared in the correct order?

Can you please paste the result as text instead?
I still can't understand which command has a `128` error code.

Also, I don't know what `Ctrl-C` does on your setup, can you please paste the output of
```
$ tmux lsk | grep C-c
```

**Comment by OlaoluwaM** [comment]
Oh sorry for the confusion. So whenever I start up my terminal with a new tmux session I get

`cut -c3- ~/.tmux.conf | sh -s __apply_plugins "" "true" "true" "true"' returned 128`

**Comment by OlaoluwaM** [comment]
Here is the output of `tmux set -g @plugin dummy && cut -c3- ~/.tmux.conf | sh -sx __apply_plugins "" true true true`
```bash
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
+ _tmux_version=320
+ command -v pkill
+ __apply_plugins '' true true true
+ window_active=
+ tmux_conf_update_plugins_on_launch=true
+ tmux_conf_update_plugins_on_reload=true
+ tmux_conf_uninstall_plugins_on_reload=true
+ TMUX_PLUGIN_MANAGER_PATH=/home/olaolu/.tmux/plugins
++ tmux show -gv @plugin
+ '[' -z dummy ']'
+ git ls-remote -hq https://github.com/gpakosz/.tmux.git master
+ '[' '!' -d /home/olaolu/.tmux/plugins/tpm ']'
+ '[' -z '' ']'
+ _is_enabled true
+ '[' xtrue = xtrue ']'
+ update_tpm=true
+ tmux display 'Updating tpm and plugins...'
+ cd /home/olaolu/.tmux/plugins/tpm
+ git checkout -q master
+ git reset -q --hard HEAD
+ git pull -q origin master
+ '[' x = xtrue ']'
+ '[' xtrue = xtrue ']'
+ perl -0777 -p -i -e 's/git clone/git clone --depth 1/g
                            ;s/(install_plugin "\$plugin")\n(\s+)done/\1&\n\2done\n\2wait/g' /home/olaolu/.tmux/plugins/tpm/scripts/install_plugins.sh
+ wait
+ perl -p -i -e 's/git submodule update --init --recursive/git submodule update --init --recursive --depth 1/g' /home/olaolu/.tmux/plugins/tpm/scripts/update_plugin.sh
+ perl -p -i -e 's,\$tmux_file\s+>/dev/null\s+2>\&1,$& || { tmux display "Plugin \$(basename \${plugin_path}) failed" && false; },' /home/olaolu/.tmux/plugins/tpm/scripts/source_plugins.sh
+ tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH /home/olaolu/.tmux/plugins
+ '[' xtrue = xtrue ']'
+ /home/olaolu/.tmux/plugins/tpm/bin/install_plugins
+ /home/olaolu/.tmux/plugins/tpm/bin/update_plugins all
+ /home/olaolu/.tmux/plugins/tpm/bin/clean_plugins all
+ tmux display 'Done updating tpm and plugins...'
++ tmux show -gqv @tpm-install
+ '[' -z '' ']'
+ tmux set -g @tpm-install I
++ tmux show -gqv @tpm-update
+ '[' -z '' ']'
+ tmux set -g @tpm-update u
++ tmux show -gqv @tpm-clean
+ '[' -z '' ']'
+ tmux set -g @tpm-clean M-u
+ '[' -f /home/olaolu/.tmux/plugins/tpm/tpm ']'
+ /home/olaolu/.tmux/plugins/tpm/tpm
+ '[' 320 -gt 260 ']'
+ tmux set -gu @tpm-install ';' set -gu @tpm-update ';' set -gu @tpm-clean ';' set -gu @plugin
+ '[' -z '' ']'
+ '[' 320 -lt 240 ']'
```

**Comment by OlaoluwaM** [comment]
Here are the contents of `~/.tmux/plugins/tpm_log.txt`

```bash
Already installed "tmux-resurrect"
Already installed "tmux-continuum"
Already installed "tmux-cpu"
Already installed "tmux-network-bandwidth"
Already installed "extrakto"
Already installed "tmux-urlview"
Updating all plugins!

  "tmux-network-bandwidth" update success
  "tmux-cpu" update success
  "extrakto" update success
  "tmux-resurrect" update success
  "tmux-urlview" update success
  "tmux-continuum" update success
```

**Comment by OlaoluwaM** [comment]
> Are the screenshot you shared in the correct order?
> 
> Can you please paste the result as text instead? I still can't understand which command has a `128` error code.
> 
> Also, I don't know what `Ctrl-C` does on your setup, can you please paste the output of
> 
> ```
> $ tmux lsk | grep C-c
> ```

Oh `Ctrl + C` just kills a process, it is not bound to any tmux operation

**Comment by gpakosz** [comment]
What I don't understand so far is why the exit code is `128` when you start tmux but is `0` when you launch `tmux set -g @plugin dummy && cut -c3- ~/.tmux.conf | sh -sx __apply_plugins "" true true true`

What's the output of `$ tmux lsk | grep C-c` btw?

**Comment by OlaoluwaM** [comment]
Here is the output of `tmux lsk | grep C-c`

```bash
 bind-key    -T copy-mode       C-c                  send-keys -X cancel
 bind-key    -T copy-mode-vi   C-c                  send-keys -X cancel
 bind-key    -T prefix                 C-c                  new-session
```

**Comment by gpakosz** [comment]
> Oh `Ctrl + C` just kills a process, it is not bound to any tmux operation

I don't think it kills anything to be honest. It would be `SIGINT` sent to tmux itself if you type `CTRL + C` when tmux is displaying its message

**Comment by OlaoluwaM** [comment]
Oh, okay, my bad. Anything else I can do to help debug this?

**Comment by gpakosz** [comment]
Can you please try the `gh-540` branch?

Quit tmux. Switch to the `gh-540` branch. Launch tmux, when you'll have a `/tmp/debug.txt` file that tries to capture what's going on with `__apply_plugins()`

**Comment by OlaoluwaM** [comment]
Also, I thought I should let you know that I had installed the `tmux` plugin for `oh-my-zsh`. With this plugin, I am able to auto-start `tmux` along with `oh-my-zsh` and when I exit `tmux` I also kill my terminal

![image](https://user-images.githubusercontent.com/37044906/145710491-2f4a46f7-6600-4766-9c73-fe0a09494b52.png)

**Comment by OlaoluwaM** [comment]
It worked!
Here are the contents of the `/tmp/debug.txt` file

```bash
  + window_active=
+ tmux_conf_update_plugins_on_launch=true
+ tmux_conf_update_plugins_on_reload=true
+ tmux_conf_uninstall_plugins_on_reload=true
+ TMUX_PLUGIN_MANAGER_PATH=/home/olaolu/.tmux/plugins
++ tmux show -gv @plugin
+ '[' -z tmux-plugins/tmux-urlview ']'
+ git ls-remote -hq https://github.com/gpakosz/.tmux.git master
+ '[' '!' -d /home/olaolu/.tmux/plugins/tpm ']'
+ '[' -z '' ']'
+ _is_enabled true
+ '[' xtrue = xtrue ']'
+ update_tpm=true
+ tmux display 'Updating tpm and plugins...'
+ cd /home/olaolu/.tmux/plugins/tpm
+ git checkout -q master
+ git reset -q --hard HEAD
+ git pull -q origin master
+ '[' x = xtrue ']'
+ '[' xtrue = xtrue ']'
+ perl -0777 -p -i -e 's/git clone/git clone --depth 1/g
                            ;s/(install_plugin "\$plugin")\n(\s+)done/\1&\n\2done\n\2wait/g' /home/olaolu/.tmux/plugins/tpm/scripts/install_plugins.sh
+ perl -p -i -e 's/git submodule update --init --recursive/git submodule update --init --recursive --depth 1/g' /home/olaolu/.tmux/plugins/tpm/scripts/update_plugin.sh
+ perl -p -i -e 's,\$tmux_file\s+>/dev/null\s+2>\&1,$& || { tmux display "Plugin \$(basename \${plugin_path}) failed" && false; },' /home/olaolu/.tmux/plugins/tpm/scripts/source_plugins.sh
+ tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH /home/olaolu/.tmux/plugins
+ '[' xtrue = xtrue ']'
+ echo 'Invoking /home/olaolu/.tmux/plugins/tpm/bin/install_plugins ...'
+ /home/olaolu/.tmux/plugins/tpm/bin/install_plugins
+ echo 'Invoking /home/olaolu/.tmux/plugins/tpm/bin/update_plugins all ...'
+ /home/olaolu/.tmux/plugins/tpm/bin/update_plugins all
+ echo 'Invoking /home/olaolu/.tmux/plugins/tpm/bin/clean_plugins all ...'
+ /home/olaolu/.tmux/plugins/tpm/bin/clean_plugins all
+ tmux display 'Done updating tpm and plugins...'
++ tmux show -gqv @tpm-install
+ '[' -z I ']'
++ tmux show -gqv @tpm-update
+ '[' -z u ']'
++ tmux show -gqv @tpm-clean
+ '[' -z M-u ']'
+ '[' -f /home/olaolu/.tmux/plugins/tpm/tpm ']'
+ /home/olaolu/.tmux/plugins/tpm/tpm
+ '[' 320 -gt 260 ']'
+ tmux set -gu @tpm-install ';' set -gu @tpm-update ';' set -gu @tpm-clean ';' set -gu @plugin
+ '[' -z '' ']'
+ '[' 320 -lt 240 ']'
+ set +x
 set -gu @tpm-clean ';' set -gu @plugin
+ '[' -z '' ']'
+ '[' 320 -lt 240 ']'
+ set +x
```

**Comment by gpakosz** [comment]
The `gh-540` branch changes pretty much nothing except not invoking perl in parallel. I still can't pinpoint the `128` error code you're getting.

**Comment by OlaoluwaM** [comment]
This may sound noobish, but is it possible for a shell to not have perl installed?

**Comment by gpakosz** [comment]
`perl` is almost always installed and is a dependency of many things like `git`.

You can double check with `$ command -v perl`

**Comment by gpakosz** [comment]
When you say "it worked", is it with tmux / oh my zsh integration disabled?

**Comment by OlaoluwaM** [comment]
No, it's with the integration enabled

**Comment by OlaoluwaM** [comment]
And yes, you are right. Perl is installed 😃

**Comment by gpakosz** [comment]
Can you please go to `~/.tmux/plugins/tpm` and do

```
$ git status
```

```
$ git --no-pager diff
```

and paste the results here?

**Comment by OlaoluwaM** [comment]
For the `git status`

```bash
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   scripts/install_plugins.sh
        modified:   scripts/source_plugins.sh
        modified:   scripts/update_plugin.sh

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by OlaoluwaM** [comment]
For the `git --no-pager diff`

```bash
diff --git a/scripts/install_plugins.sh b/scripts/install_plugins.sh
index 81e6836..732cc18 100755
--- a/scripts/install_plugins.sh
+++ b/scripts/install_plugins.sh
@@ -17,10 +17,10 @@ clone() {
        local branch="$2"
        if [ -n "$branch" ]; then
                cd "$(tpm_path)" &&
-                       GIT_TERMINAL_PROMPT=0 git clone -b "$branch" --single-branch --recursive "$plugin" >/dev/null 2>&1
+                       GIT_TERMINAL_PROMPT=0 git clone --depth 1 --depth 1 -b "$branch" --single-branch --recursive "$plugin" >/dev/null 2>&1
        else
                cd "$(tpm_path)" &&
-                       GIT_TERMINAL_PROMPT=0 git clone --single-branch --recursive "$plugin" >/dev/null 2>&1
+                       GIT_TERMINAL_PROMPT=0 git clone --depth 1 --depth 1 --single-branch --recursive "$plugin" >/dev/null 2>&1
        fi
 }

diff --git a/scripts/source_plugins.sh b/scripts/source_plugins.sh
index 6381d54..2e4ae4d 100755
--- a/scripts/source_plugins.sh
+++ b/scripts/source_plugins.sh
@@ -21,7 +21,7 @@ silently_source_all_tmux_files() {
                        # unexpanded glob which obviously doesn't exist
                        [ -f "$tmux_file" ] || continue
                        # runs *.tmux file as an executable
-                       $tmux_file >/dev/null 2>&1
+                       $tmux_file >/dev/null 2>&1 || { tmux display "Plugin $(basename ${plugin_path}) failed" && false; } || { tmux display "Plugin $(basename ${plugin_path}) failed" && false; }
                done
        fi
 }
diff --git a/scripts/update_plugin.sh b/scripts/update_plugin.sh
index 68bf605..8419753 100755
--- a/scripts/update_plugin.sh
+++ b/scripts/update_plugin.sh
@@ -22,7 +22,7 @@ pull_changes() {
        local plugin_path="$(plugin_path_helper "$plugin")"
        cd "$plugin_path" &&
                GIT_TERMINAL_PROMPT=0 git pull &&
-               GIT_TERMINAL_PROMPT=0 git submodule update --init --recursive
+               GIT_TERMINAL_PROMPT=0 git submodule update --init --recursive --depth 1 --depth 1
 }

 update() {
```

**Comment by gpakosz** [comment]
Can you confirm the `master` branch still gives you a `128` error code?

**Comment by OlaoluwaM** [comment]
It doesn't

**Comment by OlaoluwaM** [comment]
Ah, it still does

![image](https://user-images.githubusercontent.com/37044906/145721735-217766a1-e2f2-4f29-abb8-713f8c02d82f.png)

**Comment by gpakosz** [comment]
What surprises me is that the diffs you pasted show e.g.
```
+               GIT_TERMINAL_PROMPT=0 git submodule update --init --recursive --depth 1 --depth 1
```
There's `--depth 1` twice which shouldn't happen. It looks like Oh my tmux is patching TPM twice and maybe there's a race condition here if `tmux source` is invoked twice in parallel.

I pushed more code to the `gh-540` code in order to try to prevent that. Can you please test the branch and report result of `git --no-pager diff` launched from the `~/.tmux/plugins/tpm` directory?

**Comment by OlaoluwaM** [comment]
Checked out to the `gh-540` branch. 
Copied its `.tmux.conf`. 
Entered the `~/.tmux/plugins/tpm` directory and ran `git --no-pager diff`
Here is the output
```bash
diff --git a/scripts/install_plugins.sh b/scripts/install_plugins.sh
index 81e6836..98ff1a8 100755
--- a/scripts/install_plugins.sh
+++ b/scripts/install_plugins.sh
@@ -17,10 +17,10 @@ clone() {
        local branch="$2"
        if [ -n "$branch" ]; then
                cd "$(tpm_path)" &&
-                       GIT_TERMINAL_PROMPT=0 git clone -b "$branch" --single-branch --recursive "$plugin" >/dev/null 2>&1
+                       GIT_TERMINAL_PROMPT=0 git clone --depth 1 -b "$branch" --single-branch --recursive "$plugin" >/dev/null 2>&1
        else
                cd "$(tpm_path)" &&
-                       GIT_TERMINAL_PROMPT=0 git clone --single-branch --recursive "$plugin" >/dev/null 2>&1
+                       GIT_TERMINAL_PROMPT=0 git clone --depth 1 --single-branch --recursive "$plugin" >/dev/null 2>&1
        fi
 }

diff --git a/scripts/source_plugins.sh b/scripts/source_plugins.sh
index 6381d54..029f3b4 100755
--- a/scripts/source_plugins.sh
+++ b/scripts/source_plugins.sh
@@ -21,7 +21,7 @@ silently_source_all_tmux_files() {
                        # unexpanded glob which obviously doesn't exist
                        [ -f "$tmux_file" ] || continue
                        # runs *.tmux file as an executable
-                       $tmux_file >/dev/null 2>&1
+                       $tmux_file >/dev/null 2>&1 || { tmux display "Plugin $(basename ${plugin_path}) failed" && false; }
                done
        fi
 }
diff --git a/scripts/update_plugin.sh b/scripts/update_plugin.sh
index 68bf605..f5ade19 100755
--- a/scripts/update_plugin.sh
+++ b/scripts/update_plugin.sh
@@ -22,7 +22,7 @@ pull_changes() {
        local plugin_path="$(plugin_path_helper "$plugin")"
        cd "$plugin_path" &&
                GIT_TERMINAL_PROMPT=0 git pull &&
-               GIT_TERMINAL_PROMPT=0 git submodule update --init --recursive
+               GIT_TERMINAL_PROMPT=0 git submodule update --init --recursive --depth 1
 }

 update() {
```
Seems like what you did worked 😄

**Comment by OlaoluwaM** [comment]
It works! Thank you!!

**Comment by jhogendorn** [comment]
For anyone else googling this error, this will come up if you dont have perl on your path by default. In my case, as a user of asdf i did not have a global version set for perl, causing the error. Setting `asdf global perl latest` or similar resolves it.
