### ISSUE TITLE
Fail to display symbols in Terminal on macos

### ISSUE THREAD

**Issue by m-zheng** [gpakosz/.tmux#542]
Hi,

I didn't install Powerline but downloaded and installed the [PowerlineSymbols.otf](https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf). Then I adjusted `tmux_conf_theme_left_separator_*` variables in my `~/.tmux.conf.local`. 

But Terminal on macos does not display symbols correctly. It shows question mark instead. Do you know how to fix it? Any suggestions would be appreciated.

**Comment by gpakosz** [comment]
Hello @m-zheng 👋

AFAIK `Terminal.app` on macOS doesn't let you define a substitution font for symbols. `ITerm2.app` does. In such a case, installing `PowerlineSymbols.otf` has no effect. You need a font that comes with Powerline symbols, like `Source Code Pro`.
