### ISSUE TITLE
Status bar not being updated

### ISSUE THREAD

**Issue by Oliveiras** [gpakosz/.tmux#543]
No matter what I write on `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right`, it's ignored.

Even if I write a simple value, without variables or unicode chars, like below, it's still ignored.

    tmux_conf_theme_status_left="hi "
    tmux_conf_theme_status_right=" bye"

I'm using Windows 10 + WSL2 + Ubuntu + Zsh.
Here's the output of some commands, showing the versions.

```
➜  ~ uname -a
Linux NADF377 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
➜  ~ zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
➜  ~ tmux -V
tmux 3.0a
```

What else should I look for?

**Comment by gpakosz** [comment]
Hello @Oliveiras 👋

Please double check installation steps.

Please also double check how you're launching tmux. Typically Oh my tmux! won't work if you launch tmux with the `-f` option to specify a configuration file location

**Comment by Oliveiras** [comment]
Hello @gpakosz ,

I've double checked and didn't found any unmet requirement.
Here's what I've checked:

* tmux version >= 2.3
OK, mine is 3.0a
* awk, perl and sed
OK
* $TERM outside of tmux
OK, mine is set to xterm-256color
* Installations steps
OK and everything else is working
* (from the Troubleshooting) version of glib vs version of glibc
OK, glib version is 2.64 and glibc version is 2.31, checked with following commands:
```
$ sudo apt install libglib2.0-0
...
libglib2.0-0 is already the newest version (2.64.6-1~ubuntu20.04.4).
```
```
$ ldd --version ldd
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
...
```
* configure LC_CTYPE to use an UTF-8 locale
OK, it was "C.UTF-8", but I set LANG, LC_ALL (and consequently LC_TYPE) to "en_US.UTF-8".
* (from your answer) Launching tmux without -f option
OK, I'm starting it from my home folder using just `tmux`

Other than that, I'm using Windows Terminal, have installed and configured to use "Source Code Pro for Powerline" font. It's seems working.

Am I missing somethig? What else can I look for?

Thanks!

**Comment by gpakosz** [comment]
If reloading the tmux configuration with `<prefix> + r` doesn't materialize the following changes
```
tmux_conf_theme_status_left="hi "
tmux_conf_theme_status_right=" bye"
```

Then it means tmux didn't load `~/.tmux.conf` in the first place: `~/.tmux.conf` should be a symlink to `~/.tmux/.tmux.conf`.

Can you please paste the output of
```
$ head -4 ~/.tmux.conf
```
?

**Comment by gpakosz** [comment]
You can also look for `/etc/tmux.conf` or `/usr/local/etc/tmux.conf` files. If they exist, tmux won't load `~/.tmux.conf`

**Comment by Oliveiras** [comment]
Here is the output of that command and the check to see if those other files exists:

```
➜  ~ head -4 ~/.tmux.conf
# : << EOF
# https://github.com/gpakosz/.tmux
# (‑●‑●)> dual licensed under the WTFPL v2 license and the MIT license,
#         without any warranty.
➜  ~ ls -lh ~/.tmux.conf
lrwxrwxrwx 1 alex alex 16 Dec 27 11:58 /home/alex/.tmux.conf -> .tmux/.tmux.conf
➜  ~ ls -lh /etc/tmux.conf
ls: cannot access '/etc/tmux.conf': No such file or directory
➜  ~ ls -lh /usr/local/etc/tmux.conf
ls: cannot access '/usr/local/etc/tmux.conf': No such file or directory
```

Other than that, I know the file is being loaded because if I change the color (for example) in the .tmux.conf.local, it does get applied.

**Comment by Oliveiras** [comment]
I finally found the problem, I tried to install a theme plugin (gruvbox) and it interacted badly with oh my tmux. I uninstalled it and the status bar is now working fine.
Thanks for your time and sorry for not remembering mentioning that part.
