### ISSUE TITLE
Copy-mode not working on tmux 3.2

### ISSUE THREAD

**Issue by ralphie02** [gpakosz/.tmux#545]
I enter copy-mode via `prefix` `enter` and try to select a text using my keyboard and it doesn't seem to work at all. Mouse selection _sorta_ works though. I can select and paste a text.

**Comment by gpakosz** [comment]
Hello @ralphie02 👋

What's the output of `tmux lsk | grep begin-selection` for you?

Here's what I get
```
$ tmux lsk | grep begin-selection
bind-key    -T copy-mode    C-Space              send-keys -X begin-selection
bind-key    -T copy-mode    MouseDrag1Pane       select-pane \; send-keys -X begin-selection
bind-key    -T copy-mode-vi Space                send-keys -X begin-selection
bind-key    -T copy-mode-vi v                    send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDrag1Pane       select-pane \; send-keys -X begin-selection
```

Please also note that tmux behaves differently depending on whether the `VISUAL` or `EDITOR` environment variables contain the string `vi`.

**Comment by ralphie02** [comment]
`tmux lsk | grep begin-selection`
```bash
bind-key    -T copy-mode    C-Space              send-keys -X begin-selection
bind-key    -T copy-mode    MouseDrag1Pane       select-pane \; send-keys -X begin-selection
bind-key    -T copy-mode-vi Space                send-keys -X begin-selection
bind-key    -T copy-mode-vi v                    send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDrag1Pane       select-pane \; send-keys -X begin-selection
```
I'm not setting `VISUAL` or `EDITOR` in my env vars. I'm on `MacOS Big Sur 11.6` if that helps. 
I also tried this on WSL and it works fine so it seems to be isolated to Mac since I use the exact same config.

Note: My PC has tmux v3.0a while my Mac has tmux v3.2a

**Comment by gpakosz** [comment]
> and try to select a text using my keyboard and it doesn't seem to work at all

And which keys are you using?

**Comment by ralphie02** [comment]
I tried using vim navigation (h, j, k,l) and they're not working. I already tried the arrow keys, they work, but I can't select any text since `v` doesn't seem to begin selection / visual mode

**Comment by gpakosz** [comment]
If you want to use vim navigation, then
- either set `VISUAL` to `vim` before launching tmux
- or edit your `~/.tmux.conf.local` and uncomment `set -g mode-keys vi`

**Comment by ralphie02** [comment]
I always set my `EDITOR` to vim in WSL but don't in Mac. This works now, thanks!
