### ISSUE TITLE
unknown variable: TMUX_PLUGIN_MANAGER_PATH 

### ISSUE THREAD

**Issue by ibootstrapper** [gpakosz/.tmux#546]
unknown variable: TMUX_PLUGIN_MANAGER_PATH
FATAL: Tmux Plugin Manager not configured in tmux.conf

**Comment by gpakosz** [comment]
Hello @ibootstrapper 👋

Can you please tell me more?
- What OS are you using?
- Which version of tmux are you using? (`tmux -V`)
- Did you realize that Oh my tmux! comes with its own TPM integration and you should not follow TPM installation instructions?

Thank you

**Comment by barrettclark** [comment]
FWIW I am using the fish shell with tmux 3.3a and am also seeing this error. I don't know what this repo is, but can confirm the issue, in general.

**Comment by ibootstrapper** [comment]
It looks like this issue happen within timid session

**Comment by Frederick888** [comment]
I also experience this issue from time to time. I'm running tmux 3.3a on Arch Linux. My configuration can be found at [.tmux.conf.local](https://git.tsundere.moe/Frederick888/frederick-settings/blob/master/.tmux.conf.local).

When this issue happens, I often find `tmux-plugins/tmux-cpu` in my status bar refusing to show my CPU usage. And if I run `tpm/bindings/update_plugins`, I can see the error below:

```
$ /home/frederick/.tmux/plugins/tpm/bindings/update_plugins
unknown variable: TMUX_PLUGIN_MANAGER_PATH
unknown variable: TMUX_PLUGIN_MANAGER_PATH
FATAL: Tmux Plugin Manager not configured in tmux.conf
Aborting.
```

Then interestingly this can somehow fix the issue for current tmux session. CPU usage is correctly added to tmux status bar, and if I run `tpm/bindings/update_plugins` again, plugin update selection UI often just shows up normally.

I actually don't remember seeing this problem on my local machine. Instead, they happen to remote ones when I connect to them via SSH with following SSH config:

```ssh_config
Host Foo
    RemoteCommand tmuxinator start default
    RequestTTY yes
```

Not sure what @ibootstrapper meant by 'timid session' exactly, but if it's about tmux session initialisation SSH may indeed add some uncertainty here.
