### ISSUE TITLE
Variables stopped working past a certain commit

### ISSUE THREAD

**Issue by aavanian** [gpakosz/.tmux#547]
I had a working configuration that I didn't touch in a while (based on 3bfec1a25a8a66dd251d37f4efcd6a0e9f30a6da). When configuring a new computer, I used the latest version and it broke variables in status bar.

Bissecting led me to 1cd8ed93d33f3ad4384d486bc6092507a0bb7713 breaking variables even using a stock config, only modified to actually call one of those example variables by adding `#{online}` to `tmux_conf_theme_status_right`:

`tmux_conf_theme_status_right=" #{prefix}#{mouse}#{pairing}#{synchronized}#{online}#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} "
`

works on 14bd87c7b2b4efd9dee2d54bfe7f2a82041e749c:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/13487305/149438055-eb4d9942-5a0b-4ea6-b3a2-893c3ef7cf5f.png">

breaks on 1cd8ed93d33f3ad4384d486bc6092507a0bb7713:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/13487305/149437947-fdc0d6dd-bf78-4d0c-bfad-823cb063735f.png">

works without `#{online}` on 1cd8ed93d33f3ad4384d486bc6092507a0bb7713:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/13487305/149438531-9c87e6d4-3c61-45d2-a132-aabc733ba84b.png">

Using:
`tmux 3.2a`
`GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)` as system shell (`/bin/sh`)
`GNU bash, version 5.1.16(1)-release` as login shell (not sure if it matters)

**Comment by gpakosz** [comment]
Hello @aavanian 👋

Thanks for the report and sorry for the inconvenience. Can you please try the `gh-547` branch?

**Comment by aavanian** [comment]
Hi, thanks for the quick feedback. I confirm `gh-547` works (both with `#{online}` and my custom variables). 👍
