### ISSUE TITLE
Sourcing custom tmux confs

### ISSUE THREAD

**Issue by OlaoluwaM** [gpakosz/.tmux#549]
Is there a supported way for including custom tmux configuration? Although this project is lovely, it can be overwhelming to tweak even though the options are straightforward. There is so much to choose from that people like me find it harder to choose than to pick 😅.

I recently transitioned to the Catppuccin theme and wanted my tmux to look the part. However, I couldn't find a "supported" way to source my custom configuration file to override what it needs to. 

I got it working but had to edit the `.tmux.conf` file to do so. Specifically, I sourced my custom config after the line 
`run 'cut -c3- ~/.tmux.conf | sh -s _apply_configuration'`.

Is there any better way to do this?

**Comment by gpakosz** [comment]
Hello @OlaoluwaM 👋

I recommend against editing `~/.tmux.conf`. Instead you can write your override or source other files in your `~/.tmux.conf.local` copy.

**Comment by OlaoluwaM** [comment]
I tried sourcing in the `.tmux.conf.local` file but my custom config was being overridden by it in the end. It wasn't working

**Comment by gpakosz** [comment]
Oh I see.

Currently there's no way to disable theming in Oh my tmux!. I'll keep this issue open.

**Comment by LittleYe233** [comment]
Hello @gpakosz. I have been experiencing this issue for over a year, and it seems that what I can only do to deal with my local configurations is append a new line `source ~/.tmux.conf.local` to `~/.tmux.conf`. I checked the last line of `.tmux.conf` and there is a comment `# -- 8< ------` above the `cut` command, and the command seems to apply all the commented lines in `.tmux.conf`. I felt hard to understand why there should be this line. Could you please spend a short time explaining the reason simply?

**Comment by gpakosz** [comment]
Hello @OlaoluwaM 👋

It's been a while, I know...
The `gh-536` branch now allows you to disable theming entirely and from there you can define your own custom theming in your `~/.tmux.conf.local` copy.

**Comment by gpakosz** [comment]
The `gh-536` branch has been merged. Oh my tmux! theming can be disabled, theming TPM plugins can be used and custom theming from your `~/.tmux.conf.local` copy can be applied
