### ISSUE TITLE
_apply_theme problem?

### ISSUE THREAD

**Issue by IanQS** [gpakosz/.tmux#55]
Hey there,

Was wondering if you could help me. When I use the package I end up having an issue where the statusline disappears sometimes and other times it stacks on itself after a few seconds (so I have multiple status lines covering the bottom part of my screen. I've isolated the issue to within the _apply_theme but am not sure how to move forward since I'm not even sure what's happening. It's probably related to status line but I think there might also be issues with just the encoding and all that

**Comment by gpakosz** [comment]
Why OS and which version of tmux are you using?

**Comment by IanQS** [comment]
I'm using arch Linux and my tmux is 2.3-1 from the official repository

**Comment by gpakosz** [comment]
If you can, I would appreciate a video or gif of what's going on.

I didn't put energy into circling down what's going on exactly yet, but likely it's tied to Unicode symbols (see other issues). Typically on my mac, U+2328 consumes the width of 2 "regular characters.

What you can try is removing those from your `.tmux.conf.local` copy. (see the `non-unicode-symbols` branch). This should solve your issue while giving you a slightly less cool status bar.

Keep me posted.

**Comment by IanQS** [comment]
Hey thank you :) The non-unicode-symbols branch helped me debug. Turns out it was a problem with rendering 

#tmux_conf_battery_status_charging='⚡'     # U+26A1
#tmux_conf_battery_status_discharging='🔋'  # U+1F50B

Thank you so much for your help!

**Comment by gpakosz** [comment]
Good to know. I'm still unsure who's responsible for the breakage: tmux, VTE, else?

Are you using Termite by chance?

**Comment by IanQS** [comment]
I am not. I'm using terminator if you know of it.

I'm really not sure unfortunately

**Comment by gpakosz** [comment]
I know terminator. It's a bit redundant with tmux :) On Archlinux I'm using terminology-git

**Comment by gpakosz** [comment]
BTW, can you please take a screenshot of U+1F50B and  in y U+26A1 in your setup? Does any of the two take more than 1 character when displayed?

**Comment by IanQS** [comment]
Sorry what does that mean? I tried pasting that into the terminal and it just popped up as the code. I'm a little new to this.

**Comment by gpakosz** [comment]
E.g. a screenshot of `cat ~/.tmux.conf.local | grep charging`

**Comment by IanQS** [comment]
![debug](https://cloud.githubusercontent.com/assets/6968573/23529606/35d3235c-ff6c-11e6-9613-0ef948378e13.png)

**Comment by gpakosz** [comment]
Alright it looks like U+26A1 (charging) puts the rendering off. It's a VTE problem, see https://bugzilla.gnome.org/show_bug.cgi?id=772812#c7

**Comment by IanQS** [comment]
I tried it I think both of them are broken :p I'll close the issue now anyways. Thank you so much for your help!
