### ISSUE TITLE
Same keybinding for creating horizontal and vertical panes

### ISSUE THREAD

**Issue by OlaoluwaM** [gpakosz/.tmux#550]

**Comment by gpakosz** [comment]
Hello @OlaoluwaM 👋

The bindings for horizontal and vertical pane split are different: [`-` (dash) and `_` (underscore)](https://github.com/gpakosz/.tmux/blob/9a2387c0c7aa8d12cff06d6be17251e8ebdfd034/.tmux.conf#L69-L72).
Which on a [QWERTY layout](https://en.wikipedia.org/wiki/QWERTY) are on the same physical key.
