### ISSUE TITLE
Please provide a configuration to disable all "custom" keybindings

### ISSUE THREAD

**Issue by gdevenyi** [gpakosz/.tmux#553]
I already memorized classic tmux, I'd like to keep using them.

**Comment by gpakosz** [comment]
Hello @gdevenyi 👋

I'll keep this in the backlog.

**Comment by gpakosz** [comment]
Hello @gdevenyi 👋

By now, you can override Oh my tmux! bindings with `#!important` in your `~/.tmux.conf.local` copy so as to revert to what you prefer, e.g:
```
bind v new-window -c #{pane_current_path} #!important
```

**Comment by rjahanbakhshi** [comment]
It really is nice to have an excellent ready-made tmux.conf to apply everywhere but having the classic keys unbound is problematic. If we want to rebind back every original key in the config file, that will defeat the purpose of having a ready-made one. Not having the classic keybinding is a dealbreaker for me, especially window next, previous, and last.

**Comment by gdevenyi** [comment]
I have to agree with @rjahanbakhshi that having to rebind everything myself does not solve the issue as requested, I probably could've done that myself should I understand the tmux.conf well enough. We're asking for either a big block of settings in .tmux.conf.local we can uncomment to get back to defaults, or ideally, a single true/false "don't change keybindings from default"

**Comment by philippetev** [comment]
@gdevenyi Have you tried to place all your favorite settings in external file and source it at the end of **.tmux.conf.local** like this:
```
source-file ~/.your.custom.settings.tmux
```

**Comment by gdevenyi** [comment]
@philippetev the problem is, I don't *know* all the binding codes for tmux. I just want the defaults for the keypresses I learned when I use it.

I'm asking for a global "disable changing all the bindings"

**Comment by rjahanbakhshi** [comment]
Also, I, and I'm sure many others have been used to using C-a to move the cursor to the start of the line for years now. I have no issue using C-b as a prefix and don't want the C-a to be bound as an additional prefix. But I couldn't find a way to disable this binding in the .local file. The only way to do this is by modifying tmux.conf and that is unsupported here.

**Comment by NathansCodes** [comment]
@rjahanbakhshi I was also annoyed by this and I just found a solution.

Because `C-a` is set as a secondary prefix in `tmux.conf`, you can change or get rid of it by overriding it in your `.local` file.
So to remove it just paste the following in your `.local`:
`set -gu prefix2`

**Comment by rjahanbakhshi** [comment]
@NathansCodes, 

Thanks for the workaround. I moved on and now am using my own custom tmux.conf. But I'm sure others will find your workaround helpful.

**Comment by gdevenyi** [comment]
Following up here again, I would still like a single setting which tells oh-my-tumx to not touch *any* of the keybindings.

**Comment by gpakosz** [comment]
Hello @gdevenyi

> I would still like a single setting which tells oh-my-tumx to not touch _any_ of the keybindings

- What does that cover exactly?
  - What are the Oh my tmux! bindings that currently annoy you specifically?
  - According to you is it ok to add bindings that tmux doesn't already use?
  - Is it also ok to send `C-a` as a second prefix?
- Should the following features still work?
  - `tmux_conf_new_session_prompt` 
  - `tmux_conf_new_session_retain_current_path`
  - `tmux_conf_new_window_retain_current_path`
  - `tmux_conf_new_window_reconnect_ssh`
  - `tmux_conf_new_pane_retain_current_path`
  - `tmux_conf_new_pane_reconnect_ssh`

**Comment by gdevenyi** [comment]
> What are the Oh my tmux! bindings that currently annoy you specifically?

All modifications of existing keybindings. I do not know the names of the bindings, so I cannot easily do the:
`bind v new-window -c #{pane_current_path} #!important` for every single one.

> According to you is it ok to add bindings that tmux doesn't already use?

For me, yes, since I don't know them, it doesn't impact my ability to use tmux the way I learned.

> Is it also ok to send C-a as a second prefix?

For me, yes, as I don't use it. My understanding is this is a typical thing people do anyways because they come from Screen.

> Should the following features still work?

Those all have existing enable/disable settings, so I'm fine with them remaining as-is

**Comment by gpakosz** [comment]
@gdevenyi Can you please try the `gh-553` branch?

Set `tmux_conf_preserve_stock_bindings=true` in your `.local` customization file.

**Comment by gpakosz** [comment]
I pushed another commit

**Comment by gpakosz** [comment]
And another one

**Comment by gdevenyi** [comment]
Sadly that doesn't seem to have resolved it.

**Comment by gpakosz** [comment]
`<prefix>` + `n` and `<prefix> + p` work for me

Can you try to reload the configuration?

**Comment by gdevenyi** [comment]
Ah ha, despite cleaning all the files out there was a lingering tmux server running that I missed holding on to the old settings when I launched a new one.

The `n` and `p` bindings now work.

**Comment by gpakosz** [comment]
Thanks for testing,

I guess I'll merge soon if no major problem shows up

**Comment by gdevenyi** [comment]
Things seem fine on my end.

**Comment by gdevenyi** [comment]
Thank you so much ❤️
