### ISSUE TITLE
Consumes too much power

### ISSUE THREAD

**Issue by reportaman** [gpakosz/.tmux#555]
If I keep disable .tmux, which seems to run some thing in background every 60 seconds, then the CPU utilization of my 10-core apple m1 max goes down from all 10 cores being used every second to only 2-3 cores active all the time.

I like the plugin, but want to use it in a limited way.

IMO there are two parts of this plugin that can be separated and individually enabled/disabled.

1. Static part that can rely solely on Tmux's event based hook model: If user just wants to show static information like session name, username, hostname, pane command, window name.
2. Dynamic part that needs a cron job like behavior that currently exists: To display dynamic information like battery power level, clock, etc.

Here are the relevant settings from ``.tmux.conf.local``:

```bash
tmux_conf_theme_status_left=" ❐ #S | ↑#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} "
tmux_conf_theme_status_right=" #{prefix}#{mouse}#{pairing}#{synchronized}#{?battery_status,#{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} "

```

Terminal: iterm2 (latest version)
shell: zsh 5.8
tmux version: tmux next-3.4 (brew install tmux -s --head)

Create multiple sessions, each attached to a tab in iterm2, open programs like neovim/etc in multiple panes in each session. The problem occurs even if programs are not generating any text output or doing any activity in background.

**Not sure if the following matters...** 

I have GPU rendering enabled in iTerm2 with iTerm2 Preferences > General > Magic > Advanced GPU settings shown below.

<img width="394" alt="Screen Shot 2022-02-13 at 9 32 09 PM" src="https://user-images.githubusercontent.com/71736629/153805808-abf39ec6-6adc-4b11-9c19-a46c2b59cb22.png">

**Comment by gpakosz** [comment]
Hello @reportaman 👋

I don't have a M1 mac to reproduce your issue.

That being said, all you need to do to disable the "dynamic parts" is to remove `#{uptime_xxx}` and `#{battery_xxx}` variables from `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` then reload the configuration.

**Comment by gpakosz** [comment]
Can you also please see
- if all this runs under rosetta 
- if it's `{uptime_xxx}` or `{battery_xxx}` that's the cause of the power consumption

Thank you

**Comment by reportaman** [comment]
@gpakosz I see same activity pattern, all 10 CPU cores engage in activity with status line enabled. If I disable status line, the activity is limited to few cores. Though this time I did not keep eye on power, I would assume its similar seeing the CPU pattern.

As an alternative: can you provide an option to limit the frequency of updates? Instead of updating the status line every second, if I update it every 2 seconds, that could be acceptable. Additionally... not sure if you already do that, but you could maintain some state (as tmux server options) between the two runs of script, and actualize a different update frequency for different fields. Like each second there is no need to check battery, once that information is queried successfully, it could wait a minute (60 status line refresh cycles) to update again...

**Comment by gpakosz** [comment]
> I see same activity pattern, all 10 CPU cores engage in activity with status line enabled. If I disable status line, the activity is limited to few cores. Though this time I did not keep eye on power, I would assume its similar seeing the CPU pattern.

Did you try to remove `#{uptime_xxx}` and `#{battery_xxx}` variables from `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` then reload the configuration. That's way different from disabling the status line.

> As an alternative: can you provide an option to limit the frequency of updates? Instead of updating the status line every second, if I update it every 2 seconds, that could be acceptable

Oh my tmux! doesn't do anything every second *unless* you set `status-interval`to `1`.
Can you please paste the output of
```
$ tmux show -g status-interval
```
?
