### ISSUE TITLE
Why is .tmux.conf.local separate if it is not empty?

### ISSUE THREAD

**Issue by nils-werner** [gpakosz/.tmux#556]
To my understanding a local config file serves the purpose of me being to overload single config values that survive an update of the main config file. To achieve that I would assume that `.tmux.conf` was provided by Oh My Tux and `.tmux.conf.local` would be optional and empty.

Currently the project however provides both `.tmux.conf` and `.tmux.conf.local`, and both files are not empty. So if I want to update Oh My Tmux I will have to change a non-empty file, and later merge my modifications with the upstream changes.

Why is that? Why don't you just merge everything into `.tmux.conf` and let me optionally create an empty `.tmux.conf.local`?

**Comment by gpakosz** [comment]
Hello @nils-werner 👋

Having a `~/.tmux.conf.local` is effectively optional.
The `.tmux.conf.local` sample file that comes with the repository comes both as a reference file and provides documentation.

The point of not merging everything into `~/.tmux.conf` allows people to pull from Oh my tmux! and make their `master` branch evolve without having to deal with merge conflicts.

**Comment by gpakosz** [comment]
> Currently the project however provides both `.tmux.conf` and `.tmux.conf.local`, and both files are not empty. So if I want to update Oh My Tmux I will have to change a non-empty file, and later merge my modifications with the upstream changes.

It seems you overlooked a crucial step. You're supposed to copy the `~/.tmux/.tmux.conf.local` sample file to `~/.tmux.conf.local`. Or you can skip this step if you're happy with all default settings.

**Comment by nils-werner** [comment]
I am not sure I fully understand...

1. So I only need `~/.tmux.conf` and `~/.tmux.conf.local` is optional. OK, I see that, but then my tmux is missing some eyecandy and does not look like the GIF in your README anymore. So technically, `.tmux.conf.local` is optional, but you're assuming people will be using it, right?
2. Where can I put my own modifications *without changing either `~/.tmux.conf` or `~/.tmux.conf.local`*?

**Comment by gpakosz** [comment]
> OK, I see that, but then my tmux is missing some eyecandy and does not look like the GIF in your README anymore. So technically, `.tmux.conf.local` is optional, but you're assuming most people will likely be using both files, right?

Indeed GIF shows off what's possible among everything available.
Yes I assume people follow the installation instructions and create their own copy of `.tmux.conf.local` by copying from the repository and placing it in their home directory

> Where can I put my own modifications **without changing either `~/.tmux.conf` or `~/.tmux.conf.local`**? I want to be able to apply my own customizations and bindings without changing any of these two files.

I'm wondering whether you symlinked `~/.tmux.conf.local` instead of making a copy. When you make a copy, you can tweak the settings and add all the overrides you want in your own `~/.tmux.conf.local`. Once you make a copy, the `~/.tmux.conf.local` file lives outside the Oh my tmux! Git repository that you can update without having merge conflicts to solve.

**Comment by nils-werner** [comment]
> Once you make a copy, the `~/.tmux.conf.local` file lives outside the Oh my tmux! Git repository that you can update without having merge conflicts to solve.

Yes, but `~/.tmux.conf.local` [will still change from time to time](https://github.com/gpakosz/.tmux/commits/master/.tmux.conf.local) and I won't be getting those changes.

**Comment by gpakosz** [comment]
> Yes, but `~/.tmux.conf.local` [will still change from time to time](https://github.com/gpakosz/.tmux/commits/master/.tmux.conf.local) and I won't be getting those changes.

That's correct. Pulling the repository will bring you mostly bug fixes.

**Comment by nils-werner** [comment]
I am proposing an alternative approach:

 1. Rename `.tmux.conf.local` to `.tmux.config.optional`
 2. Gitignore `.tmux.conf.local`

If I want to modify the behaviour of Oh my Tmux, I will have to create a file `.tmux.conf.local` where only my modifications live, and none of the upstream code.

Scenario 1: I want to load the optional eyecandy. I will put the line

```
source -q ~/.tmux.conf.optional
```

in my `.tmux.conf.local`. That way both `.tmux.conf` and `.tmux.conf.optional` will be updated on git pull and I will never have a conflict.

Scenario 1: I want to change the field [`tmux_conf_battery_bar_length`](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf.local#L281).

I will put the content

```
source -q ~/.tmux.conf.optional
tmux_conf_battery_bar_length="5"
```

in `.tmux.conf.local`. Again, this change will never produce a conflict and all files from upstream can be updated without an issue.

Additional benefit: I can immediately see all my customizations, because they all live in one small file.

**Comment by gpakosz** [comment]
You're over engineering it.

> 1. Rename `.tmux.conf.local` to `.tmux.conf.optional`
> 2. Gitignore `.tmux.conf.local`
>
>If I want to modify the behaviour of Oh my Tmux, I will have to create a file `.tmux.conf.local` where only my modifications live, and none of the upstream code.

This is exactly what you get when creating a `~/.tmux.conf.local` that contains only a minimal set of directives.

 And you can `source -q ~/.tmux/.tmux.conf.local` from `~/.tmux.conf.local` if you want to.

**Comment by nils-werner** [comment]
Ah right.

> And you can source -q `~/.tmux/.tmux.conf.local` from `~/.tmux.conf.local` if you want to.

Weirdly enough, when I do that, e.g.

```
source -q ~/.tmux/.tmux.conf.local

set -gu prefix2

tmux_conf_theme_left_separator_main='\uE0B0'  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub='\uE0B1'   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='\uE0B2' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub='\uE0B3'  #   PowerlineSymbols.otf font, see README.md
```

I am not able to override any variables from `~/.tmux/.tmux.conf.local`

**Comment by gpakosz** [comment]
> I am not able to override any variables from ~/.tmux/.tmux.conf.local

Yeah discovered that as well with current tmux.
This is a bug imho. It got me intrigued but I didn't manage to submit a patch yet.

In the meantime you can do
```
source -q ~/.tmux/.tmux.conf.local

setenv -g tmux_conf_theme_left_separator_main '\uE0B0'
...
```

**Comment by gpakosz** [comment]
Another workaround is to do this in your `~/.tmux.conf.local` copy:

```
source -q ~/.tmux/.tmux.conf.local
source -q ~/.tmux.conf.optional
```

**Comment by gpakosz** [comment]
Also I didn't insist enough on the fact that having a `~/.tmux.conf.local` copy that only contains
```
set -gu prefix2

tmux_conf_theme_left_separator_main='\uE0B0'  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub='\uE0B1'   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='\uE0B2' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub='\uE0B3'  #   PowerlineSymbols.otf font, see README.md
```

Will get exactly what you want: Oh my tmux! defaults + your overrides.

**Comment by gpakosz** [comment]
Related: tmux/tmux#3091
