### ISSUE TITLE
Different color at the end of the powerline

### ISSUE THREAD

**Issue by philippetev** [gpakosz/.tmux#557]
Isn't that symbol (the rounded one) suppose to be with the same color like the rest of the segment it belongs?
![image](https://user-images.githubusercontent.com/5438221/155880353-fac6b631-c5f6-4e7a-9497-2721dafc364f.png)

**Comment by gpakosz** [comment]
Hello @philippetev 👋

You're correct.
Does it happen with stock Oh my tmux! configuration when you change `tmux_conf_theme_left_separator_main` and `tmux_conf_theme_left_separator_sub`?

**Comment by philippetev** [comment]
Hi!
After some digging managed to solve it. It turned out the be terminal info issue with my NAS and adding TERM=xterm-256color to ~/.bashrc fixed it. It seems the NAS uses xterm by default and that explains the color differences between your shots at the main repo page and the one above.

**Comment by gpakosz** [comment]
Good to know! Closing then.
