### ISSUE TITLE
When using <prefix> +, failed and return 'cut -c3- ~/.tmux.conf | sh -s _maximize_pane "2" %4' returned 1

### ISSUE THREAD

**Issue by zzl1327** [gpakosz/.tmux#558]
It seems freeze the mouse mode (could not operate other pane, however still under mouse mode);

And not create any tag here:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/66019572/158303812-2e5d5c06-d770-49cc-9cb9-4790013d19f5.png">

Finally will hang here:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/66019572/158303863-bf0c2624-9a9e-49b0-b4db-d4ae3a2ec6ac.png">

**Comment by zzl1327** [comment]
Hi @gpakosz 

Currently, I'm using xterm in CentOS;

And tmux version is following:

tmux -V
tmux 2.7-rc

Thanks

Edwin

**Comment by gpakosz** [comment]
Can you please make sure you're using the latest commit of Oh my tmux!?
This is commit `9a2387c0c7aa8d12cff06d6be17251e8ebdfd034`

**Comment by zzl1327** [comment]
I think it is the latest
<<
git log --name-status HEAD^..HEAD
commit 9a2387c0c7aa8d12cff06d6be17251e8ebdfd034
Author: Gregory Pakosz <gregory.pakosz@gmail.com>
Date:   Fri Jan 14 07:45:06 2022 +0100
>>

**Comment by gpakosz** [comment]
Can you please, from a tmux pane do

```
$ cut -c3- ~/.tmux.conf | sh -sx _maximize_pane $(tmux display -p '#S #D')
```
And paste what's been outputted?

**Comment by zzl1327** [comment]
/u/ziling :-)  cut -c3- ~/.tmux.conf | sh -sx _maximize_pane $(tmux display -p '#S #D')
Illegal variable name.

**Comment by gpakosz** [comment]
Is `/u/zilling :-)` your prompt?

**Comment by zzl1327** [comment]
cut -c3- ~/.tmux.conf | sh -sx _maximize_pane $(tmux display -p '#{session_name} #D' )
Illegal variable name.

Seems 'cut' could work successfully

**Comment by gpakosz** [comment]
Are you sure you didn't modified the content of `.tmux.conf`?
