### ISSUE TITLE
Problems with SSH while in tmux

### ISSUE THREAD

**Issue by jacklenox** [gpakosz/.tmux#559]
Hello,

I've recently reinstalled things on my system and set `tmux` back up using this config, which I love! (Thank you! :pray:)

However, I'm encountering issues when using `ssh` to access remote servers. Several irregularities occur, including the backspace button creating a space.

There are no obvious error messages, but when I try to open `vim` for example, I see the following notice:

```
E558: Terminal entry not found in terminfo
'tmux-256color' not known. Available builtin terminals are:
    builtin_amiga
    builtin_beos-ansi
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
```

These issues don't occur if I use SSH outside of `tmux`.

I've had a Google around, and some people suggest that setting the `default-terminal` in `.tmux.conf` to `xterm-256color` fixes the issue, but I've seen in other issues in this repo @gpakosz says you shouldn't do this.

I currently haven't made any edits to `.tmux.conf`, so all the settings are just the defaults. And my `.tmux.conf.local` is also almost untouched, save for me uncommenting the ANSI colour variables and commenting out the default colours.

And my terminal is `zsh`.

Is anyone aware of a way of fixing the issue I'm having without changing the `default-terminal`?

Thanks!

**Comment by gpakosz** [comment]
Hello @jacklenox 👋

Can you please test the following things please?
- On your local computer, can you please check the value of `TERM` outside of tmux?
- On your local computer, can you please check the value of `TERM` inside tmux?
- On your local computer, can you please check the value of
   ```
   $ infocmp -x tmux-256color > /dev/null
   ```
- On your remote computer (the one you're sshing into), can you please check the value of `TERM` outside of tmux?
- Can you please use `ssh -v` when connecting tot he remote computer and see if you see lines containing the `setting env` text?

In any case, you can add
```
set -g default-terminal "screen-256color"
```
to your `~/.tmux.conf.local` copy

**Comment by jacklenox** [comment]
Thanks @gpakosz! Taking each one in order:

> On your local computer, can you please check the value of TERM outside of tmux?

`xterm-256color`

> On your local computer, can you please check the value of TERM inside tmux?

`tmux-256color`

> `$ infocmp -x tmux-256color > /dev/null`

This command returns nothing.

> On your remote computer (the one you're sshing into), can you please check the value of TERM outside of tmux?

`tmux-256color`

> Can you please use ssh -v when connecting tot he remote computer and see if you see lines containing the setting env text?

I can see these two environment-related lines.

```
debug1: Sending environment.                                                                                                                                                 
debug1: Sending env LANG = en_GB.UTF-8
```

> In any case, you can add
> 
> set -g default-terminal "screen-256color"
> 
> to your ~/.tmux.conf.local copy

This has fixed the problem!

**Comment by gpakosz** [comment]
What's happening is that `ssh` passes the `TERM` environment variable when connecting to a remote server.

There are somewhat `3` workarounds:
- Install the `tmux-256color` terminfo description on the remote server
- Force tmux to use `screen-256color` (and lose e.g. italics support)
- Edit your `~/.ssh/config` and use `SetEnv TERM=screen-256color` to ask `ssh` to pass a specific value for the `TERM` environment variable when connecting to a remote server
