### ISSUE TITLE
Tmux with neovim (colorscheme tokyonight)

### ISSUE THREAD

**Issue by Looooopy** [gpakosz/.tmux#560]
When I use tmux with [neovim](https://github.com/neovim/neovim) and coloscheme [tokyonight](https://github.com/folke/tokyonight.nvim) i get scrambled colors like this below any idea how to solve these kind of problems?

Nvim with tmux and your config
![image](https://user-images.githubusercontent.com/16755871/159815009-817f2472-61c0-48a6-82ba-cc3337ca48bc.png)

Nvim without tmux
![image](https://user-images.githubusercontent.com/16755871/159815220-29b29103-e992-46e7-b0e5-7589bb2f4290.png)

**Comment by gpakosz** [comment]
Hello @Looooopy,

Please double check the value of `TERM` outside and within tmux

**Comment by Looooopy** [comment]
More info I am running nvim in docker and it does not appear to be happening when I am running nvim on my host. but TERM env is the same.

Test 1)
Start terminal on Host:
`xterm-256color`
Start Tmux in terminal on host: 
`screen-256color`
Starting nvim in docker:
`xterm-256color`

Test 2)
Start terminal on Host:
`xterm-256color`
Start Tmux in terminal on host: 
`screen-256color`
Starting nvim on Host:
`xterm-256color`

**Comment by Looooopy** [comment]
Seams like changing the default of 

`set -g default-terminal "screen-256color"`

to

`set -g default-terminal "tmux-256color"`

Solved that issue, thanks for guiding me on the right track!
