### ISSUE TITLE
symlink creation not working

### ISSUE THREAD

**Issue by kaiyuan-li** [gpakosz/.tmux#563]
In installation instruction, the symlink creation says:
```
$ ln -s -f .tmux/.tmux.conf
```

It should be
```
$ ln -s -f .tmux/.tmux.conf ~/.tmux.conf
```

**Comment by gpakosz** [comment]
Hello @kaiyuan-li 👋

No it *should* not 😉

On what platform does it fail for you? Because `ln` is supposed to work the same everywhere.

**Comment by kaiyuan-li** [comment]
I'm on mac. I think you are right. I tried to remove the symlink and just use `ln -s -f .tmux/.tmux.conf` and it works to create the symlink. I probably had a typo.

BTW, great product!
