### ISSUE TITLE
A problem occurred while copying

### ISSUE THREAD

**Issue by Licae** [gpakosz/.tmux#564]
When I copy the code on the left, the split screen of TMUx copies the blank lines on the right as well. Is this a bug or a tool feature? Thank you for your.
![image](https://user-images.githubusercontent.com/46914411/164141821-1b309afd-9452-47b0-9137-e67cb59b3656.png)

**Comment by grahamcrowell** [comment]
You need to be in "mouse mode" 
To toggle mouse mode use <prefix> + m

**Comment by gpakosz** [comment]
Hello @Licae 👋

From your screenshot, it looks like you used your mouse to select text in your terminal.
When a tmux window is split into panes, the behavior is not what you're expecting.

Get yourself familiar with tmux copy mode, which can be operated with the keyboard or the mouse when tmux mouse mode is enabled.
With Oh my tmux!, you can toggle mouse mode on and off with the `<prefix> + m`.

Hope that helps
