### ISSUE TITLE
Problem when sourcing .tmux.conf

### ISSUE THREAD

**Issue by motoight** [gpakosz/.tmux#568]
After exec the install command in readme.md

>$ cd

>$ git clone https://github.com/gpakosz/.tmux.git

>$ ln -s -f .tmux/.tmux.conf

>$ cp .tmux/.tmux.conf.local .

I figure out that I should source the new .tmux.conf

but I met the the following error
> tmux.conf:1492: parse error near `\n'

Can any one help me out here? Thanks!

**Comment by motoight** [comment]
I figure it out!
Use 
> tmux source-file ~/.tmux.conf 
rather than
> source ~/.tmux.conf

**Comment by gpakosz** [comment]
Hello @motoight 👋

Glad you sorted out. Indeed `source` (Bash/Zsh...) is different from `tmux source`.
