### ISSUE TITLE
Server Crashes with TPM

### ISSUE THREAD

**Issue by cujomalainey** [gpakosz/.tmux#572]
Tmux 3.3, top of tree tpm.

When mixed with TPM it crashes the tmux server. Tmux installed via homebrew on osx. Crash deletes the plugins folder.

**Comment by cujomalainey** [comment]
Note crash does not happen with a vanilla config. It only happens with oh my tmux

**Comment by cujomalainey** [comment]
Looks like it might be an upstream issue. https://github.com/tmux/tmux/issues/3203#issuecomment-1146777548

**Comment by gpakosz** [comment]
Hello @cujomalainey 👋

I cannot reproduce the issue with tmux `3.3` on macOS.

Which plugins did you enable?

**Comment by cujomalainey** [comment]
confirmed its an upstream issue (https://github.com/tmux/tmux/issues/3206), thanks for the prompt response
