### ISSUE TITLE
Split pane will get the wrong path if new_pane_reconnect_ssh is enabled

### ISSUE THREAD

**Issue by hzhangxyz** [gpakosz/.tmux#573]
version : f1cc468
tmux version: 3.3_a
config: only enable reconnect ssh, others is all the same to f1cc468 default .tmux.conf.local

what happened?
when I try to split pane, the location is wrong. run-shell will override the $PWD to $HOME, and so invoking tmux split-window in run-shell give the wrong path, aka. always $HOME.

**Comment by gpakosz** [comment]
Hello @hzhangxyz 👋

I don't understand the problem you're facing. Can you give more details on what you're doing?

**Comment by hzhangxyz** [comment]
@[gpakosz](https://github.com/gpakosz) Hello, the detail information is the following:

To avoid destroy my current working environment, I reproduce it in docker debian:sid(IMAGE ID 87282e1afcaa), although the system version seems not important to reproduce, I apt install the following package: `tmux git vim` and then:

```
cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cd .tmux
git checkout f1cc468
cd ..
cp .tmux/.tmux.conf.local .
```

Then update `.tmux.conf.local` by:
```
root@c39e42bd8d8b:~# diff .tmux/.tmux.conf.local .tmux.conf.local
33c33
< tmux_conf_new_pane_reconnect_ssh=false
---
> tmux_conf_new_pane_reconnect_ssh=true
```

Now, open tmux, and cd to a folder such as `/etc`, then, press C-b ", the new pane created is in the folder `~` instead of `/etc`

**Comment by gpakosz** [comment]
Thanks I will have a look

**Comment by gpakosz** [comment]
Can you please try the `gh-573` branch?

**Comment by hzhangxyz** [comment]
> Can you please try the `gh-573` branch?

It seems work. :)
