### ISSUE TITLE
Problem to render italic

### ISSUE THREAD

**Issue by guedesfelipe** [gpakosz/.tmux#575]
I'm having trouble rendering text in italics:

![image](https://user-images.githubusercontent.com/25853920/174101545-56cd11df-89f1-4a46-8e63-d18353c00341.png)

**Comment by gpakosz** [comment]
Hello @guedesfelipe 👋

You likely want to install the `tmux-256color` terminal description:
```
$ /*/*/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
$ sudo /usr/bin/tic -x tmux-256color.src
```

Then relaunch tmux.

See https://github.com/tmux/tmux/issues/3218

**Comment by guedesfelipe** [comment]
> 

> Hello @guedesfelipe 👋
> 
> You likely want to install the `tmux-256color` terminal description:
> 
> ```
> $ /*/*/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
> $ sudo /usr/bin/tic -x tmux-256color.src
> ```
> 
> Then relaunch tmux.
> 
> See [tmux/tmux#3218](https://github.com/tmux/tmux/issues/3218)

Hello @gpakosz 👋

Tnx a lot for the reply!

I did that and it worked, but i needed to change my config with this:
`set -g default-terminal "tmux-256color" # colors!`
instead of
`set -g default-terminal "screen-256color" # colors!`

**Comment by gpakosz** [comment]
@guedesfelipe You don't need to change anything.

`.tmux.conf` contains
```
set -g default-terminal "screen-256color"
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'
```

You just need to quit tmux entirely and relaunch it

**Comment by guedesfelipe** [comment]
> @guedesfelipe You don't need to change anything.
> 
> `.tmux.conf` contains
> 
> ```
> set -g default-terminal "screen-256color"
> if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'
> ```
> 
> You just need to quit tmux entirely and relaunch it

You're right, my config was outdated. Now is updated! Tnx so much for the reply!
