### ISSUE TITLE
Doesn't show the battery icon and graph

### ISSUE THREAD

**Issue by RussellMurad** [gpakosz/.tmux#578]
I have configured tmux.conf and tmux.conf.local properly, even installed powerline fonts as well but it seems not working. Can anyone tell me any solution regarding this problem.

![image](https://user-images.githubusercontent.com/6575563/177887092-44c27a0f-73dd-4d74-8ac7-bdadab31b9b7.png)

**Comment by gpakosz** [comment]
Hello @RussellMurad 👋

Can you please paste the output of
```
$ find /sys/class/power_supply -maxdepth 1
```
?

**Comment by RussellMurad** [comment]
Hello @gpakosz. Here is my output.

`/sys/class/power_supply
/sys/class/power_supply/ACAD
`

**Comment by RussellMurad** [comment]
Hello @gpakosz. Here is my output.

`/sys/class/power_supply`
`/sys/class/power_supply/ACAD`

**Comment by gpakosz** [comment]
It looks like your OS doesn't report a battery 🤷‍♂️

**Comment by RussellMurad** [comment]
@gpakosz I've tried the procedure with my Kali Linux. It seems it has also the same issue. But this time, kali does report battery! Could you please check?

![image](https://user-images.githubusercontent.com/6575563/178048200-9d766dd8-234e-4b58-8525-876e81533372.png)

**Comment by RussellMurad** [comment]
Here is my .tmux.conf.local file.

![image](https://user-images.githubusercontent.com/6575563/178048467-47478713-5fd0-4130-a6ef-77ba95be1906.png)
![image](https://user-images.githubusercontent.com/6575563/178048512-6bc84374-acd1-407e-9dbb-4b07a15dd264.png)

**Comment by gpakosz** [comment]
Can you please paste the output of
```
$ cut -c3- ~/.tmux.conf | sh -sx _battery_info
```
?

**Comment by RussellMurad** [comment]
Sure. Here it is - 

`+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ printf 
+ sed -E s///
+ uname -s
+ _uname_s=Linux
+ + awk {gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}
tmux -V
+ _tmux_version=330
+ command -v pkill
+ _battery_info
+ count=0
+ charge=0
+ find /sys/class/power_supply -maxdepth 1 -iname *bat*
+ IFS= read -r batpath
+ [ -z /sys/class/power_supply/BAT1 ]
+ grep -i -q device /sys/class/power_supply/BAT1/scope
+ grep -qi discharging /sys/class/power_supply/BAT1/status
+ echo false
+ discharging=false
+ bat_capacity=/sys/class/power_supply/BAT1/capacity
+ [ -r /sys/class/power_supply/BAT1/capacity ]
+ bat_energy_full=/sys/class/power_supply/BAT1/energy_full
+ bat_energy_now=/sys/class/power_supply/BAT1/energy_now
+ [ -r /sys/class/power_supply/BAT1/energy_full ]
+ count=1
+ IFS= read -r batpath
+ [ 1 -ne 0 ]
+ awk -v charge=0 -v count=1 BEGIN { print charge / count }
+ charge=0
`

**Comment by gpakosz** [comment]
Can you please do
```
$ ls -l /sys/class/power_supply/BAT1
```
and
```
$ cat /sys/class/power_supply/BAT1/energy_full
```
and
```
$ cat /sys/class/power_supply/BAT1/energy_now
```

**Comment by RussellMurad** [comment]
Sure. Here is the results.

![image](https://user-images.githubusercontent.com/6575563/178102391-cfd372eb-c600-4732-9125-f13856eb0122.png)

**Comment by RussellMurad** [comment]
For the record, I'm using Kali Linux in VMware. Could this be an issue over here?

**Comment by gpakosz** [comment]
If `/sys/class/power_supply/BAT1/energy_full` and `/sys/class/power_supply/BAT1/energy_now` are missing then there's pretty much nothing Oh my tmux! can do 🤷‍♂️

Looks like there's no `/sys/class/power_supply/BAT1/capacity` either.

> For the record, I'm using Kali Linux in VMware. Could this be an issue over here?
Looks like it is.

**Comment by gpakosz** [comment]
You should look into installing VMware Tools into your Linux guest OS
