### ISSUE TITLE
Support more formats for ssh command?

### ISSUE THREAD

**Issue by reportaman** [gpakosz/.tmux#579]
It seems like Oh my tmux! parses the ssh command pattern ``ssh username@hostname`` to retrieve username and hostname? It doesn't work when the command is something like:

```
 ssh -o 'ConnectionAttempts 60' reportaman@archlinux -t '<some commands>; zsh -l'
```

The username and hostname fields appear empty when this a command like this is entered.

Can we add support for a generic pattern: ``ssh <prefix> username@hostname <suffix>``? Thanks!

**Comment by gpakosz** [comment]
Hello @reportaman 

You can use `ssh -o ConnectionAttempts=60`.

**Comment by gpakosz** [comment]
Also, for the record discovery of `username` and `hostname` **doesn't rely on parsing** the `ssh ...` command.

**Comment by reportaman** [comment]
Hi @gpakosz 👋. I did some more testing. On my machine 1) works, 2) doesn't:

1)
```
ssh reportaman@archlinux -t '<some commands>; zsh -l'
```

2)
```
ssh -o 'ConnectionAttempts 60' reportaman@archlinux -t '<some commands>; zsh -l'
```

2) results in empty username and hostname in the status line.

I wonder if this has something to do with your script expecting GNU flavor of one of ``ps``, ``sed``, ``awk`` etc instead of BSD?

Here are some relevant details:
```
Shell: zsh (zsh 5.9 (arm-apple-darwin21.3.0)
OS: macOS Monterey 12.5
Arch: aarch64
.tmux commit: b620a4f0fb6d8631b98559022a1d5e5f2bd2ce4f (Mon Aug 1 17:14:21 2022 +0200)
```

**Comment by gpakosz** [comment]
As I mentioned here: https://github.com/gpakosz/.tmux/issues/579#issuecomment-1179550230

Use `-o ConnectionAttempts=60` instead of `-o 'ConnectionAttempts 60`.

**Comment by reportaman** [comment]
@gpakosz Ah got it, thanks!
