### ISSUE TITLE
Tmux applies a gray background color to Neovim/Helix

### ISSUE THREAD

**Issue by nahuakang** [gpakosz/.tmux#581]
👋 Thanks for `oh my tmux`! I just have one issue:

On my `iTerm2` with a colorsceme of `Nord`, everything seems to work fine when I enter `nvim` or `hx` for editing:
![Screenshot 2022-07-21 at 16 05 17](https://user-images.githubusercontent.com/18533347/180234120-a5f3afad-5155-4aba-aa34-9c4b70a82d02.png)

But on my `Alacritty` with a colorscheme of `Nord` plus `oh my tmux`, when I enter `nvim` or `hx`, there always seems to be a gray background color applied:
![Screenshot 2022-07-21 at 16 05 31](https://user-images.githubusercontent.com/18533347/180234319-ccc32c54-709e-476f-929e-f553f00eaaeb.png)

I'm wondering how I can fix this issue? Thank you!

**Comment by gpakosz** [comment]
Hello @nahuakang 👋

It's all about the value of `TERM` outside tmux and inside tmux.

**Comment by nahuakang** [comment]
Thanks for the quick response.
So with `tmux` automatically turned on in Alacritty: I get `$TERM` of `screen-256color`.
Without `tmux` in Alacritty: I get `$TERM` of `alacritty`.

On my iTerm2, the value is `xterm-256color`.

**Comment by nahuakang** [comment]
@gpakosz I just need to align `$TERM` value in `.alacritty.yml` as well as `.tmux.conf` for the issue to disappear. Thanks so much for the hint!

**Comment by gpakosz** [comment]
⚠️ You shouldn't modify `.tmux.conf`.

Eventually, add your overrides to your `~/.tmux.conf.local` copy.

All in all:
* Outside of tmux, `TERM` should be `xterm-256color` for iTerm2 and `alacritty` for Alacritty
* Inside of tmux, `TERM` should be `screen-256color` or `tmux-256color`, the later implying you installed the `tmux-256color` terminal description as it's not provided by macOS

**Comment by nahuakang** [comment]
> All in all:
> - Outside of tmux, TERM should be xterm-256color for iTerm2 and alacritty for Alacritty
> - Inside of tmux, TERM should be screen-256color or tmux-256color, the later implying you installed the tmux-256color terminal description as it's not provided by macOS

But in the Alacritty temrinal, if I have `TERM = alacritty` outside of `tmux` and `TERM = screen-256color` inside of tmux, then I have the gray background issue 🤔 Then the issue isn't resolved.

**Comment by gpakosz** [comment]
What about editing your `~/.tmux.conf.local` copy with 
```
set -g default-terminal screen-256color
set -g terminal-overrides ",alacritty:RGB"
```

**Comment by nahuakang** [comment]
With your suggested, I would still have this weird issue where in `helix` editor, the comments have a weird background around them (this doesn't happen when I set it to `xterm-256color`:
![Screenshot 2022-07-21 at 17 06 05](https://user-images.githubusercontent.com/18533347/180247858-160450e1-51c2-4648-b505-ff4c8687fd67.png)

**Comment by gpakosz** [comment]
tmux documentation states that inside tmux `TERM` should be either `screen-256color` or `tmux-256color`.

You should reach out to Alacritty folks

**Comment by nahuakang** [comment]
Will do. Thank you :)

**Comment by nahuakang** [comment]
Btw, following [this link to install `tmux-256color`](https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95) also fixes the issue.
