### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2 

### ISSUE THREAD

**Issue by Akazhiel** [gpakosz/.tmux#583]
Hello, 

I just downloaded the repository and followed the steps to install this configuration but whenever I try opening tmux, the status bar at the bottom is just the default green one, and whenever I try to source the `.tmux.conf` file I get this error `'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2 ` .

I'm using Ubuntu as OS with `tmux 3.0a` . I've tried rebooting the system and it hasn't worked. The terminal emulator I'm using is the one that comes by default and I'm using bash shell.
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

If I run this other command that I've seen in other issues `cut -c3- ~/.tmux.conf | sh -sx _apply_configuration` I get this output:
```
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ set +H
```

**Comment by gpakosz** [comment]
Can you please try with commit `18a111ff93aaaeb18ea94667d749d90aa26ec81d` ?

**Comment by Akazhiel** [comment]
Hello, it does seem to work, but for some reason on the status bar instead of showing the segments like in the example, separated with like `>` or `<`. It is just separated with `|`.
![image](https://user-images.githubusercontent.com/34244350/182175623-710f1cfe-c651-4b96-997f-f6715a981466.png)

**Comment by gpakosz** [comment]
Can you please try the `gh-583` branch now, then we'll talk about theming 🙂

**Comment by gpakosz** [comment]
For the separators, edit your copy of `.tmux.conf.local`
