### ISSUE TITLE
I don't know why he's always looking for one more window_id than my actual window_id

### ISSUE THREAD

**Issue by Timemanagerplus** [gpakosz/.tmux#585]
![image](https://user-images.githubusercontent.com/74964404/182516069-4d2eb827-a546-46cf-b6f2-84ab898feb2a.png)
![image](https://user-images.githubusercontent.com/74964404/182516127-605ccf18-330b-4eab-8be4-2e16a708c91c.png)

**Comment by gpakosz** [comment]
Hello @Timemanagerplus 👋

Sorry for the late reply. I'm sorry I have no idea. Do you still have the problem?

**Comment by Timemanagerplus** [comment]
@gpakosz Sorry, I can't access github during this time, the problem has been solved. Thank you
