### ISSUE TITLE
Suggested enhancement: remove `$` from README and docs

### ISSUE THREAD

**Issue by jpmcb** [gpakosz/.tmux#588]
When using GitHub's "copy code block" functionality and doing a fresh install, it brings over the `$` that are in the README.md:

```
❯ $ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
zsh: command not found: $
zsh: command not found: $
zsh: command not found: $
zsh: command not found: $
```

The expected flow should work _without_ the `$` when copy/pasting the blocks:

```
❯ cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
Cloning into '.tmux'...
remote: Enumerating objects: 969, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 969 (delta 7), reused 2 (delta 2), pack-reused 955
Receiving objects: 100% (969/969), 485.69 KiB | 6.23 MiB/s, done.
Resolving deltas: 100% (516/516), done.
```

Happy to provide a PR to the docs!!

**Comment by jpmcb** [comment]
> $ vs # conveys semantics 

True!

> It's a good thing people don't copy paste random commands from the internet to their terminal

While philosophically I 100% agree, practically I think it's often easier to just copy/paste a long `git clone` command. And it seems that GitHub is also promoting this kind of workflow. For example, here is a screenshot with the copy/paste flow from the code-block in the readme:

![Screen Shot 2022-08-08 at 9 39 36 AM](https://user-images.githubusercontent.com/23109390/183457824-6f0eca66-d048-4f62-b63f-718ec73845e2.png)

**Comment by gpakosz** [comment]
I would argue that feature is a bad idea 🧐

**Comment by jpmcb** [comment]
Fair enough!
