### ISSUE TITLE
How to query/set params dynamically

### ISSUE THREAD

**Issue by apsamuel** [gpakosz/.tmux#590]
Hi, I'm using the setup here heavily for my day-to-day work in TMUX. One question I had is how I would set different parameter values per session. I have scripts that wrap tmux for instance for VScode, ssh sessions, AWS ssh sessions, etc. I have a default tmux.config.local that works fine, but what happens when I want to update the params? would I just need to create different configuration files in each condition? -- also how would changing what gets included based on the operation look.

I was looking to be able to do something like `tmux set-option "****" "value"` but it appears the options defined in the local config are macros not necessarily directly accessible to be changed with the API calls?

**Comment by gpakosz** [comment]
Hello @apsamuel 👋

Oh my tmux! works by deferring to a shell script (embedded as a polyglot within `.tmux.conf` itself) that interprets the content of variables in `~/.tmux.conf.local` and issues tmux commands accordingly.

Starting with tmux `2.5` there's the `client-session-changed` hook.
Maybe there's a way to use that hook to set session options but that's really not straightforward to implement and I'm not sure if it's worth it.
  - How and where would the per-session options be defined?
    - A shared `~/.tmux.conf.local` file?
    - Different `.tmux.conf.local.{session-name}` files?
  - Can all options be session options?

In any case, that's currently way out of what Oh my tmux! can do and it would complicate things much.

**Comment by apsamuel** [comment]
No problem & totally understand.
