### ISSUE TITLE
Tmux fails to start 

### ISSUE THREAD

**Issue by luisdavim** [gpakosz/.tmux#593]
Hi, I've updated to the latest version and since then `tmux` fails to start, I was able to trace the issue to https://github.com/gpakosz/.tmux/commit/68a909d4ca560f02a095aa79bd98c2e0d71d45b0

If I checkout the commit before that one everything works again.

I'm running on Android in `termux`, I can try running on `macOS` tomorrow and see if the issue is specific to `termux`...

Let me know if there's any specific info you need.

**update:** If I checkout https://github.com/gpakosz/.tmux/commit/b620a4f0fb6d8631b98559022a1d5e5f2bd2ce4f it also works so it's probably an issue with the latest commit: https://github.com/gpakosz/.tmux/commit/5fa30deb20865bdcb966ee362f76a6b82cdb079a and https://github.com/gpakosz/.tmux/commit/68a909d4ca560f02a095aa79bd98c2e0d71d45b0 is probably also broken but that issue was fixed in the following commit.

**Comment by luisdavim** [comment]
Setting line 29 to:

```sh
bind e new-window -n "~/.tmux.conf.local" sh -c '${EDITOR:-vim} ~/.tmux.conf.local && tmux source ~/.tmux.conf && tmux display "~/.tmux.conf sourced"'
```

Are those replacements really necessary? Why do we need to avoid using `mvim` and `gvim`?

**Comment by luisdavim** [comment]
#594 would solve this issue.

**Comment by gpakosz** [comment]
Hello @luisdavim 👋

The substitutions have been introduced to fix #416.

**Comment by gpakosz** [comment]
Maybe I could do some introspection and check if `EDITOR` is set to `gvim` or `mvim` and launch them with `-f`. But let's remove the substitutions for now.

**Comment by luisdavim** [comment]
> Maybe I could do some introspection and check if `EDITOR` is set to `gvim` or `mvim` and launch them with `-f`. But let's remove the substitutions for now.

yeah, but if we go down that path there would be many more editors to take care of like VSCode, IntelliJ, some flavours of emacs, etc....
