### ISSUE TITLE
iTerm command + left is mapped to prefix

### ISSUE THREAD

**Issue by talohana** [gpakosz/.tmux#599]
Hi all,

I'm using Mac - iTerm2 with ["natural text editing"](https://apple.stackexchange.com/questions/136928/using-alt-cmd-right-left-arrow-in-iterm) key map, and the cmd + left arrow is mapped  to prefix (C-b) instead of actually going to the start of the line, which makes me actually type cmd + left arrow + left arrow to go to start of the line.

Changing the prefix key to C-a by adding the following lines in `.tmux.conf` also didn't work.
```
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix
```

Is there any way around this?

**Comment by gpakosz** [comment]
Hello @talohana 👋

I'm sorry I have no idea.
Please reach out to tmux support channels. Thanks!

**Comment by gpakosz** [comment]
Also as far as `C-a` is concerned, the default behavior of Oh my tmux! is to use both `C-b` and `C-a` as prefix.

Finally, please do not change `.tmux.conf`: only override settings in your `~/.tmux.conf.local` copy.

**Comment by talohana** [comment]
Today I played with the configuration a little more - it turns out the `C-a` prefix is what caused the issue, unbinding it fixed it.
