### ISSUE TITLE
maximize pane to center of screen

### ISSUE THREAD

**Issue by fantapop** [gpakosz/.tmux#6]
Hi,

I was reading your post about the maximize pane to a new window and it seems to come close to something im interested in.  I started using a 4k monitor recently.  When I maximize my tmux pane, all of the text goes very far to the left since the high resolution can fit so many panes.  This has been straining my neck.  What I'd like is to be able to center the zoomed pane in my monitor.  Have you thought about this at all?  Is it possible doing something like your maximize_pane() function?

thanks

**Comment by gpakosz** [comment]
I'm afraid it's not possible in tmux. There's no way to e.g. have a single pane in a window and reduce its dimensions and center it.

**Comment by fantapop** [comment]
okay, thank you.
