### ISSUE TITLE
Cannot click to switch panel in Windterm

### ISSUE THREAD

**Issue by jiang-yuan** [gpakosz/.tmux#600]
I am using .tmux default configuration for mouse mode.
When I switch to mouse mode in Windterm ssh window, clicking on the panel name rarely works. I do not if there is any confliction between .tmux and Windterm mouse function. For mobaXterm, it works well.
![image](https://user-images.githubusercontent.com/36291537/187217459-a1fa8a31-b0c1-4ecc-a60c-24ea2a9d6bdf.png)

**Comment by gpakosz** [comment]
Hello @jiang-yuan 👋

Sorry for the late reply. I'm sorry I don't use `Windterm` and Oh my tmux! does nothing specific regarding what should happen when clicking on the status bar.
