### ISSUE TITLE
the cmd of zsh mess up 

### ISSUE THREAD

**Issue by BravoLu** [gpakosz/.tmux#601]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/28304030/187684874-c87363a0-2242-4cad-b70a-4d0e93bd6c2f.png">
when I use this .tmux.conf, I found that the display of command is weird, it's normal when I do not use tmux.

**Comment by gpakosz** [comment]
Looks like you have a broken / incompatible `tmux-256color` terminal definition installed.

You can either try to reinstall it, if that works for you:
```
$ $(brew --prefix ncurses)/bin/infocmp tmux-256color | sed -e 's/pairs#0x10000/pairs#0x1000/g' -e 's/pairs#0x65536/pairs#0x32768/g' > /tmp/tmux-256color.info
$ /usr/bin/tic -x /tmp/tmux-256color.info

Or edit your `~/.tmux.conf.local` copy to add the following
```
set -g default-terminal "screen-256color"
```

Please do not edit `~/.tmux.conf`

**Comment by ZeyiLiao** [comment]
Hi I have tried the second approaches on my Mac and seems do not work.
> Looks like you have a broken / incompatible `tmux-256color` terminal definition installed.
> 
> You can either try to reinstall it, if that works for you:
> 
> ```
> $ $(brew --prefix ncurses)/bin/infocmp tmux-256color | sed -e 's/pairs#0x10000/pairs#0x1000/g' -e 's/pairs#0x65536/pairs#0x32768/g' > /tmp/tmux-256color.info
> $ /usr/bin/tic -x /tmp/tmux-256color.info
> ```
> 
> Or edit your `~/.tmux.conf.local` copy to add the following
> 
> ```
> set -g default-terminal "screen-256color"
> ```
> 
> Please do not edit `~/.tmux.conf`

I even can not do `clear` or when I press delete it will add space at the command line, I really don't know what happened.
Btw, I am using oh-my-zsh and zsh at my terminal. I am not sure if that's a issue since I run tmux well on my server which is a bash-based one.

**Comment by ZeyiLiao** [comment]
What's more, this is what I have at ~/.vimrc and it wont work at tmux panel.
```
syntax enable
set background=dark
let g:solarized_termcolors=256
let g:solarized_contrast = "high"
let g:solarized_termtrans = 1

colorscheme solarized
set mouse=r
```
