### ISSUE TITLE
rename windows

### ISSUE THREAD

**Issue by menash134** [gpakosz/.tmux#602]
Hi ,

Sorry to bother you. Could you please tell me how to rename the current window?

 <prefix> R or r does not work in your config.

**Comment by Omnia89** [comment]
Just use the standard tmux keybinding: `<prefix> ,`

**Comment by marlensouza** [comment]
Window is identify for index. Pane is will rename. To do this you use: Ctrl+b, so on character $.

**Comment by gpakosz** [comment]
Hello 👋

To rename a window: `<prefix> + ,`

To rename a session: `<prefix> + $`
