### ISSUE TITLE
Erros when loading tmux

### ISSUE THREAD

**Issue by luciferkonn** [gpakosz/.tmux#604]
I get the following errors when I load tmux.
<img width="1782" alt="Screen Shot 2022-09-19 at 5 08 10 PM" src="https://user-images.githubusercontent.com/15608474/191116853-acc21c31-ce61-4b19-b65b-3707a7671c90.png">

This seems problematic because the cursor automatically moves to the following line when I enter "ctl+b".

Any thoughts about how to solve this issue?

**Comment by gpakosz** [comment]
Hello @luciferkonn 👋

The `34` number on the left tells you have `34` active sessions. Can you please try again after having killed all `tmux` processes?

**Comment by gpakosz** [comment]
Hello @luciferkonn 👋

Closing this issue. Fell free to repoen.
