### ISSUE TITLE
Picking tmux executable from the global environment

### ISSUE THREAD

**Issue by nokeldin** [gpakosz/.tmux#607]
Trying to load this configuration on a machine that has an outdated /usr/bin/tmux, I ran into the following:

`run 'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1`

The reason is that the _apply_configuration function (and presumably all others) were picking tmux 1.8 from /usr/bin/tmux, and I had launched tmux using a local appimage. My bashrc has tmux aliased to said local appImage. 

I don't know the exact fix but I fixed it by putting the same alias at the top of the shell script in .tmux.conf 
Maybe there can be some way to get the tmux executable from the global environment (maybe by checking the executable used to run the server?). Alternatively maybe a config option can be provided.

**Comment by nokeldin** [comment]
Adding on some troubleshooting I did. It seems the issue is more deeprooted. Even though setting alias=$HOME/.local/appimages/tmux.appimage worked in getting the conf to load properly, it seems some of the functions were still picking the /usr/bin/tmux.

Specifically, for _fpp, the only way I could get it to work was by repacing all tmux calls by /path/to/tmux and all fpp calls by /path/to/fpp.

Will be great if configuration variables for all executables can be provided - shell, cut, sed, awk, fpp, tmux.

**Comment by gpakosz** [comment]
Hello @nokeldin 👋

I'm not sure which operating system you're using but this issue is related to #587

As a workaround, you can set a temporary `PATH` value in your `~/.tmux.conf.local` copy:
```
...
# -- user customizations -------------------------------------------------------
# this is the place to override or undo settings

PATH=/usr/local/bin:/usr/bin:/bin
...

**Comment by gpakosz** [comment]
> Will be great if configuration variables for all executables can be provided - shell, cut, sed, awk, fpp, tmux

I'm not a fan of this idea to be honest. Do you expect other scripts to do the same?
