### ISSUE TITLE
Issues with mouse mode copy

### ISSUE THREAD

**Issue by TommyButts02** [gpakosz/.tmux#608]
Anyone else have the issue their terminal jumping to the bottom after copying text? I've been digging through forums and tmux confs but any changed i make seem to break mouse mode entirely

**Comment by gpakosz** [comment]
Hello @TommyButts02 

This is tmux's default behavior.
What you can do is
```
$ tmux -L test -f /dev/null lsk | grep '\-and-cancel'
```

Then copy paste the result to your `~/.tmux.conf.local` copy and remove the `-an-cancel` part for each line
