### ISSUE TITLE
how to use tmux as default shell

### ISSUE THREAD

**Issue by 0xMrR0b0t** [gpakosz/.tmux#614]

**Comment by gpakosz** [comment]
Hello @0xMrR0b0t 👋

I don't use `tmux` as the default shell myself. Please ask on the usual `tmux` support channels 😊

**Comment by gpakosz** [comment]
Dupe of #587

**Comment by HXRCyberLabs** [comment]
@gpakosz, Can i get only the "Copy to OS clipboard" part of the tmux.conf file, I like to keep things in default style.
