### ISSUE TITLE
#{hostname} shows PID instead of hostname on MacOS

### ISSUE THREAD

**Issue by westhomas** [gpakosz/.tmux#615]
I recently updated to `master` and noticed the hostname was showing a number instead of my hostname in MacOS Ventura 13.1.

<img width="348" alt="Screenshot 2023-01-04 at 10 04 25 AM" src="https://user-images.githubusercontent.com/953369/210597669-44b9ef94-7b71-4a54-aa16-20b063229ec5.png">

I moved backwards in the commit log until it started working again. Apparently, this commit is responsible:

https://github.com/gpakosz/.tmux/commit/18775e1

One commit before this and it works again:

<img width="350" alt="Screenshot 2023-01-04 at 10 04 38 AM" src="https://user-images.githubusercontent.com/953369/210597797-77cecf89-4fad-4ab6-8484-f5ef1894167e.png">

I believe it's showing the PID based on what I see in that commit. However, I don't know why.

This seems to work fine on my Debian system.

**Comment by gpakosz** [comment]
Hello @westhomas 👋

- The first thing you can try is to reload the configuration with `<prefix> + r`
- If it doesn't work, does the problem still happen when you relaunch tmux entirely? (kill all tmux processes)
- If yes, can you please share `tmux_conf_theme_status_left` and also paste the output of `tmux show -gv status-left`?

**Comment by westhomas** [comment]
Reloading the config worked! Thank you!

But I'm curious why? I stopped the tmux session and restarted it multiple times. What does a "reload" do that restarting a tmux doesn't do?
