### ISSUE TITLE
Syntax error when loading .tmux.conf

### ISSUE THREAD

**Issue by kasim** [gpakosz/.tmux#616]
### TMUX version
`tmux next-3.4`

### OS
`Linux karch 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux`

### TMUX configuration
master branch

### Problem description
I changed the following lines so I could keep the tmux.conf.in in tmp
~                              |   719 # _apply_bindings() {
~                              |~  720 #   #cfg=$(mktemp) && trap 'rm -f $cfg*' EXIT
~                              |+  721 #   cfg=/tmp/tmux.conf

Now the error shown when I started tmux as following
`/tmp/tmux.conf.in:15: syntax error`

Lines 15 is
| 14 bind-key    -T prefix       C-c                  new-session
| 15 bind-key    -T prefix       \\"                   split-window
| 16 bind-key    -T prefix       \\%                   split-window -h

**Comment by gpakosz** [comment]
Hello @kasim 👋

Thanks for the report. Please try the `gh-616` branch.

**Comment by kasim** [comment]
> Hello @kasim wave
> 
> Thanks for the report. Please try the `gh-616` branch.

Tried in my local, it is working perfectly.

**Comment by gpakosz** [comment]
Except it doesn't totally work. Still looking at it

**Comment by gpakosz** [comment]
@kasim For now your best bet is to use tmux `3.3a`

**Comment by gpakosz** [comment]
Reported in tmux/tmux#3424, fixed in https://github.com/tmux/tmux/commit/a41a92744188ec5c8a8d4ddc100ec15b52d04603

Still, I recommend using the latest stable release of `tmux` which is `3.3a`
