### ISSUE TITLE
NixOS does not have /usr/bin/infocmp

### ISSUE THREAD

**Issue by maxbrunet** [gpakosz/.tmux#617]
The change made in 2cf4d9a10415f58612c1a387fbeb9c0efe79d751 breaks 256-color support on NixOS which does not have `/usr/bin/infocmp`:

```console
$ command -v infocmp
/run/current-system/sw/bin/infocmp
```

The only available binary under `/usr/bin` is `env` to allow writing portable scripts (e.g. `#!/usr/bin/env bash` shebang). But reading the past issues, doing `/usr/bin/env infocmp` would result in a regression on MacOS where we want to ensure the system `infocmp` is used. Maybe the condition could  call `infocmp` differently depending on the OS (e.g. use `uname -s`), or test if the executable exits and try to fallback to the one from the env if it does not?

**Workaround:** Add the previous command to `.tmux.conf.local`:

```shell
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'
```

**Comment by gpakosz** [comment]
Hello @maxbrunet 👋

Can you please try the `gh-617` branch?

**Comment by maxbrunet** [comment]
Hey @gpakosz :wave:, thank you for the super quick reply, `gh-617` works like a charm!

**Comment by gpakosz** [comment]
@maxbrunet Thanks for the report!
