### ISSUE TITLE
not working on void linux? (tpm isn't working)

### ISSUE THREAD

**Issue by lime-desu** [gpakosz/.tmux#618]
I have a custom function that installs oh-my-tmux on a certain directory if it doesn't exist and symlink the .tmux.conf file on the home directory now upon installation,

This is what it looks like when using omt on void linux:
![Screenshot_2023-01-23_21-37-19](https://user-images.githubusercontent.com/114978689/214058449-854303c6-9c14-4771-9c78-5d4dd24f7e4c.png)

The configuration looks like a vanilla tmux though the keybinding are working fine (C-a) prefix are working and also prefix+I to install tpm plugins isn't working 

I have tried following this [installation process ](https://github.com/gpakosz/.tmux#installation)and met all the following requirement, still no luck, same problem.

In comparison this is what my configuration looks like using oh-my-tmux on fedora:
![Screenshot from 2023-01-23 21-50-37](https://user-images.githubusercontent.com/114978689/214062869-b6a825cd-9284-4eea-aa36-ad88bf0a1aa8.png)

The difference is that there's a .tmux on home directory with all the tpm plugins installed

**Comment by gpakosz** [comment]
Hello @lime-desu 👋

I'm sorry I don't know Void Linux.
After having launched tmux, can you please paste the output of
```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
```
?

**Comment by lime-desu** [comment]
> Hello @lime-desu 👋
> 
> I'm sorry I don't know Void Linux. After having launched tmux, can you please paste the output of
> 
> ```
> $ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
> ```
> 
> ?

```
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ set +H
+ true
+ printf 
+ sed -E s///
+ uname -s
+ _uname_s=Linux
+ tmux -V
+ awk {gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}
+ _tmux_version=330
+ command -v pkill
+ _apply_configuration
+ tmux display -p #{window_active}
+ window_active=1
+ [ -z 1 ]
+ command -v reattach-to-user-namespace
+ _apply_tmux_256color
+ command infocmp -x tmux-256color
```

**Comment by gpakosz** [comment]
What's the output of `command -v infocmp` please?

**Comment by lime-desu** [comment]
> What's the output of `command -v infocmp` please?

It does exist
`/bin/infocmp`

**Comment by gpakosz** [comment]
But I suspect `infocmp -x tmux-256color` returns a non 0 exit status right?
```
$ infocmp -x tmux-256color
$ echo $?
```

**Comment by gpakosz** [comment]
Can you please try the `gh-618` branch?

**Comment by lime-desu** [comment]
> Can you please try the `gh-618` branch?

Yes, It is working now thank you very much!
