### ISSUE TITLE
Typo: uname_s

### ISSUE THREAD

**Issue by onionyst** [gpakosz/.tmux#619]
A possible variant of #618 on macOS Ventura 13.1 and tmux 3.3a. 

There may be a [typo](https://github.com/gpakosz/.tmux/commit/044d6336e84034c14760a2fe178f604a89626bfb#diff-aae53c36d76f2bb879f34e777935c4d1c6188a8309d2bf2e8d69299c119fff37R695) in `.tmux.conf` at Line 695 where `$uname_s` should be a `$_uname_s`.

**Comment by gpakosz** [comment]
Hello @onionyst 👋

There's definitely a typo. Good catch and thank you!
