### ISSUE TITLE
tmux as shell

### ISSUE THREAD

**Issue by onaforeignshore** [gpakosz/.tmux#62]
When you run tmux as the shell in a terminal emulator, i.e. without running bash/zsh/etc first, the status line doesn't get changed from the default one. Is this expected behavior or is there a way to still apply your script?

**Comment by gpakosz** [comment]
Hello @onaforeignshore 

I suspect this is because the `tmux` executable is not in `$PATH`.
If you do
```
$ tmux run 'echo $PATH'
```

What is the output? Please pay attention to single quotes above.

PS: if your goal is to start tmux on every shell login, then there are other ways.

**Comment by onaforeignshore** [comment]
Thanks for pointing that out. That was indeed the issue. I found this solution online, and now it works as it should.

On macOS Sierra, you have to do `sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` and then reboot.

The path will now be updated for all users. See [here](http://apple.stackexchange.com/questions/243322/set-path-variable-so-that-it-is-detected-in-all-applications-even-outside-termi) for more information.

**Comment by gpakosz** [comment]
Closing now that you solved it.
