### ISSUE TITLE
disable status bar and use powerline instead?

### ISSUE THREAD

**Issue by gieses** [gpakosz/.tmux#621]
Thanks for making this repo! It's awesome how many bells and whistles are in the template. I'd like to replace the status bar with the https://github.com/erikw/tmux-powerline version. However, when I put the code below, only parts of the status bar change (the middle panel). The left and right stay the same.

```

set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
# paths are adapted to the repo location locally + I added the powerline path to my PATH
set-option -g status-left "#(~/path/to/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/path/to/tmux-powerline/powerline.sh right)"
set-hook -g session-created 'run-shell "~/path/to/tmux-powerline/powerline.sh init"' # prettifies the window-status segments
```

When I refresh the plugins with prefix + r, I can see what looks like the right status bar from the powerline config but only for a very brief moment in the beginning. I tried putting the above snippet at the beginning or end but it work.

Do you have any advice?

**Comment by gpakosz** [comment]
Hello @gieses 👋

Add `tmux_conf_theme=disabled` in your `~/.tmux.conf.local` copy

**Comment by gpakosz** [comment]
That being said, if you edit `~/.tmux.conf` you're on your own. Only customize your `~/.tmux.conf.local` copy

**Comment by gieses** [comment]
@gpakosz thanks, awesome! Works without any further adjustment. Now, I realized that it's actually documented ...

Yes, I was indeed referring to the `~/.tmux.conf.local ` copy.

**Comment by gpakosz** [comment]
> Now, I realized that it's actually documented ...

It's a recent enhancement
