### ISSUE TITLE
Copy whole path or text block on double click

### ISSUE THREAD

**Issue by khskekec** [gpakosz/.tmux#625]
Hi everynone,

i've just swtiched from MacOS to Ubuntu and am totally missing this feature. I am not sure why it worked before but what i am looking for is the nice behaviour of double click. Actually it is only copying the word under cursor. Before it copy the whole text block.
This made things easir especially if you running `git status` and want to copy the file path of the file you want to add.

Can someone give me a hint?

Kind regards

Selcuk

**Comment by gpakosz** [comment]
Hello @khskekec 👋

I'm not sure what you're looking for has anything to do with tmux or Oh my tmux!
But is rather a matter of terminal emulator application that differs between macOS and Ubuntu.
