### ISSUE TITLE
recent change broke 24bit

### ISSUE THREAD

**Issue by choppsv1** [gpakosz/.tmux#626]
commit 044d633 added a call to an apply256 color function. This (or something) caused new sessions to be set to tmux-256color now rather than tmux-24bit that it was previously. 

```
$ tmux -V
tmux 3.2a
$ egrep '24|256' ~/.tmux.conf.local
# RGB 24-bit colour support (tmux >= 2.2), possible values are:
tmux_conf_theme_24b_colour=true
tmux_conf_theme_clock_style='24'
set -g default-terminal "tmux-24bit" # colors!
# set -g terminal-overrides ',tmux-256color:Tc'
# set -g default-terminal "xterm-24bit"
# set -g terminal-overrides ',xterm-24bit:Tc'
#set -g terminal-overrides ',tmux-256color:sitm=\E[3m,tmux-256color:ritm=\E[23m,tmux-256color:setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,tmux-256color:setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,tmux-256color:Tc'
```

**Comment by gpakosz** [comment]
Hello @choppsv1 👋

What is `tmux-24bit`?

**Comment by choppsv1** [comment]
I just did some googling and it looks like the official terminfo name is `tmux-direct`. I started doing this 24bit stuff a while ago prior to it being more standardized so `tmux-24bit` might be my own made up thing.

**Comment by gpakosz** [comment]
I don't know where that comes from.
AFAIK the official tmux documentation only mentions `tmux-256color`.

Can you please try to revert to a stock `ncurses` setup and use the `tmux_conf_24b_colour=true` option in your `.local` customization file copy?

**Comment by choppsv1** [comment]
I probably made it up, ncurses/tmux now uses `tmux-direct` it seems. I used to maintain a patch for emacs to support 24 bit color terminals, tmux-24bit probably dates from that time. :) In any case `TERM` needs to be `tmux-direct` for emacs to do 24bit color, when it is `tmux-256color` emacs only does 265.

**Comment by gpakosz** [comment]
Maybe I didn't search properly but the tmux Wiki doesn't mention `tmux-direct`. But my `ncurses` indeed has it

**Comment by choppsv1** [comment]
I found the info here: https://github.com/tmux/tmux/issues/2370

**Comment by gpakosz** [comment]
Can you please try the `gh-626` branch?

**Comment by choppsv1** [comment]
So, that works once I changed my old config line

```
-set -g default-terminal "tmux-24bit" # colors!
+set -g default-terminal "tmux-direct" # colors!
```

FWIW I had already used #!important to get the behavior I wanted, but I reverted that for the test. :)

Interestingly vim does not render the same with this new `tmux-direct` compared to my old `tmux-24bit` terminfo.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/3074665/220584932-0e19bbcd-47fd-44e8-8998-2ef2e381f51f.png">

**Comment by gpakosz** [comment]
Yeah terminfo definitions are not my area of expertise.

I'll land the fix to avoid changing `tmux-direct` and then there's always the `#!important` solution
