### ISSUE TITLE
Cannot clear tmux_conf_theme_status_left and tmux_conf_theme_status_right.

### ISSUE THREAD

**Issue by wadgaonkarsam** [gpakosz/.tmux#629]
Cannot clear tmux_conf_theme_status_left and tmux_conf_theme_status_right. It sticks to the same format it was set to before after setting tmux_conf_theme_status_left=""  and tmux_conf_theme_status_right="" in the .tmux.conf.local file. I am looking to remove the session name from the status, but it stays after setting tmux_conf_theme_status_left="".

**Comment by gpakosz** [comment]
Hello @wadgaonkarsam 👋

Can you please try the `gh-629` branch?

**Comment by wadgaonkarsam** [comment]
@gpakosz That fixed the issue. Thank you!
