### ISSUE TITLE
Is it possible to get new_window_reconnect_ssh

### ISSUE THREAD

**Issue by Jendker** [gpakosz/.tmux#632]
Is it possible to get the equivalent of `tmux_conf_new_pane_reconnect_ssh` but for windows? That works for paths with `tmux_conf_new_window_retain_current_path`. I am wondering `tmux_conf_new_window_reconnect_ssh` is not implemented.

**Comment by gpakosz** [comment]
Hello @Jendker 👋

It's just that I never got a used for it 🙂

**Comment by Jendker** [comment]
Oh, I see. I was wondering if there is any technical reason behind it. Thanks! I will open the PR if I get to implement it.

**Comment by Jendker** [comment]
Unfortunately I didn't manage to hack my way to add this functionality. Still, in my case it has proven helpful to use multiple windows with full size. If you will find some time to implement this feature, I'll be thankful :) Thank you so much!

**Comment by gpakosz** [comment]
Hello @Jendker 👋

Can you please give the `gh-632` branch a try?

**Comment by Jendker** [comment]
It works great. Thank you so much!
