### ISSUE TITLE
history is cleared on ssh connection

### ISSUE THREAD

**Issue by albttx** [gpakosz/.tmux#634]
Once i ssh, i lost my previous history and get a new one from the ssh connection, why that ?

**Comment by gpakosz** [comment]
Hello @albttx  👋

Hmm I'm afraid it's just how things work when connecting to a remote server with ssh?

**Comment by albttx** [comment]
Hello,

sorry for my unclear explanation, here is the steps to reproduce

```
$ ls -l
[...]

$ clear

# here, i can scroll history

$ ssh root@1.1.1.1
[...]

# here, if i have the history if i scroll

root@1.1.1.1:~$ clear

# and now, if i scroll, it's [0/0], no history
```

Of course, without tmux, it's working.

**Comment by gpakosz** [comment]
I'm still unsure what you expectations are.

Does it happen if you use tmux without Oh my tmux!? You can try with `tmux -L test -f /dev/null` to make sure no configuration what so ever is loaded.

**Comment by gpakosz** [comment]
I think you want
```
bind -n C-l send-keys C-l
```
