### ISSUE TITLE
How to get rid of the spaces in between each tabs in the bar?

### ISSUE THREAD

**Issue by TKperson** [gpakosz/.tmux#641]
![image](https://user-images.githubusercontent.com/50115012/233822295-5020debf-b37d-43a3-96b9-d22ebc0e012b.png)

**Comment by gpakosz** [comment]
Hello @TKperson 👋

It's unfortunately not possible in a way that generalises to assigning different colors and styles to last window, window with a bell, window with activity, non current window(s), and current window.

**Comment by TKperson** [comment]
Thanks for letting me know

**Comment by TKperson** [comment]
Btw, do you have any idea why tmux is showing a different color of the prompt?
Using tmux:
![image](https://user-images.githubusercontent.com/50115012/234174275-391945be-8d7c-4c26-ad3b-a9fb97592bc4.png)

Not using tmux:
![image](https://user-images.githubusercontent.com/50115012/234174370-68ca9d0a-ec02-4f7c-ae20-f67f94dd860f.png)
