### ISSUE TITLE
Add support to pin battery

### ISSUE THREAD

**Issue by yuntsewu** [gpakosz/.tmux#65]
Some of us have multiple batteries in our laptops. Would be great to be able to pin battery id, or the conf dynamically show level for all combined.

**Comment by gpakosz** [comment]
Which OS are you using?

**Comment by yuntsewu** [comment]
I use linux, it looks like its only greping from BAT0, while on linux it usually discharges BAT1 first then BAT0. And charges BAT0 first then BAT1. 

I could write this and send in a PR, is this edited on tmux conf where it looks like its commented out?

**Comment by gpakosz** [comment]
So all in all, I guess I should average charge of both batteries. What do you think?

**Comment by yuntsewu** [comment]
Yes, average would be great. 
I made a branch that's not really working yet. Still have to tweak the code. 
https://github.com/yuntsewu/.tmux/tree/2-battery-fix

**Comment by gpakosz** [comment]
I added a Linux implementation to the `multiple-batteries` branch. Can you give it a spin?

Also, if you happen to have a laptop with more than a single battery and running windows, I'm curious about the output of the following commands:
```
wmic path Win32_Battery
```
```
wmic path Win32_Battery Get BatteryStatus
```
```
wmic path Win32_Battery Get EstimatedChargeRemaining /format:list
```

**Comment by yuntsewu** [comment]
It didn't work
![2017-04-16-151529_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1158841/25074750/9f842c9c-22b7-11e7-8188-7a7503e1ed6f.png)
looks like you are trying to grab data from /tmp/sys/class/power_supply/BAT$batid, it doesn't exist on my (fedora 25) os

Data is retrieved from: 
```bash
$ cat /sys/class/power_supply/BAT*/capacity
99
85
```

**Comment by gpakosz** [comment]
damn forgot to remove the `/tmp/` prefix, I was just simulating things. Fixed, please pull.

**Comment by yuntsewu** [comment]
lol, working now
![2017-04-16-153136_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1158841/25074809/df25b06c-22b9-11e7-8b41-8b60058f0705.png)

Two thumbs up, thanks for the quick respond. Now I can use this in full screen in less distracted mode

**Comment by gpakosz** [comment]
Since I can't get my hands on a laptop with two batteries, do you happen to know people running Windows with two batteries?

**Comment by yuntsewu** [comment]
hmm, because you want to test the same feature change on Windows user...
Popular laptops today would be surface book and Thinkpad T or P series (which I use) that has two batteries. 

I don't know anyone who run those and Windows around me. But people who use the models above would be the one's you want to hunt down.
