### ISSUE TITLE
Cannot change `$TERM` variable

### ISSUE THREAD

**Issue by lime-desu** [gpakosz/.tmux#651]
I have this code set on my `.tmux.conf.local`
```sh
set -g default-terminal "xterm-256color"
```
This should override the default tmux-256 colors, but it isn't working on mine.
The variable doesn't get override:
```sh
❯ echo $TERM
tmux-256color
```

Perhaps a bug or there's something wrong with my [tmux config](https://github.com/lime-desu/dootsfile/blob/main/config/tmux/tmux.conf.local)?

Though, setting this line explicitly on.zshrc fixes my problem
```sh
[[ "$TERM_PROGRAM" == tmux ]] && export TERM=xterm-256color
```

**Comment by gpakosz** [comment]
Hello @lime-desu 👋

Inside tmux, `TERM` should not be `xterm-256color`, see tmux documentation.

That being said, you can use
```
set -g default-terminal "screen-256color" #!important
```

**Comment by lime-desu** [comment]
> Hello @lime-desu wave
> 
> Inside tmux, `TERM` should not be `xterm-256color`, see tmux documentation.
> 

Hi! 
Oh what I mean is i'm trying to change the tmux-256 `$TERM` into `xterm-256

> That being said, you can use
> 
> ```
> set -g default-terminal "screen-256color" #!important
> ```

Yeah, thank you very for this! Adding the `#!important` should take precedence since there's this snippet on `.tmux.conf`

https://github.com/gpakosz/.tmux/blob/fd1bbb56148101f4b286ddafd98f2ac2dcd69cd8/.tmux.conf#LL775C1-L775C55

I'll be closing this as resolved
Also a dup of #643 (haven't notice since its closed)
