### ISSUE TITLE
Battery bar color displayed wrong

### ISSUE THREAD

**Issue by mikahosh1no** [gpakosz/.tmux#652]
Hello, thank you for creating such an excellent project. I found that the `battery_bar` can not display colors properly after installation. From the `.tmux.conf.local` file, I noticed that emoji characters are used. As far as I understand, emoji can not change colors. Should it be changed to Ascii square? like

```
tmux_conf_battery_bar_symbol_full="■"
tmux_conf_battery_bar_symbol_empty="□"
```

### Env

- Alacritty
- ArchLinux
- zsh 5.9.3
- tmux 3.3

### Screenshot

![2023-05-13_14-53](https://github.com/gpakosz/.tmux/assets/131941394/dcb9b2eb-adab-4e05-bbba-49d9a1db3c05)

**Comment by gpakosz** [comment]
Hello @mikahosh1no 👋

It's been working for me so far
<img width="153" alt="image" src="https://github.com/gpakosz/.tmux/assets/553208/4bf3a4bf-4288-4c55-abf5-b3a5ae4afc20">

> As far as I understand, emoji can not change colors

The stock configuration is using `U+25FC` and `U+25FB` which are from the `Math Symbol` category.
I'll make more tests with `U+25A0` and `U+25A1`.

> As far as I understand, emoji can not change colors

Well all of `U+25FC`, `U+25FB`, `U+25A0` and `U+25A1` have "black" or "white" in their names and are from the `Geometric Shapes` block which is different from the `Emoticons` block which goes from `U+1F600` to `U+1F64F`.

Can you please reach out to Alacritty folks to figure out why it doesn't change color?

**Comment by mikahosh1no** [comment]
I tested the same configuration with WezTerm and the colors displayed correctly.  I'm trying to find the differences between the two, and I think it might be due to the font. When I use the Fira Code font, colors are not displayed correctly.

**Comment by Hanaasagi** [comment]
@mikahosh1no 
I have been using Alacritty and the Fira Code font, and I haven't encountered this issue. Did you install some emoji fonts?

![2023-05-21_01-28](https://github.com/gpakosz/.tmux/assets/9482395/a0b99e74-2436-4350-8ccf-4a7f51f883de)

This electric plug symbol looks like the one in Google Noto Color Emoji.  `U+25FC` is defined in this font, See https://github.com/googlefonts/noto-emoji/blob/934a5706f1f3dd2605c4d9b5d9162fd7f89d8702/svg/emoji_u25fc.svg?plain=1 

Ref: https://emojipedia.org/electric-plug/
