### ISSUE TITLE
when I install this configuration, my tmux looks different than the one in the videos

### ISSUE THREAD

**Issue by maneater2** [gpakosz/.tmux#655]
my tmux only has blue, but in the video there is red, yellow and white and other colors. Is there something I should enable or is it not meant to be like that on default?

**Comment by allthelightwe** [comment]
My OS is OpenBSD 7.3 Release
tmux tells me the version is "tmux openbsd-7.3"
the value is xterm-256color
here's a screenshot:
![image](https://github.com/gpakosz/.tmux/assets/114833619/f6228316-9ab5-46c6-8cd1-e769cfa4161b)

**Comment by allthelightwe** [comment]
although when I try it on Arch Linux it works...

**Comment by gpakosz** [comment]
tmux reads configuration files in the following order
- `/usr/local/etc/tmux.conf`
- `~/.tmux.conf`
- `$XDG_CONFIG_HOME/tmux/tmux.conf`
- `~/.config/tmux/tmux.conf`

It doesn't stop at the first one it finds. Please have a look if you don't have configuration files laying around that would set `status-left` and `status-right`.

**Comment by allthelightwe** [comment]
I only have a configuration in my `HOME`

**Comment by gpakosz** [comment]
I didn't reproduce with an OpenBSD `7.3` Vagrant box

```
$ vagrant init fnichol/openbsd-7.3
$ vagrant ssh
$ su -
$ pkg_add git
$ exit
$ git clone https://github.com/gpakosz/.tmux
$ ln -s .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
$ tmux
```

**Comment by allthelightwe** [comment]
> What's the output of the following command please?
> 
> ```
> $ env | grep TMUX
> ```

sorry for the late reply, the output of the command is:
`TMUX_CONF=/home/light/.tmux.conf`
`TMUX=/tmp/tmux-1000/default,9689,0`
`TMUX_SOCKET=/tmp/tmux-1000/default`
`TMUX_PROGRAM=tmux`
`TMUX_PANE=%1`
`TMUX_CONF_LOCAL=/home/USER/.tmux.conf.local`

**Comment by gpakosz** [comment]
Is `tmux` in your path?

**Comment by gpakosz** [comment]
@allthelightwe 

Can you please clone and install again? There was an issue with GitHub picking the wrong branch as the default branch

**Comment by gpakosz** [comment]
Hello @maneater2 👋

Are you still facing this issue?

**Comment by maneater2** [comment]
yes

**Comment by maneater2** [comment]
could it be a issue with tmux not associating .tmux.local.conf with itself?

**Comment by gpakosz** [comment]
> could it be a issue with tmux not associating .tmux.local.conf with itself?

I don't think so

As I said I didn't reproduce in an OpenBSD 7.3 Vagrant box.
Are you still using this version of OpenBSD?

**Comment by maneater2** [comment]
no, I'm using 7.4-current

**Comment by mayersj1** [comment]
I'm seeing the same thing here on NixOS 23.11.

If I include a theme plugin, it sets up the status bar just fine.

Just using the default settings in the .local.tmux.conf file, I get the same behavior as shown in the screenshot above

**Comment by mayersj1** [comment]
@gpakosz You are correct.  I just pulled the latest and the status bar is working again now.
