### ISSUE TITLE
when i am trying to copy somthing it's automatically scrolling down how to stop this

### ISSUE THREAD

**Issue by never-ask-why** [gpakosz/.tmux#657]

**Comment by chevalierNoir** [comment]
Having a similar issue. This happens a lot when I copy something while scrolling up. On a mac keyboard, when I press `fn` and drag the mouse for copying, it sometimes works but sometimes doesn't.

**Comment by Tsugami** [comment]
https://github.com/gpakosz/.tmux/issues/118#issuecomment-346336181
