### ISSUE TITLE
When will the alert bell appear?

### ISSUE THREAD

**Issue by GreenSleeper** [gpakosz/.tmux#661]
I'm confused about when the alert bell appears.
When I run a command that continues for a while and leave that window, after that command completes, sometimes the bell appears and usually it doesn't.

**Comment by gpakosz** [comment]
Hello @GreenSleeper 👋

Sorry for the late answer. This question is not Oh my tmux nor tmux specific.

> sometimes the bell appears and usually it doesn't

It all depends on the program being run.
