### ISSUE TITLE
Neovim breaks with random symbols

### ISSUE THREAD

**Issue by TheKamboy** [gpakosz/.tmux#662]
When trying to use Neovim random characters appear.

Example:
![image](https://github.com/gpakosz/.tmux/assets/89111294/ff75a959-9429-4b96-bb3b-0ce2de76abd0)

It should look like this:
![image](https://github.com/gpakosz/.tmux/assets/89111294/dec3cc49-44b0-422d-a037-7738510aef56)

Can anyone help me?

**Comment by TheKamboy** [comment]
The "1" shouldn't be there.

**Comment by TheKamboy** [comment]
That was a long wait for a response!
Thanks, though.

**Comment by gpakosz** [comment]
Yeah I know.

In any case, double check the value of `TERM` outside and inside tmux
