### ISSUE TITLE
Copy Not working in gnome-terminal..

### ISSUE THREAD

**Issue by ronit18** [gpakosz/.tmux#666]
First of all great project. Love it and i dont know if this issue is by .tmux or gnome-terminal or because of my playing in gnome.

I have problem in gnome-terminal in which when i am in copy mode i use y to yank a line so it doesnt copy that line to my os clipboard, I have installed xclip xsel also. I have not touched the .tmux.conf file mostly, just changed one or two keybinds of url view. I have also enabled `tmux_conf_copy_to_os_clipboard=true`. This is output of 
`tmux lsk | grep MouseDragEnd1Pane`
```
bind-key    -T copy-mode    MouseDragEnd1Pane    send-keys -X copy-pipe-and-cancel wl-copy
bind-key    -T copy-mode-vi MouseDragEnd1Pane    send-keys -X copy-pipe wl-copy-no-clear
```

Then after trying a lot, I thought of trying other terminal emulator and tried this in alacritty, and it is working fine in that with the same config but not working in gnome-terminal.I even tried to by with clean .tmux and still didnt work. I dont know where might be problem but after trying alacritty and saw that it was working i thought of posting this issue.

**Comment by gpakosz** [comment]
Hello @ronit18 👋

Sorry for the delay.

I don't where this `wl-copy-no-clear` binding comes from. That's the issue.
