### ISSUE TITLE
Tmux 2.4 does not work when scrolling

### ISSUE THREAD

**Issue by amir20** [gpakosz/.tmux#67]
Hello,

Thanks for the great tmux profile. I am new to tmux. I had been using `tmux 2.3` and everything worked as expected. Today I upgrade to `2.4` and when scrolling up, the window doesn't actually scroll. Instead, it behaves as if the up arrow was pressed. 

OS: Mac OS 10.12.4
`tmux -V`: tmux 2.4

**Comment by gpakosz** [comment]
What's the key combination you're using for scrolling-up? Or is it mouse mode?

**Comment by amir20** [comment]
I am using my mouse/trackpad on my laptop.

**Comment by gpakosz** [comment]
I just compiled tmux `HEAD`, works for me. Can you give it a try?

**Comment by gpakosz** [comment]
Though I'm not sure what you mean by:
> Instead, it behaves as if the up arrow was pressed

I compiled tmux `HEAD`, used the most recent commit of the `master` branch of this configuration and hit `<prefix> + m` to enable mouse mode. Then when scrolling up with my trackpad, tmux entered copy mode and imho it scrolled as expected

**Comment by amir20** [comment]
Oh that's not what i mean. Shouldn't the scrolling work without entering mouse mode?

**Comment by amir20** [comment]
I recorded this https://asciinema.org/a/cwt5rzqmpfdjts04y7qysjg4t. I start tmux, cat something long and then try to scroll. I don't _think_ it used to behave that way. I might be wrong though.

**Comment by gpakosz** [comment]
Here, with tmux `2.3`, when I don't enable mouse mode scrolling does nothing

**Comment by gpakosz** [comment]
I can't reproduce your 'key up' behavior

**Comment by SikhNerd** [comment]
Do you have alternate mode scrolling enabled in your terminal?

iterm the advanced option is "Scroll wheel sends arrow keys when in alternate screen mode"
terminal.app the option is a checkbox "Scroll the alternate screen" under keyboard

**Comment by amir20** [comment]
> terminal.app the option is a checkbox "Scroll the alternate screen" under keyboard

That's what it was! Thanks! 

Is there anyway to enable mouse mode by default?

**Comment by gpakosz** [comment]
@SikhNerd I don't see the option in `iTerm2`

@amir20 add `tmux set -g mouse on`  at the end of your `~/.tmux.conf.local` copy

**Comment by SikhNerd** [comment]
<img width="1015" alt="screen shot 2017-04-20 at 12 07 54 pm" src="https://cloud.githubusercontent.com/assets/232652/25248159/1206a4ae-25c2-11e7-8c44-55a93428c2b3.png">

@gpakosz  ^

**Comment by gpakosz** [comment]
@SikhNerd > Right thanks. I was looking in profile options :)

So yeah it seems it's disabled by default.

@amir20 Do you consider it resolved?

**Comment by amir20** [comment]
Yes it does. Thanks @gpakosz. We can close. :)

**Comment by gpakosz** [comment]
👌
