### ISSUE TITLE
tpm not downloading additional plugins from `tmux.conf.local`

### ISSUE THREAD

**Issue by Clumsy-Coder** [gpakosz/.tmux#671]
TPM doesn't seem to download tmux plugins when their defined in `tmux.conf.local`

## commands run
```bash
rm -rf ~/.local/share/tmux ~/.config/tmux ~/.config/oh-my-tmux
git clone https://github.com/gpakosz/.tmux.git ~/.config/oh-my-tmux
mkdir -p ~/.config/tmux
ln -s ~/.config/oh-my-tmux/.tmux.conf ~/.config/tmux/tmux.conf
cp ~/dotfiles/tools/tmux/tmux.conf ~/.config/tmux/tmux.conf.local
tmux
```

---

## `~/.config/tmux/tmux.conf.local`
```tmux
source-file ~/dotifles/tools/tmux/plugins.tmux.conf
```

## `~/dotifles/tools/tmux/plugins.tmux.conf`
```tmux
set -g @plugin 'tmux-plugins/tmux-sensible'
```

---

## `ls -lah ~/.config/tmux`
```bashtotal 8
drwxr-xr-x   5 umar  staff   160B 12 Sep 09:11 .
drwxr-xr-x  22 umar  staff   704B 12 Sep 09:11 ..
drwxr-xr-x   4 umar  staff   128B 12 Sep 09:11 plugins
lrwxr-xr-x   1 umar  staff    41B 12 Sep 09:11 tmux.conf -> /Users/umar/.config/oh-my-tmux/.tmux.conf
-rw-r--r--   1 umar  staff    76B 12 Sep 09:11 tmux.conf.local
```

## `ls -lah ~/.config/tmux/plugins`
```bash
total 8
drwxr-xr-x   4 umar  staff   128B 11 Sep 10:30 .
drwxr-xr-x   6 umar  staff   192B 11 Sep 10:30 ..
drwxr-xr-x  18 umar  staff   576B 11 Sep 10:30 tpm
-rw-r--r--   1 umar  staff    70B 11 Sep 10:30 tpm_log.txt

```

---

Not sure what am I missing

**Comment by gpakosz** [comment]
Hello @Clumsy-Coder,

Oh my tmux! doesn't support sourcing yet another configuration file from the `.local` customization file.

**Comment by gpakosz** [comment]
> ```
> source-file [-Fnqv] path ...
>               (alias: source)
>         Execute commands from one or more files specified by path (which may be glob(7) patterns).  If -F is present, then path is expanded as a format.  If -q is given, no error will be returned if path
>         does not exist.  With -n, the file is parsed but no commands are executed.  -v shows the parsed commands and line numbers if possible.
>```

It's not trivial to support glob patterns in path, as well as the different options.

**Comment by atrestis** [comment]
Hello, I got the same issue, my plugins definition (for installation) is under user customizations section, however whenever I try to update/install new plugins I get the error of: "GitHub doesn't seem to be reachable, skipping installing and/or updating tpm and plugins...". 

My tmux.conf.local is a symbolic link to my dotfiles configuration, although I don't see how this would be a problem. 

Can anyone suggest any hints on how to resolve this? 
Cheers

**Comment by augustobmoura** [comment]
> Hello, I got the same issue, my plugins definition (for installation) is under user customizations section, however whenever I try to update/install new plugins I get the error of: "GitHub doesn't seem to be reachable, skipping installing and/or updating tpm and plugins...".
> 
> My tmux.conf.local is a symbolic link to my dotfiles configuration, although I don't see how this would be a problem.
> 
> Can anyone suggest any hints on how to resolve this? Cheers

This is definitely a problem, I have a similar setup, where `.tmux.conf.local` and tmux-fingers wasn't working at all. I fixed it by copying the file instead of linking it. A hard link would probably also make it work

**Comment by gpakosz** [comment]
> I fixed it by copying the file instead of linking it. A hard link would probably also make it work

This is unrelated to this issue.

Oh my tmux doesn't support having its `.local` customization file source more files.
As I mentioned in my initial comments, this is not trivial to solve.

**Comment by Clumsy-Coder** [comment]
@gpakosz I'm still following this issue.

**Comment by gpakosz** [comment]
@Clumsy-Coder Cool! Please tell me if the `gh-671` branch works for you 🙏

**Comment by Clumsy-Coder** [comment]
@gpakosz I tried the branch. It works. I tested with the following steps

0. Remove tmux folders
```bash
rm -rfv ~/.config/oh-my-tmux ~/.config/tmux
```

2. create directory
```bash
mkdir -p ~/.config/tmux
```
3. clone repo
```bash
git clone --branch gh-671 https://github.com/gpakosz/.tmux.git ~/.config/oh-my-tmux
```

4. symlink tmux config file
```bash
ln -sf ~/.config/oh-my-tmux/.tmux.conf ~/.config/tmux/tmux.conf
```

5. add the following in `~/.config/tmux/tmux.conf.local
```bash
echo "set -g @plugin 'jaclu/tmux-menus'" > ~/.config/tmux/tmux.conf.local
```
6. open tmux
```bash
tmux
```

7. run installed plugin. (tmux command `< prefix + \ >` )

NOTE: I tested it in a VM using [vagrant](https://www.vagrantup.com/) and virtualbox as the VM runner. I used [ubuntu-22.04](https://portal.cloud.hashicorp.com/vagrant/discover/ubuntu/jammy64) as the OS

**Comment by Clumsy-Coder** [comment]
@gpakosz I tried the branch. It works. I tested with the following steps

0. Remove tmux folders
```bash
rm -rfv ~/.config/oh-my-tmux ~/.config/tmux ~/dotfiles/tools/tmux/
```

2. create directory
```bash
mkdir -p ~/.config/tmux ~/dotfiles/tools/tmux/
```
3. clone repo
```bash
git clone --branch gh-671 https://github.com/gpakosz/.tmux.git ~/.config/oh-my-tmux
```

4. symlink oh-my-tmux config file
```bash
ln -sf ~/.config/oh-my-tmux/.tmux.conf ~/.config/tmux/tmux.conf
```

5. add the plugin in `~/dotfiles/tools/tmux/plugin.tmux.conf`. Using plugin [tmux-menus](https://github.com/jaclu/tmux-menus)
```bash
echo "set -g @plugin 'jaclu/tmux-menus'" > ~/dotfiles/tools/tmux/plugin.tmux.conf
```

6. source the `plugin.tmux.conf` in `~/.config/tmux/tmux.conf.local`
```bash
echo "source ~/dotfiles/tools/tmux/plugin.tmux.conf" > ~/.config/tmux/tmux.conf.local
```

6. open tmux
```bash
tmux
```

8. run installed plugin. tmux command `prefix + \`

NOTE: I tested it in a VM using [vagrant](https://www.vagrantup.com/) and virtualbox as the VM runner. I used [ubuntu-22.04](https://portal.cloud.hashicorp.com/vagrant/discover/ubuntu/jammy64) as the OS

**Comment by gpakosz** [comment]
@Clumsy-Coder Thank you for the test

I will have a look

**Comment by gpakosz** [comment]
I can't reproduce the fact that plugins get uninstalled

Are you sure you don't have other configuration files around?

**Comment by gpakosz** [comment]
In fact I can reproduce with vagrant

**Comment by gpakosz** [comment]
I believe it happens when exiting and the background job that installs tmux plugins hasn't finished yet

**Comment by gpakosz** [comment]
I think I was able to fix the discovery of the plugins that would sometimes return nothing, causing uninstallation

I pushed another commit to the branch

**Comment by Clumsy-Coder** [comment]
@gpakosz I tried it again with steps mentioned earlier. It works great!

**Comment by gpakosz** [comment]
I push more changes and reverted to my first idea of implementing it.

I can't rely on using the `after-set-option` hook as a configuration could use `set-hook -gu after-set-option` or `set-option -gu after-set-option`.

**Comment by Clumsy-Coder** [comment]
@gpakosz doesn't seem to work using the steps mentioned above. Doesn't even trigger the update or install when opening a tmux session

**Comment by gpakosz** [comment]
Hmm investigating more then

**Comment by gpakosz** [comment]
Ok I pushed more changes...

As I initially expected, this is hard to iron out all the edge cases 🙃

**Comment by Clumsy-Coder** [comment]
@gpakosz this one works as intended. Whats the edge case you're trying to fix?

**Comment by gpakosz** [comment]
There's a simple implementation that consists in spawning an ephemeral tmux client/server pair, set the `after-set-option` hook to accumulate all `set -g @plugin` commands into a variable, and source the `.local` customization file which in turn can source more files.

The problem is that if any of the configuration files uses `set-hook -gu after-set-option` or `set-option -gu after-set-option`, then plugins won't be discovered at all.

The current implementation doesn't use hook, and instead does more work outside of tmux in POSIX shell syntax.
