### ISSUE TITLE
Pasting pastes all previously copied text, not just the last copied text (Ubuntu Linux, X11, xclip)

### ISSUE THREAD

**Issue by kwsp** [gpakosz/.tmux#672]
When I paste (Ctrl-V or Ctrl-Shift-V), all previously text are pasted. For example, if I copy "A", I can paste "A", but if I copy "B" after, I can only paste "AB".

**Comment by gpakosz** [comment]
Hello @kwsp,

This sounds unrelated to Oh my tmux! itself.

Please double check you're not also facing this with a stock configuration, e.g. by launching `tmux` with
```
$ tmux -L test -f /dev/null
```

**Comment by kwsp** [comment]
Thanks for the tip. It's been a while and I currently cannot reproduce this issue. I'll reopen when it comes back and I'll have more information.
