### ISSUE TITLE
ssh centOS-7 use vim  E437: terminal capability "cm" required

### ISSUE THREAD

**Issue by NatureLR** [gpakosz/.tmux#675]
![image](https://github.com/gpakosz/.tmux/assets/30221928/4a6294ed-7063-4fc5-8951-0a0dfa472b20)

when  set `export TERM=screen-256color` in tmux    it's ok

ubuntu 22.04  it's ok

**Comment by gpakosz** [comment]
Hello @NatureLR 👋

You likely want to edit your `~/.ssh/config` file and use `SetEnv TERM=xterm-256color`,

E.g. for all hosts you're sshing into
```
Host *
  SetEnv TERM=xterm-256color
```

**Comment by NatureLR** [comment]
> Hello @NatureLR 👋
> 
> You likely want to edit your `~/.ssh/config` file and use `SetEnv TERM=xterm-256color`,
> 
> E.g. for all hosts you're sshing into
> 
> ```
> Host *
>   SetEnv TERM=xterm-256color
> ```

good thank u
