### ISSUE TITLE
Status bar problem on Android (termux)

### ISSUE THREAD

**Issue by lattice0** [gpakosz/.tmux#676]
I started using this yesterday on Termux and it worked fine. Used for hours. Today, when using again,  the status bar started flickering, and I get an error:

![Screenshot_20231009_125637_Termius](https://github.com/gpakosz/.tmux/assets/6632321/6471cd8c-aaf6-478e-b716-9aa20e14c324)

host is ubuntu 22.04 and I'm trying over SSH using Termius on Android. I also cannot divide into panes as it starts to flicker. I tried rebooting everything, on both sides.

Did I do something wrong? I installed with
```

$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

and did not modify the .tmux.conf.

**Comment by gpakosz** [comment]
Hello @lattice0 👋

Are you still having problems with termux?
