### ISSUE TITLE
Wttr.in weather reporting is not reliable

### ISSUE THREAD

**Issue by ciscohack** [gpakosz/.tmux#681]
Hello Expert,

is it possible to add some other weather provider alternative then wttr.in as it's not reliable failed many time and it's icon also looks bad... oh-my-tmux is such a great tool request to add some other weather provider and CPU usage detail on left side.

**Comment by gpakosz** [comment]
Hello @ciscohack 👋

The `#{weather}` custom variable is given as an example.

As of CPU usage, there's the `#{loadavg}` variable.

**Comment by ciscohack** [comment]
@gpakosz Thanks for the prompt response.  this variable #{loadavg} shows system load or user CPU load as if I check the OS monitoring tool info seems not in sync

**Comment by gpakosz** [comment]
Then you may want to try the `tmux-cpu` TPM plugin, see the `.local` customization file

**Comment by ciscohack** [comment]
Ok thanks let me check that
