### ISSUE TITLE
There will be one more question mark by default, and there will be duplicate content in subsequent entries.

### ISSUE THREAD

**Issue by DeepTiming** [gpakosz/.tmux#686]
![image](https://github.com/gpakosz/.tmux/assets/38682323/19c962cc-862e-4277-81e3-dc731cfb841c)

There will be one more question mark by default, and there will be duplicate content in subsequent entries.

If you don't use tmux, it's OK. I just used the recommended default configuration.

How to solve it？Thanks！

**Comment by gpakosz** [comment]
Hello @DeepTiming 👋

Please reach out to regular tmux support channels if it's not something specific to Oh my tmux!
That being said, double check the value of your `TERM` environment variable before and after launching tmux.
The tmux wiki has entries about `TERM`
