### ISSUE TITLE
catppuccin theme ignored

### ISSUE THREAD

**Issue by jeusdi** [gpakosz/.tmux#687]
I've just installed a clean oh my tmux from https://github.com/gpakosz/.tmux 
I've tried to install catppuccin tmux theme from https://github.com/catppuccin/tmux
I've added this line at the end of my .tmux.conf.local:
set -g @plugin 'catppuccin/tmux'
Necertheless, it seems it's ignored.
Any ideas?

**Comment by gpakosz** [comment]
Hello @jeusdi 👋

I just tried on macOS and it works for me, except I don't have the proper fonts installed.
But definitely the plugin has been picked up by TPM

**Comment by jeusdi** [comment]
Thanks @gpakosz . I've tried again using key bindings and it worked.
