### ISSUE TITLE
if I only need the theme?

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [gpakosz/.tmux#69]
hi, i think your tmux theme is wonderful, i have a tmux.conf too. how do i borrow your theme but not tmux behaviour ?

**Comment by gpakosz** [comment]
Well there's a to get back the colors.

Start using my configuration. And once tmux has launch do:
```
$ tmux show -g status-left
$ tmux show -g status-right
```

This will show you the colors you need to use.

**Comment by gpakosz** [comment]
Another way is to override settings at the end of your `~/.tmux.conf.local` copy. This would work for most settings and bindings

**Comment by gpakosz** [comment]
@FinallyFinancialFreedom Hello, did you manage to customize this configuration to your own desires in the end?
