### ISSUE TITLE
Feature: `hostname_local` to always show the local hostname even if SSH connected

### ISSUE THREAD

**Issue by ww7** [gpakosz/.tmux#691]
I'm using nested `Oh my tmux! ` and want to show `#{hostname_local}` on parent Tmux when SSH connected.

Please add such variable if you think anyone else would want it.

**Comment by gpakosz** [comment]
Hello @ww7 👋

There are tmux variables for this, see the tmux manual
```
     host                   #H       Hostname of local host
     host_short             #h       Hostname of local host (no domain name)
 ```
