### ISSUE TITLE
Battery status in WezTerm w/ Fira Code Nerd Font

### ISSUE THREAD

**Issue by davidfmatheson** [gpakosz/.tmux#692]
The battery status in the lower-right is grey:
<img width="228" alt="image" src="https://github.com/gpakosz/.tmux/assets/2395513/5b16d08b-ac65-409a-b9ff-0a9d21e5f689">

Everything else in the status bar has color. When I open `tmux.conf` and search for `tmux_conf_battery` then the colors load.

I am on Mac OS X 12.7.1, and this seems to work fine on iTerm2. It's only WezTerm.

**Comment by gpakosz** [comment]
Hello @davidfmatheson 👋

If it's only WezTerm, then try to use different values for `tmux_conf_battery_bar_symbol_full` and `tmux_conf_battery_bar_symbol_empty` in your `.local` customization file.

**Comment by gpakosz** [comment]
Hmm I just tried WezTerm, and it seems to work for me

<img width="191" alt="image" src="https://github.com/gpakosz/.tmux/assets/553208/a1b7a101-2cb3-47b2-b468-56cb4472f203">

**Comment by gpakosz** [comment]
Oh wait sometimes it doesn't work

<img width="128" alt="image" src="https://github.com/gpakosz/.tmux/assets/553208/7294340a-3178-47cb-9302-b13c275a5c32">

**Comment by gpakosz** [comment]
It's definitely a WezTerm.

Here,
- Open WezTerm ← battery symbols are whit
- Use `<prefix> + e` to edit the `.local` customization file ← battery symbols are colored upon using vim
- Battery symbols remained colored until I quit WezTerm

**Comment by gpakosz** [comment]
It seems that forcing the value of `default-terminal` in your `.local` customization file will work around the WezTerm bug

```
set -g default-terminal "screen-256color" #!important
```

**Comment by gpakosz** [comment]
Well not always... I have no idea, please see with WezTerm authors

**Comment by davidfmatheson** [comment]
Yeah, the work around didn't work for me, either. Turns out it works in WezTerm nightly (20231203-124028-e3cd2e93), guess I should've tried that first. Thanks for checking @gpakosz!
