### ISSUE TITLE
Find a replacement for urlview (unmaintained)?

### ISSUE THREAD

**Issue by maxbrunet** [gpakosz/.tmux#695]
It seems `urlview` is no longer maintained[^orphan]. Packaging systems will start dropping it (e.g. NixOS/nixpkgs#274280) as issues will accumulate with no hope for them of being fixed upstream.

Some alternatives:

- [firecat53/urlscan](https://github.com/firecat53/urlscan)
- [m3m0ryh0l3/extracturl](https://github.com/m3m0ryh0l3/extracturl) (does not appear actively maintained either)
- [patrick-kidger/exvoker](https://github.com/patrick-kidger/exvoker)
- ...?

I have only tried `urlscan` so far, and it looks like a good drop-in replacement.

[^orphan]: https://salsa.debian.org/debian/urlview/-/commit/4ad7d236c745b665db1d2fd07ce5ffc1748e4240

**Comment by gpakosz** [comment]
Hello @maxbrunet 👋,

Maybe the binding should be dropped entirely

**Comment by maxbrunet** [comment]
Hello @gpakosz 👋

It is true that I don't use it so much, so I likely would not miss it. I only use it every once in while to find a new PR link for a branch pushed recently

I suppose one could configure a binding in the local config or use a plugin if they would like the feature back

**Comment by gpakosz** [comment]
Maybe if there's an Homebrew formula for `urlscan` I might keep it

**Comment by maxbrunet** [comment]
A few Linux distros have a package for it: https://repology.org/project/urlscan/versions

But I cannot find it in Homebrew. On macOS, it would be Nix, MacPort, or `pipx`

**Comment by gpakosz** [comment]
Can you please try the `gh-695` branch?

**Comment by maxbrunet** [comment]
Thank you, I tested it and this technically looks good to me, however now that I see `urlscan` in action with the config, I am not convinced by the default experience, the output is very verbose and feels barely more useful than scrolling up the shell output in my opinion (pressing `c` helps to get a compact view, but the `/` binding closes it instead of searching) (it also matches my `username@machine` prompt as an email address)

One might want to use the `--compact`, `--dedupe`, and `--regex 'https?://.+'` flags, but not sure if everyone would agree if the config hardcodes them. I wonder if adding an option to choose the command would be possible with the default still being `urlview` (that would make experimentation easy at least)

And if that's adding too much complexity, dropping the feature is still on the table imo (personally I do not depend on it heavily in my day to day)

**Comment by gpakosz** [comment]
Updated the `gh-695` branch with the options you suggest

**Comment by maxbrunet** [comment]
Thank you for the update, it works and looks very close to what we have with `urlview`.

`--dedupe` is inefficient for me, because my right prompt contains a timestamp and that makes each URL "unique", that would probably be an issue to discuss upstream

If you decide to ship this change, I would update the README to mention `urlscan` as well:
 
https://github.com/gpakosz/.tmux/blob/5354501a5bff69457b37132c1959e9063b1c1714/README.md#L134

Thanks a lot for your time and responsiveness! :heart:

**Comment by gpakosz** [comment]
> I think I would be ok if a my prompt appears once in the result 😅

What prompt are we talking about?

**Comment by maxbrunet** [comment]
`$PROMPT`, `urlscan` tries to be smart and guesses `user@host` in the prompt as an email address even though it is not a `mailto:` URL

**Comment by gpakosz** [comment]
But `--regex 'https?://.+\.\w'` solves this right?

**Comment by maxbrunet** [comment]
No, unfortunately this regex is too simplistic and does not match all possible URLs (e.g. `http://localhost:3000`, and I tried to remove `\.` or change `\.\w`, but it gets truly complex to have an accurate regex)

This is the default in `urlview`:

```regex
(((http|https|ftp|gopher)|mailto):(//)?[ˆ <>"\t]*|(www|ftp)[0-9]?\.[-a-z0-9.]+)[ˆ .,;\t\n\r<">\):]?[ˆ, <>"\t]*[ˆ .,;\t\n\r<">\):]
```

And this is `urlscan`: [firecat53/urlscan@`1.0.1`/urlscan/urlscan.py#L248-L273](https://github.com/firecat53/urlscan/blob/1.0.1/urlscan/urlscan.py#L248-L273)

I think it is simpler to do without `--regex` and use `urlscan --compact --dedupe` only

**Comment by gpakosz** [comment]
Or I removed the use of `--regex`

**Comment by maxbrunet** [comment]
> Or I removed the use of `--regex`

Yes, that's what I suggest :)

**Comment by gpakosz** [comment]
I meant "ok I removed ..." 😅 Damn autocarrot! 🥕
