### ISSUE TITLE
invalid environment variable

### ISSUE THREAD

**Issue by Evollt** [gpakosz/.tmux#697]
/Users/evollt/.tmux.conf:1117: invalid environment variable
'"$TMUX_PROGRAM" ${TMUX_SOCKET:+-S "$TMUX_SOCKET"} source "$TMUX_CONF"' returned 1

When i reload configuration.

I changed this string:
`tmux_conf_theme_status_left=${tmux_conf_theme_status_left-' ❐ #S | ↑#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '}`

**Comment by gpakosz** [comment]
Hello @Evollt,

- What OS are you using?
- What's the tmux version?
- Can you please make sure you're using the most recent commit of this repository
- Can you please make sure you didn't modify the `.conf` file?

**Comment by gpakosz** [comment]
Hello @sethraymond,

I suggest you start the setup over, make sure you remove all config files, kill all tmux processes.
Then try to add TPM plugins 1 by 1.
