### ISSUE TITLE
Fail to install plugin

### ISSUE THREAD

**Issue by owenstake** [gpakosz/.tmux#699]
`<prefix> + I` do not install my plugin with `set -g @plugin xxx`

**Comment by vargn** [comment]
What a coincidence, I came here for the same reason. I am a bit confused, the usage instructions says

use the `set -g @plugin ...` syntax to enable a plugin

But then it also says

⚠️ do not add `set -g @plugin 'tmux-plugins/tpm'` to any configuration file

What's the `...`, if not `'tmux-plugins/tpm'`?

**Comment by gpakosz** [comment]
Hello @owenstake,

I'm not sure what you're doing.
Edit your `.local` customization file with `<prefix> + e` and see there on how to enable plugins.
If you don't edit your `.local` customization file with `<prefix> + e`, then you need to reload the tmux configuration with `<prefix> + r`.
