### ISSUE TITLE
Mouse mode throws error: 'cut -c3- ~/.tmux.conf | sh -s _toggle_mouse' returned 127

### ISSUE THREAD

**Issue by vpassapera** [gpakosz/.tmux#70]
Tmux Version: tmux/yakkety,now 2.2-3 amd64 [installed]
.tmux version: master (latest)
zsh version: zsh/yakkety,now 5.2-5ubuntu1 amd64 [installed]

**Comment by gpakosz** [comment]
I don't have a yakkety Ubuntu box at hand, can you please launch
```
cut -c3- ~/.tmux.conf | sh -sx _toggle_mouse
```

and paste the output?

**Comment by gpakosz** [comment]
Alright, I installed a vagrant box and it works for me
```
$ vagrant init ubuntu/yakkety64; vagrant up --provider virtualbox
$ vagrant ssh
```

Inside vagrant I installed `zsh` with package maintainer recommended configuraiton and checked versions with `apt list --installed`:
```
tmux/yakkety,now 2.2-3 amd64 [installed]
zsh/yakkety,now 5.2-5ubuntu1 amd64 [installed]
```

Mouse mode toggling triggered with key bindings or manually through command line works for me:
```
ubuntu@ubuntu-yakkety ~ % cut -c3- ~/.tmux.conf | sh -s _toggle_mouse
ubuntu@ubuntu-yakkety ~ % echo $?
0
ubuntu@ubuntu-yakkety ~ %
```

**Comment by vpassapera** [comment]
```
[12:28:47 AM] [vpassapera@workstation] ~  →  cut -c3- ~/.tmux.conf | sh -sx _toggle_mouse
+ cat
+ set -e
+ __newline=

+ _toggle_mouse
+ + tmux show -g -w
grep -q mode-mouse
+ tmux show -g
+ grep mouse
+ head -n 1
+ cut -d  -f2
+ old=off
+ new=
+ [ off = on ]
+ new=on
+ tmux set -g mouse on ; display mouse: on
+ et -g @shell_mode vi
sh: 1042: et: not found
[12:29:01 AM] [vpassapera@workstation] ~  →  cut -c3- ~/.tmux.conf | sh -sx _toggle_mouse
+ cat
+ set -e
+ __newline=

+ _toggle_mouse
+ + greptmux show -g -w
 -q mode-mouse
+ tmux show -g
+ grep mouse+ 
head -n 1
+ cut -d  -f2
+ old=on
+ new=
+ [ on = on ]
+ new=off
+ tmux set -g mouse off ; display mouse: off
+ et -g @shell_mode vi
sh: 1042: et: not found
```

**Comment by vpassapera** [comment]
I do also have oh-my-zsh installed, but no tmux plugins enabled on oh-my-zsh. I've also disabled the extra tmux plugins i had installed to tmux.conf and killed the server.

**Comment by gpakosz** [comment]
The output should be
```
ubuntu@ubuntu-yakkety:~$ cut -c3- ~/.tmux.conf |sh -sx _toggle_mouse
+ cat
+ set -e
+ __newline=

+ _toggle_mouse
+ tmux show -g -w
+ grep -q mode-mouse
+ tmux show -g
+ cut -d  -f2
+ head -n 1
+ grep mouse
+ old=on
+ new=
+ [ on = on ]
+ new=off
+ tmux set -g mouse off ; display mouse: off
```

And in your output there's
```
et -g @shell_mode vi
```

Are you sure you didn't alter `.tmux.conf` ?

**Comment by vpassapera** [comment]
You're right, I noticed in my ansible manifest that there was a line edit to it that I had missed.

Thanks!

**Comment by gpakosz** [comment]
I edited my comment above

**Comment by gpakosz** [comment]
See https://github.com/gpakosz/.tmux/issues/11#issuecomment-166112867 for an explanation of how `.tmux.conf` is both a valid configuration file and a valid shell script.

**Comment by vpassapera** [comment]
Thanks! And yeah, I didn't realize it was a polyglot. Thanks for this clarification.

**Comment by Esprim0** [comment]
If it try the mouse binding it shows me the 127 error.

If i run the command i get following output.
```
cut -c3- ~/.tmux.conf | sh -s _toggle_mouse

Output:
sh: 1644: t-option: not found
```

How can i fix this?

**Comment by gpakosz** [comment]
@Esprim0 Did you change `.tmux.conf`?

**Comment by Esprim0** [comment]
> @Esprim0 Did you change `.tmux.conf`?

Yes. I added following lines:
`echo set-option -g default-command "/usr/bin/zsh" >> ~/.tmux.conf
echo set-option -g default-shell "/usr/bin/zsh" >> ~/.tmux.conf`
