### ISSUE TITLE
How to copy text without exiting copy mode

### ISSUE THREAD

**Issue by owenstake** [gpakosz/.tmux#704]
[tmux - Copy text without exiting copy mode - Super User](https://superuser.com/questions/928779/copy-text-without-exiting-copy-mode )

Is there a advanced solution in oh-my-tmux?

**Comment by gpakosz** [comment]
Hello @owenstake 👋

You can edit your `.local` customization file and use non cancelling bindings.

For a list of default tmux bindings, you can use
```
$ tmux -f /dev/null -L test lsk | grep and-cancel
```

For Oh my tmux! specifically, you can use
```
bind -T copy-mode-vi y send -X copy-selection
```

Keep in mind that Oh my tmux! updates bindings on the fly depending on the value of `tmux_conf_copy_to_os_clipboard`
