### ISSUE TITLE
Auto update for update OMT configuration

### ISSUE THREAD

**Issue by itokun99** [gpakosz/.tmux#707]
"Hi, I'm new to the CLI world and I've been using this configuration, which I absolutely love. It's an amazing configuration compared to the default setup. However, I've encountered an issue with the auto-update feature (similar to [nvchad](https://nvchad.com/docs/quickstart/install#update)), and I couldn't find information about it in the README. Perhaps adding this feature could benefit users who appreciate this configuration but might not be as advanced in utilizing it 😊. Thank you!"

**Comment by gpakosz** [comment]
Hello @itokun99 

> However, I've encountered an issue with the auto-update feature

Which issue?

**Comment by gpakosz** [comment]
@itokun99 ?
