### ISSUE TITLE
Adding weather and mail segments

### ISSUE THREAD

**Issue by stanleykylee** [gpakosz/.tmux#71]
Hi,

New to using and customizing tmux and I came across this. Everything looks great and I'm starting to understand a bit of what is happening. I wanted to do something similar to #38. Essentially I just want a mail and weather indicator, which seems possible with the default tmux [quick guide](http://powerline.readthedocs.io/en/master/configuration.html#quick-guide). However I'm a bit lost and not sure where to begin with this?

Any pointers would help, thanks!

**Comment by gpakosz** [comment]
Hello @stanleykylee,

This configuration, while providing a "Powerline look" has nothing to do with Powerline per se. The only thing this configuration borrows from Powerline is the patched font, that's it.

As such, the guide you mention has nothing to do with customizing this configuration which currently doesn't support weather and mail "segments". I would also like to mention that I have no plan to add these:
  - there is no well defined solution that would suit most of people's needs
  - "mail" is loosely defined: what does it mean? Gmail, Yahoo, ... mail count? Outlook mail count? `~/.maildir`, ...

Finally, as far as #38 goes, if you have some utility installed on your OS that gives you the current weather, you can e.g. edit your `~/.tmux.conf.local` copy and add `#(/path/to/weather)` to either `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right` variables.

**Comment by AXington** [comment]
@gpakosz I've tried the method you listed here to add slack notifications to my right status bar. It's not displaying anything currently. Just shows nothing on the bar at all. I added it between the prefix and the battery info. Any thoughts on what I might be doing wrong... also, how often will the bar update/reload as is, currently.

**Comment by gpakosz** [comment]
@AXington can you please open a dedicated issue?

**Comment by vakaobr** [comment]
I'm using the following script to show the weather on my right indicator: 
`#!/bin/bash
#
# Weather
# =======
#
# By Jezen Thomas <jezen@jezenthomas.com>
#
# This script sends a couple of requests over the network to retrieve
# approximate location data, and the current weather for that location. This is
# useful if for example you want to display the current weather in your tmux
# status bar.

# There are three things you will need to do before using this script.
#
# 1. Install jq with your package manager of choice (homebrew, apt-get, etc.)
# 2. Sign up for a free account with OpenWeatherMap to grab your API key
# 3. Add your OpenWeatherMap API key where it says API_KEY

# OPENWEATHERMAP API KEY (place yours here)
API_KEY=506add2ec2c20064e450ba66598d944d

set -e

# Not all icons for weather symbols have been added yet. If the weather
# category is not matched in this case statement, the command output will
# include the category ID. You can add the appropriate emoji as you go along.
#
# Weather data reference: http://openweathermap.org/weather-conditions
weather_icon() {
  case $1 in
    500) echo 🌦
      ;;
    520) echo 🌦
      ;;
    800) echo ☀️
      ;;
    801) echo 🌤
      ;;
    803) echo ⛅️
      ;;
    804) echo ☁️
      ;;
    *) echo "$1"
  esac
}

LOCATION=$(curl --silent http://ip-api.com/csv)
CITY=$(echo "$LOCATION" | cut -d , -f 6)
LAT=$(echo "$LOCATION" | cut -d , -f 8)
LON=$(echo "$LOCATION" | cut -d , -f 9)

WEATHER=$(curl --silent http://api.openweathermap.org/data/2.5/weather\?lat="$LAT"\&lon="$LON"\&APPID="$API_KEY"\&units=metric)

CATEGORY=$(echo "$WEATHER" | jq .weather[0].id)
TEMP="$(echo "$WEATHER" | jq .main.temp | cut -d . -f 1)°C"
WIND_SPEED="$(echo "$WEATHER" | jq .wind.speed | awk '{print int($1+0.5)}')ms"
ICON=$(weather_icon "$CATEGORY")

printf "%s" "$CITY:$ICON $TEMP $WIND_SPEED"
`
