### ISSUE TITLE
Why is the status bar always a little further from the bottom?

### ISSUE THREAD

**Issue by CrazyCatZhang** [gpakosz/.tmux#711]
<img width="1792" alt="Snipaste_2024-01-21_01-07-56" src="https://github.com/gpakosz/.tmux/assets/67346540/0a4607cd-6d4c-466d-a9d4-3e21f7b6a72f">

**Comment by gpakosz** [comment]
Hello @CrazyCatZhang 👋

It's all about the terminal emulator you're using, the size of the window and the size of the font

**Comment by CrazyCatZhang** [comment]
thanks, I tried adjusting the font size, and the current one should be the most suitable. a little gap is not a big deal.
