### ISSUE TITLE
Styling breaks since 7e00233

### ISSUE THREAD

**Issue by Frederick888** [gpakosz/.tmux#712]
### Environment

System: macOS
Terminal: Kitty 0.32.0 (`$TERM`: `xterm-kitty`)
Tmux: 3.3a
Awk: GNU Awk 5.3.0
`sh --version`: GNU bash, version 5.2.26(1)-release (x86_64-apple-darwin23.2.0)

### `.tmux.conf.local`

Only overrode the separators. I made sure this was the only change after the default `.tmux.conf.local` changed too.

```tmux
tmux_conf_theme_left_separator_main='\uE0B0'  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub='\uE0B1'   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='\uE0B2' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub='\uE0B3'  #   PowerlineSymbols.otf font, see README.md
```

### Symptom

When using 1469d46:

<img width="254" alt="Screenshot 2024-01-22 at 11 03 59 am" src="https://github.com/gpakosz/.tmux/assets/4507647/821eea4d-6d90-41c0-9cd2-9ccc9b0e815b">

When using 7e00233:

<img width="235" alt="Screenshot 2024-01-22 at 11 03 19 am" src="https://github.com/gpakosz/.tmux/assets/4507647/62c85822-259b-4108-b2a8-8e78c4a054fa">

**Comment by mayersj1** [comment]
I can verify the same here. Anything after 7e00233 results in the plain status bar shown in the screenshot above.  Reverting back to 7e00233 allows the proper theme configuration to be applied.

NixOS 23.11
tmux 3.3a

**Comment by gpakosz** [comment]
Hello @Frederick888 and @mayersj1,

Can you please try reloading the configuration with `<prefix> + r`?

**Comment by gpakosz** [comment]
I tried on both macOS Ventura `13.4` and Sonoma `14.2.1` along with tmux `3.3a` and I don't reproduce the issue, which may be caused by not reloading the configuration

**Comment by Frederick888** [comment]
@gpakosz I'm afraid the issue persists after reloading. Just tested under Arch too and it had the same issue.

**Comment by Frederick888** [comment]
I realised that this only happens with GNU sed. macOS (and BSD?) sed works fine. (GNU sed is my default sed under macOS too.)

**Comment by gpakosz** [comment]
@Frederick888 Ah thanks for mentioning GNU sed, that gives me a way to investigate.

I won't be able to fix that in the next couple of hours though. Stay tuned...

**Comment by gpakosz** [comment]
Can you please the `gh-712` branch?

**Comment by Frederick888** [comment]
@gpakosz Yup it works :) Thank you

**Comment by mayersj1** [comment]
Verified fixed with latest pull.  Thanks for the quick turnaround!
