### ISSUE TITLE
Mouse selection on tmux not being copied over to os clipboard on fedora wayland

### ISSUE THREAD

**Issue by smetroid** [gpakosz/.tmux#714]
I came here to see if anyone else was having issues with mouse selection and copying the selected text to the OS clipboard on Fedora Wayland.  It turns out that I had to add the following line to my `.tmux.conf.local` file to get it working.

```
set -s copy-command 'wl-copy'
```

Credit goes to the person below.

https://www.guyrutenberg.com/2021/07/02/tmux-wayland-clipboard-integration/

**Comment by smetroid** [comment]
Closing this ticket, leaving this comment here for reference, hopefully it helps someone else.

**Comment by gpakosz** [comment]
Hello @smetroid,

I believe this issue is actually a dupe of #666.

Could you please try the `gh-666` branch and undo your `set -s copy-command 'wl-copy'` modification please?

**Comment by gpakosz** [comment]
I merged #666, can you please try the most recent `master` branch while undoing your `set -s copy-command 'wl-copy'` modification please?

**Comment by smetroid** [comment]
@gpakosz I commented out my update (change above) and updated my local `.tmux` repo with the latest code from master.  I can confirm that the latest master updates have fixed the mouse selection to OS clipboard on Fedora 39 Wayland ... no need for the change mentioned above.

Thank you for your work and this repo

**Comment by gpakosz** [comment]
Thanks @smetroid for the confirmation, much appreciated

**Comment by lzy37ld** [comment]
Sry, I am new to the tmux here and very much liked its convenience.

I tried to **pull the latest repo** and enable my mouse mode, I could select the text but could not copy it in the tmux(I know prefix + p could do it, but it's not convenient.) or my Mac clipboard. What should I do here?

**Comment by gpakosz** [comment]
Hello @lzy37ld,

Please open a separate issue and detail your OS, tmux version, terminal emulator and what you're trying to achieve and how.

Thank you
