### ISSUE TITLE
Consider renaming `.tmux.conf.local` to `.tmux.config.local.example`

### ISSUE THREAD

**Issue by ncihnegn** [gpakosz/.tmux#715]
I use `.tmux` as a git submodule in `~/.config/tmux`.
So my changes to `.tmux.conf.local` will have conflicts when I pull from your repo.

**Comment by gpakosz** [comment]
Hello @ncihnegn,

I don't believe it's an issue.

In my repository the file is named `.tmux.conf.local` while it should be name `~/.config/tmux/tmux.conf.local` without a leading dot when loaded from `$XDG_CONFIG_HOME`

**Comment by ncihnegn** [comment]
Ah, the naming can be confusing.

But it is still a problem. Adding `~/.config/tmux/tmux.conf` and `~/.config/tmux/tmux.conf.local` are still modifications to the `~/.config/tmux/` submodule.

I don't understand why we need to make a link for `tmux.conf`. We should be able to use it as is.

It will be nice to use a layout like `~/.tmux/tmux.conf` plus `~/.tmux.conf.local`. The vanilla configuration and the user customization should be in different directories so that they can be tracked separately.

**Comment by gpakosz** [comment]
> The vanilla configuration and the user customization should be in different directories so that they can be tracked separately

Sure.
So you can have:
```
~
├── .config (your own git repository)
│   ├ .tmux (this repository as a submodule)
│   │ ├ .tmux.conf (upstream)
│   │ └ .tmux.conf.local (upstream)
│   └ tmux
│     ├ tmux.conf -> ../.tmux/.tmux.conf (symlink)
│     └ tmux.conf.local (your own copy with your own customizations)
├── ...
└── ...
```

**Comment by ncihnegn** [comment]
Yes, that's what I am doing. But the unnecessary link is bugging me.

**Comment by gpakosz** [comment]
> the unnecessary link is bugging me

The following won't work:
```
~
├── .config (your own git repository)
│   └ tmux (this repository as a submodule)
│     ├ .tmux.conf
│     └ .tmux.conf.local.example
├── ...
└── ...
```

Renaming `.tmux.conf.local` to `.tmux.conf.local.example` won't help with tmux looking for a file named `~/.config/tmux/tmux.conf` and not `~/.config/tmux/.tmux.conf`
