### ISSUE TITLE
color problem with tmux git version

### ISSUE THREAD

**Issue by colinhd8** [gpakosz/.tmux#72]
I cloned tmux from github then install and run it, i found that there is no color on the foot bar.
like this:
![tmux](https://cloud.githubusercontent.com/assets/5259758/25832080/ed1d8f94-349a-11e7-90f8-3ed9a7d81354.PNG)

Does it mean it's not support git version of tmux?
OS: 4.8.15-300.fc25.x86_64
.tmux: latest from git

**Comment by jtr109** [comment]
Have you ever install and configure the [powerline](https://github.com/powerline/powerline)?
[Read the configuration of this repositry](https://github.com/gpakosz/.tmux#configuration) may help.
The configuration of fonts is also important. You can also find the way in the link above. By the way, it is a good idea to install the specified font via otf file by [this repository](https://github.com/supermarin/powerline-fonts).

FYI.

**Comment by colinhd8** [comment]
Yes, i have installed and configure the powerline. The fonts also be installed.
If i use the tmux which was installed by dnf command, everything is ok.

**Comment by jtr109** [comment]
What about using `xterm-256color`. See [it](https://github.com/gpakosz/.tmux#installation).

> outside of tmux, `$TERM` must be set to `xterm-256color`.

Hope it helps you.

**Comment by colinhd8** [comment]
Yes, it's already xterm-256color.
I'm using xshell, and set the terminal type by Properties->Terminal->Terminal Type.
After login by ssh, i confirm the term type by echo $TERM, and it shows xterm-256color.

**Comment by gpakosz** [comment]
Do you have colors when not using this configuration?

Make sure you kill all `tmux` processes then try
```
$ tmux -f /dev/null
$ tmux set -g status-right '#[fg=#e4e4e4,bg=#d70000,none]TEST'
```

You should see the word `TEST` written in white on a red background.

**Comment by colinhd8** [comment]
found the problem.
'tmux_conf_theme_24b_colour=true' was the reason. 
but for tmux 2.2, it's ok.

**Comment by gpakosz** [comment]
`tmux_conf_theme_24b_colour=true` works for me, running macOS Sierra
![image](https://cloud.githubusercontent.com/assets/553208/25848109/28fbb8f6-34b9-11e7-87e6-f2d0b040c0fa.png)

**Comment by colinhd8** [comment]
@gpakosz can you share the script (24-bit-color.sh)?
By the way, is this 
powerline
![powerline](https://cloud.githubusercontent.com/assets/5259758/25857095/962e96ea-350a-11e7-8a18-de249de5b542.PNG)
? how to config it?

**Comment by gpakosz** [comment]
Here is `24-bit-color.sh`: https://gist.github.com/gpakosz/4f5a87739c9ef45bce2f8be870450c1d

Here is an article describing how I configure my prompt: http://pempek.net/articles/2013/10/27/pretty-elided-shell-prompt/ (sorry for the poor SSL certificate, I'm about to switch to let's encrypt)

**Comment by colinhd8** [comment]
@gpakosz Thank you so much. I'll try it.

**Comment by gpakosz** [comment]
Any news?

**Comment by colinhd8** [comment]
Seems that my terminal can't display 24bit color correctly(by run the script of 24-bit-color.sh). So i set tmux_conf_theme_24b_colour=false to resolve this problem.

Thanks.
