### ISSUE TITLE
tmux 3.4-1 prints weird characters on every startup

### ISSUE THREAD

**Issue by module0x90** [gpakosz/.tmux#720]
Hi,

just to let you know, I am on Arch Linux and with the recent upgrade of tmux (3.3_a-7 -> 3.4-1) every time I start a terminal (urxvt) with tmux I get this:

^[]10;rgb:e5e5/e5e5/e5e5^[^[]11;rgb:0000/0000/0000^[

.. and then the actual terminal prompt
In my setup - but I have a rather elaborate setup with a .zlogin script as well as some tmux plugins, it appears it somehow issues an "Esc" key stroke twice, as it prefixes the garbage output with "sudo". My zsh has Esc-Esc mapped to prefix the current command with "sudo".

Just a heads up. I have downgraded tmux for now and I might look into this issue in a little while.

This might have probably to do with (tmux changelog) 

* Query the client terminal for foreground and background colours and if OSC 10
  or 11 is received but no colour has been set inside tmux, return the colour
  from the first attached client.

as there was a similar issue (same output)

https://github.com/TaDaa/vimade/issues/23

logged for vim (but quite a while back).
Also please see https://www.reddit.com/r/vim/comments/cnyrva/first_line_occasionally_has_weird_characters_and/, where TaDaaAhah (https://www.reddit.com/user/TaDaaAhah) wrote:

"For the weird text it looks like ansii query for terminal colors ."

Cheers

Tom

**Comment by gpakosz** [comment]
Hello Tom,

First thin you can try is to launch tmux with a stock configuration:
```
$ tmux -f /dev/null -L test
```

**Comment by module0x90** [comment]
It happens also with as stock config.
The default-terminal line doesn't fix it.

This happens with urxvt, even xterm but not with sakura.

Feel free to close this, as I would say it comes down to tmux and the terminal someone is using.
Nothing to do with your config. ;-)

**Comment by module0x90** [comment]
WONTFIX
