### ISSUE TITLE
Question: How to enable "copy-selection-no-clear" option?

### ISSUE THREAD

**Issue by waldauf** [gpakosz/.tmux#721]
Hello,

first, thank You for Your great config which I've been using for years. 

I would like to have the possibility to copy the text in copy-mode (via keyboard or mouse) and after copying to register/clipboard I stay in copy-mode. I found out there is an option for that called `copy-selection-no-clear`. But I am not sure how to use it with Your config.

Is it possible to set this behaving in Your config?
- "y" to copy text to TMUX's register.
- "Enter" to copy text to system clipboard

**Comment by gpakosz** [comment]
Tmux has evolved a lot and according to https://github.com/tmux/tmux/wiki/Clipboard it depends on many factors whether it's going to copy to the OS clipoard.

**Comment by waldauf** [comment]
Hi @gpakosz !
Thank You for Your help. I dived more deeply into it and played with the setting and found this magic configuration which enables me:

- Stay in copy-mode after copy text, including mouse text marking.
- `y` copies to Tmux register.
- `Enter` copies to the system clipboard. 

Configuration part in `.local`:
```
tmux_conf_copy_to_os_clipboard=true
~
###
# Prevent TMUX to leave copy-mode after copying selected text
###
# https://www.fosslinux.com/105809/tmux-copy-paste-mode-tips-and-tricks-for-productivity.htm#block-4
set-option -g default-command "reattach-to-user-namespace -l zsh"

# https://www.reddit.com/r/tmux/comments/v73005/how_to_prevent_tmux_from_exiting_copy_mode_after/
# https://unix.stackexchange.com/questions/639288/retain-selection-highlight-after-copying-text-to-clipboard-in-tmux
bind -T copy-mode-vi y send -X copy-selection-no-clear
bind-key -Tcopy-mode-vi Enter send -X copy-selection-no-clear
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear
```

**Comment by waldauf** [comment]
Hi @gpakosz !
Thank You for Your help. I dived more deeply into it and played with the setting and found this magic configuration which enables me:

- Stay in copy-mode after copy text, including mouse text marking.
- `y` copies to Tmux register.
- `Enter` copies to the system clipboard. 

Configuration part in `.local`:
```
tmux_conf_copy_to_os_clipboard=true
~
###
# Prevent TMUX to leave copy-mode after copying selected text
###
# https://www.fosslinux.com/105809/tmux-copy-paste-mode-tips-and-tricks-for-productivity.htm#block-4
set-option -g default-command "reattach-to-user-namespace -l zsh"

# https://www.reddit.com/r/tmux/comments/v73005/how_to_prevent_tmux_from_exiting_copy_mode_after/
# https://unix.stackexchange.com/questions/639288/retain-selection-highlight-after-copying-text-to-clipboard-in-tmux
bind -T copy-mode-vi y send -X copy-selection-no-clear
bind-key -Tcopy-mode-vi Enter send -X copy-selection-no-clear
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear
```

**Comment by gpakosz** [comment]
You don't need `reattach-to-user-namespace` as of tmux `2.6`
