### ISSUE TITLE
conflict with vim < C-b >?

### ISSUE THREAD

**Issue by twmht** [gpakosz/.tmux#722]
I found out I need to enter < C-b > in vim twice in order to move back the page, any idea?

**Comment by gpakosz** [comment]
Hello @twmht 👋

Yes this is standard tmux behavior: `CTRL` + `b` is tmux's default prefix and using it twice sends the key combination to the process in the current pane.

**Comment by gpakosz** [comment]
You can stop using `CTRL` + `b` as a prefix, which I do,

See your `.local` customization file

```
# replace C-b by C-a instead of using both prefixes
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix
```

**Comment by twmht** [comment]
@gpakosz 
Appeciate!
Because you have taken into account the scenario where the editor is vim, it led me to believe that you have already considered this. May I ask if there would be any changes if the editor is vim?

**Comment by gpakosz** [comment]
On a general basis, it seems that users of Oh my tmux! don't want tmux stock bindings to be removed so I guess there's pretty much nothing to do except unbinding `CTRL` + `b` in tmux or use other bindings in Vim
