### ISSUE TITLE
 copy mode is trippin with mouse

### ISSUE THREAD

**Issue by mauer9** [gpakosz/.tmux#723]
i'm on fedora+wayland+gnome

I downloaded tmux and oh-my-tmux, installed catpuccin.
tmux crashes in copy mode with mouse:

https://github.com/gpakosz/.tmux/assets/75573495/dc9c375a-bf64-4e55-a766-68773ba8b232

**Comment by gpakosz** [comment]
Hello @mauer9 

Can you reproduce without Oh my tmux!?

**Comment by mauer9** [comment]
https://github.com/gpakosz/.tmux/assets/75573495/f2d9b37f-4ce0-4949-be1c-10effa1f865b

**Comment by mauer9** [comment]
I think tmux can't send keys:


https://github.com/gpakosz/.tmux/assets/75573495/aabed35f-6820-491b-aa91-3108ad5858a7

**Comment by gpakosz** [comment]
In any case please open an issue in the tmux repository.

Oh my tmux! can't be responsible for a tmux server crash. At most, it could reveal a bug in tmux.
