### ISSUE TITLE
`tmux_conf_battery_bar_palette="#xxxxxx,#yyyyyy,#zzzzzz"` seems broken

### ISSUE THREAD

**Issue by serpro69** [gpakosz/.tmux#724]
Hi,

After I recently upgraded, it seems that using `tmux_conf_battery_bar_palette` with 3 colors is not supported anymore?

I've had it set to custom colors and noticed that battery bar disappeared after I've upgraded recently (current version `69a0bedc3604e97dcabd8365f78924fe7ab68fd3`, previous version `fd1bbb56148101f4b286ddafd98f2ac2dcd69cd8` )

At first blamed my changes to the tmux.conf.local, but then I tried to just use the default one and uncommented the `tmux_conf_battery_bar_palette="#d70000,#e4e4e4,#000000` and that gives me the same result - the battery bar disappears

This is with `tmux_conf_battery_bar_palette="gradient"`:

![image](https://github.com/gpakosz/.tmux/assets/22973227/eacfd254-61a7-4449-8d8d-0a5a3becc13a)

This is after uncommenting the next line `tmux_conf_battery_bar_palette="#d70000,#e4e4e4,#000000"   # red, white, black` : 

![image](https://github.com/gpakosz/.tmux/assets/22973227/10862e68-c1a6-48bd-8607-a8cbdacca8ff)

**Comment by gpakosz** [comment]
Hello @serpro69 👋

Sorry for that!
Can you please try the `gh-724` branch?

**Comment by serpro69** [comment]
Hi @gpakosz ,
Thanks for a prompt reply :)

`gh-724` seems to have broken even more. This is how things look like for me after switching to that branch and restoring everything to defaults (as per `tmux/.tmux.conf.local`) :

![image](https://github.com/gpakosz/.tmux/assets/22973227/d2a09185-6305-42ef-9eee-b57e51f888e1)

**Comment by gpakosz** [comment]
Hello @serpro69,

My bad I've used a non POSIX substitution.
Can you please try again? I pushed a fix.

**Comment by serpro69** [comment]
Awesome! Seems to be fixed and working again :grinning: 

![image](https://github.com/gpakosz/.tmux/assets/22973227/9fb7d6db-e09d-4103-91fb-9ca7c690e823)
