### ISSUE TITLE
Question: Change bg color of status bar if prefix is active

### ISSUE THREAD

**Issue by waldauf** [gpakosz/.tmux#728]
Hello,

is it possible to change the background color of the status bar when <prefix> is active? I think it can help with being aware of activating prefix mode without the need to check the sign in the status bar.

**Comment by gpakosz** [comment]
Hello @waldauf 👋

You could do something like
```
tmux_conf_theme_status_bg="#{?client_prefix,$tmux_conf_theme_colour_16,$tmux_conf_theme_colour_1}"
```
But it's not pretty imho.

**Comment by waldauf** [comment]
Hello @gpakosz,

it is not the last fashion hit but for me, it fulfilled the purpose. 

Thank You for Your help!
