### ISSUE TITLE
Not Displaying Correct Battery Percentage

### ISSUE THREAD

**Issue by jhowellburke** [gpakosz/.tmux#73]
I am trying to figure out how to get the status bar to display the correct battery percentage. For some reason my status bar only shows 99% and the always charging icon. Even when it's not charging and my battery as of right now is only 83%, but tmux status bar showing 99%. I check in the tmux.conf.local file to see how you're getting this information but have been unable to find it. I really love how clean and crisp everything looks, I just wanted to battery percentage to work and this would be perfect. Thanks for the help!

![tmux1](https://cloud.githubusercontent.com/assets/18719719/25860150/7d8ea870-3495-11e7-824b-6de0f9f575dd.png)

**Comment by gpakosz** [comment]
Does your laptop have two batteries?

**Comment by jhowellburke** [comment]
I'm not sure I wasn't aware of it having two batteries, but maybe it does. Here is a screen shot of the current layout. Notice on the command line there is not indicator or 2 batteries and yet looking at the battery status through the gui shows 2 different batteries with one being 99% while the other one is only 48%. On the remaining section where it shows 79% that's the information I would like to pull in to show up in status bar.
![whole-screen](https://cloud.githubusercontent.com/assets/18719719/25861775/8c769fdc-349a-11e7-8229-227a3f10ed74.png)

**Comment by gpakosz** [comment]
Right, please try the WIP branch named `multiple-batteries`.

**Comment by jhowellburke** [comment]
Okay I ran the commands you recommended. Is there any changes I need to make to the configs in order for the changes to take effect? I have already reloaded my tmux.conf.local (tmux source-file ~/.tmux.conf) Thanks again for the help

**Comment by jhowellburke** [comment]
Hey never mind It appears to be working. Thanks for creating this. I really like how much you've put into this, and all the options available.
