### ISSUE TITLE
Fail to minimize back to original window/pane

### ISSUE THREAD

**Issue by floyddcn** [gpakosz/.tmux#732]
My customization of .tmux: I adjust the **prefix +** to **prefix -z** 
Actions:  I  maximize one pane to a new window by prefix -z 
Expectation: In the new window,i press down 'prefix -z' but some error occurred,and nothing happend (i expect the window to be minimized to the pane of original window).
What can i do to recover the window to pane???

Following is the error screenshot:
![image](https://github.com/gpakosz/.tmux/assets/48442748/66a0e3dc-0291-4874-a91e-5f0d9c33cd87)
![image](https://github.com/gpakosz/.tmux/assets/48442748/9c72d25b-d513-4af4-9b40-3d4dc4f9d840)

**Comment by gpakosz** [comment]
Hello @floyddcn and sorry for the late answer

> My customization of .tmux: I adjust the prefix + to prefix -z

If by this you mean editing your `.local` customization file to add
```
bind + resize-pane -Z
```

Then try with
```
bind + resize-pane -Z #!important
```
