### ISSUE TITLE
Suggestion for keybinds

### ISSUE THREAD

**Issue by dr3mro** [gpakosz/.tmux#733]
Hello, 
FIrst thanks for your great har work
second

Why not create a keybinding for that in .tmux.conf?

These two settings let you create/kill a new session when pressing Prefix S (Shift+s) or Prefix K (Shift+k) respectively:

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

Prefix Shift+s will open a command prompt in the status line, asking for a new session name. It will either create a new session with that name or attach to an already existing session by that name.

**Comment by gpakosz** [comment]
Hello @dr3mro 👋

>Why not create a keybinding for that in .tmux.conf?
>
>These two settings let you create/kill a new session when pressing Prefix S (Shift+s) or Prefix K (Shift+k) respectively:
>
>bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
>bind K confirm kill-session

Well, first there's `tmux_conf_new_session_prompt=true`.

And then, what bindings look ideal to ones doesn't look ideal to others.
As such I now refrain myself as much as possible from adding bindings or changing bindings.
Why `kill-session` but not `kill-window`?
I suggest that you define your own bindings in your `.local` customization file

**Comment by dr3mro** [comment]
👍
