### ISSUE TITLE
unbind c-b 无效？

### ISSUE THREAD

**Issue by VinceFanZ** [gpakosz/.tmux#74]
禁用 c-b 无效。。。

发现这句
set -g prefix2 C-a 
要把prefix2  改成 prefix 才可以

**Comment by gpakosz** [comment]
Please ask your question in English

**Comment by jtr109** [comment]
Sorry for that. @gpakosz 

He may wanted to know how to disable the prefix C-b.
Honestly, I don't really know what he wants to express even in my native language. It can be translated like below:

> It is invalid to disable C-b
>
> I found the line
> set -g prefix2 C-a
> the prefix2 should be change into prefix  for the purpose

I think this issue can be closed if the prefix C-b can indeed be disabled by `set -g prefix C-b`.

**Comment by gpakosz** [comment]
This configuration makes a choice: keep as much default bindings as possible, and add new ones. In that respect, I chose to use <kbd>Ctrl</kbd>+<kbd>a</kbd> as the secondary prefix. This means both  <kbd>Ctrl</kbd>+<kbd>b</kbd> and <kbd>Ctrl</kbd>+<kbd>a</kbd> work as prefix.

If you want to stop using <kbd>Ctrl</kbd>+<kbd>b</kbd> and only use <kbd>Ctrl</kbd>+<kbd>a</kbd> then you can edit your `~/tmux.conf.local` copy and add:

```
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix
```

**Comment by VinceFanZ** [comment]
thx

**Comment by gpakosz** [comment]
I guess this answers your question 😉. If it's the case please close the issue. Thanks
