### ISSUE TITLE
Can't get status line to update

### ISSUE THREAD

**Issue by DVCoder** [gpakosz/.tmux#742]
I've managed to get oh-my-tmux working in the past, but occasionally, after a server reboot, when I create a new tmux session, the status bar reverts to the default tmux configurations. Even reloading it manually with ~/.tmux.conf doesn't make any difference. I've also made sure to remove any tmux folders in /tmp/.

**Comment by gpakosz** [comment]
Hello @DVCoder 👋

The manual says
> By default, loads the system configuration file from `@SYSCONFDIR@/tmux.conf`, if present, then looks for a user configuration file at `~/.tmux.conf`, `$XDG_CONFIG_HOME/tmux/tmux.conf` or `~/.config/tmux/tmux.conf`

Can you please check these locations for other configuration files?

**Comment by DVCoder** [comment]
> Hello @DVCoder 👋
> 
> The manual says
> 
> > By default, loads the system configuration file from `@SYSCONFDIR@/tmux.conf`, if present, then looks for a user configuration file at `~/.tmux.conf`, `$XDG_CONFIG_HOME/tmux/tmux.conf` or `~/.config/tmux/tmux.conf`
> 
> Can you please check these locations for other configuration files?

I find it very strange I had to do these steps ...

1. Current Tmux session run the command: cut -c3- "$TMUX_CONF" | sh -s _apply_configuration --> But, it didn't show > separators, it was only the | 
2. Tried to reload the ~/.tmux.conf , it didn't change the separators 
3. tmux kill-server --> then remove /temp/tmux**
4. Restarted tmux and everything looks good ...

**Comment by gpakosz** [comment]
Closing as `invalid`. Feel free to reopen if needed
