### ISSUE TITLE
small arraw symbol in macos terminal app

### ISSUE THREAD

**Issue by wangereth** [gpakosz/.tmux#747]
<img width="178" alt="image" src="https://github.com/gpakosz/.tmux/assets/164353295/2f610b8a-56d8-4f68-8e36-2e647d9251c1">
small arraw on macos terminal app
<img width="184" alt="image" src="https://github.com/gpakosz/.tmux/assets/164353295/89a2a2e4-3d42-4a47-a2d4-e0320e71151b">
normal on alacritty
Can't figure out why.
<img width="1086" alt="image" src="https://github.com/gpakosz/.tmux/assets/164353295/044d16c0-06e3-437d-8170-6aa3a648fb40">
This is my settings

**Comment by gpakosz** [comment]
Hello @wangereth,

It's all about the font size settings in different terminal emulators.
