### ISSUE TITLE
clipboard problem in linux

### ISSUE THREAD

**Issue by C1tas** [gpakosz/.tmux#75]
how can i copy to linux clipboard in copy mode,not only in tmux copy buffer

**Comment by gpakosz** [comment]
Hello @C1tas,

Can you please give a try at the `clipboard` branch I just pushed?

With this branch:
  1. edit your `~/.tmux.conf.local` copy to add `tmux_conf_share_os_clipboard=true`
  2. now when when you hit <kbd>y</kbd> while in copy mode, selection is also sent to the OS clipboard

**Comment by C1tas** [comment]
Thanks for your patient

i have followed your guide  

![](https://django.c1tas.com/pic/orign/19)

when i click `y`

but still in copy-buffer

![](https://django.c1tas.com/pic/orign/20)

but the system clipboard doesn't change

![](https://django.c1tas.com/pic/orign/21)

i found it in `.tmux.conf`

![](https://django.c1tas.com/pic/orign/22)

i don't know where goes wrong

**Comment by gpakosz** [comment]
I forgot to mention you need to reload the configuration by hitting <kbd>prefix</kbd>+<kbd>r</kbd>.

After configuration is reloaded you should be able to confirm bindings are updated by doing:
```
$ tmux list-keys | grep copy-pipe
```

**Comment by gpakosz** [comment]
FYI, I force pushed the `clipboard` dev branch. The setting is now called `tmux_conf_copy_to_os_clipboard`.

On Linux, you need to make sure you have either `xsel` or `xclip` installed and you need to reload your configuration.

**Comment by C1tas** [comment]
Thanks for your patient :D

Cytas

在 2017年5月16日，上午12:44，Gregory Pakosz <notifications@github.com<mailto:notifications@github.com>> 写道：


FYI, I force pushed the clipboard dev branch. The setting is now called tmux_conf_copy_to_os_clipboard.

On Linux, you need to make sure you have either xsel or xclip installed and you need to reload your configuration.

**Comment by gpakosz** [comment]
Does it work for you?

**Comment by C1tas** [comment]
yes , it works well
Thanks

**Comment by gpakosz** [comment]
Good to know. I'll merge the branch once I've tested it on Cygwin and WSL (Bash for Windows)
