### ISSUE TITLE
At the same window while the other panel was in git clone an error occurs with the newly opened panel 

### ISSUE THREAD

**Issue by awarewen** [gpakosz/.tmux#751]
![图片](https://github.com/user-attachments/assets/7205c973-148c-4338-b8e4-2c6418e3ccc6)

![图片](https://github.com/user-attachments/assets/2d0a2738-1ecb-407a-979d-b52044f8ff2a)

And when the git clone is over, it returns to normal

Other windows are not affected.

**Comment by awarewen** [comment]
tmux -V : 3.4 version

**Comment by gpakosz** [comment]
Hello @awarewen,

Is this also happening when you don't use Oh my tmux!?

**Comment by awarewen** [comment]
> Hello @awarewen,
> 
> Is this also happening when you don't use Oh my tmux!?

![图片](https://github.com/user-attachments/assets/5857fe73-f111-4a7b-b532-fb76841bfa35)
Not

**Comment by awarewen** [comment]
![图片](https://github.com/user-attachments/assets/f97c7d2a-af45-4d94-b5df-37c11e19c886)
![图片](https://github.com/user-attachments/assets/47f55d8b-1cd5-4bb7-92ef-c68470399d11)
OKKKK! other newly windows is same

**Comment by gpakosz** [comment]
> an error occurs with the newly opened panel

I have no idea about what you mean, can you please elaborate?

**Comment by awarewen** [comment]
https://github.com/user-attachments/assets/f99585e1-6b41-45a4-b308-a5b055eba6a8

when the first panel is in git clone,unable to open new panels and windows. Can you try it ?

Logs:
---
[tmux-client-22874.log](https://github.com/user-attachments/files/16415696/tmux-client-22874.log)
[tmux-out-22876.log](https://github.com/user-attachments/files/16415698/tmux-out-22876.log)
[tmux-server-22876.log](https://github.com/user-attachments/files/16415699/tmux-server-22876.log)

**Comment by gpakosz** [comment]
I cannot reproduce on `macOS`.

Are you using TPM plugins?

**Comment by gpakosz** [comment]
Hello @awarewen,

Did you find what was causing the issue?

**Comment by awarewen** [comment]
> Hello @awarewen,
> 
> Did you find what was causing the issue?

When i upgraded the plugin list the error went away. 
my plugins list:
```conf
  set -g @plugin 'CrispyConductor/tmux-copy-toolkit'
  set -g @plugin 'tmux-plugins/tmux-yank'
  set -g @plugin 'tmux-plugins/tmux-open'
# custom theme
  set -g @plugin 'jimeh/tmux-themepack' 
# set theme
	#set -g @themepack 'powerline/block/blue'
	#set -g @themepack 'powerline/block/cyan'
	#set -g @themepack 'powerline/default/green'
	set -g @themepack 'powerline/double/magenta'
```
