### ISSUE TITLE
Highlighted text not visible during search in msfconsole when using tmux

### ISSUE THREAD

**Issue by darkvpier** [gpakosz/.tmux#752]
## Issue description

I'm experiencing an issue where highlighted text during search in msfconsole is not visible when using tmux. It is not limited to Metasploit Framework (msfconsole) but for various tools like the linpeas script.

## Information

* tmux 3.4
* `uname -av`: `Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux`
* `echo $TERM`: `tmux-256color`
* qterminal `1.4.0`
* Metasploit Framework Version: `6.4.18-dev`

## To reproduce the issue:
```
sudo msfconsole
search smbv3
```
### Expected:
The search results with highlighted matches should be displayed within the tmux pane.
![image](https://github.com/user-attachments/assets/db7d6424-7d51-498d-a4fe-01aebc95374d)

### Error in tmux:
The search results are displayed, but the highlighted text for matches is not visible.
![352866551-144bb2ff-e65e-41df-af88-835feffe5b43~2](https://github.com/user-attachments/assets/611c92b9-3b16-44d1-8d1d-b72f3c5fd4c9)

**Comment by gpakosz** [comment]
Hello @darkvpier 👋

Is it better if you add this line in your `.local` customization file?

```
set -g default-terminal "screen-256color" #!important
```

**Comment by darkvpier** [comment]
> Hello @darkvpier 👋
> 
> Is it better if you add this line in your `.local` customization file?
> 
> ```
> set -g default-terminal "screen-256color" #!important
> ```

done that, still not working

**Comment by gpakosz** [comment]
This is very much related to the value of the `TERM` environment variable and I would expect your problem to reproduce without using Oh my tmux!

**Comment by darkvpier** [comment]
> This is very much related to the value of the `TERM` environment variable and I would expect your problem to reproduce without using Oh my tmux!

The problem exist even if I use Tmux without Oh my tmux! is there a fix for it

**Comment by gpakosz** [comment]
I'm sorry I have no idea
