### ISSUE TITLE
TMUX Error When Sourcing Config File

### ISSUE THREAD

**Issue by haohu321** [gpakosz/.tmux#753]
Hi,

I got the following errors when source ~/.tmux.conf file:

```

'TMUX_PROGRAM="$(LSOF=$(PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" command -v lsof); $LSOF -b -w -a -d txt -p 50521 -Fn 2>/dev/null | perl -n -e "if (s/^n((?:.(?!dylib$|so$))+)$/\1/g && s/(?:\s+\([^\s]+?\))?$/[0/0]
'"$TMUX_PROGRAM" -S /tmp/tmux-100305/default set-environment -g TMUX_SOCKET "/tmp/tmux-100305/default"' returned 127
'"$TMUX_PROGRAM" set-environment -g TMUX_CONF $(for conf in "$HOME/.tmux.conf" "$XDG_CONFIG_HOME/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"; do [ -f "$conf" ] && printf "%s" "$conf" && break; done)' returned 127
'"$TMUX_PROGRAM" set-environment -g TMUX_CONF_LOCAL "$TMUX_CONF.local"' returned 127
'"$TMUX_PROGRAM" source "$TMUX_CONF_LOCAL"' returned 127
```

I didn't touch the `.tmux.conf` file and all my `tmux.conf.local` didn't take effect due to this error.  Here is my local environment:

OS: Linux CentOS 7
Shell: ZSH + oh-my-zsh
Tmux: 3.4

Would appreciate any help to fix this.

**Comment by RixzZ** [comment]
Same issue here.

In my case I moved my configuration from ~/ to ~/.config/tmux/.

OS: MacOS Sonoma
SHELL: ZSH + zinit + Oh My Posh
Tmux: 3.4

**Comment by gpakosz** [comment]
Hello,

I currently don't have access to CentOS but on macOS Sonoma I have no issue.

**Comment by gpakosz** [comment]
I just installed `CentOS 7` with `Vagrant`, then compiled tmux from source and I can't reproduce this.

Do you have Perl installed?

**Comment by gpakosz** [comment]
@haohu321 Can you please try the latest commit in the `master` branch?

**Comment by rubiin** [comment]
I still have this error even on latest commit 
![image](https://github.com/user-attachments/assets/d64aa453-13b0-4410-8e9b-c908bee3d459)

**Comment by gpakosz** [comment]
@rubiin Can you please open a dedicated issue? Something's failing with the TPM plugins you're using

**Comment by rubiin** [comment]
i deleted the plugins folder and the second issue is gone. now just the first error

**Comment by gpakosz** [comment]
@rubiin Please open a dedicated issue: kill all tmux processes, start from the latest version of the `master` branch, remove the use of TPM plugins, and in the issue please detail your OS, `TERM` value and your tmux version. Thanks!
