### ISSUE TITLE
Error when tmux new a terminal: /root/.tmux.conf:31: usage: new-window

### ISSUE THREAD

**Issue by thisjiang** [gpakosz/.tmux#755]
tmux version: **tmux 2.7**
```
tmux new -s test
/root/.tmux.conf:31: usage: new-window [-adkP] [-c start-directory] [-F format] [-n window-name] [-t target-window] [command]
```

**Comment by gpakosz** [comment]
Hello @thisjiang,

Thanks for the report. This bug has been introduced by #679.

Support for `new-window -e` has been added in tmux `3.0`.
Can you please upgrade until I figure out if there's a solution?

**Comment by gpakosz** [comment]
Can you please try the `gh-755` branch?
