### ISSUE TITLE
disable sticky keybinds

### ISSUE THREAD

**Issue by OliverGuy** [gpakosz/.tmux#758]
Hey there, thanks for this tmux configuration, I'm using it everywhere 😃 

I have one tiny issue: whenever I'm hopping between panes (or windows, for that matter), there's a delay during which I can keep using `hkjl` to switch between panes.

As a vim/vi-mode user, I find this slightly annoying and would rather have tmux consume a single key press after `<prefix>` so I don't have to wait to type again.

How would one achieve this ?

**Comment by gpakosz** [comment]
Hello @OliverGuy 👋

I believe you want to play with `escape-time`, e.g. in your `.local` customization file

```
set -s escape-time 5
```

**Comment by OliverGuy** [comment]
Works like a charm, merci !
