### ISSUE TITLE
Support for Debian Linux bullseye

### ISSUE THREAD

**Issue by jean-bonilha** [gpakosz/.tmux#759]
I tried to run this Tmux setting on Debian Linux Bullseye but with no success.
Could you or someone clarify for me what I need to do for it to work?

**Comment by gpakosz** [comment]
Hello @jean-bonilha 👋

I'm not sure what it means when you say "with no success".
I just tried using Oh my tmux! on a fresh Debian Bullseye box and it works fine for me.

**Comment by gpakosz** [comment]
Hello @jean-bonilha 👋

Any news?
