### ISSUE TITLE
Crash on Oracle Linux 9 with tmux 3.2

### ISSUE THREAD

**Issue by vadonka** [gpakosz/.tmux#760]
Its crashed on OL9. Just using the default config, after a few seconds it crashed with [server exited] output.
Nothing on the logs or the stdout. If i run tmux with factory default config this issue not happening.

**Comment by gpakosz** [comment]
Hello @vadonka 👋

Were you able to figure out what makes tmux crash by using` tmux -vv` or `tmux -vvv`?

**Comment by gpakosz** [comment]
@vadonka ?

**Comment by jbrinson3** [comment]
I also ran into this problem, but with Rocky 9. After the the default install of the tmux config from git, upon starting tmux it loads without the ohmytmux look/feel and then quits after a few seconds. When running with the -vv and -vvv options the only output was the server exited message. I tried running tmux without the ohmytmux and it had no issues staying open.

OS: Rocky 9.4
tmux: 3.2a (also didn't work with compiled version 3.6)

**Comment by jbrinson3** [comment]
I just figured it out. For there was a line near the end that said this:
"This configuration requires perl Time::HiRes"
I installed the appropriate perl module and it worked.

**Comment by gpakosz** [comment]
Oh well so it's indeed not a crash but an explicit call to `kill-server`
And there's a message that comes with it.

Are you saying the message is not visible for long enough?

**Comment by gpakosz** [comment]
@vadonka What if you install perl's Time::HiRes?

**Comment by jbrinson3** [comment]
It either didn't display the message that went with `kill server` or it was very, very quick. The only message I had that stayed was `[server exited]`.

**Comment by gpakosz** [comment]
It's supposed to display a message in the status bar for 3 seconds before killing the server

**Comment by gpakosz** [comment]
If you edit line `1693` of `.tmux.conf` and test for the existence of the `MTime::FooBar` module, then launch tmux, you should see a message for 3 seconds in the status bar then tmux will exit

**Comment by gpakosz** [comment]
But if you run tmux and try to time right away, then it dismisses the message

**Comment by gpakosz** [comment]
I started the `gh-760` branch that removes the hard dependency on perl's Time::HiRes module, which is supposedly required by the main perl package 🤷‍♂️

**Comment by gpakosz** [comment]
@jbrinson3 Could you please try the `gh-760` branch, without perl's `Time::HiRes` module please?
