### ISSUE TITLE
Issues after upgrading to tmux 3.5 when using fish shell

### ISSUE THREAD

**Issue by matallui** [gpakosz/.tmux#761]
After upgrading to tmux 3.5 (from 3.4.1), this config stopped working for me.
Tmux went back to that classic green lock (like nothing was configured) and the colors were off on vim and everything.

Not sure what happened all of the sudden and haven't found a solution.
Just wanted to post here and see if anyone else encountered the same issue

**Comment by matallui** [comment]
I realized the errors were all coming from this snippet:

```
%if #{==:#{TMUX_PROGRAM},}
  run 'TMUX_PROGRAM="$(LSOF=$(PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" command -v lsof); $LSOF -b -w -a -d txt -p #{pid} -Fn 2>/dev/null | perl -n -e "if (s/^n((?:.(?!dylib$|so$))+)$/\1/g && s/(?:\s+\([^\s]+?\))?$//g) { print; exit } } exit 1; {" || readlink "/proc/#{pid}/exe" 2>/dev/null)"; { [ -f "$TMUX_PROGRAM" ] && [ -x "$TMUX_PROGRAM" ]; } || TMUX_PROGRAM="$(command -v tmux || printf tmux)"; "$TMUX_PROGRAM" -S #{socket_path} set-environment -g TMUX_PROGRAM "$TMUX_PROGRAM"'
%endif
%if #{==:#{TMUX_SOCKET},}
  run '"$TMUX_PROGRAM" -S #{socket_path} set-environment -g TMUX_SOCKET "#{socket_path}"'
%endif
%if #{==:#{TMUX_CONF},}
  run '"$TMUX_PROGRAM" set-environment -g TMUX_CONF $(for conf in "$HOME/.tmux.conf" "$XDG_CONFIG_HOME/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"; do [ -f "$conf" ] && printf "%s" "$conf" && break; done)'
%endif
%if #{==:#{TMUX_CONF_LOCAL},}
  run '"$TMUX_PROGRAM" set-environment -g TMUX_CONF_LOCAL "$TMUX_CONF.local"'
%endif
```

If I set those env variables in my shell before running `tmux`, it all worked again.

**Comment by hanwentao** [comment]
I encountered the same issue.  How did you set env variables? @matallui

**Comment by gpakosz** [comment]
I don't have any issue with macOS, tmux 3.5 and zsh.
I need to figure out what changed in tmux

**Comment by sungkang** [comment]
i had the same issue as @matallui but even after manually setting those env vars, my local tweaks seem to have not taken correctly.

os: macOS 15.0 Sequoia
terminal: kitty
shell: fish

**Comment by gpakosz** [comment]
This won't be a so straightforward fix.

In the meantime, explicitly setting `TMUX_PROGRAM`, `TMUX_CONF` and `TMUX_CONF_LOCAL` is the way to go

**Comment by michael555444** [comment]
I had the same issue after 3.5 upgrade and all fixed after downgrading (3.5-1 => 3.4-10)

System:
- OS: `Arch Linux`
- Architecture: `x86_64`
- Kernel version: `6.10.10-arch1-1`
- Terminal: `Kitty`
- Shell: `fish`

**Comment by zenodotus280** [comment]
> I had the same issue after 3.5 upgrade and all fixed after downgrading (3.5-1 => 3.4-10)

First time I've ever needed to downgrade after years of using Arch! Here's the command for anyone else looking for a quick fix:

`sudo pacman -U https://archive.archlinux.org/packages/t/tmux/tmux-3.4-9-x86_64.pkg.tar.zst`

Relevant [Arch Wiki](https://wiki.archlinux.org/title/Arch_Linux_Archive#How_to_downgrade_one_package)
[List of tmux versions](https://archive.archlinux.org/packages/t/tmux/).

**Comment by gpakosz** [comment]
Can you please try the `gh-761` branch?

**Comment by asrorbek-mannonov** [comment]
```
'trap '[ -n "$sleep_pid" ] && kill -9 "$sleep_pid"; exit 0' TERM; while [ x"$('/opt/homebrew/Cellar/tmux/3.5/bin/tmux' -S '/private/tmp/tmux-501/default' display -p '#{pid}')" = x"10921" ]; do nice cut -c3- '/Users/<username>/.tmux.
'trap '[ -n "$sleep_pid" ] && kill -9 "$sleep_pid"; exit 0' TERM; while [ x"$('/opt/homebrew/Cellar/tmux/3.5/bin/tmux' -S '/private/tmp/tmux-501/default' display -p '#{pid}')" = x"10921" ]; do nice cut -c3- '/Users/<username>/.tmux.
```

I got the above warning, but the config is working again.


> Can you please try the `gh-761` branch?

**Comment by matallui** [comment]
Adding this to my `.config/fish.config` was what fixed it for me:

```
# Fix tmux 3.5 issues
set -gx TMUX_PROGRAM /opt/homebrew/bin/tmux
set -gx TMUX_CONF $HOME/.tmux.conf
set -gx TMUX_CONF_LOCAL $HOME/.tmux.conf.local
```
cc: @hanwentao @sungkang

**Comment by sungkang** [comment]
> Adding this to my `.config/fish.config` was what fixed it for me:
> 
> ```
> # Fix tmux 3.5 issues
> set -gx TMUX_PROGRAM /opt/homebrew/bin/tmux
> set -gx TMUX_CONF $HOME/.tmux.conf
> set -gx TMUX_CONF_LOCAL $HOME/.tmux.conf.local
> ```
> 
> cc: @hanwentao @sungkang

yup i had that as a temp fix to get it mostly working until the tmux fix is pushed out. I am just waiting for the tmux guys to push out a fix for this soon.

https://github.com/tmux/tmux/issues/4143

@gpakosz has been working with them and seems like they got it resolved.

**Comment by gpakosz** [comment]
I updated the `gh-761` branch

**Comment by gpakosz** [comment]
Can you please test the most recent version of the `gh-761` branch? Commit `3bef43eba9f5ca9cc2a07b961005c78b9b96dcb8`.

Thank you

**Comment by asrorbek-mannonov** [comment]
> Can you please test the most recent version of the `gh-761` branch? Commit `3bef43eba9f5ca9cc2a07b961005c78b9b96dcb8`.
> 
> Thank you

branch `gh-761` is working fine without issues for me.

**Comment by gpakosz** [comment]
Things to watch for:
- Battery status updates correctly
- Uptime updates correctly
- Loadavg updates correctly
- TPM plugins install and work correctly
- Keeping tmux running shouldn't cause high CPU usage (except what runs in panes)
- Killing tmux shouldn't leave stray processes behind (`ps aux | grep tmux`)

**Comment by ank-everstake** [comment]
Pulled `gh-761`. Seems all is working fine as before, thanks!

**Comment by gpakosz** [comment]
@XyLyXyRR Please make sure you are really using an unmodified version of Oh my tmux! master branch. Then kill all tmux processes and launch it again. If you still have the problem, please open a dedicated issue. Thank you!
