### ISSUE TITLE
Why we shouldn't remove bottom lines in `.tmux.conf.local`?

### ISSUE THREAD

**Issue by eval-exec** [gpakosz/.tmux#762]
Hello, I want to know why we shouldn't remove these lines?
https://github.com/gpakosz/.tmux/blob/5f1047550ba2ba16a27bf8c9ea958fbbf974598d/.tmux.conf.local#L480-L482

I think these lines are "comments" because they have `#` as line prefix.
Where are these lines used?

**Comment by gpakosz** [comment]
Hello @eval-exec 👋

They are indeed comments when read by tmux itself, but the `.local` file is also executed as a shell script with `cut -c3- path_to_local_file | sh -s some_function_name`
