### ISSUE TITLE
TPM plugins and status-right/status-left?

### ISSUE THREAD

**Issue by davidfmatheson** [gpakosz/.tmux#764]
I've been using your standard config with [catppuccin tmux](https://github.com/catppuccin/tmux). They've recently rewritten the plugin in a way where it seems that it [matters](https://github.com/catppuccin/tmux/issues/342#issuecomment-2395278581) the order in which the plugins are loaded and that `status-left` and `status-right` are set. Is there a way to handle this? I'm a bit new to tmux config, I will admit.

**Comment by gpakosz** [comment]
Hello @davidfmatheson 👋

I'm sorry I don't know catpuccin tmux.
My expectations, in terms of ordering is that
- Oh my tmux sets `status-left` and `status-right` tmux options
- Then each TPM plugin can rewrite `status-left` and `status-right` on their own
  - I don't believe TPM defines in which order plugins are loaded

Does that help?

**Comment by gpakosz** [comment]
Oh my tmux! scans its `.local` customization file for `set -g @plugin` directives, and fills the `@tpm_plugins` variable that TPM consumes.

The order of which plugin names appear in `@tpm_plugins` is the order in which they are listed in the `.local` customization file.
