### ISSUE TITLE
Issues after upgrading to tmux 3.5a when using fish shell on Android

### ISSUE THREAD

**Issue by XyLyXyRR** [gpakosz/.tmux#765]
Unfortunately, this problem does not resolve on my Android phone, but it does resolve on my computer.

## Information

- tmux: `3.5a`
- .tmux: `2c9ef1c`

fastfetch:
```
u0_a767@localhost
-----------------
OS: Android REL 12 aarch64
Host: Xiaomi Redmi K30 5G
Kernel: Linux 4.19.113-perf-ga1b60ef832fb
Uptime: 5 days, 18 hours, 54 mins
Packages: 132 (dpkg)
Shell: fish 3.7.1
WM: Window Manager
Terminal: Termux googleplay.2024.08.29
CPU: SM7250 (8) @ 2.40 GHz
Memory: 4.19 GiB / 7.25 GiB (58%)
Swap: 2.16 GiB / 6.00 GiB (36%)
Disk (/): 2.75 GiB / 3.01 GiB (91%) - ext4 [Read-only]
Disk (/storage/emulated): 77.97 GiB / 107.04 GiB (73%) - fuse
Local IP (tun0): 172.19.0.1/30
Local IP (wlan0): 192.168.123.5/24
Locale: en_US.UTF-8
```

The output is `'sh -c '"$TMUX_PROGRAM" ${TMUX_SOCKET:+-S "$TMUX_SOCKET"} source "$TMUX_CONF"'' returned 127`.

If I run tmux in this way: `TMUX_PROGRAM=(which tmux) tmux new`, it's looks fine.

When I run `which tmux` or `command -s tmux`, it's show me `/data/data/com.termux/files/usr/bin/tmux`.

After run `killall tmux || rm -rf ~/.local/share/tmux/ && gh repo clone gpakosz/.tmux ~/.local/share/tmux && tmux new`, this problem still occur.

**Comment by gpakosz** [comment]
Hello @XyLyXyRR,

What I don't get is that Android is nothing special. It should be all about tmux version, Oh my tmux! version and fish version.

**Comment by gpakosz** [comment]
Did Oh my tmux! work for you before tmux `3.5` or `3.5a`?

**Comment by XyLyXyRR** [comment]
Yes, it's works fine before this.

Wait, I forgot upload tmux server and client logs.

[tmux-client-7719.log](https://github.com/user-attachments/files/17275207/tmux-client-7719.log)
[tmux-out-7721.log](https://github.com/user-attachments/files/17275209/tmux-out-7721.log)
[tmux-server-7721.log](https://github.com/user-attachments/files/17275210/tmux-server-7721.log)

**Comment by gpakosz** [comment]
Can you please launch tmux without defining `TMUX_PROGRAM`, then within a pane launch

```
$ cut -c3- /path/to/tmux.conf | sh -sx _apply_configuration
```

**Comment by XyLyXyRR** [comment]
Here is the output.

[tmux.cut.log](https://github.com/user-attachments/files/17275273/tmux.cut.log)

**Comment by gpakosz** [comment]
What would help is giving me the output of the following

```
$ tmux display -p '#{pid}'
1234 # fictional PID, replace with the returned value in the command below
```

Then use the PID that's been returned in the following command
```
$ lsof -b -w -a -d txt -p 1234 -Fn
```

**Comment by gpakosz** [comment]
Also,

When within a tmux pane, can you please give me the output of
```
$ env | grep TMUX
```

You should have a `TMUX` environment variable, for example
```
TMUX=/private/tmp/tmux-501/default,56574,0
```

`56574` is supposed to be the same value as what `tmux display -p '#{pid}'` returns.

**Comment by XyLyXyRR** [comment]
[tmux.cut.1.log](https://github.com/user-attachments/files/17275386/tmux.cut.1.log)

And `$ lsof -b -w -a -d txt -p 8117 -Fn` output `lsof: Unknown option 'b' (see "lsof --help")`.

`$ env | grep TMUX` output:
```
TMUX=/data/data/com.termux/files/usr/var/run/tmux-10767/default,8117,0
TMUX_PANE=%0
```

**Comment by XyLyXyRR** [comment]
`lsof --help` shows this:

```
Toybox 0.8.4-android multicall binary: https://landley.net/toybox (see toybox --help)                                                                                               usage: lsof [-lt] [-p PID1,PID2,...] [FILE...]                                                                          List all open files belonging to all active processes, or processes using                                               listed FILE(s).                                                                                                         -l      list uids numerically                               -p      for given comma-separated pids only (default all pids)                                                          -t      terse (pid only) output
```

**Comment by gpakosz** [comment]
> Unknown option 'b' (see "lsof --help")
Interesting

**Comment by gpakosz** [comment]
So Oh my tmux is supposed to rely on `readlink` in that case

**Comment by gpakosz** [comment]
Going back to `tmux.cut.log` given above

```
+ printf %s+  /data/data/com.termux/files/usr/var/run/tmux-10767/default,8117,0
cut -d, -f2
+ TMUX_PID=8117
+ lsof -b -w -a -d txt -p 8117 -Fn
+ perl -n -e if (s/^n((?:.(?!dylib$|so$))+)$/\1/g) { print; exit } } exit 1; {
+ readlink /proc/8117/exe
+ TMUX_PROGRAM=/apex/com.android.runtime/bin/linker64
```

We see that `TMUX_PID` is set to `8117` based on splitting the value of the `TMUX` environment variable.
Then `lsof` is being invoked and fails (because `-b` is not a supported option).
Then `realink /proc/8117/exe` gives `/apex/com.android.runtime/bin/linker64` instead of pointing to `/data/data/com.termux/files/usr/bin/tmux`.

I have no idea why it's happening

**Comment by gpakosz** [comment]
Can you try to compare the output of the following commands between tmux `3.4` and `3.5` or `3.5a` please?

Within a tmux pane
```
$ echo $TMUX; echo $(tmux display -p '#{pid}'); echo $(readlink /proc/$(tmux display -p '#{pid}')/exe)
```

**Comment by XyLyXyRR** [comment]
I'm afraid I can't roll back to version 3.4
- termux doesn't provide packages for older versions
- tmux's release page doesn't have precompiled Android executables
- tmux's appimage version doesn't work on my Android
- Source code compilation encounters nasty c errors

This is what I got from tmux 3.4 source compile:
[tmp.tmux.build.log](https://github.com/user-attachments/files/17276764/tmp.tmux.build.log)

**Comment by gpakosz** [comment]
Then can you please run the commands above with tmux `3.5a`?

I’m trying to understand why readlink would return such a path to linker64

**Comment by XyLyXyRR** [comment]
```
/data/data/com.termux/files/usr/var/run/tmux-10767/default,30942,0
30942
/apex/com.android.runtime/bin/linker64
```

**Comment by gpakosz** [comment]
This is very wrong. And also worth a termux issue imho

**Comment by XyLyXyRR** [comment]
According to this [link](https://github.com/termux/termux-packages/wiki/Build-environment), I build tmux 3.4 and installed with `dpkg -i tmux_3.4_aarch64.deb`, but seems like still got this output:
```
/data/data/com.termux/files/usr/var/run/tmux-10767/default,32133,0
32133
/apex/com.android.runtime/bin/linker64
```

`tmux -V` is `tmux 3.4` already.

**Comment by gpakosz** [comment]
What does readlink return for other pids?

**Comment by XyLyXyRR** [comment]
```
lrwxrwxrwx - u0_a767  7 Oct 19:21 /proc/3539/exe -> /apex/com.android.runtime/bin/linker64                              lrwxrwxrwx - u0_a767  7 Oct 19:21 /proc/3609/exe -> /apex/com.android.runtime/bin/linker64                              lrwxrwxrwx - u0_a767  7 Oct 19:21 /proc/3611/exe -> /apex/com.android.runtime/bin/linker64                              lrwxrwxrwx - u0_a767  7 Oct 19:21 /proc/3635/exe -> /apex/com.android.runtime/bin/linker64
lrwxrwxrwx - root     7 Oct 19:21 /proc/self/exe -> /data/data/com.termux/files/usr/bin/eza
lrwxrwxrwx - root     7 Oct 19:21 /proc/thread-self/exe -> /data/data/com.termux/files/usr/bin/eza
```

**Comment by gpakosz** [comment]
Can you please open an issue to the termux project? I don't have any Android devices

**Comment by XyLyXyRR** [comment]
It works!

**Comment by gpakosz** [comment]
I won't merge until knowing what's going on in termux, as `gh-765` is just a last chance workaround: if the identified executable doesn't understand `display -p #{pid}` then likely it's not a valid tmux executable, so resort to using `command -v` or even `printf tmux`
