### ISSUE TITLE
Changing the battery bar color

### ISSUE THREAD

**Issue by RainSharky** [gpakosz/.tmux#768]
I tried to change the color of the battery bar segments to match my overall color scheme, however I had no luck.

### My .tmux.conf.local file (HEX Color Codes changed)
```shell
# battery bar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_full_fg,colour_empty_fg,colour_bg"
tmux_conf_battery_bar_palette="gradient"
#tmux_conf_battery_bar_palette="#903F41,#e4e4e4,#000000"   # red, white, black

# battery hbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
tmux_conf_battery_hbar_palette="gradient"
#tmux_conf_battery_hbar_palette="#903F41,#E0914D,#90b088"  # red, orange, green

# battery vbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
tmux_conf_battery_vbar_palette="gradient"
#tmux_conf_battery_vbar_palette="#903F41,#E0914D,#90b088"  # red, orange, green
``` 

I tried different variations of setting comments and uncommenting with no success. 

![image](https://github.com/user-attachments/assets/3a268d1d-6ed6-4c76-96e1-82b01f5ab887)

Am I searching at the wrong place? 
Help would be appreciated :^) 
Thanks!

**Comment by gpakosz** [comment]
Hello @RainSharky,

Please make sure you
- Uncomment the `tmux_conf_battery_bar_palette=...` line
- Use lowercases


```
tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#000000"
```

There's currently no way to express a custom linear gradient with multiple steps though

**Comment by RainSharky** [comment]
```shell
# battery bar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_full_fg,colour_empty_fg,colour_bg"
tmux_conf_battery_bar_palette="gradient"
tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#000000"   # red, white, black
``` 
![image](https://github.com/user-attachments/assets/d5794b73-c839-4d13-be19-9bd7e6fad90c)

This seems to work. Thanks!

The other two palettes 
`#tmux_conf_battery_hbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green `
and
`#tmux_conf_battery_vbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green`

Dont have any effect tho. 
Is that how its suppose to work?

**Comment by gpakosz** [comment]
They don't have effect because they start with `#` which is the character used to comment in a tmux configuration file

**Comment by RainSharky** [comment]
I know that, but if I uncomment them, they still dont work. The colors do not get changed. 

Only uncommenting 

`tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#000000"   # red, white, black`

works. Sorry for the misunderstanding.

**Comment by gpakosz** [comment]
The last line that's not commented wins

`bar`, `hbar` and `vbar` as different kind of bars

**Comment by RainSharky** [comment]
Maybe this makes it more clear

```shell
# battery bar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_full_fg,colour_empty_fg,colour_bg"
#tmux_conf_battery_bar_palette="gradient"
#tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#1c1c1c"   # red, white, black

# battery hbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
tmux_conf_battery_hbar_palette="gradient"
tmux_conf_battery_hbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green

# battery vbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
#tmux_conf_battery_vbar_palette="gradient"
#tmux_conf_battery_vbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green
``` 
### Outcome
![image](https://github.com/user-attachments/assets/78e00345-d437-45d5-8d69-ee6c41c43b2a)

```shell
# battery bar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_full_fg,colour_empty_fg,colour_bg"
#tmux_conf_battery_bar_palette="gradient"
#tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#1c1c1c"   # red, white, black

# battery hbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
#tmux_conf_battery_hbar_palette="gradient"
#tmux_conf_battery_hbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green

# battery vbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
tmux_conf_battery_vbar_palette="gradient"
tmux_conf_battery_vbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green
``` 

### Outcome
![image](https://github.com/user-attachments/assets/4f7d72b6-c04e-4b0b-b7e7-7a6f76cdda05)

```shell
# battery bar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_full_fg,colour_empty_fg,colour_bg"
tmux_conf_battery_bar_palette="gradient"
tmux_conf_battery_bar_palette="#903f41,#e4e4e4,#1c1c1c"   # red, white, black

# battery hbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
#tmux_conf_battery_hbar_palette="gradient"
#tmux_conf_battery_hbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green

# battery vbar palette, possible values are:
#   - gradient (default)
#   - heat
#   - "colour_low,colour_half,colour_full"
#tmux_conf_battery_vbar_palette="gradient"
#tmux_conf_battery_vbar_palette="#903f41,#e0914d,#90b088"  # red, orange, green
``` 

### Outcome
![image](https://github.com/user-attachments/assets/3cfc2f20-86e2-43c1-9aed-cbc8c48d6def)

**Comment by gpakosz** [comment]
`tmux_conf_battery_hbar_palette` and `tmux_conf_battery_vbar_palette` apply when you use `#{battery_hbar}` or `#{battery_vbar}` in `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right`

**Comment by RainSharky** [comment]
Thats the information I was missing, thank you!
