### ISSUE TITLE
tmux_conf_theme_left_separator_XXX values????

### ISSUE THREAD

**Issue by gagan0723** [gpakosz/.tmux#77]
I've PowerlineSymbols.otf font installed, but can not figure out how the ~/.tmux.conf.local copy uses the right code points for tmux_conf_theme_left_separator_XXX values.

**Comment by gpakosz** [comment]
If you followed installation instructions, you did
```
$ cp ~/.tmux/.tmux.conf.local ~/.tmux.conf.local
```

Now open your `~/.tmux.conf.local` copy and uncomment [lines `131-134`](https://github.com/gpakosz/.tmux/blob/264a577ba183bf7ce74da22a18fbb1bdba8244bf/.tmux.conf.local#L131-L134) like this:
```
tmux_conf_theme_left_separator_main=''  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub=''   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub=''  #   PowerlineSymbols.otf font
```

Then hit `<prefix> + r` to reload the configuration.

**Comment by gagan0723** [comment]
After uncommenting lines 131-134, this is what I get.



Screenshot of the installed fonts.
![screenshot from 2017-05-29 00-00-23](https://cloud.githubusercontent.com/assets/6944095/26532470/d9f6e6e2-4401-11e7-9cc1-8a78c2e4c909.png)




Screenshot of the tmux.
![screenshot from 2017-05-28 23-56-57](https://cloud.githubusercontent.com/assets/6944095/26532463/a64b7d26-4401-11e7-946b-fe66635450e6.png)

**Comment by gpakosz** [comment]
Likely you installed a font with the old Powerline codepoints

**Comment by gagan0723** [comment]
Is the documentation at  [Install Powerline Font](http://powerline.readthedocs.io/en/master/installation/linux.html) the right and way to install the latest of Powerline Font?

**Comment by gpakosz** [comment]
I would assume it's the case.

You need to make sure you didn't mess the encoding of your `~/.tmux.conf.local` which should be encoded in UTF-8. I also believe that your OS locale should be UTF-8 compatible.

You need to verify whether the font you installed contains glyphs for `U+E0B0`, `U+E0B1`, `U+E0B2`, `U+E0B3` code points.

**Comment by gpakosz** [comment]
Make also sure you meet [terminal emulator requirements](http://powerline.readthedocs.io/en/master/usage.html#usage-terminal-emulators).
 
E.g. `rxvt-unicode` must be compiled with `--enable-unicode3`.

Hope that helps.

**Comment by gagan0723** [comment]
OS locale is UTF-8 compatible.
![screenshot from 2017-05-30 22-47-41](https://cloud.githubusercontent.com/assets/6944095/26604293/2e23f1cc-458a-11e7-8baa-d585aca20f7f.png)

 Font I installed contains glyphs for U+E0B0, U+E0B1, U+E0B2, U+E0B3 code points.
![screenshot from 2017-05-30 22-45-18](https://cloud.githubusercontent.com/assets/6944095/26604332/4a562324-458a-11e7-9f4c-e32a3ea76638.png)

**Comment by gpakosz** [comment]
Well, as per your screenshot, glyphs rendered for `U+E0B0`, `U+E0B1`, `U+E0B2`, `U+E0B3` code points are not the powerline symbols:
![image](https://cloud.githubusercontent.com/assets/553208/26605027/ae3ae65c-458c-11e7-9932-d6f6fbe0541f.png)

**Comment by gagan0723** [comment]
I don't really understand what's wrong. This is what I have in ~/.tmux.conf.local file.
![screenshot from 2017-05-30 23-10-18](https://cloud.githubusercontent.com/assets/6944095/26605201/6388ddfc-458d-11e7-92f2-6e4982bd1e73.png)


As per your screenshot, they aren't the same.

**Comment by gpakosz** [comment]
What's wrong is your font setup.

You have 3 options:
  - either you install the proper `PowerlineSymbols.otf` font and double check your terminal setup supports `font-config`, [as instructed in the matrix in the Powerline manual](http://powerline.readthedocs.io/en/master/usage.html#usage-terminal-emulators)
  - either you install a patched font
  - either you find, in the font you installed,  the code points corresponding to the "triangle"/"separator" Powerline glyphs and change the value of the `tmux_conf_theme_xxx_separator` variables

This is really external to my tmux configuration 😐

**Comment by preginald** [comment]
@gagan0723 check out [this gist](https://gist.github.com/kepbod/11075559) that shows you how to install Powerline fonts.

https://gist.github.com/kepbod/11075559
