### ISSUE TITLE
Feature request: center-aligned content

### ISSUE THREAD

**Issue by jontxu** [gpakosz/.tmux#770]
Hi, great project, I've been using it for a while and my tmux looks great.

One thing I've realised is that there's no option to align some modules (for lack of a better word) in the center of the status bar by using  something like `tmux_conf_theme_status_center`. Personally I'd  like to show the windows in the centre.

I'm aware this means somewhat heavy changes in the `tmux.conf` file. Not sure if it's in the roadmap or not... I could try to make a fork and open a PR later on if needed.

**Comment by gpakosz** [comment]
Hello @jontxu,

Are you asking about adding `set -g status-justify centre` or `set -g status-justify absolute-centre` to your `.local` customization copy?

As far as I know, it's the only thing that can be centered.

**Comment by jontxu** [comment]
`set -g status-justify centre` did the trick, thanks.

But If I wanted to add other things (date, battery, etc.) a workaround seems to be `set -g status-right "#[align=centre] whatever #[align=right] the rest" which I think is doable with `tmux_conf_theme_status_right` in `.local`.

Or perhaps a `tmux_conf_theme_status_center` could come in handy but I guess it may imply some nontrivial changes in `tmux.conf`. Could be something like (in a really concise way): `set -g status-right "#[align=centre]$status_centre #[align=right]$status_right"`.

Maybe not worth the effort all things considered. Feel free to close the issue if that's the case.

**Comment by gpakosz** [comment]
I don't think we can have such a thing as `tmux_conf_theme_status_center`, because tmux doesn't have `status-center`.

The center is for the windows list.

**Comment by gpakosz** [comment]
I mean it seems that you can hack to expand `status-right` and have some of it be displayed in the center of the status bar, but that still implies the window list is to the left of it.

**Comment by gpakosz** [comment]
For now, it seems that it's good enough for people to using `#[align=centre]` or `#[align=absolute-centre]` in `tmux_conf_theme_status_right`.

And it seems to me that people who would want to go this route don't expect to have many windows in their window list.

I don't think we can generalize that in a way that doesn't cause issues when the window list becomes big.

**Comment by jontxu** [comment]
Sure, makes sense. Thanks for the feedback anyway.

**Comment by gpakosz** [comment]
Also, I'm not sure who `tmux_conf_theme_status_center` would behave if someone uses `set -g status-justify centre` or `set -g status-justify absolute-centre` at the same time
