### ISSUE TITLE
how disable set window title with current path

### ISSUE THREAD

**Issue by billowqiu** [gpakosz/.tmux#78]
tmux version: 2.4
.tmux:  git version 264a577ba183bf7ce74da22a18fbb1bdba8244bf

I use prefix + ， to rename window name, but then it restore to current path when i type CR in terminal.

**Comment by gpakosz** [comment]
> I use prefix + ， to rename pane name

I suppose what you're meaning is that you're using `prefix + ,` to rename the current window.

This configuration sets `setw -g automatic-rename on` which automatically renames windows.

By default, `automatic-rename-format` is set to `#{pane_current_cmd}`. This renames windows to the name of the program being executed in the active/focused pane: `bash`, `vim`, ...

Given that, if you're seeing the current path it means you at least changed the value of `automatic-rename-format` and e.g. did `setw -g automatic-rename-format to #{pane_current_path}`.

Finally, to disable automatic window renaming, edit your `~/.tmux.conf.local` copy and append:
```
setw -g automatic-rename off
```

**Comment by billowqiu** [comment]
I add this to the ~/.tmux.conf.local.
Everything is not changed.
![qq 20170526135447](https://cloud.githubusercontent.com/assets/720496/26482622/f9b447c4-421a-11e7-8130-db45f0329c71.png)

**Comment by gpakosz** [comment]
I read the `tmux` manual again.

You mentioned title gets changed when hitting `CR`. It means the renaming happens as part of your prompt. You didn't mention which shell you were using and I suspect you're using `zsh` and this is your `zsh` prompt configuration that sends escape sequences to rename windows.

Try adding the following to your `~/.tmux.conf.local` copy instead:
```
setw -g allow-rename off
```

**Comment by billowqiu** [comment]
"allow-rename" is the correct config，thanks。
I use the bash shell。

**Comment by gpakosz** [comment]
You likely have something in your Bash prompt (`echo $PS1`)

**Comment by gpakosz** [comment]
Did you manage to find out what in your `$PS1` prompt renamed window to current directory?

**Comment by billowqiu** [comment]
my $PS1 is “[\u@\h \W]\$”。

**Comment by gpakosz** [comment]
Then something else is renaming the window title. Setting `allow-rename` to `off` doesn't fix the problem at the source.

I'm going to close this issue since it's outside my configuration's scope.
