### ISSUE TITLE
Custom plugin not showing any information in status bar.

### ISSUE THREAD

**Issue by AXington** [gpakosz/.tmux#79]
> Finally, as far as #38 goes, if you have some utility installed on your OS that gives you the current weather, you can e.g. edit your ~/.tmux.conf.local copy and add #(/path/to/weather) to either tmux_conf_theme_status_left or tmux_conf_theme_status_right variables. In that respect, the "extensibility" is the same as stock tmux: use #() to read the output of a command that you know exists in your $PATH.

This may be a syntax error on my part, or it could be a lot of things and I have another question to go with it...

I have a plugin I'm working on to add slack notifications to my status-bar-right.

tmux.conf.local I have ```tmux_conf_theme_status_right='#{prefix}#{pairing} #{slack-alerts}  #{?battery_status...``` It should, currently show "X Direct Messages, X Mentions, X Unread". At least that's what I have the script outputting right now. It is a python script that just prints the results of some parsing, etc, that I'm doing.

Another question that I have is, how often is the status bar updated. I'd rather not have it poll slack constantly... I guess I could daemonize it, but that seems overkill.

**Comment by gpakosz** [comment]
Hello @AXington 

The paragraph you're quoting mentions `#()`. `#()` is `tmux`'s builtin way to display external programs' output to the status line.

As such, if you have a Python script called `slack-alerts` in your `$PATH`, then you should modify `tmux_conf_theme_status_right` this way:
```
tmux_conf_theme_status_right='#{prefix}#{pairing} #(slack-alerts) #{?battery_status...'
```

About status line refresh rate, this configuration sets
```
set -g status-interval 10
```

Which means every 10 seconds the status-line gets redrawn when you're just staring at the screen. However, `tmux` can redraw the status line more often than that, e.g. when you're switching panes... So you're right when you're saying you likely have to prevent your script from hammering Slack APIs.
