### ISSUE TITLE
Status bar not rendering correctly in Mintty on Bash on Windows

### ISSUE THREAD

**Issue by AXington** [gpakosz/.tmux#83]
Messing around with bash on windows with Mintty wsl bridge and the status bar isn't loading properly.
https://github.com/mintty/wsltty

Everything is currently green on it, even though my agnoster theme is looking fine and I've got the powerline fonts installed an linked in the registry the way you specified in the readme.

![status bar green](https://cloud.githubusercontent.com/assets/2721182/26709223/250f2584-471f-11e7-8b93-66918a23208f.JPG)
![inconsolata registry](https://cloud.githubusercontent.com/assets/2721182/26709239/443cfd5a-471f-11e7-9020-853c5a3ae8f1.JPG)
![agnoster](https://cloud.githubusercontent.com/assets/2721182/26709251/5bfe6348-471f-11e7-8ecc-4fa18689f735.JPG)
![tmuxconflocalpowerlinsymbols](https://cloud.githubusercontent.com/assets/2721182/26709267/82678a46-471f-11e7-9a2d-6c99238de2cc.JPG)

**Comment by gpakosz** [comment]
Works for me.

Things you need to verify:
  - make sure you're running Windows 10 Creators update
  - make sure you're running Ubuntu 16.04 ($cat /etc/issue inside WSL)
  - make sure you kill all `tmux` process and didn't alter `~/.tmux.conf` nor `~/.tmux.conf.local`

**Comment by AXington** [comment]
The tmux.conf is completely untouched, tmux.conf.local is the same as it is
on my Mac and my Ubuntu computer. I am starting to see some other problems
with wsltty so I think it's a wsltty or Windows issue. I'll check the dist
version tonight after work. But honestly, probably just gonna move to using
a vm so I can mount my Ubuntu disks in it rather than install ext fs
drivers on Windows and not have to mess with the silly windows registry.

**Comment by AXington** [comment]
Was on Ubuntu 14.04, good call. I updated, working properly now. I thought I had done the distupgrade... guess not.

**Comment by gpakosz** [comment]
@AXington good to know! Please pay attention to the [Troubleshooting paragraph in README](https://github.com/gpakosz/.tmux/tree/264a577ba183bf7ce74da22a18fbb1bdba8244bf#troubleshooting). Until I do something automatic you have to edit your `~/.tmux.conf.local` copy to remove attributes like `bold` or `blink`
