### ISSUE TITLE
generating orphan zsh processes

### ISSUE THREAD

**Issue by silentred** [gpakosz/.tmux#84]
MacOS 10.12.3
iTerm 2
tmux 2.5

```
~ ps -ef | grep zsh
  501 45395 45394   0  8:19PM ttys000    0:01.50 -zsh
  501 49352 45395   0  8:26PM ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn zsh
  501 47316     1   0  8:25PM ttys001    0:00.01 -zsh
  501 47317     1   0  8:25PM ttys002    0:00.01 -zsh
  501   524   512   0  6May17 ttys003    0:03.29 -zsh
  501  9064  9063   0 Fri09PM ttys004    0:01.58 -zsh
  501 76506 76504   0 20May17 ttys005    0:01.90 -zsh
  501 47318     1   0  8:25PM ttys006    0:00.01 -zsh
  501 47359     1   0  8:25PM ttys007    0:00.01 -zsh
  501 48994     1   0  8:26PM ttys008    0:00.01 -zsh
  501 48995     1   0  8:26PM ttys009    0:00.01 -zsh
  501 48996     1   0  8:26PM ttys010    0:00.01 -zsh
  501 49037     1   0  8:26PM ttys011    0:00.01 -zsh
```

Like above, after creating and exiting session, there are lots of orphan zsh processes remaining.

**Comment by gpakosz** [comment]
I don't use `zsh` myself. Are you sure the problem exhibits when running `$ tmux -f /dev/null` to use stock configuration instead of mine?

**Comment by silentred** [comment]
I am sure. Running `tmux -f /dev/null` or removing .tmux.conf don't generate orphan zsh. This problem could be eazily reproduced.

**Comment by gpakosz** [comment]
Can you try with `tmux` version `2.3` or `2.4`?

**Comment by gpakosz** [comment]
Also what you can try to troubleshoot the problem and figure out whether it's a `tmux` bug or not is to use a `~/.tmux.conf` file that just does a bunch of `run -b` invocations and see whether you still have orphan zsh processes

**Comment by silentred** [comment]
I removed the last comment lines from .tmux.conf, the problem is gone.
From
```
# EOF
 #
 # # exit the script if any statement returns a non-true return value
```
to the end. Those code seems to be the cause.

**Comment by gpakosz** [comment]
That makes no sense

**Comment by silentred** [comment]
After removing the comment, the good-looking status bar used to be at the bottom is gone now.

**Comment by gpakosz** [comment]
That's expected.

**Comment by silentred** [comment]
I am using zsh + oh my zsh. This problem happens on my personal mac, my workplace mac, my colleague's mac. I guess this is an common case.

**Comment by gpakosz** [comment]
If you want to troubleshoot this, here is what you can try
  - try to reproduce with `tmux` versions `2.3` and/or `2.4`
  - create a `~/.tmux.conf` that only contains commands like `run -b false || true`
  - progressively comment "variables" in `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` (see your `~/.tmux.conf.local` copy)

All that until orphan processes are gone

**Comment by gpakosz** [comment]
@silentred Please try this

Edit `~/.tmux.conf` and replace lines
```
#       *sh)
#         tmux set -g default-command "exec $default_shell... 2> /dev/null & reattach-to-user-namespace -l $default_shell"
```
by
```
#       *sh)
#         tmux set -g default-command "reattach-to-user-namespace -l $default_shell"
```

**Comment by silentred** [comment]
I have tried these things:
1. tmux-2.3, not work, but orphan number deceases to 2 for each session. tmux-2.5 generates 4 orphans each session.
2. comment both `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right`, not work.
3. replace `tmux set -g default-command "exec $default_shell... 2> /dev/null & reattach-to-user-namespace -l $default_shell"` as you suggested, not work.

**Comment by gpakosz** [comment]
BTW commenting out `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` entirely brings you nothing because in the case there's not defined ~/.tmux.conf` picks default values for the variables.

You need to progressively shorten them. Ultimately if you end up setting them to empty values and problem disappears it means the orphans are caused by one of the "variables" in there. A "variable" being e.g. `#{battery_bar}`.

**Comment by silentred** [comment]
Uninstalling oh-my-zsh fixed the problem.

**Comment by gpakosz** [comment]
Right. So this `.tmux.conf` needs to shell out a lot to implement all of its features. It seems doing so while having `oh-my-zsh` installed causes troubles.

I believe your next step should be to figure out what exactly in your `oh-my-zsh` configuration triggers the problem and also double check `oh-my-zsh` without this conf doesn't create orphans on its own

**Comment by gpakosz** [comment]
> Right. So this `.tmux.conf` needs to shell out a lot to implement all of its features. It seems doing so while having `oh-my-zsh` installed causes troubles.

Elaborating on this.
  - removing `run -b` lines in `~/.tmux.conf` is a way to make it shell out less
  - removing `if -b` lines in `~/.tmux.conf` is a way to make it shell out less
  - editing `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` is a way to make it shell out less
    - if you remove `#{?battery_bar, #{battery_bar},}` it's 1 shell invocation less
    - ...
  - uninstalling `reattach-to-user-namespace` will make it shell out less

I know this is tedious, but going through this and gradually removing situations when my configuration shells out could help you pin-point which invocation doesn't play well with `oh-my-zsh` if any.

**Comment by zxdposter** [comment]
@gpakosz
this part, run directly increase by 1, in .tmux.conf increase by 4
`tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;`
and this part, always increase by 1
`tmux -q -L tmux_theme_status_left_test -f /dev/null new-session -d \; show -g -v status-left \; kill-session`

If I use oh-my-zsh, reload config will increase by 4，if I don't use, increase by 1.

these part can we skip?

**Comment by gpakosz** [comment]
@zxdposter Thanks for troubleshooting it.

I need to double check but as far as I remember, tmux 1.9a had a buggy `swap-pane` command and now I'm supporting only tmux `>= 2.1` so you can remove the following lines from ~/.tmux.conf`
```
#   if tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session; then
#     tmux bind + run 'cut -c3- ~/.tmux.conf | sh -s _maximize_pane #{session_name} #D'
#   else
#     tmux bind + display 'your tmux version has a buggy swap-pane command - see ticket #108, fixed in upstream commit 78e783e'
#   fi
```

I need to double check the `status-left` test.

Still, I need to understand why it's the cause of orphan processes when Oh My ZSH is installed

**Comment by gpakosz** [comment]
If I understand correctly, when you do
```
$ tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;
```
straight from your shell command line, it's creating 1 orphan process.

Since I myself wasn't able to reproduce it, even with Oh My ZSH installed, can you please test if the following also creates an orphan process?
```
$ tmux -c sh -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;
```

**Comment by zxdposter** [comment]
@gpakosz 
cannot run
`tmux -c sh -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;`

Error message
```
usage: tmux [-2CluvV] [-c shell-command] [-f file] [-L socket-name]
            [-S socket-path] [command [flags]]
```

**Comment by gpakosz** [comment]
Ah yeah sur that can't work, my bad :(

What about
```
SHELL=sh tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;
```

**Comment by zxdposter** [comment]
@gpakosz increase by 2

**Comment by gpakosz** [comment]
🤔

```
tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window sh \; new-window sh \; swap-pane -t :1 \; kill-session;
```

(I'm trying to keep the feature test while avoiding spawning zsh with oh-my-zsh)

**Comment by zxdposter** [comment]
Still increase by 1, hope picture can be helpful.
![wx20170621-175125](https://user-images.githubusercontent.com/13846260/27378372-43943888-56aa-11e7-9ea9-92a1bb81a875.png)

**Comment by gpakosz** [comment]
It indeed helps.

How about?
```
tmux -q -L swap-pane-test -f /dev/null new-session -d \; set -s default-shell /bin/sh \; new-window \; new-window \; swap-pane -t :1 \; kill-session;
```

**Comment by zxdposter** [comment]
bingo! work out.

**Comment by gpakosz** [comment]
A last one please?

```
tmux -q -L swap-pane-test -f /dev/null new-session -d \; set default-shell '/bin/sh' \; set default-command '' \; new-window \; new-window \; swap-pane -t :1 \; kill-session;
```

**Comment by zxdposter** [comment]
Yes, work out, its done!
![wx20170621-180243](https://user-images.githubusercontent.com/13846260/27378888-d975b614-56ab-11e7-8ccd-316d9b953b04.png)

**Comment by gpakosz** [comment]
Alright, I appreciate the patience you put into this with me.

I'll soon update the configuration. I'm not sure I'll keep both test because they may be now unneeded with tmux `>= 2.1` but it's good & important to understand what was going on 👍.

Thanks again!

**Comment by zxdposter** [comment]
Learn a lot from you, I should thank you. 👍

**Comment by zxdposter** [comment]
@gpakosz 
After my test， `set default-shell '/bin/sh' \;` should be put like that:
`tmux -q -L swap-pane-test -f /dev/null set default-shell '/bin/sh' \; new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;`

Otherwise, reload config will still make orphan zsh processes.

Run directly won't appear.

**Comment by gpakosz** [comment]
@silentred @zxdposter 

Since they concern tmux `<= 2.0`, I removed both test. Can you please give the `upcoming` branch try?

**Comment by zxdposter** [comment]
I already try it, seems to have settled.

**Comment by silentred** [comment]
Thank you. @gpakosz  @zxdposter
