### ISSUE TITLE
Every time I reload .tmux.conf will make "zsh" process num increase by 4!

### ISSUE THREAD

**Issue by zxdposter** [gpakosz/.tmux#88]
![wx20170621-142116](https://user-images.githubusercontent.com/13846260/27370019-278db258-568d-11e7-895c-e0e3cab956fd.png)

Some days ago, I find my zsh process num will always increase, and never quit, today I found the problem.

Why appear this problem?

**Comment by gpakosz** [comment]
This seems to be similar to #84 and caused by Oh My ZSH. OP didn't give more feedback though
