### ISSUE TITLE
How to disable the current `H` and `L` behaviour in vi-edit mode

### ISSUE THREAD

**Issue by well1791** [gpakosz/.tmux#90]
I know this is more `tmux` related, but I haven't found any direct source to disable these configurations.

```
run -b 'tmux bind -ct vi-edit H start-of-line 2> /dev/null || true'
run -b 'tmux bind -ct vi-edit L end-of-line 2> /dev/null || true'
```

so far I tried this in my `.tmux.conf.local`

```
run -b 'tmux unbind -ct vi-edit H 2> /dev/null || true'
run -b 'tmux unbind -ct vi-edit L 2> /dev/null || true'
```

but that didn't luck.

I even commented those lines in my `.tmux.conf` but still the same behavior (which is weird from my POV). And on top of that, I don't want to write my `.tmux.conf` file.

Thanks in advance for any help! 🙇

**Comment by gpakosz** [comment]
Hello @well1791, which version of tmux are you using?

**Comment by well1791** [comment]
Hi @gpakosz, indeed that's the version I'm using. Looks like I have no choice then.

Thanks for your answer!
