### ISSUE TITLE
`laptop battery status line information` not working in my case

### ISSUE THREAD

**Issue by pigeon1990** [gpakosz/.tmux#91]
hello:
  I'm using 6fc4ad7 commit in my computer.but `laptop battery status line information`  not working.please help me

OS:OSX 10.11.3
tmux:2.5
iterm2:3.0.15

![0497588f-35e1-442d-81c1-fde014ffe410](https://user-images.githubusercontent.com/25000315/27506195-152143f4-58e6-11e7-8255-83b00e4089c0.png)

**Comment by gpakosz** [comment]
Hello @pigeon1990,

Branch `github-91` should fix it. Can you confirm?

**Comment by pigeon1990** [comment]
@gpakosz is working for me. thanks！
