### ISSUE TITLE
Battery wont appear 

### ISSUE THREAD

**Issue by vegangaro** [gpakosz/.tmux#92]
I just cant put that shinny thing to even appear! Even consulted what all other batteries plugins need to show up...

But so far no luck!  

Any tips?

Arch Linux - KDE - Xterm - Zsh

Screen: http://imgur.com/CDoZbPL

**Comment by gpakosz** [comment]
Can you please paste the output of `$ ls /sys/class/power_supply/BAT0/` ?

**Comment by vegangaro** [comment]
Yelds `ls: cannot access '/sys/class/power_supply/BAT0/': No such file or directory`

**Comment by gpakosz** [comment]
Then `$ ls /sys/class/power_supply/` ?

**Comment by vegangaro** [comment]
yelds nothing

**Comment by vegangaro** [comment]
is this a laptop feature only? haha

**Comment by gpakosz** [comment]
That explains why you don't see a battery indicator.

> is this a laptop feature only? haha

What's the hardware you're running tmux on?

**Comment by vegangaro** [comment]
Desktop 

lmaaaaooooooo

**Comment by gpakosz** [comment]
> Desktop

So yeah *very likely* there's no battery in it and the kernel doesn't report any battery.

**Comment by vegangaro** [comment]
haha...sorry to waste your time! haha

**Comment by gpakosz** [comment]
No problem, I let you close this issue.

**Comment by vegangaro** [comment]
"I have a dream..that darn battery on my tmux...." lemme me put ma hands on a ultrabook...

you just wait sir haha
