### ISSUE TITLE
prefix + not working

### ISSUE THREAD

**Issue by slackerzz** [gpakosz/.tmux#94]
prefix +  doesn't maximize the current pane

**Comment by gpakosz** [comment]
Which version of tmux are you using?
Which OS?
Which shell?

**Comment by slackerzz** [comment]
tmux 2.1
Ubuntu 16.04
zsh (oh my zsh) in Tilda terminal

however it used to work, i think the culprit could one of the commit done in the last month

**Comment by gpakosz** [comment]
That's interesting. Nothing changed with respect to maximizing panes specifically.

Can you print the output of `$ tmux list-keys | grep maximize`. Should output
```
$ tmux list-keys | grep maximize
bind-key    -T prefix       +                 run-shell "cut -c3- ~/.tmux.conf | sh -s _maximize_pane #{session_name} #D"
```

Also what you can do to debug that with me, is create a window with 2 panes, then select one pane and do `$ cut -c3- ~/.tmux.conf | sh -s _maximize_pane`

**Comment by slackerzz** [comment]
Overwriting ```~/.tmux.conf.local``` with the one in the repo fixed the issue
It was probably a mistake of mine!
