### ISSUE TITLE
Internet Online/Offline Status in statusbar

### ISSUE THREAD

**Issue by nxtcoder17** [gpakosz/.tmux#96]
I have been using tmux since a while now . I think it would make a nice addition if you could just add an Online/Offline Status Icon somewhere aroud battery bar which glows in different color when i am offline but turns RED when i am offline . It's just a request for anaddition to the project . Anyway i have loved tmux+Your_Config combination anyway . Thanks in advance ...

**Comment by gpakosz** [comment]
Hello @PHENOMENAL-AB.

If you have `ping` installed, just add this to either `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right`:

```
#(ping -t 1 -c 1 google.com >/dev/null 2>&1 && printf '✔' || printf '✘')
```
