### ISSUE TITLE
hostname is showing IP instead of real hostname

### ISSUE THREAD

**Issue by spivoler** [gpakosz/.tmux#98]
Hi, 

Thanks for the cool theme. I found one issue with status bar: when I do ssh, the status bar shows IP address of remote server instead of its hostname. Anything I missed? Also I didn't find any definition of hostname function in your config file. Why? Thanks.

**Comment by spivoler** [comment]
I figured out why. It is all about my .ssh/config. I put ip address over there, not hostname. Thanks.

**Comment by gpakosz** [comment]
Hello @spivoler,

You figured it out yourself. The reason is that I'm asking `ssh` the values for `user` and `hostname` and if you put ip addresses into your `~/.ssh/config` file that's what you get back.

**Comment by matthew-z** [comment]
@spivoler I was wondering if it is possible to retrieve real hostname from the server.  My servers share the same ip address, and I differentiate them by port number.
