### ISSUE TITLE
windows status name after ssh

### ISSUE THREAD

**Issue by luisdavim** [gpakosz/.tmux#99]
Using iTerm on macOS, after I use ssh the window status stays as `user@server:path` and doesn't revert back to `bash`.

**Comment by gpakosz** [comment]
I'm afraid this has nothing to do with my configuration. Can you double check with `tmux -f /dev/null`?

**Comment by luisdavim** [comment]
You're right, sorry for opening the issue before checking that.
On Linux using gnome-terminal I don't have this issue, it must be something in iTerm.
Thanks.

**Comment by gpakosz** [comment]
Alright, closing then!

**Comment by luisdavim** [comment]
In case anyone finds this looking for a solution, this fixes my issue:
```export TERM=vt100```
or:
```alias ssh='TERM=vt100 /usr/bin/ssh'```

**Comment by luisdavim** [comment]
Actually ignore my previous comment, setting `TERM=vt100` comes with some unwanted side effects, the proper solution is to set the `window_status` format to use `#{pane_current_command}` (introduced in tmux 1.8) instead of `#w` @gpakosz maybe you can include that in your config...

**Comment by gpakosz** [comment]
I disagree with the suggestion.

The fact that you have something that renames your windows doesn't mean `#{pane_current_command}` should be preferred to `#W`.

If you really can't fix the thing that renames your window, indeed you can edit your `~/.tmux.conf.local` copy to be:
```
tmux_conf_theme_window_status_format='#I #{pane_current_command}'
tmux_conf_theme_window_status_current_format='#I #{pane_current_command}'
```
But I recommend against doing it.
